import {RetainedActionForm} from "@/components/RetainedActionForm";
import Link from "next/link";
import {AppShell} from "@/components/AppShell";
import {requireRouteAccess} from "@/lib/auth/session";
import {hasPermission} from "@/lib/permissions/effective";
import {getBusinessSettings} from "@/lib/settings-business";
import {saveBusinessSettingAction} from "./actions";
export default async function Page({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}){
 const session=await requireRouteAccess("/settings/business");if(!await hasPermission(session,"SETTINGS_VIEW"))return <AppShell active="/settings" title="Настройки бизнеса"><p role="alert">Нет доступа к настройкам.</p></AppShell>;const data=await getBusinessSettings(session),params=await searchParams,manage=await hasPermission(session,"SETTINGS_MANAGE");
 return <AppShell active="/settings" title="Настройки бизнеса" subtitle="Организация, филиалы, места хранения и способы оплаты">
 <Link href="/settings">← Все настройки</Link>{params.error&&<p className="notice error">{params.error}</p>}{params.ok&&<p className="notice">Настройки сохранены.</p>}
 <section className="panel"><h2>Организация</h2><p>Валюта: {data.organization.defaultCurrency}. Часовой пояс: {data.organization.timezone}.</p>
 <RetainedActionForm action={saveBusinessSettingAction}><input type="hidden" name="kind" value="organization"/><fieldset disabled={!manage||!data.canManageGlobal}><label>Название<input name="name" defaultValue={data.organization.name} required maxLength={100}/></label><label>Буфер после возврата, минуты<input name="turnaroundBufferMinutes" type="number" min="0" max="10080" defaultValue={data.settings?.turnaroundBufferMinutes??0}/></label><p>Изменение буфера применяется при последующем расчёте бронирований. Ранее созданные брони сохраняют свои границы.</p><button className="primary">Сохранить</button></fieldset></RetainedActionForm></section>
 <section className="panel"><h2>Филиалы</h2>{[...data.branches,...(data.canManageGlobal&&manage?[null]:[])].map(branch=><RetainedActionForm action={saveBusinessSettingAction} key={branch?.id??"new"}><h3>{branch?.name??"Новый филиал"}</h3><input type="hidden" name="kind" value="branch"/><input type="hidden" name="id" value={branch?.id??""}/><fieldset disabled={!manage||branch?.status!==undefined&&branch.status!=="ACTIVE"&&!data.canManageGlobal}><label>Название<input name="name" defaultValue={branch?.name} required/></label><label>Код<input name="code" defaultValue={branch?.code} required pattern="[A-Za-z0-9_-]{1,50}"/></label><label>Город<input name="city" defaultValue={branch?.city} required/></label><label>Адрес<input name="address" defaultValue={branch?.address??""}/></label><label>Телефон<input name="phone" defaultValue={branch?.phone??""}/></label><label>Часовой пояс<input name="timezone" defaultValue={branch?.timezone??data.organization.timezone} readOnly={!data.canManageGlobal} required/></label><label>Статус<select name="status" defaultValue={branch?.status??"ACTIVE"} disabled={!data.canManageGlobal}><option value="ACTIVE">Активен</option><option value="INACTIVE">Неактивен</option></select></label>{!data.canManageGlobal&&<input type="hidden" name="status" value="ACTIVE"/>}<button className="primary">Сохранить филиал</button></fieldset></RetainedActionForm>)}</section>
 <section className="panel"><h2>Места хранения</h2>{data.branches.filter(branch=>branch.status==="ACTIVE").map(branch=><div key={branch.id}><h3>{branch.name}</h3>{[...branch.locations,...(manage?[null]:[])].map(location=><RetainedActionForm action={saveBusinessSettingAction} key={location?.id??"new"}><input type="hidden" name="kind" value="location"/><input type="hidden" name="branchId" value={branch.id}/><input type="hidden" name="id" value={location?.id??""}/><fieldset disabled={!manage}><label>Название<input name="name" defaultValue={location?.name} placeholder="Новое место хранения" required/></label><label>Код<input name="code" defaultValue={location?.code} required pattern="[A-Za-z0-9_-]{1,50}"/></label><label>Тип<select name="type" defaultValue={location?.type??"WAREHOUSE"}>{Object.entries({SHOWROOM:"Зал",WAREHOUSE:"Склад",STORAGE_ZONE:"Зона хранения",CLEANING:"Чистка",REPAIR:"Ремонт",TRANSIT:"В пути",OTHER:"Другое"}).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><input type="checkbox" name="isActive" defaultChecked={location?.isActive??true}/> Активное место хранения</label><button className="secondary">Сохранить место</button></fieldset></RetainedActionForm>)}</div>)}</section>
 <section className="panel"><h2>Способы оплаты</h2><p>Выключение скрывает способ из новых операций и сохраняет историю платежей.</p>{[...data.paymentMethods,...(data.canManageGlobal&&manage?[null]:[])].map(method=><RetainedActionForm action={saveBusinessSettingAction} key={method?.id??"new"}><input type="hidden" name="kind" value="payment"/><input type="hidden" name="id" value={method?.id??""}/><fieldset disabled={!manage||!data.canManageGlobal}><label>Код<input name="code" defaultValue={method?.code} readOnly={Boolean(method)} required pattern="[A-Z][A-Z0-9_]{1,49}"/></label><label>Название<input name="displayName" defaultValue={method?.displayName} required maxLength={100}/></label><label><input type="checkbox" name="isActive" defaultChecked={method?.isActive??true}/> Доступен для новых операций</label><button className="secondary">Сохранить способ оплаты</button></fieldset></RetainedActionForm>)}</section>
 </AppShell>;
}
