"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRouteAccess } from "@/lib/auth/session";
import { createTenantContext } from "@/lib/tenant/context";
import { requireInventoryPermission } from "@/lib/inventory/permissions";
import { receiveBulk,receiveSerialized,transferBulk,transferSerialized,changeBulk,changeSerializedStatus } from "@/lib/inventory/management";
import { requireBranchAccess } from "@/lib/staff/branch-access";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim(),n=(f:FormData,k:string)=>Number.parseInt(t(f,k),10),go=(ok:boolean,m:string):never=>redirect(`/warehouse/operations?${ok?"ok":"error"}=${encodeURIComponent(m)}`);
async function ctx(action:"RECEIPT"|"TRANSFER"|"SENSITIVE"){const s=await requireRouteAccess("/warehouse");requireInventoryPermission(s.role,action);return{s,tenant:createTenantContext(s.organizationId)}}
export async function receiptAction(f:FormData){try{const{s,tenant}=await ctx("RECEIPT"),base={variantId:t(f,"variantId"),branchId:t(f,"branchId"),locationId:t(f,"locationId"),quantity:n(f,"quantity"),comment:t(f,"reason"),idempotencyKey:t(f,"idempotencyKey")};await requireBranchAccess(tenant,s.membershipId,base.branchId);if(t(f,"mode")==="BULK")await receiveBulk(tenant,base,{userId:s.userId});else await receiveSerialized(tenant,base,{userId:s.userId});revalidatePath("/warehouse");go(true,"Приёмка сохранена.")}catch(e){go(false,e instanceof Error?e.message:"Операция не выполнена.")}}
export async function transferAction(f:FormData){try{const{s,tenant}=await ctx("TRANSFER");await requireBranchAccess(tenant,s.membershipId,t(f,"fromBranchId"));await requireBranchAccess(tenant,s.membershipId,t(f,"toBranchId"));if(t(f,"mode")==="BULK")await transferBulk(tenant,{variantId:t(f,"variantId"),fromBranchId:t(f,"fromBranchId"),fromLocationId:t(f,"fromLocationId"),toBranchId:t(f,"toBranchId"),toLocationId:t(f,"toLocationId"),quantity:n(f,"quantity"),reason:t(f,"reason"),idempotencyKey:t(f,"idempotencyKey")},{userId:s.userId});else await transferSerialized(tenant,{instanceId:t(f,"instanceId"),fromBranchId:t(f,"fromBranchId"),toBranchId:t(f,"toBranchId"),toLocationId:t(f,"toLocationId"),reason:t(f,"reason"),idempotencyKey:t(f,"idempotencyKey")},{userId:s.userId});revalidatePath("/warehouse");go(true,"Перемещение выполнено.")}catch(e){go(false,e instanceof Error?e.message:"Операция не выполнена.")}}
export async function correctionAction(f:FormData){try{const{s,tenant}=await ctx("SENSITIVE"),mode=t(f,"mode"),type=t(f,"type") as "ADJUSTMENT"|"WRITE_OFF"|"LOSS"|"FOUND"|"RESTORE";if(mode==="BULK"){await requireBranchAccess(tenant,s.membershipId,t(f,"branchId"));await changeBulk(tenant,{variantId:t(f,"variantId"),branchId:t(f,"branchId"),locationId:t(f,"locationId"),delta:n(f,"delta"),type:type as "ADJUSTMENT"|"WRITE_OFF"|"LOSS"|"FOUND",reason:t(f,"reason"),idempotencyKey:t(f,"idempotencyKey")},{userId:s.userId})}else{if(type==="ADJUSTMENT")throw new Error("Для SERIALIZED используйте явную статусную операцию.");await changeSerializedStatus(tenant,{instanceId:t(f,"instanceId"),type,reason:t(f,"reason"),idempotencyKey:t(f,"idempotencyKey")},{userId:s.userId});}revalidatePath("/warehouse");go(true,"Операция сохранена.")}catch(e){go(false,e instanceof Error?e.message:"Операция не выполнена.")}}
