import {notFound} from "next/navigation";
import Link from "next/link";
import {AppShell} from "@/components/AppShell";
import {FittingForm} from "@/components/FittingForm";
import {ConversionForm} from "@/components/ConversionForm";
import {requireRouteAccess} from "@/lib/auth/session";
import {getEffectivePermissions} from "@/lib/permissions/effective";
import {getFitting,fittingHistory} from "@/lib/fittings/service";
import {FITTING_STATUS_LABELS} from "@/lib/fittings/validation";
import {workflowOptions} from "@/lib/workspace/conversion";
import {updateFittingAction} from "../actions";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;ok?:string;q?:string}>}){const session=await requireRouteAccess("/fittings"),{id}=await params,p=await searchParams,row=await getFitting(session,id);if(!row)notFound();const history=await fittingHistory(session,id);const permissions=await getEffectivePermissions(session),options=await workflowOptions(session,"FITTING_VIEW",row.branchId,p.q),canEdit=permissions.has("FITTING_MANAGE")&&(permissions.has("FITTING_ASSIGN")||row.assignedMembershipId===session.membershipId);return <AppShell active="/fittings" title="Примерка" subtitle={`${row.branch.name} · ${FITTING_STATUS_LABELS[row.status]}`}><Link href="/fittings">← Примерки</Link>{row.inquiryId&&<p><Link href={`/chats/${row.inquiryId}`}>Исходное обращение</Link></p>}{p.error&&<p className="notice error">{p.error}</p>}{p.ok&&<p className="notice">Сохранено.</p>}<form><label>Поиск клиента или товара<input name="q" defaultValue={p.q}/></label><button>Найти</button></form>{canEdit&&!["COMPLETED","CANCELLED","NO_SHOW"].includes(row.status)?<FittingForm creationKey={row.creationKey} action={updateFittingAction} options={options} actorId={session.membershipId} row={row}/>:<section className="panel"><p>{row.customer?`${row.customer.firstName} ${row.customer.lastName??""}`:row.guestName} · {row.guestContact}</p><p>{row.startsAt.toLocaleString("ru",{timeZone:row.branch.timezone})} — {row.endsAt.toLocaleTimeString("ru",{timeZone:row.branch.timezone})}</p><p>Сотрудник: {row.assignedTo.user.displayName}</p><p>{row.comment}</p><ul>{row.items.map(item=><li key={item.id}>{item.nameSnapshot} · {item.sizeSnapshot}</li>)}</ul></section>}{permissions.has("ORDER_CREATE")&&permissions.has("FITTING_MANAGE")&&!["CANCELLED","NO_SHOW"].includes(row.status)&&<ConversionForm source="FITTING" sourceId={row.id} orderId={row.orderId} initial={{requestedFrom:row.inquiry?.requestedFrom,requestedUntil:row.inquiry?.requestedUntil,customerId:row.customerId,customerLabel:row.customer?`${row.customer.firstName} ${row.customer.lastName??""}`:row.guestName}} options={await workflowOptions(session,"ORDER_VIEW",row.branchId,p.q)} actorId={session.membershipId}/>}<section className="panel"><h2>История примерки</h2><p>Последние 100 изменений.</p>{history.map(entry=><p key={entry.id}>{entry.occurredAt.toLocaleString("ru",{timeZone:row.branch.timezone})} · {entry.actorUser?.displayName??"Система"} · {entry.action==="FITTING_CREATED"?"Создана":entry.action==="FITTING_UPDATED"?"Изменена":"Связана с заказом"}</p>)}</section></AppShell>}
