import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { requireRouteAccess } from "@/lib/auth/session";
import { createTenantContext } from "@/lib/tenant/context";
import { getCalendar, type CalendarDayDto, type CalendarOrderDto } from "@/lib/calendar/queries";
import { CALENDAR_STATUSES, parseCalendarQuery } from "@/lib/calendar/validation";
import { dateKey, formatLocalTime, localDateKey, moveAnchor } from "@/lib/calendar/timezone";
type Raw = Record<string, string | string[] | undefined>;
const dayLabel=(d:{year:number;month:number;day:number},long=false)=>new Intl.DateTimeFormat("ru-KZ",long?{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}:{weekday:"short",day:"numeric",month:"short",timeZone:"UTC"}).format(new Date(Date.UTC(d.year,d.month-1,d.day)));
function href(raw:Raw,patch:Record<string,string|undefined>){const p=new URLSearchParams();for(const[k,v]of Object.entries(raw)){if(Array.isArray(v))v.forEach(x=>p.append(k,x));else if(v)p.set(k,v)}for(const[k,v]of Object.entries(patch)){p.delete(k);if(v)p.set(k,v)}return`/calendar?${p}`}
function Items({order}:{order:CalendarOrderDto}){return <span className="calendar-items">{order.items.slice(0,2).map((x,i)=><small key={i}>{x.name} · {x.variant}{x.quantity>1?` ×${x.quantity}`:""}</small>)}{order.items.length>2&&<small>+{order.items.length-2} позиции</small>}</span>}
function OrderCard({order,timeZone,kind}:{order:CalendarOrderDto;timeZone:string;kind?:"start"|"end"|"active"}){return <article className={`calendar-order ${order.status.toLowerCase()} ${kind??""}`}><div><Link href={`/orders/${order.id}`}><b>{order.orderNumber}</b></Link><i>{order.status}</i></div><Link href={`/customers/${order.customerId}`}>{order.customerName}</Link>{order.phone&&<span>{order.phone}</span>}<span>{order.branchName}</span><span>{formatLocalTime(kind==="end"?order.rentalEnd:order.rentalStart,timeZone)}</span><Items order={order}/><strong>{order.totalMinor.toLocaleString("ru-KZ")} {order.currency}</strong></article>}
function DayView({day,timeZone}:{day:CalendarDayDto;timeZone:string}){return <div className="day-sections"><section className="card"><h2>Выдача <em>{day.starts.length}</em></h2>{day.starts.map(o=><OrderCard key={o.id} order={o} timeZone={timeZone} kind="start"/>)}{!day.starts.length&&<p className="calendar-empty">Выдач нет.</p>}</section><section className="card"><h2>Возврат <em>{day.ends.length}</em></h2>{day.ends.map(o=><OrderCard key={o.id} order={o} timeZone={timeZone} kind="end"/>)}{!day.ends.length&&<p className="calendar-empty">Возвратов нет.</p>}</section><section className="card"><h2>Активные аренды <em>{day.active.length}</em></h2>{day.active.map(o=><OrderCard key={o.id} order={o} timeZone={timeZone} kind="active"/>)}{!day.active.length&&<p className="calendar-empty">Активных аренд нет.</p>}</section></div>}
function WeekView({days,timeZone}:{days:CalendarDayDto[];timeZone:string}){return <div className="calendar-scroll"><div className="week-grid">{days.map(d=><section className={`calendar-day card ${d.key===localDateKey(new Date(),timeZone)?"today":""}`} key={d.key}><Link className="day-title" href={`/calendar?view=day&date=${d.key}`}><b>{dayLabel(d.date)}</b></Link><div className="day-counts"><span>Выдач <b>{d.starts.length}</b></span><span>Возвратов <b>{d.ends.length}</b></span><span>Активных <b>{d.active.length}</b></span></div>{[...new Map([...d.starts,...d.ends].map(o=>[o.id,o])).values()].slice(0,4).map(o=><OrderCard key={o.id} order={o} timeZone={timeZone}/>)}{d.starts.length+d.ends.length>4&&<small>Ещё событий: {d.starts.length+d.ends.length-4}</small>}</section>)}</div></div>}
function MonthView({days}:{days:CalendarDayDto[]}){const first=days[0]?.date,offset=first?((new Date(Date.UTC(first.year,first.month-1,first.day)).getUTCDay()+6)%7)+1:1;return <div className="calendar-scroll"><div className="month-grid">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=><b className="weekday" key={x}>{x}</b>)}{days.map((d,i)=><Link href={`/calendar?view=day&date=${d.key}`} className="month-day card" style={i===0?{gridColumnStart:offset}:undefined} key={d.key}><b>{d.date.day}</b><span>Выдач <strong>{d.starts.length}</strong></span><span>Возвратов <strong>{d.ends.length}</strong></span><span>Активных <strong>{d.active.length}</strong></span></Link>)}</div></div>}
export default async function CalendarPage({searchParams}:{searchParams:Promise<Raw>}){const session=await requireRouteAccess("/calendar"),raw=await searchParams,query=parseCalendarQuery({view:raw.view,date:raw.date,branchId:raw.branchId,status:raw.status,q:raw.q}),data=await getCalendar(createTenantContext(session.organizationId),query),anchor=dateKey(data.anchor),prev=dateKey(moveAnchor(query.view,data.anchor,-1)),next=dateKey(moveAnchor(query.view,data.anchor,1));return <AppShell active="/calendar" title="Календарь аренды" subtitle={`${dayLabel(data.period.start,true)} · ${data.timeZone}`}><section className="today-summary card"><b>Сегодня</b><span>Выдач <strong>{data.today.starts.length}</strong></span><span>Возвратов <strong>{data.today.ends.length}</strong></span><span>Активных броней <strong>{data.today.active.length}</strong></span></section><div className="calendar-toolbar card"><nav><Link className="secondary button-link" href={href(raw,{date:prev})}>←</Link><Link className="secondary button-link" href={href(raw,{date:localDateKey(new Date(),data.timeZone)})}>Сегодня</Link><Link className="secondary button-link" href={href(raw,{date:next})}>→</Link></nav><nav>{(["day","week","month"] as const).map(v=><Link className={`${query.view===v?"primary":"secondary"} button-link`} href={href(raw,{view:v,date:anchor})} key={v}>{v==="day"?"День":v==="week"?"Неделя":"Месяц"}</Link>)}</nav><form><input type="hidden" name="view" value={query.view}/><input type="date" name="date" defaultValue={anchor}/><select name="branchId" defaultValue={query.branchId??""}><option value="">Все филиалы</option>{data.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><input name="q" defaultValue={query.search} placeholder="Заказ, клиент или телефон"/><div className="status-filters">{CALENDAR_STATUSES.map(s=><label key={s}><input type="checkbox" name="status" value={s} defaultChecked={query.statuses.includes(s)}/>{s}</label>)}</div><button className="secondary">Применить</button></form></div>{data.capacityWarnings.length>0&&<section className="capacity-warning card"><b>Низкая доступность</b><span>Нет или мало свободных: {data.capacityWarnings.length} вариантов.</span>{data.capacityWarnings.slice(0,5).map((x,i)=><small key={`${x.variantId}-${i}`}>{x.label}: {x.available} из {x.total}</small>)}</section>}{query.view==="day"?<DayView day={data.days[0]} timeZone={data.timeZone}/>:query.view==="week"?<WeekView days={data.days} timeZone={data.timeZone}/>:<MonthView days={data.days}/>}</AppShell>}
