import type { Prisma, PrismaClient } from "@/generated/prisma/client";
import type { NamespaceSnapshot } from "@/lib/catalog/full-import-planner";
type Db=PrismaClient|Prisma.TransactionClient;

export async function readCatalogImportNamespace(db:Db,ids?:{organizationId:string;branchId:string;locationId:string}):Promise<NamespaceSnapshot>{
 const organizations=await db.organization.findMany({where:ids?{id:ids.organizationId}:{name:"MARIPOSA",status:"ACTIVE"},select:{id:true,name:true,slug:true,status:true}});if(organizations.length!==1||organizations[0].status!=="ACTIVE")throw new Error(`Target organization is ambiguous or inactive: ${organizations.length}`);const organization=organizations[0];
 const branches=await db.branch.findMany({where:ids?{id:ids.branchId,organizationId:organization.id,status:"ACTIVE"}:{organizationId:organization.id,status:"ACTIVE",OR:[{city:{equals:"Astana",mode:"insensitive"}},{city:{equals:"Астана",mode:"insensitive"}},{name:{equals:"Astana",mode:"insensitive"}},{name:{equals:"Астана",mode:"insensitive"}}]},select:{id:true,name:true,city:true}});if(branches.length!==1)throw new Error(`Target branch is ambiguous: ${branches.length}`);const branch=branches[0];
 const locations=await db.location.findMany({where:ids?{id:ids.locationId,organizationId:organization.id,branchId:branch.id,isActive:true}:{organizationId:organization.id,branchId:branch.id,isActive:true,type:{in:["WAREHOUSE","SHOWROOM"]}},orderBy:[{type:"asc"},{code:"asc"}],select:{id:true,name:true,code:true}});if(locations.length!==1)throw new Error(`Target opening location is ambiguous: ${locations.length}`);const location=locations[0];
 const variants=await db.productVariant.findMany({where:{organizationId:organization.id},select:{sku:true}});const instances=await db.productInstance.findMany({where:{organizationId:organization.id},select:{barcode:true}});const codes=await db.product.findMany({where:{organizationId:organization.id},select:{internalCode:true}});const historical=await db.product.findMany({where:{organizationId:organization.id,trackingMode:"SERIALIZED",internalCode:{in:["0060","0142"]}},select:{id:true,name:true,internalCode:true,_count:{select:{variants:true}},variants:{select:{_count:{select:{instances:true}}}}}});
 return {organization:{id:organization.id,name:organization.name,slug:organization.slug},branch,location,variantSkus:variants.map(v=>v.sku),instanceBarcodes:instances.map(v=>v.barcode),productCodes:codes.map(v=>v.internalCode),historicalSerialized:historical.map(p=>({id:p.id,name:p.name,internalCode:p.internalCode,variantCount:p._count.variants,instanceCount:p.variants.reduce((n,v)=>n+v._count.instances,0)}))};
}
