import { createHash } from "node:crypto";
import type { Prisma, PrismaClient } from "@/generated/prisma/client";
import type { FullCatalogPlan } from "@/lib/catalog/full-import-planner";
import { getCatalogImportDatabaseFingerprint } from "@/lib/catalog/full-import-fingerprint";

type Db=PrismaClient|Prisma.TransactionClient;
export const PRODUCTION_CONFIRMATION_PHRASE="IMPORT MARIPOSA FULL CATALOG 4915";
const stableUuid=(kind:string,key:string)=>{const h=createHash("sha256").update(`mariposa-final-3a:${kind}:${key}`).digest("hex");return `${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`};
const s=(v:unknown)=>String(v??"");const n=(v:unknown)=>Number(v);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const chunks=<T>(rows:T[],size=100)=>Array.from({length:Math.ceil(rows.length/size)},(_,i)=>rows.slice(i*size,(i+1)*size));
async function stage<T>(db:Db,fn:(tx:Prisma.TransactionClient)=>Promise<T>){return "$transaction" in db?db.$transaction(fn,{timeout:120000}):fn(db as Prisma.TransactionClient)}

export type ApplyOptions={organizationId:string;branchId:string;locationId:string;workbookSha256:string;planSha256:string;databaseFingerprint:string;confirmationPhrase:string;rehearsal?:boolean;interruptAfterStage?:string};

function assertSafety(plan:FullCatalogPlan,input:ApplyOptions){
 if(input.confirmationPhrase!==PRODUCTION_CONFIRMATION_PHRASE)throw new Error("Production import confirmation phrase mismatch");
 if(input.workbookSha256!==plan.workbook.sha256)throw new Error("Workbook hash approval mismatch");if(input.planSha256!==plan.planSha256)throw new Error("Plan hash approval mismatch");
 if(input.organizationId!==plan.target.organization.id||input.branchId!==plan.target.branch.id||input.locationId!==plan.target.location.id)throw new Error("Approved target identity mismatch");
 if(!input.rehearsal&&plan.target.organization.name!=="MARIPOSA")throw new Error("Production apply requires exact MARIPOSA target");
 if(/pilot/i.test(plan.target.organization.name)||/pilot/i.test(plan.target.organization.slug))throw new Error("PILOT organization is forbidden as full-import target");
 const t=plan.totals;if(t.sourceRows!==1063||t.products!==330||t.executions!==206||t.variants!==1052||t.physicalUnits!==4915||t.finalCollisions!==0||t.review!==0||t.missingRequiredFields!==0)throw new Error("Approved control totals mismatch");
}

async function verifyExisting<T>(label:string,current:T|null,expected:T){if(current&&!same(current,expected))throw new Error(`${label} deterministic payload conflict`)}

export async function applyFullCatalogPlan(db:Db,plan:FullCatalogPlan,input:ApplyOptions){
 assertSafety(plan,input);const batchId=stableUuid("batch",`${input.organizationId}:${plan.workbook.sha256}:${plan.planSha256}`);let batch=await db.catalogImportBatch.findUnique({where:{id:batchId}});const fingerprint=await getCatalogImportDatabaseFingerprint(db,input.organizationId,input.branchId,input.locationId);if(!batch&&fingerprint.sha256!==input.databaseFingerprint)throw new Error(`Database fingerprint drift: ${fingerprint.sha256}`);
 const batchPayload={organizationId:input.organizationId,batchKey:plan.batchKey,sourceFilename:plan.workbook.filename,sourceSha256:plan.workbook.sha256,planSha256:plan.planSha256,mode:"OPENING_CATALOG" as const,branchId:input.branchId,locationId:input.locationId,sourceRowCount:1063,productCount:330,executionCount:206,variantCount:1052,physicalUnitCount:4915,preservedSkuCount:576,generatedSkuCount:476};
 if(batch){for(const [k,v] of Object.entries(batchPayload))if((batch as Record<string,unknown>)[k]!==v)throw new Error(`CatalogImportBatch conflict at ${k}`);if(batch.status==="APPLIED")return {batchId,replayed:true};}
 else batch=await db.catalogImportBatch.create({data:{id:batchId,...batchPayload,status:"APPLYING",metadata:{databaseFingerprint:input.databaseFingerprint,stage:"BATCH"}}});
 const checkpoint=async(name:string)=>{await db.catalogImportBatch.update({where:{id:batchId},data:{metadata:{databaseFingerprint:input.databaseFingerprint,stage:name}}});if(input.interruptAfterStage===name)throw new Error(`REHEARSAL_INTERRUPT:${name}`)};
 try{
  await stage(db,async tx=>{const expected=plan.sizes.map(size=>({id:size.id,organizationId:input.organizationId,sizeSystem:size.sizeSystem,code:size.code,name:size.name,recommendedHeightCm:size.recommendedHeightCm,lengthCm:size.lengthCm,sortOrder:0,isActive:true})),existing=await tx.size.findMany({where:{id:{in:expected.map(v=>v.id)}},select:{id:true,organizationId:true,sizeSystem:true,code:true,name:true,recommendedHeightCm:true,lengthCm:true,sortOrder:true,isActive:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of expected)await verifyExisting("Size",byId.get(row.id)??null,row);for(const batch of chunks(expected.filter(v=>!byId.has(v.id))))await tx.size.createMany({data:batch})});await checkpoint("SIZES");
  const categoryIds=new Map<string,string>(),categoryExpected=[] as Array<{id:string;organizationId:string;name:string;slug:string;status:"ACTIVE"}>;for(const product of plan.products)if(!categoryIds.has(product.category)){const id=stableUuid("category",`${input.organizationId}:${product.category}`);categoryIds.set(product.category,id);categoryExpected.push({id,organizationId:input.organizationId,name:product.category,slug:`import-${createHash("sha256").update(product.category).digest("hex").slice(0,16)}`,status:"ACTIVE"})}await stage(db,async tx=>{const existing=await tx.category.findMany({where:{id:{in:categoryExpected.map(v=>v.id)}},select:{id:true,organizationId:true,name:true,slug:true,status:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of categoryExpected)await verifyExisting("Category",byId.get(row.id)??null,row);if(categoryExpected.some(v=>!byId.has(v.id)))await tx.category.createMany({data:categoryExpected.filter(v=>!byId.has(v.id))})});
  await stage(db,async tx=>{const expected=plan.products.map(product=>({id:product.id,organizationId:input.organizationId,categoryId:categoryIds.get(product.category)!,name:product.name,internalCode:product.internalCode,trackingMode:"BULK" as const,publicationStatus:"DRAFT" as const,isRentable:true,isSellable:true})),existing=await tx.product.findMany({where:{id:{in:expected.map(v=>v.id)}},select:{id:true,organizationId:true,categoryId:true,name:true,internalCode:true,trackingMode:true,publicationStatus:true,isRentable:true,isSellable:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of expected){const current=byId.get(row.id);if(current?.publicationStatus!=="ACTIVE")await verifyExisting("Product",current??null,row)}for(const batch of chunks(expected.filter(v=>!byId.has(v.id))))await tx.product.createMany({data:batch})});await checkpoint("PRODUCTS");
  await stage(db,async tx=>{const expected=plan.executions.map(execution=>({id:execution.id,organizationId:input.organizationId,productId:execution.productId,name:execution.name,code:plan.executionApplyCodes[execution.id],sortOrder:0,isActive:true})),existing=await tx.productExecution.findMany({where:{id:{in:expected.map(v=>v.id)}},select:{id:true,organizationId:true,productId:true,name:true,code:true,sortOrder:true,isActive:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of expected)await verifyExisting("Execution",byId.get(row.id)??null,row);for(const batch of chunks(expected.filter(v=>!byId.has(v.id))))await tx.productExecution.createMany({data:batch})});await checkpoint("EXECUTIONS");
  await stage(db,async tx=>{const expected=plan.variants.map(variant=>({id:s(variant.id),organizationId:input.organizationId,productId:s(variant.productId),executionId:variant.executionId?s(variant.executionId):null,sizeId:s(variant.sizeId),sku:s(variant.sku),isActive:true})),existing=await tx.productVariant.findMany({where:{id:{in:expected.map(v=>v.id)}},select:{id:true,organizationId:true,productId:true,executionId:true,sizeId:true,sku:true,isActive:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of expected)await verifyExisting("Variant",byId.get(row.id)??null,row);for(const batch of chunks(expected.filter(v=>!byId.has(v.id))))await tx.productVariant.createMany({data:batch})});await checkpoint("VARIANTS");
  await stage(db,async tx=>{const expected=plan.provenance.map(ref=>({id:stableUuid("source",`${batchId}:${s(ref.sourceKey)}`),organizationId:input.organizationId,importBatchId:batchId,sourceKey:s(ref.sourceKey),sourceRowIndex:n(ref.sourceRowIndex),originalName:s(ref.originalName),originalCategory:s(ref.originalCategory)||null,originalInternalCode:s(ref.originalInternalCode)||null,originalSku:s(ref.originalSku)||null,originalBarcode:s(ref.originalBarcode)||null,sourceQuantity:n(ref.quantity),targetQuantityContribution:n(ref.targetQuantityContribution),targetFingerprint:s(ref.targetFingerprint),productId:s(ref.productId),executionId:ref.executionId?s(ref.executionId):null,productVariantId:s(ref.productVariantId),normalizedMetadata:{sizeSystem:s(ref.system),mapping:ref.mapping??null,legacyStatus:s(ref.legacyStatus),ownerComment:ref.ownerComment??null}})),existing=await tx.catalogSourceReference.findMany({where:{id:{in:expected.map(v=>v.id)}},select:{id:true,organizationId:true,importBatchId:true,sourceKey:true,sourceRowIndex:true,originalName:true,originalCategory:true,originalInternalCode:true,originalSku:true,originalBarcode:true,sourceQuantity:true,targetQuantityContribution:true,targetFingerprint:true,productId:true,executionId:true,productVariantId:true}}),byId=new Map(existing.map(v=>[v.id,v]));for(const row of expected){const {normalizedMetadata:_,...payload}=row;void _;await verifyExisting("Source reference",byId.get(row.id)??null,payload)}for(const batch of chunks(expected.filter(v=>!byId.has(v.id))))await tx.catalogSourceReference.createMany({data:batch})});await checkpoint("PROVENANCE");
  for(let i=0;i<plan.variants.length;i+=25)await stage(db,async tx=>{const rows=plan.variants.slice(i,i+25).map((variant,offset)=>({variant,movement:plan.initialMovements[i+offset],variantId:s(variant.id),quantity:n(variant.quantity)})),variantIds=rows.map(r=>r.variantId),keys=rows.map(r=>s(r.movement.idempotencyKey)),existingMovements=await tx.inventoryMovement.findMany({where:{organizationId:input.organizationId,idempotencyKey:{in:keys}}}),levels=await tx.stockLevel.findMany({where:{organizationId:input.organizationId,productVariantId:{in:variantIds},branchId:input.branchId,locationId:input.locationId}}),movementByKey=new Map(existingMovements.map(v=>[v.idempotencyKey,v])),levelsByVariant=new Map<string,typeof levels>();for(const level of levels){const list=levelsByVariant.get(level.productVariantId)??[];list.push(level);levelsByVariant.set(level.productVariantId,list)}const stockCreates=[],movementCreates=[];for(const row of rows){const existingMovement=movementByKey.get(s(row.movement.idempotencyKey)),variantLevels=levelsByVariant.get(row.variantId)??[];if(variantLevels.length>1)throw new Error(`Multiple StockLevels for ${row.variantId}`);if(existingMovement){if(existingMovement.type!=="INITIAL"||existingMovement.quantity!==row.quantity||existingMovement.productVariantId!==row.variantId||existingMovement.toBranchId!==input.branchId||existingMovement.toLocationId!==input.locationId||variantLevels.length!==1||variantLevels[0].quantity!==row.quantity)throw new Error(`Opening movement replay conflict for ${row.variantId}`);continue}if(variantLevels.length&&variantLevels[0].quantity!==0)throw new Error(`Unexpected existing stock for ${row.variantId}`);if(variantLevels.length)await tx.stockLevel.update({where:{id:variantLevels[0].id},data:{quantity:row.quantity}});else stockCreates.push({id:stableUuid("stock",`${batchId}:${row.variantId}`),organizationId:input.organizationId,productVariantId:row.variantId,branchId:input.branchId,locationId:input.locationId,quantity:row.quantity});movementCreates.push({id:s(row.movement.id),organizationId:input.organizationId,productVariantId:row.variantId,type:"INITIAL" as const,quantity:row.quantity,toBranchId:input.branchId,toLocationId:input.locationId,sourceType:"CATALOG_OPENING_IMPORT",sourceId:batchId,idempotencyKey:s(row.movement.idempotencyKey),reason:`Opening catalog import ${batchId}`})}if(stockCreates.length)await tx.stockLevel.createMany({data:stockCreates});if(movementCreates.length)await tx.inventoryMovement.createMany({data:movementCreates})});await checkpoint("OPENING_STOCK");
  const reconciliation=await verifyAppliedCatalog(db,plan,batchId,input,false);if(!reconciliation.ok)throw new Error(`Pre-finalization reconciliation failed: ${reconciliation.errors.join("; ")}`);await checkpoint("RECONCILED");
  await stage(db,async tx=>{for(const historical of plan.historicalArchivalPlan){
   const product=await tx.product.findUniqueOrThrow({where:{id:historical.productId},select:{id:true,organizationId:true,internalCode:true,trackingMode:true,_count:{select:{variants:true}},variants:{select:{_count:{select:{instances:true}}}}}});
   const instances=product.variants.reduce((sum,v)=>sum+v._count.instances,0),expected=historical.internalCode==="0060"?[5,51]:[3,17];if(product.organizationId!==input.organizationId||product.trackingMode!=="SERIALIZED"||product._count.variants!==expected[0]||instances!==expected[1])throw new Error(`Historical product drift ${historical.internalCode}`);await tx.product.update({where:{id:product.id},data:{publicationStatus:"ARCHIVED",archivedAt:new Date()}})
  }await tx.product.updateMany({where:{organizationId:input.organizationId,id:{in:plan.products.map(product=>product.id)}},data:{publicationStatus:"ACTIVE"}})});await checkpoint("ACTIVATED");
  await db.catalogImportBatch.update({where:{id:batchId},data:{status:"APPLIED",completedAt:new Date(),metadata:{databaseFingerprint:input.databaseFingerprint,stage:"APPLIED"}}});return {batchId,replayed:false};
 }catch(error){await db.catalogImportBatch.updateMany({where:{id:batchId,status:"APPLYING"},data:{metadata:{databaseFingerprint:input.databaseFingerprint,stage:"INTERRUPTED",error:error instanceof Error?error.message:"unknown"}}});throw error}
}

export async function verifyAppliedCatalog(db:Db,plan:FullCatalogPlan,batchId:string,input:Pick<ApplyOptions,"organizationId"|"branchId"|"locationId">,requireApplied=true){
 const errors:string[]=[];const batch=await db.catalogImportBatch.findUnique({where:{id:batchId}});if(!batch)errors.push("batch missing");else if(requireApplied&&batch.status!=="APPLIED")errors.push(`batch status ${batch.status}`);if(batch&&(batch.sourceSha256!==plan.workbook.sha256||batch.planSha256!==plan.planSha256))errors.push("batch hash mismatch");
 const ids=plan.products.map(p=>p.id),variantIds=plan.variants.map(v=>s(v.id));const products=await db.product.count({where:{organizationId:input.organizationId,id:{in:ids}}});const executions=await db.productExecution.count({where:{organizationId:input.organizationId,productId:{in:ids}}});const importedVariants=await db.productVariant.findMany({where:{organizationId:input.organizationId,id:{in:variantIds}},select:{id:true,sku:true}});const variants=importedVariants.length;const refs=await db.catalogSourceReference.count({where:{organizationId:input.organizationId,importBatchId:batchId}});const levels=await db.stockLevel.findMany({where:{organizationId:input.organizationId,productVariantId:{in:variantIds},branchId:input.branchId,locationId:input.locationId},select:{quantity:true}});const movements=await db.inventoryMovement.findMany({where:{organizationId:input.organizationId,sourceType:"CATALOG_OPENING_IMPORT",sourceId:batchId,type:"INITIAL"},select:{quantity:true}});const instances=await db.productInstance.count({where:{organizationId:input.organizationId}});const purchases=await db.purchase.count({where:{organizationId:input.organizationId}});const orders=await db.order.count({where:{organizationId:input.organizationId}});const finance=await db.financialTransaction.count({where:{organizationId:input.organizationId}});
 if(products!==330)errors.push(`products ${products}`);if(executions!==206)errors.push(`executions ${executions}`);if(variants!==1052)errors.push(`variants ${variants}`);if(refs!==1063)errors.push(`references ${refs}`);if(levels.length!==1052||levels.reduce((a,v)=>a+v.quantity,0)!==4915)errors.push("stock reconciliation");if(movements.length!==1052||movements.reduce((a,v)=>a+v.quantity,0)!==4915)errors.push("movement reconciliation");if(instances!==68)errors.push(`historical instances ${instances}`);if(purchases||orders||finance)errors.push("fake business records detected");
 const actualSku=new Map(importedVariants.map(v=>[v.id,v.sku.normalize("NFKC").trim().toUpperCase()]));if(plan.variants.some(v=>actualSku.get(s(v.id))!==s(v.sku).normalize("NFKC").trim().toUpperCase()))errors.push("imported SKU payload mismatch");const preserved=plan.variants.filter(v=>v.skuDecision==="PRESERVED").length,generated=plan.variants.filter(v=>v.skuDecision==="GENERATED").length;if(preserved!==576||generated!==476)errors.push(`SKU decision totals ${preserved}/${generated}`);const allVariantSkus=await db.productVariant.findMany({where:{organizationId:input.organizationId},select:{id:true,sku:true}}),allBarcodes=await db.productInstance.findMany({where:{organizationId:input.organizationId},select:{barcode:true}}),scanOwners=new Map<string,string>();for(const row of allVariantSkus){const key=row.sku.normalize("NFKC").trim().toUpperCase();if(scanOwners.has(key)&&scanOwners.get(key)!==row.id)errors.push(`duplicate variant scan ${key}`);scanOwners.set(key,row.id)}for(const row of allBarcodes){const key=row.barcode.normalize("NFKC").trim().toUpperCase();if(scanOwners.has(key))errors.push(`variant/instance scan collision ${key}`)}
 if(requireApplied){const historical=await db.product.findMany({where:{organizationId:input.organizationId,internalCode:{in:["0060","0142"]}},select:{internalCode:true,publicationStatus:true,trackingMode:true}});if(historical.length!==2||historical.some(p=>p.publicationStatus!=="ARCHIVED"||p.trackingMode!=="SERIALIZED"))errors.push("historical archival mismatch")}
 return {ok:errors.length===0,errors,counts:{products,executions,variants,refs,stockLevels:levels.length,stockQuantity:levels.reduce((a,v)=>a+v.quantity,0),movements:movements.length,movementQuantity:movements.reduce((a,v)=>a+v.quantity,0),historicalInstances:instances,purchases,orders,finance}};
}
