import type {FinancialTransactionKind} from "@/generated/prisma/client";
import Link from "next/link";
import "./reports.css";
import {AppShell} from "@/components/AppShell";
import {requireRouteAccess} from "@/lib/auth/session";
import {hasPermission} from "@/lib/permissions/effective";
import {getCrmReports} from "@/lib/reports/queries";
import {financeFilterOptions,type FinanceRawFilters} from "@/lib/finance/filters";
import {orderStatusLabel,orderTypeLabel} from "@/lib/ui/labels";
const financeLabels:Partial<Record<FinancialTransactionKind,string>>={CASH_EXPENSE:"Расход кассы",RENTAL_CHARGE:"Начисление аренды",SALE_CHARGE:"Начисление продажи",DAMAGE_CHARGE:"Ущерб",DISCOUNT:"Скидка",PAYMENT_RECEIVED:"Оплата",CUSTOMER_REFUND:"Возврат оплаты",DEPOSIT_RECEIVED:"Приём залога",DEPOSIT_REFUNDED:"Возврат залога",DEPOSIT_WITHHELD:"Удержание залога",REVERSAL:"Корректировка"};
const money=(n:bigint,currency:string)=>`${n.toLocaleString("ru-KZ")} ${currency}`;
export default async function Page({searchParams}:{searchParams:Promise<FinanceRawFilters>}){const session=await requireRouteAccess("/reports"),raw=await searchParams;let data:Awaited<ReturnType<typeof getCrmReports>>;try{data=await getCrmReports(session,{from:raw.from,until:raw.until,branchId:raw.branchId})}catch(error){return <AppShell active="/reports" title="Отчёты"><p className="notice error">{error instanceof Error?error.message:"Нет доступа."}</p><Link href="/reports">Сбросить фильтры</Link></AppShell>}
 const options=await financeFilterOptions(session,"REPORT_FINANCE_VIEW"),q=new URLSearchParams({from:data.period.fromLabel,until:data.period.untilLabel,...(raw.branchId?{branchId:raw.branchId}:{})}),ordersQ=new URLSearchParams({from:data.period.fromLabel,until:data.period.endExclusive.toISOString().slice(0,10),dateField:"created",...(raw.branchId?{branchId:raw.branchId}:{})});
 return <AppShell active="/reports" title="Отчёты CRM" subtitle="Операции за период и состояние сейчас показаны отдельно"><form className="panel form-grid report-filters"><label>С даты UTC<input name="from" type="date" defaultValue={data.period.fromLabel} required/></label><label>По дату UTC включительно<input name="until" type="date" defaultValue={data.period.untilLabel} required/></label><label>Филиал<select name="branchId" defaultValue={raw.branchId??""}><option value="">Все доступные</option>{options.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="secondary">Показать</button></form>
 <nav className="report-links" aria-label="Другие отчёты"><Link href={`/reports/funnel?${q}`}>Воронка обращений</Link><Link href={`/reports/products?${q}`}>Аналитика товаров и размеров</Link><Link href={`/finance?${q}`}>Финансовый журнал</Link><a href={`/finance/export?${q}`}>Excel операций</a><a href={`/reports/export?${q}`}>Excel сводки</a><Link href={`/orders?${ordersQ}`}>Заказы периода</Link>{await hasPermission(session,"PURCHASE_VIEW")&&<Link href="/purchases/report">Закупки и поступления</Link>}{await hasPermission(session,"INVENTORY_VIEW")&&<><Link href="/warehouse/movements">Движения склада</Link><Link href="/warehouse">Остатки сейчас</Link></>}</nav>
 <section className="panel"><h2>Финансовые операции периода</h2><p>Эффекты проводок по валютам. Залог показан отдельно от выручки; корректировки уменьшают или увеличивают соответствующий показатель.</p><div className="report-table-scroll"><table className="report-finance-table"><caption className="visually-hidden">Финансовые операции за выбранный период</caption><thead><tr><th scope="col">Операция</th><th scope="col">Валюта</th><th scope="col">Количество</th><th scope="col">Начислено</th><th scope="col">Движение денег</th><th scope="col">Изменение залогов</th><th scope="col">Изменение долга</th></tr></thead><tbody>{data.finance.map(row=><tr key={`${row.currency}-${row.kind}`}><th scope="row">{financeLabels[row.kind] ?? row.kind}</th><td>{row.currency}</td><td>{row.count}</td>{[row.revenueEffectMinor,row.cashEffectMinor,row.depositEffectMinor,row.obligationEffectMinor].map((value,index)=><td key={index}>{value===undefined ? <span aria-label="Нет доступа">—</span> : value.toLocaleString("ru-KZ")}</td>)}</tr>)}</tbody></table></div>{!data.finance.length&&<p>Разрешённых операций в этом периоде нет.</p>}</section>
 <section className="panel"><h2>Заказы и средний чек</h2><p>Заказы, созданные в выбранный период; отменённые, истёкшие и неявки исключены из среднего. Считается текущая договорная стоимость заказа, делённая на число заказов соответствующего типа и валюты. Это не выручка по платежам.</p>{data.orders.map(row=><p key={`${row.type}-${row.currency}`}>{orderTypeLabel(row.type)} · {row.count} заказов · {row.currency}{row.contractTotal!==undefined&&row.averageContract!==undefined&&<> · сумма {money(row.contractTotal,row.currency)} · средний чек {money(row.averageContract,row.currency)}</>}</p>)}<p>Активные клиенты периода по заказам: {data.customerCount??"нет доступа"}. Новые карточки: {data.newCustomers??"нет доступа"}.</p><small>При выборе филиала новые клиенты учитываются только при наличии заказа в этом филиале. У карточки клиента нет собственного филиала.</small></section>
 <section className="panel"><h2>Статусы и ответственные</h2><p>Текущие статусы и назначения заказов, созданных в период; это не историческая оценка работы сотрудников.</p>{data.statuses.map(row=><p key={`${row.type}-${row.status}`}><Link href={`/orders?${ordersQ}&type=${row.type}&status=${row.status}`}>{orderTypeLabel(row.type)} · {orderStatusLabel(row.status)}: {row.count}</Link></p>)}{data.assignees.map(row=><p key={row.id??"none"}><Link href={`/orders?${ordersQ}&assignedMembershipId=${row.id??"UNASSIGNED"}`}>{row.name}: {row.count}</Link></p>)}</section>
 <section className="panel"><h2>Долги и залоги сейчас</h2><p>Полная доступная история на текущий момент, независимо от периода выше. Долг и переплата не взаимозачитываются между заказами.</p>{data.balances.map(row=><p key={row.currency}>{row.currency}{row.debt!==undefined&&<> · долг {money(row.debt,row.currency)} · переплата {money(row.credit??BigInt(0),row.currency)}</>}{row.deposit!==undefined&&<> · удерживаемые залоги {money(row.deposit,row.currency)}</>}</p>)}<Link href={`/orders?payment=UNPAID${raw.branchId?`&branchId=${raw.branchId}`:""}`}>Неоплаченные заказы</Link> · <Link href={`/orders?payment=PARTIAL${raw.branchId?`&branchId=${raw.branchId}`:""}`}>Частично оплаченные</Link></section>
 <section className="panel"><h2>Популярные товары и размеры</h2><p>20 вариантов с наибольшим количеством фактических выдач в аренду за период. Брони и черновики не учитываются.</p>{data.topProducts.map(row=><p key={row.id}><Link href={`/products/${row.variant?.productId}`}>{row.variant?.product.name??row.id} · {row.variant?.execution?.name} · {row.variant?.size.name??row.variant?.size.code} · {row.variant?.sku}</Link>: {row.quantity} выданных единиц ({row.movements} записей движения)</p>)}{!data.topProducts.length&&<p>Выдач за период нет.</p>}</section>
 <section className="panel"><h2>Загрузка и простой</h2><p>{data.historicalUtilization.reason}</p><p>Подтверждённая фактическая аренда за период: {data.rentalQuantityTime.unitDays.toLocaleString("ru-KZ",{maximumFractionDigits:2})} единиц × дней. Учтено {data.rentalQuantityTime.coveredAllocations} выдач; с неполной историей исключено {data.rentalQuantityTime.incompleteAllocations}.</p>{data.inventory&&<p>BULK сейчас: парк {data.inventory.activeFleet}; на складе {data.inventory.physicalOnHand}; в аренде {data.inventory.issuedOutstanding}; резерв сейчас {data.inventory.plannedReservations}; чистка {data.inventory.cleaning}; ремонт {data.inventory.repair}; вид обслуживания не уточнён {data.inventory.unclassifiedMaintenance}. Показатели пересекаются.</p>}</section>
 </AppShell>;
}
