"use server";
import {revalidatePath} from "next/cache";
import {redirect,unstable_rethrow} from "next/navigation";
import {ZodError} from "zod";
import {requireRouteAccess} from "@/lib/auth/session";
import {requireCustomerPermission} from "@/lib/customers/permissions";
import {CustomerError} from "@/lib/customers/errors";
import {addAddress,addContact,addNote,archiveCustomer,archiveNote,createCustomer,updateAddress,updateContact,updateCustomer,updateNote} from "@/lib/customers/management";
import {analyzeImport,confirmImport,createImportPreview,type Mapping} from "@/lib/customers/import";
import {createTenantContext} from "@/lib/tenant/context";
const text=(f:FormData,k:string)=>String(f.get(k)??"").trim(),nullable=(f:FormData,k:string)=>text(f,k)||null,checked=(f:FormData,k:string)=>f.get(k)==="on";
const go=(p:string,k:"ok"|"error",m:string):never=>redirect(`${p}?${k}=${encodeURIComponent(m)}`);
function message(e:unknown){unstable_rethrow(e);return e instanceof CustomerError?e.message:e instanceof ZodError?e.issues[0]?.message??"Проверьте форму.":"Операция не выполнена.";}
async function ctx(action:"WRITE_CUSTOMERS"|"ARCHIVE_CUSTOMERS"|"IMPORT_CUSTOMERS"){const s=await requireRouteAccess("/customers");requireCustomerPermission(s.role,action);return{s,tenant:createTenantContext(s.organizationId)};}
function customer(f:FormData){return{firstName:text(f,"firstName"),lastName:nullable(f,"lastName"),middleName:nullable(f,"middleName"),birthDate:nullable(f,"birthDate"),preferredLanguage:nullable(f,"preferredLanguage"),source:text(f,"source"),status:text(f,"status")||"ACTIVE",marketingConsent:checked(f,"marketingConsent")};}
function contacts(f:FormData){return[{type:"PHONE" as const,value:text(f,"phone"),label:"Основной",isPrimary:true},{type:"PHONE" as const,value:text(f,"phone2"),label:"Дополнительный",isPrimary:false},{type:"EMAIL" as const,value:text(f,"email"),label:null,isPrimary:true}].filter(x=>x.value);}
export async function createCustomerAction(f:FormData){try{const{s,tenant}=await ctx("WRITE_CUSTOMERS");const c=await createCustomer(tenant,{customer:customer(f),contacts:contacts(f),createdByUserId:s.userId,allowDuplicate:checked(f,"allowDuplicate")});revalidatePath("/customers");redirect(`/customers/${c.id}?ok=${encodeURIComponent("Клиент создан.")}`);}catch(e){if((e as {digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;const d=e instanceof CustomerError?e.duplicates[0]:undefined;redirect(`/customers/new?error=${encodeURIComponent(message(e))}${d?`&duplicate=${d.id}&duplicateLabel=${encodeURIComponent(`${d.customerNumber} ${d.name}`)}`:""}`);}}
export async function updateCustomerAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await updateCustomer(tenant,id,customer(f));revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Данные сохранены.");}catch(e){go(`/customers/${id}/edit`,"error",message(e));}}
export async function archiveCustomerAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("ARCHIVE_CUSTOMERS");await archiveCustomer(tenant,id);revalidatePath("/customers");go(`/customers/${id}`,"ok","Клиент архивирован.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function restoreCustomerAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("ARCHIVE_CUSTOMERS");await updateCustomer(tenant,id,{...customer(f),status:"ACTIVE"});revalidatePath("/customers");go(`/customers/${id}`,"ok","Клиент восстановлен.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function addContactAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await addContact(tenant,id,{type:text(f,"type") as "PHONE"|"EMAIL"|"OTHER",value:text(f,"value"),label:nullable(f,"label"),isPrimary:checked(f,"isPrimary"),allowDuplicate:checked(f,"allowDuplicate")});revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Контакт добавлен.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function updateContactAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await updateContact(tenant,text(f,"contactId"),{type:text(f,"type") as "PHONE"|"EMAIL"|"OTHER",value:text(f,"value"),label:nullable(f,"label"),isPrimary:checked(f,"isPrimary"),allowDuplicate:checked(f,"allowDuplicate")});revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Контакт обновлён.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function addAddressAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await addAddress(tenant,id,{type:text(f,"type"),country:nullable(f,"country"),city:nullable(f,"city"),addressLine:text(f,"addressLine"),comment:nullable(f,"comment"),isPrimary:checked(f,"isPrimary")});revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Адрес добавлен.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function updateAddressAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await updateAddress(tenant,text(f,"addressId"),{type:text(f,"type"),country:nullable(f,"country"),city:nullable(f,"city"),addressLine:text(f,"addressLine"),comment:nullable(f,"comment"),isPrimary:checked(f,"isPrimary")});revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Адрес обновлён.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function addNoteAction(f:FormData){const id=text(f,"customerId");try{const{s,tenant}=await ctx("WRITE_CUSTOMERS");await addNote(tenant,id,{text:text(f,"text")},s.userId);revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Заметка добавлена.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function updateNoteAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await updateNote(tenant,text(f,"noteId"),{text:text(f,"text")});revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Заметка обновлена.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function archiveNoteAction(f:FormData){const id=text(f,"customerId");try{const{tenant}=await ctx("WRITE_CUSTOMERS");await archiveNote(tenant,text(f,"noteId"));revalidatePath(`/customers/${id}`);go(`/customers/${id}`,"ok","Заметка архивирована.");}catch(e){go(`/customers/${id}`,"error",message(e));}}
export async function uploadImportAction(f:FormData){try{const{s,tenant}=await ctx("IMPORT_CUSTOMERS");const file=f.get("file");if(!(file instanceof File))throw new CustomerError("IMPORT_INVALID","Выберите файл.");const b=await createImportPreview(tenant,file,s.userId);redirect(`/customers/import/${b.id}`);}catch(e){if((e as {digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;go("/customers/import","error",message(e));}}
export async function analyzeImportAction(f:FormData){const id=text(f,"batchId");try{const{tenant}=await ctx("IMPORT_CUSTOMERS");const m:Mapping={firstName:Number(text(f,"firstName"))};for(const k of ["lastName","middleName","phone","email","birthDate","source","city","address","comment"] as const){const v=text(f,k);if(v)m[k]=Number(v);}await analyzeImport(tenant,id,m);redirect(`/customers/import/${id}?analyzed=1`);}catch(e){if((e as {digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;go(`/customers/import/${id}`,"error",message(e));}}
export async function confirmImportAction(f:FormData){const id=text(f,"batchId");try{const{s,tenant}=await ctx("IMPORT_CUSTOMERS");const r=await confirmImport(tenant,id,s.userId);revalidatePath("/customers");redirect(`/customers?ok=${encodeURIComponent(`Импортировано: ${r.imported}; пропущено: ${r.skipped}; ошибок: ${r.errors}.`)}`);}catch(e){if((e as {digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;go(`/customers/import/${id}`,"error",message(e));}}
