import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { OperationalItemSelector } from "@/components/OperationalItemSelector";
import { requireRouteAccess } from "@/lib/auth/session";
import { hasPermission, requirePermission } from "@/lib/permissions/effective";
import { getStocktake } from "@/lib/stocktake/queries";
import { createTenantContext } from "@/lib/tenant/context";
import { bulkAction, cancelAction, completeAction, reconcileAction, resolveAction } from "../actions";

type Stocktake=NonNullable<Awaited<ReturnType<typeof getStocktake>>>;
type Variant=Stocktake["bulkCounts"][number]["productVariant"];
const variantLabel=(variant:Variant)=>[variant.execution?.name,variant.size.name||variant.size.code].filter(Boolean).join(" · ");

export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){
  const session=await requireRouteAccess("/warehouse/stocktakes/x");await requirePermission(session,"STOCKTAKE_VIEW");const [canCount,canReconcile]=await Promise.all([hasPermission(session,"STOCKTAKE_COUNT"),hasPermission(session,"STOCKTAKE_RECONCILE")]),{id}=await params,query=await searchParams,stocktake=await getStocktake(createTenantContext(session.organizationId),id);if(!stocktake)notFound();
  const scanned=new Set(stocktake.scans.map(row=>row.productInstanceId)),missing=stocktake.expectedItems.filter(row=>!scanned.has(row.productInstanceId)),countedBulk=stocktake.bulkCounts.filter(row=>row.countedQuantity!=null).length;
  return <AppShell active="/warehouse" title={`Инвентаризация · ${stocktake.location.name}`} subtitle={`${stocktake.branch.name} · ${stocktake.status}`}>
    {(query.ok||query.error)&&<div className={query.error?"alert error":"alert success"}>{query.error||query.ok}</div>}
    <section className="card stocktake-progress" aria-label="Прогресс инвентаризации"><span><b>{countedBulk}</b> / {stocktake.bulkCounts.length}<small>BULK пересчитано</small></span><span><b>{stocktake.scans.length}</b> / {stocktake.expectedItems.length}<small>SERIALIZED учтено</small></span></section>
    {stocktake.status==="IN_PROGRESS"&&canCount&&<section className="card operational-scan-entry stocktake-mobile-entry"><div><h2>Пересчитать товар</h2><p>Найдите товар и отдельно подтвердите фактическое количество.</p></div><OperationalItemSelector purpose="STOCKTAKE_COUNT" stocktakeSessionId={id} triggerLabel="Сканировать товар" prompt="Сканируйте товар для пересчёта"/></section>}
    <div className="stocktake-desktop-sheet"><SerializedSection stocktake={stocktake} missing={missing} canReconcile={canReconcile}/><BulkSection stocktake={stocktake} canCount={canCount} canReconcile={canReconcile}/>{stocktake.status==="IN_PROGRESS"&&canCount&&<StocktakeActions id={id}/>}</div>
    <details className="card stocktake-mobile-sheet"><summary>Все позиции <span>{stocktake.bulkCounts.length+stocktake.expectedItems.length}</span></summary><SerializedSection stocktake={stocktake} missing={missing} canReconcile={canReconcile}/><BulkSection stocktake={stocktake} canCount={canCount} canReconcile={canReconcile}/></details>
    {stocktake.status==="IN_PROGRESS"&&canCount&&<details className="card stocktake-mobile-controls"><summary>Действия с инвентаризацией</summary><StocktakeActions id={id}/></details>}
    {stocktake.status==="COUNTED"&&canReconcile&&<form action={reconcileAction}><input type="hidden" name="sessionId" value={id}/><button>Завершить сверку</button></form>}
  </AppShell>
}

function StocktakeActions({id}:{id:string}){return <div className="toolbar stocktake-actions"><form action={completeAction}><input type="hidden" name="sessionId" value={id}/><button>Завершить подсчёт</button></form><form action={cancelAction}><input type="hidden" name="sessionId" value={id}/><button className="secondary">Отменить</button></form></div>}

function SerializedSection({stocktake,missing,canReconcile}:{stocktake:Stocktake;missing:Stocktake["expectedItems"];canReconcile:boolean}){return <section className="card stocktake-section"><h2>SERIALIZED</h2><p>Ожидалось {stocktake.expectedItems.length} · отсканировано {stocktake.scans.length} · не найдено {missing.length}</p><div className="stocktake-mobile-list">{stocktake.scans.map(row=><div className="inventory-row stocktake-row" key={row.id}><div><strong>{row.productInstance.productVariant.product.name}</strong><small>{variantLabel(row.productInstance.productVariant)} · {row.productInstance.inventoryNumber}</small></div><span>{row.classification}</span>{stocktake.status==="COUNTED"&&canReconcile&&row.classification!=="MATCHED"&&<form action={resolveAction}><input type="hidden" name="sessionId" value={stocktake.id}/><input type="hidden" name="kind" value="scan"/><input type="hidden" name="recordId" value={row.id}/><select name="resolution"><option>ACKNOWLEDGED</option><option>ACCEPT_LOCATION</option><option>ACCEPT_TRANSFER</option><option>FOUND</option></select><input name="reason" required placeholder="Причина"/><button>Решить</button></form>}</div>)}{stocktake.status==="COUNTED"&&missing.map(row=><div className="inventory-row stocktake-row" key={row.id}><div><strong>{row.productInstance.productVariant.product.name}</strong><small>{variantLabel(row.productInstance.productVariant)} · {row.productInstance.inventoryNumber} · Не найден</small></div>{canReconcile&&<form action={resolveAction}><input type="hidden" name="sessionId" value={stocktake.id}/><input type="hidden" name="kind" value="missing"/><input type="hidden" name="recordId" value={row.id}/><select name="resolution"><option>ACKNOWLEDGED</option><option>MARK_LOST</option></select><input name="reason" required placeholder="Причина"/><button>Решить</button></form>}</div>)}</div></section>}

function BulkSection({stocktake,canCount,canReconcile}:{stocktake:Stocktake;canCount:boolean;canReconcile:boolean}){return <section className="card stocktake-section"><h2>BULK</h2><div className="stocktake-mobile-list">{stocktake.bulkCounts.map(row=>{const difference=row.countedQuantity==null?null:row.countedQuantity-row.expectedQuantity;return <form action={stocktake.status==="IN_PROGRESS"?bulkAction:resolveAction} className="inventory-row stocktake-row" key={row.id}><input type="hidden" name="sessionId" value={stocktake.id}/><input type="hidden" name="variantId" value={row.productVariantId}/><input type="hidden" name="recordId" value={row.id}/><input type="hidden" name="kind" value="bulk"/><div><strong>{row.productVariant.product.name}</strong><small>{variantLabel(row.productVariant)}</small><small>Ожидалось {row.expectedQuantity} · Фактически {row.countedQuantity??"—"} · Разница {difference==null?"—":difference>0?`+${difference}`:difference}</small></div><input name="count" type="number" min="0" inputMode="numeric" defaultValue={row.countedQuantity??""} disabled={stocktake.status!=="IN_PROGRESS"||!canCount}/>{stocktake.status==="IN_PROGRESS"?canCount&&<button>Сохранить</button>:canReconcile&&row.countedQuantity!==row.expectedQuantity&&<><select name="resolution"><option>ACKNOWLEDGED</option><option>APPLY_ADJUSTMENT</option></select><input name="reason" required placeholder="Причина"/><button>Решить</button></>}</form>})}</div></section>}
