import type { AppRole } from "@/lib/auth/access";

export const PERMISSION_REGISTRY = {
  CATALOG_VIEW:["CATALOG","Просмотр каталога"],CATALOG_CREATE:["CATALOG","Создание товаров"],CATALOG_EDIT:["CATALOG","Редактирование каталога"],CATALOG_ARCHIVE:["CATALOG","Архивация товаров"],CATALOG_PHOTO_MANAGE:["CATALOG","Управление фотографиями"],CATALOG_PURCHASE_COST_VIEW:["CATALOG","Просмотр закупочной стоимости"],
  CUSTOMER_VIEW:["CUSTOMERS","Просмотр клиентов"],CUSTOMER_CREATE:["CUSTOMERS","Создание клиентов"],CUSTOMER_EDIT:["CUSTOMERS","Редактирование клиентов"],CUSTOMER_ARCHIVE:["CUSTOMERS","Архивация клиентов"],CUSTOMER_IMPORT:["CUSTOMERS","Импорт клиентов"],
  LEAD_VIEW:["LEADS","Просмотр обращений"],LEAD_CREATE:["LEADS","Создание обращений"],LEAD_EDIT:["LEADS","Работа с обращениями"],LEAD_ASSIGN:["LEADS","Назначение ответственного"],LEAD_CLOSE:["LEADS","Закрытие обращений"],LEAD_CONVERT_TO_ORDER:["LEADS","Преобразование обращения в заказ"],
  ORDER_VIEW:["ORDERS","Просмотр заказов"],ORDER_CREATE:["ORDERS","Создание заказов"],ORDER_EDIT:["ORDERS","Редактирование заказов"],ORDER_CANCEL:["ORDERS","Отмена заказов"],
  RENTAL_RESERVE:["RENTALS","Бронирование"],RENTAL_CONFIRM:["RENTALS","Подтверждение брони"],RENTAL_PREPARE:["RENTALS","Подготовка заказа"],RENTAL_ISSUE:["RENTALS","Выдача аренды"],
  RETURN_PROCESS:["RETURNS","Приём возврата"],RETURN_INSPECT:["RETURNS","Осмотр возврата"],MAINTENANCE_COMPLETE:["RETURNS","Завершение чистки и ремонта"],
  INVENTORY_VIEW:["INVENTORY","Просмотр склада"],INVENTORY_RECEIVE:["INVENTORY","Приёмка товара"],INVENTORY_TRANSFER:["INVENTORY","Перемещение товара"],INVENTORY_ADJUST:["INVENTORY","Корректировка остатков"],INVENTORY_WRITE_OFF:["INVENTORY","Списание и потери"],
  STOCKTAKE_VIEW:["STOCKTAKE","Просмотр инвентаризаций"],STOCKTAKE_COUNT:["STOCKTAKE","Проведение подсчёта"],STOCKTAKE_RECONCILE:["STOCKTAKE","Сверка инвентаризации"],
  STAFF_VIEW:["STAFF","Просмотр сотрудников"],STAFF_INVITE:["STAFF","Приглашение сотрудников"],STAFF_EDIT:["STAFF","Изменение сотрудников"],STAFF_DEACTIVATE:["STAFF","Отключение сотрудников"],STAFF_PERMISSION_MANAGE:["STAFF","Управление индивидуальными правами"],
  PAYMENT_VIEW:["FINANCE","Просмотр платежей"],PAYMENT_CREATE:["FINANCE","Создание платежей"],PAYMENT_REFUND:["FINANCE","Возврат платежей"],FINANCE_DASHBOARD_VIEW:["FINANCE","Финансовая панель"],FINANCE_PURCHASE_COST_VIEW:["FINANCE","Закупочная стоимость"],FINANCE_MARGIN_VIEW:["FINANCE","Маржинальность"],PURCHASE_VIEW:["PURCHASES","Просмотр закупок"],PURCHASE_CREATE:["PURCHASES","Создание закупок"],PURCHASE_EDIT:["PURCHASES","Редактирование закупок"],PURCHASE_CANCEL:["PURCHASES","Отмена закупок"],REPORT_FINANCE_VIEW:["REPORTS","Финансовые отчёты"],
} as const;
export type PermissionKey=keyof typeof PERMISSION_REGISTRY;export type PermissionCategory=typeof PERMISSION_REGISTRY[PermissionKey][0];
const operational=["CATALOG_VIEW","CATALOG_PHOTO_MANAGE","CUSTOMER_VIEW","CUSTOMER_CREATE","CUSTOMER_EDIT","LEAD_VIEW","LEAD_CREATE","LEAD_EDIT","LEAD_CLOSE","LEAD_CONVERT_TO_ORDER","ORDER_VIEW","ORDER_CREATE","ORDER_EDIT","RENTAL_RESERVE","RENTAL_CONFIRM","RENTAL_PREPARE","RENTAL_ISSUE","RETURN_PROCESS","RETURN_INSPECT","MAINTENANCE_COMPLETE","INVENTORY_VIEW","INVENTORY_RECEIVE","STOCKTAKE_VIEW","STOCKTAKE_COUNT"]as const;
const director=[...operational,"LEAD_ASSIGN","CATALOG_CREATE","CATALOG_EDIT","CATALOG_ARCHIVE","CATALOG_PURCHASE_COST_VIEW","CUSTOMER_ARCHIVE","CUSTOMER_IMPORT","ORDER_CANCEL","INVENTORY_TRANSFER","INVENTORY_ADJUST","INVENTORY_WRITE_OFF","STOCKTAKE_RECONCILE","STAFF_VIEW","STAFF_INVITE","STAFF_EDIT","STAFF_DEACTIVATE","FINANCE_DASHBOARD_VIEW","FINANCE_PURCHASE_COST_VIEW","FINANCE_MARGIN_VIEW","PURCHASE_VIEW","REPORT_FINANCE_VIEW"]as const;
export const ROLE_DEFAULT_PERMISSIONS:Record<AppRole,ReadonlySet<PermissionKey>>={OWNER:new Set(Object.keys(PERMISSION_REGISTRY)as PermissionKey[]),DIRECTOR:new Set(director),SELLER:new Set(operational),CASHIER:new Set(["CATALOG_VIEW","CUSTOMER_VIEW","ORDER_VIEW","INVENTORY_VIEW","STOCKTAKE_VIEW"])};
export function isPermissionKey(value:string):value is PermissionKey{return value in PERMISSION_REGISTRY}
export function defaultHasPermission(role:AppRole,key:PermissionKey){return role==="OWNER"||ROLE_DEFAULT_PERMISSIONS[role].has(key)}
