import "server-only";
import type { Prisma } from "@/generated/prisma/client";
import { InventoryError } from "@/lib/inventory/errors";

export async function member(tx:Prisma.TransactionClient,organizationId:string,userId:string){if(!await tx.organizationMembership.findFirst({where:{organizationId,userId,status:"ACTIVE"},select:{id:true}}))throw new InventoryError("NOT_FOUND","Ресурс не найден.");}
export async function movement(tx:Prisma.TransactionClient,data:Prisma.InventoryMovementUncheckedCreateInput){return tx.inventoryMovement.create({data});}
export async function issueInventory(tx:Prisma.TransactionClient,input:{organizationId:string;branchId:string;variantId:string;instanceId:string|null;allocationId:string;quantity:number;userId:string}){
  if(input.instanceId){await movement(tx,{organizationId:input.organizationId,productVariantId:input.variantId,productInstanceId:input.instanceId,type:"RENTAL_ISSUE",quantity:-1,fromBranchId:input.branchId,sourceType:"CAPACITY_ALLOCATION",sourceId:input.allocationId,idempotencyKey:`rental-issue:${input.allocationId}`,createdByUserId:input.userId});return;}
  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${input.organizationId+":stock:"+input.branchId+":"+input.variantId},0))`;
  const levels=await tx.stockLevel.findMany({where:{organizationId:input.organizationId,branchId:input.branchId,productVariantId:input.variantId,quantity:{gt:0}},orderBy:{createdAt:"asc"}});let remaining=input.quantity;
  for(const level of levels){const take=Math.min(level.quantity,remaining);if(!take)continue;await tx.stockLevel.update({where:{id:level.id},data:{quantity:{decrement:take}}});await movement(tx,{organizationId:input.organizationId,productVariantId:input.variantId,type:"RENTAL_ISSUE",quantity:-take,fromBranchId:input.branchId,fromLocationId:level.locationId,sourceType:"CAPACITY_ALLOCATION",sourceId:input.allocationId,idempotencyKey:`rental-issue:${input.allocationId}:${level.id}`,createdByUserId:input.userId});remaining-=take;if(!remaining)break;}
  if(remaining)throw new InventoryError("INSUFFICIENT_STOCK","Недостаточно физического остатка для выдачи.");
}
export async function returnSerializedInventory(tx:Prisma.TransactionClient,input:{organizationId:string;branchId:string;locationId:string;variantId:string;instanceId:string;allocationId:string;userId:string}){await movement(tx,{organizationId:input.organizationId,productVariantId:input.variantId,productInstanceId:input.instanceId,type:"RENTAL_RETURN",quantity:1,toBranchId:input.branchId,toLocationId:input.locationId,sourceType:"CAPACITY_ALLOCATION",sourceId:input.allocationId,idempotencyKey:`rental-return:${input.allocationId}`,createdByUserId:input.userId});}
export async function returnBulkInventory(tx:Prisma.TransactionClient,input:{organizationId:string;branchId:string;variantId:string;allocationId:string;fromReturned:number;quantity:number;userId:string}){
  const issues=await tx.inventoryMovement.findMany({where:{organizationId:input.organizationId,sourceId:input.allocationId,type:"RENTAL_ISSUE"},orderBy:{createdAt:"asc"}});let skip=input.fromReturned,remaining=input.quantity;
  for(const issue of issues){let available=Math.abs(issue.quantity);const used=Math.min(skip,available);skip-=used;available-=used;const take=Math.min(available,remaining);if(!take)continue;let level=await tx.stockLevel.findFirst({where:{organizationId:input.organizationId,productVariantId:input.variantId,branchId:input.branchId,locationId:issue.fromLocationId}});level=level?await tx.stockLevel.update({where:{id:level.id},data:{quantity:{increment:take}}}):await tx.stockLevel.create({data:{organizationId:input.organizationId,productVariantId:input.variantId,branchId:input.branchId,locationId:issue.fromLocationId,quantity:take}});await movement(tx,{organizationId:input.organizationId,productVariantId:input.variantId,type:"RENTAL_RETURN",quantity:take,toBranchId:input.branchId,toLocationId:issue.fromLocationId,sourceType:"CAPACITY_ALLOCATION",sourceId:input.allocationId,idempotencyKey:`rental-return:${input.allocationId}:${input.fromReturned+input.quantity-remaining+take}`,createdByUserId:input.userId});remaining-=take;if(!remaining)break;}
  if(remaining)throw new InventoryError("INVALID","История выдачи BULK не соответствует возврату.");
}
