import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { EmptyState, SectionCard, StatusChip } from "@/components/ui";
import { Icon, type IconName } from "@/components/ui/Icon";
import { requireRouteAccess } from "@/lib/auth/session";
import { getDashboard, type DashboardMoney, type DashboardPeriodPreset } from "@/lib/dashboard/queries";
import { createTenantContext } from "@/lib/tenant/context";
import { DASHBOARD_WARNING_LABELS, dashboardStatusLabel } from "@/lib/ui/labels";
import "./dashboard.css";

type Raw=Promise<Record<string,string|string[]|undefined>>;
const presets:Array<[DashboardPeriodPreset,string]>=[["TODAY","Сегодня"],["SEVEN_DAYS","7 дней"],["THIS_MONTH","Этот месяц"],["LAST_MONTH","Прошлый месяц"],["CUSTOM","Период"]];
const one=(value:string|string[]|undefined)=>typeof value==="string"?value:undefined;
const money=(rows?:DashboardMoney[])=>rows?.length?rows.map(x=>`${BigInt(x.amountMinor).toLocaleString("ru-KZ")} ${x.currency}`).join(" · "):"0";
const local=(value:Date,zone:string)=>new Intl.DateTimeFormat("ru-KZ",{timeZone:zone,day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(value);
const quickIcon=(href:string):IconName=>href.startsWith("/orders")?"orders":href.startsWith("/products")?"products":href.startsWith("/returns")?"return":"warehouse";
const alertTone=(type:string):"danger"|"warning"|"info"=>type==="OVERDUE_RETURN"||type==="DEBT_AFTER_RETURN"?"danger":type==="DAMAGE_DECISION_REQUIRED"||type==="DEPOSIT_REVIEW_REQUIRED"?"warning":"info";

export default async function DashboardPage({searchParams}:{searchParams:Raw}){
  const session=await requireRouteAccess("/"),raw=await searchParams,preset=(one(raw.period)??"TODAY")as DashboardPeriodPreset;
  const data=await getDashboard(createTenantContext(session.organizationId),{preset,start:one(raw.start),end:one(raw.end),branchId:one(raw.branch)},session);
  if(!data)return <AppShell active="/" title="Главная"><p className="notice error">Главная страница временно недоступна.</p></AppShell>;
  const finance=data.financial,operations=data.operations,firstName=session.displayName.trim().split(/\s+/)[0]||"коллега";
  return <AppShell active="/" title={`Добрый день, ${firstName}`} subtitle="Рабочая сводка и задачи магазина">
    <form className="dashboard-context" method="get" aria-label="Параметры сводки"><div className="dashboard-date"><span>Сегодня</span><strong>{new Intl.DateTimeFormat("ru-KZ",{timeZone:data.timeZone,dateStyle:"long"}).format(data.generatedAt)}</strong></div><label><span>Филиал</span><select name="branch" defaultValue={data.scope.selectedBranchId??""}><option value="">Все доступные филиалы</option>{data.scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}{b.status!=="ACTIVE"?" · неактивен":""}</option>)}</select></label><label><span>Период</span><select name="period" defaultValue={preset}>{presets.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{preset==="CUSTOM"&&<><label><span>С</span><input type="date" name="start" defaultValue={one(raw.start)}/></label><label><span>По</span><input type="date" name="end" defaultValue={one(raw.end)}/></label></>}<button className="secondary" type="submit">Показать</button></form>

    <div className="dashboard-workbench">
      <SectionCard title="Быстрые действия" description="Частые операции" className="dashboard-quick"><div className="quick-grid">{data.quickActions.map(x=><Link href={x.href} key={x.href}><span className="quick-icon"><Icon name={quickIcon(x.href)}/></span><span>{x.label}</span><Icon name="arrow" size={15}/></Link>)}{!data.quickActions.length&&<EmptyState compact title="Нет доступных действий"/>}</div></SectionCard>
      <SectionCard title="Ближайшие" description="Выдачи и возвраты" className="dashboard-upcoming">{data.upcoming.length?<div className="timeline-list">{data.upcoming.map(x=><Link href={`/orders/${x.orderId}`} className="timeline-row" key={`${x.type}-${x.orderId}`}><time>{local(x.at,data.timeZone)}</time><span className={`timeline-symbol ${x.type.toLowerCase()}`}><Icon name={x.type==="ISSUE"?"orders":"return"}/></span><span className="timeline-main"><strong>{x.type==="ISSUE"?"Выдача":"Возврат"} · {x.customer}</strong><small>{x.orderNumber} · {x.items}</small><small>{x.branch}</small></span><StatusChip tone={x.type==="ISSUE"?"info":"warning"}>{dashboardStatusLabel(x.status)}</StatusChip></Link>)}</div>:<EmptyState compact title="Ближайших событий нет" description="На выбранный период задач не найдено."/>}</SectionCard>
    </div>

    {(finance||operations)&&<section className="dashboard-kpis" aria-label="Ключевые показатели">{finance?.netAccruedRevenue&&<Kpi label="Начисленная выручка" value={money(finance.netAccruedRevenue)} note="За выбранный период"/>}{finance?.paymentsReceived&&<Kpi label="Получено оплат" value={money(finance.paymentsReceived)} note="Без залогов"/>}{finance?.outstandingDebt&&<Kpi label="Долг клиентов" value={money(finance.outstandingDebt)} note="На текущий момент" tone="danger"/>}{finance?.heldDeposits&&<Kpi label="Удерживается залогов" value={money(finance.heldDeposits)} note="Не является выручкой"/>}{operations&&<Kpi label="Активно в аренде" value={String(operations.activeRentalQuantity)} note={`Просрочено: ${operations.overdueQuantity}`} tone={operations.overdueQuantity?"danger":"default"}/>}{operations&&<Kpi label="Выдано за период" value={String(operations.issuedQuantity)} note={`${operations.issuedOrderCount} заказов`}/>} {finance?.acquisitionReceived&&<Kpi label="Принято по закупкам" value={money(finance.acquisitionReceived)} note="За выбранный период"/>}</section>}

    {data.alerts.length>0&&<SectionCard title="Требует внимания" description="Задачи, которые мешают завершить работу" className="dashboard-section attention-card"><div className="attention-list">{data.alerts.map((x,index)=><article key={`${x.type}-${x.orderId??x.productInstanceId}-${index}`}><span className={`attention-icon ${alertTone(x.type)}`}><Icon name="alert"/></span><span>{x.label}</span>{x.orderId&&<Link href={`/orders/${x.orderId}`} className="row-action">{x.actionAllowed?"Перейти к действию":"Открыть"}<Icon name="arrow" size={14}/></Link>}</article>)}</div></SectionCard>}

    {(finance?.daily.length||operations?.daily.length)?<section className="dashboard-dynamics dashboard-section">{finance&&<SectionCard title="Денежная динамика" description="Начисления, оплаты и возвраты по дням"><div className="metric-list">{finance.daily.map(x=><div key={x.date}><time>{formatDay(x.date)}</time>{x.revenue&&<Metric label="Начислено" value={money(x.revenue)}/>} {x.payments&&<Metric label="Оплаты" value={money(x.payments)}/>} {x.refunds&&<Metric label="Возвраты" value={money(x.refunds)}/>}</div>)}</div></SectionCard>}{operations&&<SectionCard title="Движение аренд" description="Фактически выданные и возвращённые товары"><div className="metric-list">{operations.daily.map(x=><div key={x.date}><time>{formatDay(x.date)}</time><Metric label="Выдано" value={String(x.issued)}/><Metric label="Возвращено" value={String(x.returned)}/></div>)}</div></SectionCard>}</section>:null}

    {data.products.length>0&&<SectionCard title="Товары" description="Экономика за всё время" className="dashboard-section"><div className="dashboard-table"><div className="dashboard-table-head"><span>Модель</span><span>Начислено</span><span>Выдано</span><span>Окупаемость</span></div>{data.products.map(x=><Link href={`/products/${x.productId}`} className="dashboard-table-row" key={`${x.productId}-${x.currency}`}><strong>{x.name}</strong><span>{BigInt(x.rentalRevenueMinor).toLocaleString("ru-KZ")} {x.currency}</span><span>{x.issuedQuantity}</span><span>{x.rentalPaybackBasisPoints&&x.scopeComplete&&x.costCoverageComplete&&x.revenueAttributionComplete?`${(Number(x.rentalPaybackBasisPoints)/100).toLocaleString("ru-KZ")}%`:"Окупаемость недоступна"}</span></Link>)}</div></SectionCard>}

    {data.branches.length>1&&<SectionCard title="Филиалы" description="Сравнение за выбранный период" className="dashboard-section"><div className="branch-grid">{data.branches.map(x=><article key={x.branchId}><span className="branch-icon"><Icon name="branch"/></span><strong>{x.branchName}</strong>{x.netRevenue&&<small>Начислено: {money(x.netRevenue)}</small>}{x.netCustomerCash&&<small>Получено от клиентов: {money(x.netCustomerCash)}</small>}</article>)}</div>{(!data.scope.allActiveBranchesCovered||!data.scope.historicalScopeComplete)&&<p className="scope-note">Показаны только филиалы и история, доступные вашей учётной записи.</p>}</SectionCard>}

    {(data.integrityWarnings.length||data.products.some(x=>!x.revenueAttributionComplete||!x.scopeComplete))?<SectionCard title="Нужно проверить данные" className="dashboard-section dashboard-integrity"><div className="integrity-list">{data.integrityWarnings.map(x=><p key={x}>{DASHBOARD_WARNING_LABELS[x]??"Обнаружено несоответствие данных. Обратитесь к руководителю."}</p>)}{data.products.some(x=>!x.revenueAttributionComplete||!x.scopeComplete)&&<p>Экономика части товаров рассчитана по неполной истории.</p>}</div></SectionCard>:null}
  </AppShell>;
}

function Kpi({label,value,note,tone="default"}:{label:string;value:string;note:string;tone?:"default"|"danger"}){return <article className={`kpi-card ${tone}`}><span>{label}</span><strong title={value}>{value}</strong><small>{note}</small></article>}
function Metric({label,value}:{label:string;value:string}){return <span><small>{label}</small><b>{value}</b></span>}
function formatDay(value:string){const date=new Date(`${value}T00:00:00Z`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("ru-KZ",{day:"2-digit",month:"short",timeZone:"UTC"}).format(date)}
