"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { recordStocktakeItemAction, resolveCatalogIdentifierAction, resolveOperationalContextAction, resolveOrderIdentifierAction, searchOperationalItemsAction } from "@/app/scan-actions";
import type { OperationalContext, OperationalContextActionResult, OperationalIdentifierResult, OperationalSearchHit, SafeSize, ScanPurpose } from "@/lib/inventory/operational-contract";
import type { CameraDecoderSession, CameraDiagnostic, CameraFailure } from "@/lib/scanning/camera-adapter";

const cameraMessages: Record<CameraFailure,string> = { PERMISSION_DENIED: "Доступ к камере запрещён. Разрешите камеру в настройках Safari или введите код вручную.", UNSUPPORTED: "Камера недоступна в этом браузере. Введите код вручную.", UNAVAILABLE: "Не удалось открыть камеру. Возможно, она занята другим приложением." };
const sizeLabel=(size:SafeSize)=>size.sizeSystem==="ONE_SIZE"?"Без размера":size.sizeSystem==="VOLUME_ML"?`${size.code} мл`:size.recommendedHeightCm?`${size.code} · рост ${size.recommendedHeightCm} см`:size.lengthCm?`${size.code} · ${size.lengthCm} см`:size.name||size.code;

export function OperationalItemSelector({triggerLabel="Сканировать",compact=false,purpose="CATALOG_LOOKUP",prompt="Наведите камеру на штрихкод",stocktakeSessionId,branchId,onSelect,onProductSelectionRequired}:{triggerLabel?:string;compact?:boolean;purpose?:"CATALOG_LOOKUP"|"ORDER_ITEM_SELECT"|"RETURN_RECEIVE"|"WAREHOUSE_LOOKUP"|"STOCKTAKE_COUNT";prompt?:string;stocktakeSessionId?:string;branchId?:string;onSelect?:(result:Extract<OperationalIdentifierResult,{kind:"BULK_VARIANT"|"SERIALIZED_INSTANCE"}>)=>void;onProductSelectionRequired?:(result:Extract<OperationalIdentifierResult,{kind:"PRODUCT_NEEDS_VARIANT_SELECTION"}>)=>void}) {
  const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[result,setResult]=useState<OperationalIdentifierResult|null>(null),[context,setContext]=useState<OperationalContext|null>(null),[hits,setHits]=useState<OperationalSearchHit[]>([]),[message,setMessage]=useState(""),[cameraState,setCameraState]=useState<"idle"|"starting"|"active">("idle"),[diagnostic,setDiagnostic]=useState<CameraDiagnostic|null>(null),[restartRequested,setRestartRequested]=useState(false);
  const [pending,startTransition]=useTransition(); const videoRef=useRef<HTMLVideoElement>(null),sessionRef=useRef<CameraDecoderSession|null>(null),acceptedRef=useRef(false),lastSubmitRef=useRef<{value:string;at:number}>({value:"",at:0});
  const stopCamera=useCallback(()=>{sessionRef.current?.stop();sessionRef.current=null;setCameraState("idle");},[]);
  const close=useCallback(()=>{stopCamera();setOpen(false);setResult(null);setContext(null);setHits([]);setMessage("");},[stopCamera]);
  const resolve=useCallback((raw:string)=>{const value=raw.trim(),now=Date.now();if(!value||pending||(lastSubmitRef.current.value===value&&now-lastSubmitRef.current.at<1200))return;if(purpose==="ORDER_ITEM_SELECT"&&!branchId){setMessage("Сначала выберите филиал.");return;}lastSubmitRef.current={value,at:now};acceptedRef.current=true;stopCamera();setMessage("");setHits([]);startTransition(async()=>{const response=purpose==="CATALOG_LOOKUP"?await resolveCatalogIdentifierAction(value):purpose==="ORDER_ITEM_SELECT"?await resolveOrderIdentifierAction(value,branchId!):await resolveOperationalContextAction(value,purpose,stocktakeSessionId);if(!response.ok){setMessage(response.message);return;}setResult(response.result);setContext(purpose==="CATALOG_LOOKUP"||purpose==="ORDER_ITEM_SELECT"?null:(response as Extract<OperationalContextActionResult,{ok:true}>).context);if(response.result.kind==="NOT_FOUND")setMessage("Код не найден. Проверьте код или найдите товар по названию.");else if(response.result.kind==="NOT_AVAILABLE")setMessage("Товар найден, но сейчас недоступен для операций.");else if(response.result.kind==="AMBIGUOUS_IDENTIFIER")setMessage("Код неоднозначен. Обратитесь к администратору каталога.");});},[branchId,pending,purpose,stocktakeSessionId,stopCamera]);
  const startCamera=useCallback(async()=>{stopCamera();acceptedRef.current=false;setDiagnostic(null);setMessage("");setCameraState("starting");try{const {createCameraDecoderAdapter}=await import("@/lib/scanning/zxing-camera-adapter");if(!videoRef.current)return;sessionRef.current=await createCameraDecoderAdapter().start(videoRef.current,value=>{if(acceptedRef.current)return;acceptedRef.current=true;setQuery(value);resolve(value)},setDiagnostic);setCameraState("active")}catch(error){setCameraState("idle");const failure=(error as {cameraFailure?:CameraFailure}).cameraFailure??"UNAVAILABLE";setMessage(cameraMessages[failure])}},[resolve,stopCamera]);
  const scanAgain=useCallback(()=>{setResult(null);setContext(null);setHits([]);setQuery("");setMessage("");lastSubmitRef.current={value:"",at:0};acceptedRef.current=false;setRestartRequested(true)},[]);
  useEffect(()=>{if(restartRequested&&result===null&&videoRef.current){setRestartRequested(false);void startCamera()}},[restartRequested,result,startCamera]);
  useEffect(()=>{const pagehide=()=>stopCamera(),visibility=()=>{if(document.hidden)stopCamera()};window.addEventListener("pagehide",pagehide);document.addEventListener("visibilitychange",visibility);return()=>{window.removeEventListener("pagehide",pagehide);document.removeEventListener("visibilitychange",visibility);stopCamera()}},[stopCamera]);
  const search=()=>startTransition(async()=>{setResult(null);setContext(null);setMessage("");const response=await searchOperationalItemsAction(query,purpose as ScanPurpose,branchId);if(response.ok)setHits(response.results);else setMessage(response.message)});
  const resolved=result&&result.kind!=="NOT_FOUND"&&result.kind!=="NOT_AVAILABLE"&&result.kind!=="AMBIGUOUS_IDENTIFIER"?result:null;
  return <>
    <button type="button" className={compact?"scan-trigger compact":"scan-trigger"} onClick={()=>setOpen(true)} aria-haspopup="dialog">⌁ <span>{triggerLabel}</span></button>
    {open&&<div className="scanner-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="scanner-sheet" role="dialog" aria-modal="true" aria-label="Поиск и сканирование товара">
      <header><div><strong>{purpose==="RETURN_RECEIVE"?"Найти возврат":purpose==="WAREHOUSE_LOOKUP"?"Найти на складе":purpose==="STOCKTAKE_COUNT"?"Пересчитать товар":purpose==="ORDER_ITEM_SELECT"?"Добавить в заказ":"Найти товар"}</strong><small>Код, сканер или камера</small></div><button type="button" onClick={close} aria-label="Закрыть">×</button></header>
      {resolved?<ResolvedResult result={resolved} context={context} purpose={purpose} onResolve={resolve} onScanAgain={scanAgain} onSelect={result=>{onSelect?.(result);close()}} onProductSelectionRequired={result=>{onProductSelectionRequired?.(result);close()}} stocktakeSessionId={stocktakeSessionId} setContext={setContext} setMessage={setMessage}/>:<><div className="camera-stage"><video ref={videoRef} muted playsInline/><span className="camera-frame"/><p>{cameraState==="starting"?"Открываем камеру…":cameraState==="active"?prompt:"Камера выключена"}</p></div><button type="button" className="primary camera-button" onClick={cameraState==="active"?stopCamera:startCamera} disabled={cameraState==="starting"}>{cameraState==="active"?"Остановить камеру":"Открыть камеру"}</button>{diagnostic&&<details className="scanner-diagnostic"><summary>Диагностика камеры</summary><span>{diagnostic.decoder} · {diagnostic.videoWidth}×{diagnostic.videoHeight}</span><span>{diagnostic.cameraLabel??"Камера"} · {diagnostic.lastDecodeState}</span><small>{diagnostic.formats.join(", ")}</small></details>}</>}
      <form className="scanner-input" onSubmit={event=>{event.preventDefault();resolve(query)}}><label>Код / SKU / штрихкод<input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Tab"&&query.trim()){event.preventDefault();resolve(query)}}} autoComplete="off" inputMode="text" placeholder="Введите или отсканируйте код"/></label><button className="secondary" disabled={pending}>Найти код</button></form>
      <button type="button" className="scanner-name-search" onClick={search} disabled={pending||query.trim().length<2}>Искать по названию</button>
      {message&&<p className="scanner-message" role="status">{message}</p>}
      {hits.length>0&&<div className="scanner-results" aria-label="Результаты поиска">{hits.map(hit=>purpose!=="CATALOG_LOOKUP"&&hit.variant?<button type="button" key={`${hit.product.id}-${hit.variant.id}`} onClick={()=>resolve(hit.variant!.sku)}><strong>{hit.product.name}</strong><span>{hit.variant.execution?.name}{hit.variant.execution?" · ":""}{sizeLabel(hit.variant.size)}</span><small>SKU {hit.variant.sku}</small></button>:<Link key={`${hit.product.id}-${hit.variant?.id??"product"}`} href={`/products/${hit.product.id}`} onClick={stopCamera}><strong>{hit.product.name}</strong><span>{hit.variant?.execution?.name}{hit.variant?.execution?" · ":""}{hit.variant?sizeLabel(hit.variant.size):"Открыть товар"}</span>{hit.variant&&<small>SKU {hit.variant.sku}</small>}</Link>)}</div>}
      <p className="scanner-privacy">Видео обрабатывается только на устройстве и не загружается.</p>
    </section></div>}
  </>;
}

function ResolvedResult({result,context,purpose,onResolve,onScanAgain,onSelect,onProductSelectionRequired,stocktakeSessionId,setContext,setMessage}:{result:Exclude<OperationalIdentifierResult,{kind:"NOT_FOUND"|"NOT_AVAILABLE"|"AMBIGUOUS_IDENTIFIER"}>;context:OperationalContext|null;purpose:"CATALOG_LOOKUP"|"ORDER_ITEM_SELECT"|"RETURN_RECEIVE"|"WAREHOUSE_LOOKUP"|"STOCKTAKE_COUNT";onResolve:(sku:string)=>void;onScanAgain:()=>void;onSelect:(result:Extract<OperationalIdentifierResult,{kind:"BULK_VARIANT"|"SERIALIZED_INSTANCE"}>)=>void;onProductSelectionRequired:(result:Extract<OperationalIdentifierResult,{kind:"PRODUCT_NEEDS_VARIANT_SELECTION"}>)=>void;stocktakeSessionId?:string;setContext:(value:OperationalContext|null)=>void;setMessage:(value:string)=>void}){
  if(result.kind==="PRODUCT_NEEDS_VARIANT_SELECTION")return <div className="scanner-success" role="status"><b className="scanner-success-title">Выберите вариант</b><strong>{result.product.name}</strong><div className="scanner-variants">{result.variants.map(variant=>purpose==="CATALOG_LOOKUP"?<Link key={variant.id} href={`/products/${result.product.id}?variant=${variant.id}`}>{variant.execution?.name&&<b>{variant.execution.name} · </b>}{sizeLabel(variant.size)}</Link>:<button type="button" key={variant.id} onClick={()=>onResolve(variant.sku)}>{variant.execution?.name&&<b>{variant.execution.name} · </b>}{sizeLabel(variant.size)}</button>)}</div><div className="scanner-success-actions">{purpose==="ORDER_ITEM_SELECT"?<button type="button" className="primary" onClick={()=>onProductSelectionRequired(result)}>Проверить доступность вариантов</button>:<Link className="primary" href={`/products/${result.product.id}`}>Открыть товар</Link>}<button type="button" className="secondary" onClick={onScanAgain}>Сканировать ещё</button></div></div>;
  if(purpose==="STOCKTAKE_COUNT"&&(context?.kind==="STOCKTAKE_BULK"||context?.kind==="STOCKTAKE_SERIALIZED"))return <StocktakeResult result={result} context={context} sessionId={stocktakeSessionId??""} onSaved={next=>{setContext(next);setMessage("")}} onError={setMessage} onScanAgain={onScanAgain}/>;
  if(purpose==="ORDER_ITEM_SELECT")return <div className="scanner-success" role="status"><b className="scanner-success-title">✓ Товар найден</b><strong>{result.product.name}</strong><span>{result.execution?.name&&`${result.execution.name} · `}{sizeLabel(result.variant.size)}</span><small>{result.kind==="SERIALIZED_INSTANCE"?`Экземпляр ${result.instance.inventoryNumber}; в заказ добавится вариант, экземпляр назначается при подготовке`:`SKU ${result.variant.sku}`}</small><div className="scanner-success-actions"><button type="button" className="primary" onClick={()=>onSelect(result)}>Выбрать товар</button><button type="button" className="secondary" onClick={onScanAgain}>Сканировать ещё</button></div></div>;
  const returnOrderId=context?.kind==="RETURN_SERIALIZED"?context.order.id:context?.kind==="RETURN_BULK"&&context.orders.length===1?context.orders[0].orderId:null;
  const primaryHref=returnOrderId?`/orders/${returnOrderId}`:`/products/${result.product.id}`;
  const primaryLabel=purpose==="RETURN_RECEIVE"&&returnOrderId?"Продолжить возврат":"Открыть товар";
  return <div className="scanner-success" role="status"><b className="scanner-success-title">✓ Товар найден</b><strong>{result.product.name}</strong><span>{result.execution?.name&&`${result.execution.name} · `}{sizeLabel(result.variant.size)}</span><small>{result.kind==="SERIALIZED_INSTANCE"?`Экземпляр ${result.instance.inventoryNumber} · ${result.instance.barcode} · ${result.instance.operationalStatus}`:`SKU ${result.variant.sku}`}</small><ContextDetails context={context}/><div className="scanner-success-actions"><Link className="primary" href={primaryHref}>{primaryLabel}</Link><button type="button" className="secondary" onClick={onScanAgain}>Сканировать ещё</button></div></div>;
}

function StocktakeResult({result,context,sessionId,onSaved,onError,onScanAgain}:{result:Exclude<OperationalIdentifierResult,{kind:"NOT_FOUND"|"NOT_AVAILABLE"|"AMBIGUOUS_IDENTIFIER"|"PRODUCT_NEEDS_VARIANT_SELECTION"}>;context:Extract<OperationalContext,{kind:"STOCKTAKE_BULK"|"STOCKTAKE_SERIALIZED"}>;sessionId:string;onSaved:(context:Extract<OperationalContext,{kind:"STOCKTAKE_BULK"|"STOCKTAKE_SERIALIZED"}>)=>void;onError:(message:string)=>void;onScanAgain:()=>void}){
  const router=useRouter();const [count,setCount]=useState(context.kind==="STOCKTAKE_BULK"&&context.countedQuantity!=null?String(context.countedQuantity):"");const[pending,startTransition]=useTransition();
  const numeric=count===""?null:Number(count),difference=context.kind==="STOCKTAKE_BULK"&&numeric!=null&&Number.isInteger(numeric)?numeric-context.expectedQuantity:null;
  const save=()=>startTransition(async()=>{const response=await recordStocktakeItemAction(sessionId,result.normalizedIdentifier,context.kind==="STOCKTAKE_BULK"?Number(count):undefined);if(!response.ok){onError(response.message);return;}onSaved(response.context);router.refresh()});
  return <div className="scanner-success stocktake-scan-result" role="status"><b className="scanner-success-title">{context.kind==="STOCKTAKE_SERIALIZED"&&context.alreadyObserved?"✓ Экземпляр учтён":"Товар найден"}</b><strong>{result.product.name}</strong><span>{result.execution?.name&&`${result.execution.name} · `}{sizeLabel(result.variant.size)}</span><small>{context.locationName}</small>{context.kind==="STOCKTAKE_BULK"?<><div className="stocktake-figures"><span>Ожидалось <b>{context.expectedQuantity}</b></span><span>Фактически <b>{context.countedQuantity??"—"}</b></span><span>Разница <b className={(difference??context.difference??0)<0?"negative":(difference??context.difference??0)>0?"positive":""}>{difference??context.difference??"—"}</b></span></div><label className="stocktake-count-input">Фактически<input type="number" min="0" step="1" inputMode="numeric" value={count} onChange={event=>setCount(event.target.value)} placeholder="0"/></label><button type="button" className="primary" disabled={pending||numeric==null||!Number.isInteger(numeric)||numeric<0} onClick={save}>Сохранить количество</button></>:<><div className="scanner-context"><b>{context.alreadyObserved?"Уже отсканирован":classificationLabel(context.classification)}</b><span>Экземпляр {result.kind==="SERIALIZED_INSTANCE"?result.instance.inventoryNumber:""}</span></div>{!context.alreadyObserved&&<button type="button" className="primary" disabled={pending} onClick={save}>Учесть экземпляр</button>}</>}<button type="button" className="secondary stocktake-next" onClick={onScanAgain}>Следующий товар</button></div>
}

const classificationLabel=(value:"MATCHED"|"WRONG_LOCATION"|"WRONG_BRANCH"|"UNEXPECTED")=>({MATCHED:"Совпадает с ожидаемым",WRONG_LOCATION:"Другая зона хранения",WRONG_BRANCH:"Другой филиал",UNEXPECTED:"Не ожидался в этом пересчёте"}[value]);

function ContextDetails({context}:{context:OperationalContext|null}){if(!context||context.kind==="STOCKTAKE_BULK"||context.kind==="STOCKTAKE_SERIALIZED")return null;if(context.kind==="RETURN_SERIALIZED")return <div className="scanner-context"><b>{context.overdue?"Возврат просрочен":"Можно принять возврат"}</b><span>{context.order.orderNumber} · {context.order.customerName}</span><small>{context.order.branchName}</small></div>;if(context.kind==="RETURN_BULK")return <div className="scanner-context"><b>{context.orders.length>1?"Выберите заказ":context.orders.length===1?"Можно продолжить возврат":"Нет невозвращённого количества"}</b>{context.orders.map(order=><Link key={order.allocationId} href={`/orders/${order.orderId}`}>{order.orderNumber} · {order.customerName} · {order.outstanding} шт.</Link>)}</div>;if(context.kind==="RETURN_NOT_ELIGIBLE")return <div className="scanner-context warning"><b>Возврат сейчас недоступен</b><span>{context.message}</span></div>;if(context.kind==="WAREHOUSE_BULK")return <div className="scanner-context"><b>Остатки по доступным местам</b>{context.levels.length?context.levels.map(level=><span key={`${level.branchId}-${level.locationId??"none"}`}>{level.branchName} · {level.locationName}: <b>{level.quantity}</b></span>):<span>Остаток отсутствует</span>}</div>;return <div className="scanner-context"><b>{context.branchName} · {context.locationName}</b><span>{context.operationalStatus} · {context.conditionStatus}</span></div>}
