"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useFormStatus } from "react-dom";
import type { OrderChannel } from "@/generated/prisma/client";
import { OperationalItemSelector } from "@/components/OperationalItemSelector";
import { quoteRentalVariantAction, searchRentalCustomersAction, searchRentalItemsAction } from "@/app/orders/mobile-actions";
import type { OperationalIdentifierResult, SafeSize } from "@/lib/inventory/operational-contract";
import type { RentalVariantQuote } from "@/lib/orders/mobile";
import { orderChannelLabel } from "@/lib/ui/labels";

type Customer={id:string;customerNumber:string;firstName:string;lastName:string|null;contacts?:Array<{value:string}>};
type Variant={id:string;sku:string;product:{name:string;internalCode?:string};execution?:{name:string}|null;size:{name:string;code:string;sizeSystem?:string};priceMinor?:string|null};
type Opt={customers:Customer[];branches:Array<{id:string;name:string}>;variants:Variant[]};
type Existing={id:string;branchId:string;customerId:string;channel:OrderChannel;rentalStartAt:Date|null;rentalEndAt:Date|null;discountTotalMinor:bigint;internalComment:string|null};
type DraftLine=RentalVariantQuote&{quantity:number;unitPriceMinor:string;discountMinor:string;adjustmentReason:string;needsRecheck:boolean};

const money=(value:bigint,currency="KZT")=>`${value.toLocaleString("ru-KZ")} ${currency==="KZT"?"₸":currency}`;
const sizeLabel=(size:SafeSize|Variant["size"])=>size.sizeSystem==="ONE_SIZE"?"Без размера":size.sizeSystem==="VOLUME_ML"?`${size.code} мл`:("recommendedHeightCm" in size&&size.recommendedHeightCm)?`${size.code} · рост ${size.recommendedHeightCm} см`:("lengthCm" in size&&size.lengthCm)?`${size.code} · ${size.lengthCm} см`:size.name||size.code;
const localDate=(date:Date|null)=>date?new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16):"";
const asMoney=(raw:string)=>/^\d+$/.test(raw)?BigInt(raw):BigInt(0);

function Submit({editing,disabled=false}:{editing:boolean;disabled?:boolean}){const{pending}=useFormStatus();return <button className="primary order-submit" disabled={pending||disabled} aria-busy={pending}>{pending?"Сохраняем…":editing?"Сохранить изменения":"Создать заказ"}</button>}

export function OrderForm({action,options,order}:{action:(formData:FormData)=>void|Promise<void>;options:Opt;defaultVariantId?:string;order?:Existing}){
  if(order)return <EditOrderForm action={action} options={options} order={order}/>;
  return <RentalOrderBuilder action={action} options={options}/>;
}

function RentalOrderBuilder({action,options}:{action:(formData:FormData)=>void|Promise<void>;options:Opt}){
  const [branchId,setBranchId]=useState(options.branches.length===1?options.branches[0]!.id:"");
  const [rentalStart,setRentalStart]=useState(""),[rentalEnd,setRentalEnd]=useState("");
  const [customerQuery,setCustomerQuery]=useState(""),[customers,setCustomers]=useState(options.customers.slice(0,12)),[customerId,setCustomerId]=useState("");
  const [itemQuery,setItemQuery]=useState(""),[quotes,setQuotes]=useState<RentalVariantQuote[]>([]),[lines,setLines]=useState<DraftLine[]>([]);
  const [orderDiscount,setOrderDiscount]=useState("0"),[message,setMessage]=useState("");
  const [pending,startTransition]=useTransition();
  const customer=customers.find(item=>item.id===customerId)||options.customers.find(item=>item.id===customerId);
  const contextReady=Boolean(branchId&&rentalStart&&rentalEnd&&new Date(rentalEnd)>new Date(rentalStart));
  const markContextChanged=()=>{setQuotes([]);setLines(current=>current.map(line=>({...line,needsRecheck:true})));};
  const context=(quantity=1)=>({branchId,rentalStart,rentalEnd,quantity});

  const searchCustomers=()=>startTransition(async()=>{const response=await searchRentalCustomersAction(customerQuery);if(response.ok)setCustomers(response.results);else setMessage(response.message)});
  const loadItems=(query:string)=>{if(!contextReady){setMessage("Сначала выберите филиал и период аренды.");return;}startTransition(async()=>{const response=await searchRentalItemsAction(query,context());if(response.ok){setQuotes(response.results);setMessage(response.results.length?"":"Товары не найдены.")}else setMessage(response.message)})};
  const searchItems=()=>loadItems(itemQuery);
  const addVariant=(variantId:string,serialized=false)=>startTransition(async()=>{
    if(!contextReady){setMessage("Сначала выберите филиал и период аренды.");return;}
    const existing=lines.find(line=>line.variantId===variantId),quantity=(existing?.quantity??0)+1,response=await quoteRentalVariantAction(variantId,context(quantity));
    if(!response.ok){setMessage(response.message);return;}
    if(!response.result.canFulfill){setMessage(`На выбранные даты доступно ${response.result.availableCapacity}, требуется ${quantity}.`);return;}
    setLines(current=>existing?current.map(line=>line.variantId===variantId?{...line,...response.result,quantity,needsRecheck:false}:line):[...current,{...response.result,quantity:1,unitPriceMinor:response.result.priceMinor??"",discountMinor:"0",adjustmentReason:"",needsRecheck:false}]);
    setMessage(serialized?"В заказ добавлен вариант. Конкретный экземпляр назначается при подготовке.":"Товар добавлен в заказ.");
  });
  const onScanned=(result:Extract<OperationalIdentifierResult,{kind:"BULK_VARIANT"|"SERIALIZED_INSTANCE"}>)=>addVariant(result.variant.id,result.kind==="SERIALIZED_INSTANCE");
  const changeQuantity=(variantId:string,value:number)=>{if(!Number.isInteger(value)||value<1)return;startTransition(async()=>{const response=await quoteRentalVariantAction(variantId,context(value));if(!response.ok){setMessage(response.message);return;}setLines(current=>current.map(line=>line.variantId===variantId?{...line,...response.result,quantity:value,needsRecheck:false}:line));if(!response.result.canFulfill)setMessage(`Для этой позиции доступно ${response.result.availableCapacity}, требуется ${value}.`)})};
  const recheck=()=>startTransition(async()=>{const checked:DraftLine[]=[];for(const line of lines){const response=await quoteRentalVariantAction(line.variantId,context(line.quantity));if(!response.ok){setMessage(response.message);return;}checked.push({...line,...response.result,needsRecheck:false})}setLines(checked);setMessage(checked.every(line=>line.canFulfill)?"Все позиции доступны на выбранные даты.":"Некоторых позиций недостаточно на выбранные даты.")});
  const total=lines.reduce((sum,line)=>sum+asMoney(line.unitPriceMinor)*BigInt(line.quantity)-asMoney(line.discountMinor),BigInt(0))-asMoney(orderDiscount);
  const payload=JSON.stringify(lines.map(line=>({productVariantId:line.variantId,quantity:line.quantity,unitPriceMinor:line.unitPriceMinor||undefined,discountMinor:line.discountMinor||"0",adjustmentReason:line.adjustmentReason||null})));
  const disabled=!branchId||!customerId||!contextReady||lines.length===0||pending||lines.some(line=>!line.canFulfill);

  return <form action={action} className="order-workspace mobile-rental-order">
    <input type="hidden" name="customerId" value={customerId}/><input type="hidden" name="itemsJson" value={payload}/>
    <div className="order-builder">
      <section className="ui-card order-step"><header><i>1</i><div><h2>Клиент</h2><p>Найдите по имени, телефону или номеру.</p></div></header>{customer?<div className="selected-entity"><span><b>{customer.firstName} {customer.lastName}</b><small>{customer.customerNumber}{customer.contacts?.[0]?.value?` · ${customer.contacts[0].value}`:""}</small></span><button type="button" className="text-button" onClick={()=>setCustomerId("")}>Изменить</button></div>:<><div className="lookup-row"><input value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();searchCustomers()}}} placeholder="Телефон, имя или номер"/><button type="button" className="secondary" onClick={searchCustomers} disabled={pending||customerQuery.trim().length<2}>Найти</button></div><div className="lookup-results" role="listbox">{customers.map(item=><button type="button" key={item.id} onClick={()=>setCustomerId(item.id)}><b>{item.firstName} {item.lastName}</b><small>{item.customerNumber}{item.contacts?.[0]?.value?` · ${item.contacts[0].value}`:""}</small></button>)}{!customers.length&&<p>Клиент не найден.</p>}</div><Link href="/customers/new" className="ui-button secondary">+ Новый клиент</Link></>}</section>
      <section className="ui-card order-step"><header><i>2</i><div><h2>Период аренды</h2><p>Этот период используется для расчёта доступности.</p></div></header><label>Филиал<select name="branchId" required value={branchId} onChange={event=>{setBranchId(event.target.value);markContextChanged()}}><option value="">Выберите филиал</option>{options.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><div className="rental-dates"><label>Начало<input type="datetime-local" name="rentalStart" required value={rentalStart} onChange={event=>{setRentalStart(event.target.value);markContextChanged()}}/></label><label>Возврат<input type="datetime-local" name="rentalEnd" required value={rentalEnd} onChange={event=>{setRentalEnd(event.target.value);markContextChanged()}}/></label></div></section>
      <section className="ui-card order-step rental-items-step"><header><i>3</i><div><h2>Товары</h2><p>Поиск, код, аппаратный сканер или камера.</p></div></header><div className="rental-item-tools"><OperationalItemSelector triggerLabel="Сканировать товар" purpose="ORDER_ITEM_SELECT" branchId={branchId} onSelect={onScanned} onProductSelectionRequired={result=>{setItemQuery(result.product.code);loadItems(result.product.code)}}/><div className="lookup-row"><input value={itemQuery} onChange={event=>setItemQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();searchItems()}}} placeholder="Например: Белоснежка 120"/><button type="button" className="secondary" onClick={searchItems} disabled={pending||itemQuery.trim().length<2}>Найти</button></div></div>{quotes.length>0&&<div className="rental-search-results" aria-label="Товары на выбранные даты">{quotes.map(quote=><article key={quote.variantId}><div><strong>{quote.product.name}</strong><span>{quote.execution?.name&&`${quote.execution.name} · `}{sizeLabel(quote.size)}</span><small>SKU {quote.sku}</small></div><div className={quote.canFulfill?"availability available":"availability unavailable"}><b>{quote.canFulfill?"Доступно":"Недоступно"}</b><span>{quote.availableCapacity} из {quote.totalCapacity}</span></div><button type="button" className="secondary" disabled={!quote.canFulfill||pending} onClick={()=>addVariant(quote.variantId)}>Добавить</button></article>)}</div>}
        <div className="rental-basket">{lines.map(line=><article key={line.variantId} className={!line.canFulfill?"unavailable":""}><div className="rental-line-identity"><strong>{line.product.name}</strong><span>{line.execution?.name&&`${line.execution.name} · `}{sizeLabel(line.size)}</span><small>{line.trackingMode==="SERIALIZED"?"SERIALIZED · экземпляр назначается позже":`SKU ${line.sku}`}</small></div><label>Кол-во<input type="number" min="1" inputMode="numeric" value={line.quantity} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,quantity:Math.max(1,Number(event.target.value)||1),needsRecheck:true}:item))} onBlur={()=>changeQuantity(line.variantId,line.quantity)}/></label><label>Цена<input inputMode="numeric" pattern="[0-9]*" required={!line.priceMinor} value={line.unitPriceMinor} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,unitPriceMinor:event.target.value.replace(/\D/g,"")}:item))} placeholder="Цена аренды"/></label><label>Скидка<input inputMode="numeric" pattern="[0-9]*" value={line.discountMinor} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,discountMinor:event.target.value.replace(/\D/g,"")}:item))}/></label><button type="button" className="text-button danger-text" onClick={()=>setLines(current=>current.filter(item=>item.variantId!==line.variantId))}>Удалить</button><span className="rental-line-state">{line.needsRecheck?"Будет перепроверено":line.canFulfill?`Доступно ${line.availableCapacity}`:`Недостаточно: ${line.availableCapacity}`}</span></article>)}{!lines.length&&<p className="muted">Добавьте хотя бы один товар.</p>}</div>{lines.some(line=>line.needsRecheck)&&<button type="button" className="secondary" onClick={recheck} disabled={!contextReady||pending}>Перепроверить доступность</button>}</section>
      <details className="ui-card order-step order-extra"><summary>Дополнительно</summary><div className="form-grid"><label>Источник<select name="source" defaultValue="CRM">{["CRM","PHONE","WHATSAPP","INSTAGRAM","WEBSITE","OTHER"].map(value=><option value={value} key={value}>{orderChannelLabel(value)}</option>)}</select></label><label>Скидка заказа<input name="discountMinor" inputMode="numeric" pattern="[0-9]*" value={orderDiscount} onChange={event=>setOrderDiscount(event.target.value.replace(/\D/g,""))}/></label></div><label>Внутренний комментарий<textarea name="internalComment" maxLength={4000}/></label></details>
      {message&&<p className="notice" role="status">{message}</p>}
    </div>
    <aside className="ui-card order-checkout"><div><h2>Итог</h2><span>{lines.length} поз. · {lines.reduce((sum,line)=>sum+line.quantity,0)} шт.</span></div><strong>{total>=0?money(total):"Проверьте скидки"}</strong><small>Цена и доступность повторно проверяются сервером. Заказ создаётся как черновик.</small><Submit editing={false} disabled={disabled}/></aside>
  </form>;
}

function EditOrderForm({action,options,order}:{action:(formData:FormData)=>void|Promise<void>;options:Opt;order:Existing}){
  const [customerQuery,setCustomerQuery]=useState(""),[customerId,setCustomerId]=useState(order.customerId),[orderDiscount,setOrderDiscount]=useState(order.discountTotalMinor.toString());
  const customers=useMemo(()=>{const query=customerQuery.trim().toLocaleLowerCase("ru");return(query?options.customers.filter(customer=>`${customer.customerNumber} ${customer.firstName} ${customer.lastName??""} ${customer.contacts?.map(contact=>contact.value).join(" ")??""}`.toLocaleLowerCase("ru").includes(query)):options.customers).slice(0,12)},[customerQuery,options.customers]);
  const customer=options.customers.find(item=>item.id===customerId);
  return <form action={action} className="order-workspace"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="customerId" value={customerId}/><div className="order-builder"><section className="ui-card order-step"><header><i>1</i><div><h2>Тип и филиал</h2></div></header><div className="order-type-switch"><button type="button" className="active">Аренда</button><button type="button" disabled>Продажа</button></div><label>Филиал<select name="branchId" required defaultValue={order.branchId}><option value="">Выберите филиал</option>{options.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label></section><section className="ui-card order-step"><header><i>2</i><div><h2>Клиент</h2></div></header><input value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Имя, телефон или номер"/>{customer?<div className="selected-entity"><span><b>{customer.firstName} {customer.lastName}</b><small>{customer.customerNumber}</small></span><button type="button" className="text-button" onClick={()=>setCustomerId("")}>Изменить</button></div>:<div className="lookup-results">{customers.map(item=><button type="button" key={item.id} onClick={()=>setCustomerId(item.id)}><b>{item.firstName} {item.lastName}</b><small>{item.customerNumber}</small></button>)}</div>}</section><section className="ui-card order-step"><header><i>3</i><div><h2>Период аренды</h2></div></header><div className="rental-dates"><label>Начало<input type="datetime-local" name="rentalStart" required defaultValue={localDate(order.rentalStartAt)}/></label><label>Возврат<input type="datetime-local" name="rentalEnd" required defaultValue={localDate(order.rentalEndAt)}/></label></div></section><section className="ui-card order-step"><header><i>4</i><div><h2>Дополнительно</h2></div></header><div className="form-grid"><label>Источник<select name="source" defaultValue={order.channel}>{["CRM","PHONE","WHATSAPP","INSTAGRAM","WEBSITE","OTHER"].map(value=><option value={value} key={value}>{orderChannelLabel(value)}</option>)}</select></label><label>Скидка заказа<input name="discountMinor" inputMode="numeric" value={orderDiscount} onChange={event=>setOrderDiscount(event.target.value.replace(/\D/g,""))}/></label></div><label>Комментарий<textarea name="internalComment" maxLength={4000} defaultValue={order.internalComment??""}/></label></section></div><aside className="ui-card order-checkout"><h2>Изменения</h2><Submit editing={true}/></aside></form>;
}
