"use client";
import {RetainedActionForm,type RetainedFormAction} from "@/components/RetainedActionForm";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { useFormStatus } from "react-dom";
import type { OrderChannel } from "@/generated/prisma/client";
import { OperationalItemSelector } from "@/components/OperationalItemSelector";
import { quoteRentalVariantAction, searchRentalCustomersAction, searchRentalItemsAction } from "@/app/orders/mobile-actions";
import type { OperationalIdentifierResult, SafeSize } from "@/lib/inventory/operational-contract";
import type { RentalVariantQuote } from "@/lib/orders/mobile";
import { orderChannelLabel } from "@/lib/ui/labels";
import { formatBusinessLocalDateTimeInput } from "@/lib/calendar/timezone";

type Customer={id:string;customerNumber:string;firstName:string;lastName:string|null;contacts?:Array<{value:string}>};
type Variant={id:string;sku:string;product:{name:string;internalCode?:string};execution?:{name:string}|null;size:{name:string;code:string;sizeSystem?:string};priceMinor?:string|null};
type Opt={customers:Customer[];branches:Array<{id:string;name:string;timezone:string}>;variants:Variant[]};
type Existing={id:string;branchId:string;customerId:string;channel:OrderChannel;rentalStartAt:Date|null;rentalEndAt:Date|null;discountTotalMinor:bigint;internalComment:string|null};
type DraftLine=RentalVariantQuote&{quantity:number;unitPriceMinor:string;discountMinor:string;adjustmentReason:string;needsRecheck:boolean};

const money=(value:bigint,currency="KZT")=>`${value.toLocaleString("ru-KZ")} ${currency==="KZT"?"₸":currency}`;
const sizeLabel=(size:SafeSize|Variant["size"])=>size.sizeSystem==="ONE_SIZE"?"Без размера":size.sizeSystem==="VOLUME_ML"?`${size.code} мл`:("recommendedHeightCm" in size&&size.recommendedHeightCm)?`${size.code} · рост ${size.recommendedHeightCm} см`:("lengthCm" in size&&size.lengthCm)?`${size.code} · ${size.lengthCm} см`:size.name||size.code;
const localDate=(date:Date|null,timeZone:string)=>date?formatBusinessLocalDateTimeInput(date,timeZone):"";
const asMoney=(raw:string)=>/^\d+$/.test(raw)?BigInt(raw):BigInt(0);
const meaningfulLength=(value:string)=>(value.match(/[\p{L}\p{N}]/gu)??[]).length;

function Submit({editing,disabled=false}:{editing:boolean;disabled?:boolean}){const{pending}=useFormStatus();return <button className="primary order-submit" disabled={pending||disabled} aria-busy={pending}>{pending?"Сохраняем…":editing?"Сохранить изменения":"Создать заказ"}</button>}

type CommercialAccess={canOverridePrice:boolean;canDiscount:boolean};
export function OrderForm({action,options,order,canOverridePrice,canDiscount}:{action:RetainedFormAction;options:Opt;defaultVariantId?:string;order?:Existing}&CommercialAccess){
  if(order)return <EditOrderForm action={action} options={options} order={order} canOverridePrice={canOverridePrice} canDiscount={canDiscount}/>;
  return <RentalOrderBuilder action={action} options={options} canOverridePrice={canOverridePrice} canDiscount={canDiscount}/>;
}

function RentalOrderBuilder({action,options,canOverridePrice,canDiscount}:{action:RetainedFormAction;options:Opt}&CommercialAccess){
  const [branchId,setBranchId]=useState(options.branches.length===1?options.branches[0]!.id:"");
  const [rentalStart,setRentalStart]=useState(""),[rentalEnd,setRentalEnd]=useState("");
  const [customerQuery,setCustomerQuery]=useState(""),[customers,setCustomers]=useState<Customer[]>([]),[customerId,setCustomerId]=useState(""),[customerSearchState,setCustomerSearchState]=useState<"idle"|"loading"|"done">("idle");
  const [itemQuery,setItemQuery]=useState(""),[quotes,setQuotes]=useState<RentalVariantQuote[]>([]),[lines,setLines]=useState<DraftLine[]>([]);
  const [itemSearchState,setItemSearchState]=useState<"idle"|"waiting-context"|"loading"|"done">("idle"),[orderDiscount,setOrderDiscount]=useState("0"),[message,setMessage]=useState("");
  const [pending,startTransition]=useTransition();
  const customerRequest=useRef(0),itemRequest=useRef(0);
  const customer=customers.find(item=>item.id===customerId)||options.customers.find(item=>item.id===customerId);
  const contextReady=Boolean(branchId&&rentalStart&&rentalEnd&&rentalEnd>rentalStart);
  const markContextChanged=()=>{itemRequest.current++;setQuotes([]);setItemSearchState("idle");setLines(current=>current.map(line=>({...line,needsRecheck:true})));};
  const context=(quantity=1)=>({branchId,rentalStart,rentalEnd,quantity});

  const changeCustomerQuery=(value:string)=>{customerRequest.current++;setCustomerQuery(value);setCustomers([]);setCustomerSearchState("idle")};
  const changeItemQuery=(value:string)=>{itemRequest.current++;setItemQuery(value);setQuotes([]);setItemSearchState(meaningfulLength(value)<3?"idle":contextReady?"idle":"waiting-context")};
  useEffect(()=>{if(customerId||meaningfulLength(customerQuery)<3)return;const query=customerQuery.trim(),request=customerRequest.current,timer=window.setTimeout(()=>{setCustomerSearchState("loading");startTransition(async()=>{const response=await searchRentalCustomersAction(query);if(request!==customerRequest.current)return;if(response.ok){setCustomers(response.results);setCustomerSearchState("done")}else{setCustomers([]);setCustomerSearchState("done");setMessage(response.message)}})},300);return()=>window.clearTimeout(timer)},[customerId,customerQuery]);
  useEffect(()=>{if(meaningfulLength(itemQuery)<3||!contextReady)return;const query=itemQuery.trim(),request=itemRequest.current,timer=window.setTimeout(()=>{setItemSearchState("loading");startTransition(async()=>{const response=await searchRentalItemsAction(query,{branchId,rentalStart,rentalEnd,quantity:1});if(request!==itemRequest.current)return;if(response.ok){setQuotes(response.results);setItemSearchState("done")}else{setQuotes([]);setItemSearchState("done");setMessage(response.message)}})},300);return()=>window.clearTimeout(timer)},[itemQuery,branchId,rentalStart,rentalEnd,contextReady]);
  const addVariant=(variantId:string,serialized=false)=>startTransition(async()=>{
    if(!contextReady){setMessage("Сначала выберите филиал и период аренды.");return;}
    const existing=lines.find(line=>line.variantId===variantId),quantity=(existing?.quantity??0)+1,response=await quoteRentalVariantAction(variantId,context(quantity));
    if(!response.ok){setMessage(response.message);return;}
    if(!response.result.canFulfill){setMessage(`На выбранные даты доступно ${response.result.availableCapacity}, требуется ${quantity}.`);return;}
    setLines(current=>existing?current.map(line=>line.variantId===variantId?{...line,...response.result,quantity,needsRecheck:false}:line):[...current,{...response.result,quantity:1,unitPriceMinor:response.result.priceMinor??"",discountMinor:"0",adjustmentReason:"",needsRecheck:false}]);
    setMessage(serialized?"В заказ добавлен вариант. Конкретный экземпляр назначается при подготовке.":"Товар добавлен в заказ.");
  });
  const onScanned=(result:Extract<OperationalIdentifierResult,{kind:"BULK_VARIANT"|"SERIALIZED_INSTANCE"}>)=>addVariant(result.variant.id,result.kind==="SERIALIZED_INSTANCE");
  const changeQuantity=(variantId:string,value:number)=>{if(!Number.isInteger(value)||value<1)return;startTransition(async()=>{const response=await quoteRentalVariantAction(variantId,context(value));if(!response.ok){setMessage(response.message);return;}setLines(current=>current.map(line=>line.variantId===variantId?{...line,...response.result,quantity:value,needsRecheck:false}:line));if(!response.result.canFulfill)setMessage(`Для этой позиции доступно ${response.result.availableCapacity}, требуется ${value}.`)})};
  const recheck=()=>startTransition(async()=>{const checked:DraftLine[]=[];for(const line of lines){const response=await quoteRentalVariantAction(line.variantId,context(line.quantity));if(!response.ok){setMessage(response.message);return;}checked.push({...line,...response.result,needsRecheck:false})}setLines(checked);setMessage(checked.every(line=>line.canFulfill)?"Все позиции доступны на выбранные даты.":"Некоторых позиций недостаточно на выбранные даты.")});
  const total=lines.reduce((sum,line)=>sum+asMoney(line.unitPriceMinor)*BigInt(line.quantity)-asMoney(line.discountMinor),BigInt(0))-asMoney(orderDiscount);
  const payload=JSON.stringify(lines.map(line=>({productVariantId:line.variantId,quantity:line.quantity,unitPriceMinor:line.unitPriceMinor||undefined,discountMinor:line.discountMinor||"0",adjustmentReason:line.adjustmentReason||null})));
  const disabled=!branchId||!customerId||!contextReady||lines.length===0||pending||lines.some(line=>!line.canFulfill);
  const groupedQuotes=useMemo(()=>{const products=new Map<string,{product:RentalVariantQuote["product"];executions:Map<string,{name:string|null;quotes:RentalVariantQuote[]}>}>();for(const quote of quotes){let product=products.get(quote.product.id);if(!product){product={product:quote.product,executions:new Map()};products.set(quote.product.id,product)}const key=quote.execution?.id??"direct";let execution=product.executions.get(key);if(!execution){execution={name:quote.execution?.name??null,quotes:[]};product.executions.set(key,execution)}execution.quotes.push(quote)}return[...products.values()]},[quotes]);

  return <RetainedActionForm action={action} className="order-workspace mobile-rental-order">
    <input type="hidden" name="customerId" value={customerId}/><input type="hidden" name="itemsJson" value={payload}/>
    <div className="order-builder">
      <section className="ui-card order-step"><header><i>1</i><div><h2>Клиент</h2><p>Введите минимум 3 буквы или цифры.</p></div></header>{customer?<div className="selected-entity"><span><b>{customer.firstName} {customer.lastName}</b><small>{customer.contacts?.[0]?.value??"Телефон не указан"} · Клиент №{customer.customerNumber}</small></span><button type="button" className="text-button" onClick={()=>{setCustomerId("");changeCustomerQuery("")}}>Изменить</button></div>:<><label className="live-search-field">Поиск клиента<input value={customerQuery} onChange={event=>changeCustomerQuery(event.target.value)} placeholder="Имя, телефон или номер" autoComplete="off" aria-autocomplete="list" aria-controls="customer-suggestions"/></label>{meaningfulLength(customerQuery)>=3&&<div id="customer-suggestions" className="lookup-results live-suggestions" role="listbox" aria-busy={customerSearchState==="loading"}>{customers.map(item=><button type="button" key={item.id} onClick={()=>setCustomerId(item.id)}><b>{item.firstName} {item.lastName}</b><small>{item.contacts?.[0]?.value??"Телефон не указан"}</small><small>Клиент №{item.customerNumber}</small></button>)}{customerSearchState==="loading"&&<p>Ищем клиентов…</p>}{customerSearchState==="done"&&!customers.length&&<p>Клиенты не найдены</p>}</div>}<Link href="/customers/new" className="ui-button secondary">+ Новый клиент</Link></>}</section>
      <section className="ui-card order-step"><header><i>2</i><div><h2>Период аренды</h2><p>Этот период используется для расчёта доступности.</p></div></header><label>Филиал<select name="branchId" required value={branchId} onChange={event=>{setBranchId(event.target.value);markContextChanged()}}><option value="">Выберите филиал</option>{options.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><div className="rental-dates"><label>Начало<input type="datetime-local" name="rentalStart" required value={rentalStart} onChange={event=>{setRentalStart(event.target.value);markContextChanged()}}/></label><label>Возврат<input type="datetime-local" name="rentalEnd" required value={rentalEnd} onChange={event=>{setRentalEnd(event.target.value);markContextChanged()}}/></label></div></section>
      <section className="ui-card order-step rental-items-step"><header><i>3</i><div><h2>Товары</h2><p>Поиск, код, аппаратный сканер или камера.</p></div></header><div className="rental-item-tools"><OperationalItemSelector triggerLabel="Сканировать товар" purpose="ORDER_ITEM_SELECT" branchId={branchId} onSelect={onScanned} onProductSelectionRequired={result=>changeItemQuery(result.product.code)}/><label className="live-search-field">Поиск товара<input value={itemQuery} onChange={event=>changeItemQuery(event.target.value)} placeholder="Например: Белоснежка или 538" autoComplete="off" aria-autocomplete="list" aria-controls="rental-product-suggestions"/></label></div>{itemSearchState==="waiting-context"&&<p className="notice">Выберите филиал и корректный период аренды — затем появится доступность.</p>}{itemSearchState==="loading"&&<p className="muted">Ищем товары и проверяем доступность…</p>}{groupedQuotes.length>0&&<div id="rental-product-suggestions" className="rental-search-results grouped" aria-label="Товары на выбранные даты">{groupedQuotes.map(group=><section className="rental-product-result" key={group.product.id}><header><strong>{group.product.name}</strong><small>Код {group.product.code}</small></header>{[...group.executions.entries()].map(([key,execution])=><div className="rental-execution-result" key={key}>{execution.name&&<b>{execution.name}</b>}{execution.quotes.map(quote=><article key={quote.variantId}><div><span>{sizeLabel(quote.size)}</span><small>SKU {quote.sku}</small></div><div className={quote.canFulfill?"availability available":"availability unavailable"}><b>{quote.canFulfill?`Доступно ${quote.availableCapacity}`:"Недоступно"}</b><span>из {quote.totalCapacity}</span></div><button type="button" className="secondary" disabled={!quote.canFulfill||pending} onClick={()=>addVariant(quote.variantId)}>Добавить</button></article>)}</div>)}</section>)}</div>}{itemSearchState==="done"&&!groupedQuotes.length&&<p className="muted">Товары не найдены.</p>}
        <div className="rental-basket">{lines.map(line=><article key={line.variantId} className={!line.canFulfill?"unavailable":""}><div className="rental-line-identity"><strong>{line.product.name}</strong><span>{line.execution?.name&&`${line.execution.name} · `}{sizeLabel(line.size)}</span><small>{line.trackingMode==="SERIALIZED"?"SERIALIZED · экземпляр назначается позже":`SKU ${line.sku}`}</small></div><label>Кол-во<input type="number" min="1" inputMode="numeric" value={line.quantity} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,quantity:Math.max(1,Number(event.target.value)||1),needsRecheck:true}:item))} onBlur={()=>changeQuantity(line.variantId,line.quantity)}/></label><label>Цена<input inputMode="numeric" pattern="[0-9]*" required={!line.priceMinor} readOnly={!canOverridePrice} value={line.unitPriceMinor} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,unitPriceMinor:event.target.value.replace(/\D/g,"")}:item))} placeholder="Цена аренды"/></label><label>Скидка<input inputMode="numeric" pattern="[0-9]*" readOnly={!canDiscount} value={line.discountMinor} onChange={event=>setLines(current=>current.map(item=>item.variantId===line.variantId?{...item,discountMinor:event.target.value.replace(/\D/g,"")}:item))}/></label><button type="button" className="text-button danger-text" onClick={()=>setLines(current=>current.filter(item=>item.variantId!==line.variantId))}>Удалить</button><span className="rental-line-state">{line.needsRecheck?"Будет перепроверено":line.canFulfill?`Доступно ${line.availableCapacity}`:`Недостаточно: ${line.availableCapacity}`}</span></article>)}{!lines.length&&<p className="muted">Добавьте хотя бы один товар.</p>}</div>{lines.some(line=>line.needsRecheck)&&<button type="button" className="secondary" onClick={recheck} disabled={!contextReady||pending}>Перепроверить доступность</button>}</section>
      <details className="ui-card order-step order-extra"><summary>Дополнительно</summary><div className="form-grid"><label>Источник<select name="source" defaultValue="CRM">{["CRM","PHONE","WHATSAPP","INSTAGRAM","WEBSITE","OTHER"].map(value=><option value={value} key={value}>{orderChannelLabel(value)}</option>)}</select></label><label>Скидка заказа<input name="discountMinor" inputMode="numeric" pattern="[0-9]*" readOnly={!canDiscount} value={orderDiscount} onChange={event=>setOrderDiscount(event.target.value.replace(/\D/g,""))}/></label></div><label>Внутренний комментарий<textarea name="internalComment" maxLength={4000}/></label></details>
      {message&&<p className="notice" role="status">{message}</p>}
    </div>
    <aside className="ui-card order-checkout"><div><h2>Итог</h2><span>{lines.length} поз. · {lines.reduce((sum,line)=>sum+line.quantity,0)} шт.</span></div><strong>{total>=0?money(total):"Проверьте скидки"}</strong><small>Цена и доступность повторно проверяются сервером. Заказ создаётся как черновик.</small><Submit editing={false} disabled={disabled}/><Link href="/orders">Отмена</Link></aside>
  </RetainedActionForm>;
}

function EditOrderForm({action,options,order,canDiscount}:{action:RetainedFormAction;options:Opt;order:Existing}&CommercialAccess){
  const orderTimeZone=options.branches.find(branch=>branch.id===order.branchId)?.timezone??"UTC";
  const [customerQuery,setCustomerQuery]=useState(""),[customerId,setCustomerId]=useState(order.customerId),[orderDiscount,setOrderDiscount]=useState(order.discountTotalMinor.toString());
  const customers=useMemo(()=>{const query=customerQuery.trim().toLocaleLowerCase("ru");return(query?options.customers.filter(customer=>`${customer.customerNumber} ${customer.firstName} ${customer.lastName??""} ${customer.contacts?.map(contact=>contact.value).join(" ")??""}`.toLocaleLowerCase("ru").includes(query)):options.customers).slice(0,12)},[customerQuery,options.customers]);
  const customer=options.customers.find(item=>item.id===customerId);
  return <RetainedActionForm action={action} className="order-workspace"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="customerId" value={customerId}/><div className="order-builder"><section className="ui-card order-step"><header><i>1</i><div><h2>Тип и филиал</h2></div></header><div className="order-type-switch"><button type="button" className="active">Аренда</button><button type="button" disabled>Продажа</button></div><label>Филиал<select name="branchId" required defaultValue={order.branchId}><option value="">Выберите филиал</option>{options.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label></section><section className="ui-card order-step"><header><i>2</i><div><h2>Клиент</h2></div></header><input value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Имя, телефон или номер"/>{customer?<div className="selected-entity"><span><b>{customer.firstName} {customer.lastName}</b><small>{customer.customerNumber}</small></span><button type="button" className="text-button" onClick={()=>setCustomerId("")}>Изменить</button></div>:<div className="lookup-results">{customers.map(item=><button type="button" key={item.id} onClick={()=>setCustomerId(item.id)}><b>{item.firstName} {item.lastName}</b><small>{item.customerNumber}</small></button>)}</div>}</section><section className="ui-card order-step"><header><i>3</i><div><h2>Период аренды</h2></div></header><div className="rental-dates"><label>Начало<input type="datetime-local" name="rentalStart" required defaultValue={localDate(order.rentalStartAt,orderTimeZone)}/></label><label>Возврат<input type="datetime-local" name="rentalEnd" required defaultValue={localDate(order.rentalEndAt,orderTimeZone)}/></label></div></section><section className="ui-card order-step"><header><i>4</i><div><h2>Дополнительно</h2></div></header><div className="form-grid"><label>Источник<select name="source" defaultValue={order.channel}>{["CRM","PHONE","WHATSAPP","INSTAGRAM","WEBSITE","OTHER"].map(value=><option value={value} key={value}>{orderChannelLabel(value)}</option>)}</select></label><label>Скидка заказа<input name="discountMinor" inputMode="numeric" readOnly={!canDiscount} value={orderDiscount} onChange={event=>setOrderDiscount(event.target.value.replace(/\D/g,""))}/></label></div><label>Комментарий<textarea name="internalComment" maxLength={4000} defaultValue={order.internalComment??""}/></label></section></div><aside className="ui-card order-checkout"><h2>Изменения</h2><Submit editing={true}/><Link href={`/orders/${order.id}`}>Отмена</Link></aside></RetainedActionForm>;
}
