"use server";import{revalidatePath}from"next/cache";import{redirect,unstable_rethrow}from"next/navigation";import{ZodError}from"zod";import{requireRouteAccess}from"@/lib/auth/session";import{createTenantContext}from"@/lib/tenant/context";import{requireOrderPermission}from"@/lib/orders/permissions";import{OrderError}from"@/lib/orders/errors";import{addOrderItem,cancelOrder,confirmOrder,createOrder,removeOrderItem,reserveOrder,updateOrder,updateOrderItem}from"@/lib/orders/management";import type{OrderAction}from"@/lib/auth/access";
const text=(f:FormData,k:string)=>String(f.get(k)??"").trim(),num=(f:FormData,k:string)=>BigInt(text(f,k)||"0");function msg(e:unknown){unstable_rethrow(e);return e instanceof OrderError?e.message:e instanceof ZodError?e.issues[0]?.message??"Проверьте форму.":"Операция не выполнена."}async function ctx(a:OrderAction){const s=await requireRouteAccess("/orders");requireOrderPermission(s.role,a);return{s,tenant:createTenantContext(s.organizationId)}}function base(f:FormData){return{branchId:text(f,"branchId"),customerId:text(f,"customerId"),source:text(f,"source"),rentalStart:text(f,"rentalStart"),rentalEnd:text(f,"rentalEnd"),discountMinor:num(f,"discountMinor"),internalComment:text(f,"internalComment")||null}}function item(f:FormData){return{productVariantId:text(f,"productVariantId"),quantity:Number(text(f,"quantity")),unitPriceMinor:text(f,"unitPriceMinor")?num(f,"unitPriceMinor"):undefined,discountMinor:num(f,"itemDiscountMinor"),adjustmentReason:text(f,"adjustmentReason")||null}}const go=(p:string,k:"ok"|"error",m:string):never=>redirect(`${p}?${k}=${encodeURIComponent(m)}`);
export async function createOrderAction(f:FormData){try{const{s,tenant}=await ctx("CREATE_ORDERS"),o=await createOrder(tenant,base(f),[item(f)],{userId:s.userId});revalidatePath("/orders");redirect(`/orders/${o.id}?ok=${encodeURIComponent("Заказ создан.")}`)}catch(e){if((e as{digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;go("/orders/new","error",msg(e))}}
export async function updateOrderAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("EDIT_ORDERS");await updateOrder(tenant,id,base(f),{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Заказ обновлён.")}catch(e){go(`/orders/${id}/edit`,"error",msg(e))}}
export async function addItemAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("EDIT_ORDERS");await addOrderItem(tenant,id,item(f),{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Позиция добавлена.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
export async function updateItemAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("EDIT_ORDERS");await updateOrderItem(tenant,id,text(f,"orderItemId"),item(f),{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Позиция обновлена.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
export async function removeItemAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("EDIT_ORDERS");await removeOrderItem(tenant,id,text(f,"orderItemId"),{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Позиция удалена.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
export async function reserveOrderAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("RESERVE_ORDERS");await reserveOrder(tenant,id,{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Capacity зарезервирован.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
export async function confirmOrderAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("CONFIRM_ORDERS");await confirmOrder(tenant,id,{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Бронь подтверждена.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
export async function cancelOrderAction(f:FormData){const id=text(f,"orderId");try{const{s,tenant}=await ctx("CANCEL_ORDERS");await cancelOrder(tenant,id,text(f,"cancellationReason"),{userId:s.userId});revalidatePath(`/orders/${id}`);go(`/orders/${id}`,"ok","Заказ отменён.")}catch(e){go(`/orders/${id}`,"error",msg(e))}}
