import {rentalQuantityTime} from "./quantity-time";
import "server-only";
import {db} from "@/lib/db";
import type {AuthContext} from "@/lib/auth/session";
import {financeQueryScope,type FinanceRawFilters} from "@/lib/finance/filters";
import {visibleFinanceEffects} from "@/lib/finance/read-visibility";
import {hasPermission} from "@/lib/permissions/effective";
import {warehouseStates} from "@/lib/inventory/warehouse-states";
export async function getCrmReports(actor:AuthContext,raw:FinanceRawFilters){
 const {where,scope,visibility,period}=await financeQueryScope(actor,raw,"REPORT_FINANCE_VIEW"),branchId=raw.branchId||scope.branchId;
 const canOrders=await hasPermission(actor,"ORDER_VIEW"),canInventory=await hasPermission(actor,"INVENTORY_VIEW");
 const orderWhere={...scope,branchId,createdAt:{gte:period.from,lt:period.endExclusive},status:{notIn:["CANCELLED","EXPIRED","NO_SHOW"] as const}};
 // Contract values are grouped by currency and never described as ledger revenue.
 const [finance,orders,statuses,customers,assignees,currentBalances,movements]=await Promise.all([
 visibility.hasRows?db.financialTransaction.groupBy({by:["currency","kind"],where,_sum:visibility.fields,_count:{_all:true}}):[],
 canOrders?db.order.groupBy({by:["type","currency"],where:{...orderWhere,status:{notIn:["CANCELLED","EXPIRED","NO_SHOW"]}},...(visibility.revenue?{_sum:{totalMinor:true as const}}:{}),_count:{_all:true}}):[],
 canOrders?db.order.groupBy({by:["status","type"],where:{...scope,branchId,createdAt:{gte:period.from,lt:period.endExclusive}},_count:{_all:true}}):[],
 canOrders?db.order.groupBy({by:["customerId"],where:{...orderWhere,status:{notIn:["CANCELLED","EXPIRED","NO_SHOW"]}},_count:{_all:true}}):[],
 canOrders?db.order.groupBy({by:["assignedMembershipId"],where:{...orderWhere,status:{notIn:["CANCELLED","EXPIRED","NO_SHOW"]}},_count:{_all:true}}):[],
 visibility.obligation||visibility.deposits?db.financialTransaction.groupBy({by:["currency","orderId","customerId"],where:{...scope,branchId,occurredAt:{lte:new Date()}},_sum:{...(visibility.obligation?{obligationEffectMinor:true as const}:{}),...(visibility.deposits?{depositEffectMinor:true as const}:{})}}):[],
 canInventory?db.inventoryMovement.groupBy({by:["type"],where:{organizationId:actor.organizationId,occurredAt:{gte:period.from,lt:period.endExclusive},...(branchId?{OR:[{fromBranchId:branchId},{toBranchId:branchId}]}:{})},_sum:{quantity:true},_count:{_all:true}}):[]]);

 const [issueRows,newCustomers,allocations]=await Promise.all([
 canInventory?db.inventoryMovement.groupBy({by:["productVariantId"],where:{organizationId:actor.organizationId,type:"RENTAL_ISSUE",fromBranchId:branchId,occurredAt:{gte:period.from,lt:period.endExclusive}},_sum:{quantity:true},_count:{_all:true}}):[],
 await hasPermission(actor,"CUSTOMER_VIEW")?db.customer.count({where:{organizationId:actor.organizationId,createdAt:{gte:period.from,lt:period.endExclusive},...(branchId?{orders:{some:{branchId}}}:{})}}):null,
 canInventory?db.capacityAllocation.findMany({where:{...scope,branchId,sourceType:"ORDER",issuedAt:{not:null,lt:period.endExclusive},OR:[{returnedAt:null},{returnedAt:{gte:period.from}}]},select:{id:true,issuedAt:true,issuedQuantity:true,returnedQuantity:true,returnedAt:true,productInstanceId:true,bulkPhysicalResolutions:{select:{occurredAt:true,totalQuantity:true,kind:true}}}}):[]]);
 const topIssues=issueRows.map(row=>({id:row.productVariantId,quantity:Math.abs(row._sum.quantity??0),movements:row._count._all})).sort((a,b)=>b.quantity-a.quantity||a.id.localeCompare(b.id)).slice(0,20);
 const variants=topIssues.length?await db.productVariant.findMany({where:{organizationId:actor.organizationId,id:{in:topIssues.map(r=>r.id)}},select:{id:true,sku:true,productId:true,product:{select:{name:true}},execution:{select:{name:true}},size:{select:{name:true,code:true}}}}):[];
 let rentalUnitMilliseconds=0,incompleteAllocations=0;for(const allocation of allocations){const value=rentalQuantityTime({start:period.from,end:new Date(Math.min(Date.now(),period.endExclusive.getTime())),...allocation,serialized:Boolean(allocation.productInstanceId),resolutions:allocation.bulkPhysicalResolutions});if(value.complete)rentalUnitMilliseconds+=value.unitMilliseconds;else incompleteAllocations++;}
 const names=assignees.length?await db.organizationMembership.findMany({where:{organizationId:actor.organizationId,id:{in:assignees.flatMap(r=>r.assignedMembershipId?[r.assignedMembershipId]:[])}},select:{id:true,user:{select:{displayName:true}}}}):[];
 const balances=new Map<string,{debt?:bigint;credit?:bigint;deposit?:bigint}>();for(const row of currentBalances){const value=balances.get(row.currency)??{};if(visibility.obligation){const amount=row._sum.obligationEffectMinor??BigInt(0);value.debt=(value.debt??BigInt(0))+(amount>BigInt(0)?amount:BigInt(0));value.credit=(value.credit??BigInt(0))+(amount<BigInt(0)?-amount:BigInt(0));}if(visibility.deposits)value.deposit=(value.deposit??BigInt(0))+(row._sum.depositEffectMinor??BigInt(0));balances.set(row.currency,value);}
 const inventory=canInventory?await db.$transaction(async tx=>{const stock=await tx.stockLevel.groupBy({by:["branchId","productVariantId"],where:{...scope,branchId,productVariant:{isActive:true,product:{trackingMode:"BULK",publicationStatus:"ACTIVE",archivedAt:null}}},_sum:{quantity:true}});const total={physicalOnHand:0,activeFleet:0,issuedOutstanding:0,cleaning:0,repair:0,unclassifiedMaintenance:0,plannedReservations:0};for(let offset=0;offset<stock.length;offset+=200){const rows=await warehouseStates(tx,actor.organizationId,stock.slice(offset,offset+200).map(row=>({branchId:row.branchId,productVariantId:row.productVariantId,quantity:row._sum.quantity??0})),new Date());for(const row of rows)for(const key of Object.keys(total) as (keyof typeof total)[])total[key]+=row[key];}return total;},{timeout:30000}):null;
 return{period,newCustomers,topProducts:topIssues.map(row=>({...row,variant:variants.find(v=>v.id===row.id)})),rentalQuantityTime:{unitDays:rentalUnitMilliseconds/86400000,incompleteAllocations,coveredAllocations:allocations.length-incompleteAllocations},finance:finance.map(row=>({currency:row.currency,kind:row.kind,count:row._count._all,...visibleFinanceEffects(row._sum,visibility)})),orders:orders.map(row=>({type:row.type,currency:row.currency,count:row._count._all,...(visibility.revenue?{contractTotal:row._sum?.totalMinor??BigInt(0),averageContract:(row._sum?.totalMinor??BigInt(0))/BigInt(Math.max(1,row._count._all))}:{})})),statuses:statuses.map(row=>({type:row.type,status:row.status,count:row._count._all})),customerCount:canOrders?customers.length:null,assignees:assignees.map(row=>({id:row.assignedMembershipId,name:names.find(m=>m.id===row.assignedMembershipId)?.user.displayName??"Не назначен",count:row._count._all})),balances:[...balances].map(([currency,value])=>({currency,...value})),inventory,movements:movements.map(row=>({type:row.type,count:row._count._all,quantity:row._sum.quantity??0})),historicalUtilization:{available:false as const,reason:"Для достоверного процента загрузки и дней простоя не хватает подтверждённой истории полного парка. Текущий остаток нельзя использовать как исторический знаменатель. Ниже доступны реальные движения и состояние сейчас."}};
}
