import"server-only";import{db}from"@/lib/db";import type{MembershipRole,Prisma}from"@/generated/prisma/client";import type{TenantContext}from"@/lib/tenant/context";import{StaffError}from"@/lib/staff/errors";import{requireStaffPermission}from"@/lib/staff/permissions";
export type StaffActor={userId:string;membershipId:string;role:MembershipRole};
async function membership(tx:Prisma.TransactionClient,t:TenantContext,id:string){const m=await tx.organizationMembership.findFirst({where:{id,organizationId:t.organizationId},include:{branchAccess:true}});if(!m)throw new StaffError("NOT_FOUND","Сотрудник не найден.");return m}
async function revoke(tx:Prisma.TransactionClient,membershipId:string){await tx.authSession.updateMany({where:{membershipId,revokedAt:null},data:{revokedAt:new Date()}})}
async function ownerGuard(tx:Prisma.TransactionClient,t:TenantContext,targetId:string){await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${t.organizationId+":owners"},0))`;const target=await membership(tx,t,targetId);if(target.role==="OWNER"&&target.status==="ACTIVE"&&await tx.organizationMembership.count({where:{organizationId:t.organizationId,role:"OWNER",status:"ACTIVE"}})<=1)throw new StaffError("INVALID","Нельзя изменить последнего активного владельца.");return target}
export async function deactivateStaff(t:TenantContext,id:string,a:StaffActor){return db.$transaction(async tx=>{let m=await membership(tx,t,id);requireStaffPermission(a.role,"MANAGE",m.role);if(m.role==="OWNER")m=await ownerGuard(tx,t,id);await tx.organizationMembership.update({where:{id},data:{status:"SUSPENDED"}});await revoke(tx,id)})}
export async function reactivateStaff(t:TenantContext,id:string,a:StaffActor){return db.$transaction(async tx=>{const m=await membership(tx,t,id);requireStaffPermission(a.role,"MANAGE",m.role);await tx.organizationMembership.update({where:{id},data:{status:"ACTIVE"}});await revoke(tx,id)})}
export async function changeStaffRole(t:TenantContext,id:string,role:MembershipRole,a:StaffActor){return db.$transaction(async tx=>{let m=await membership(tx,t,id);requireStaffPermission(a.role,"MANAGE",m.role);requireStaffPermission(a.role,"MANAGE",role);if(m.role==="OWNER"&&role!=="OWNER")m=await ownerGuard(tx,t,id);await tx.organizationMembership.update({where:{id},data:{role}});await revoke(tx,id)})}
export async function setBranchAccess(t:TenantContext,id:string,input:{branchIds:string[];defaultBranchId:string|null},a:StaffActor){return db.$transaction(async tx=>{const m=await membership(tx,t,id);requireStaffPermission(a.role,"MANAGE",m.role);const ids=[...new Set(input.branchIds)];const branches=await tx.branch.findMany({where:{organizationId:t.organizationId,id:{in:ids},status:"ACTIVE"},select:{id:true}});if(branches.length!==ids.length)throw new StaffError("NOT_FOUND","Филиал не найден.");if(m.role!=="OWNER"&&!ids.length)throw new StaffError("INVALID","Сотруднику нужен хотя бы один филиал.");if(input.defaultBranchId&&!ids.includes(input.defaultBranchId)&&m.role!=="OWNER")throw new StaffError("INVALID","Основной филиал должен быть разрешён.");await tx.membershipBranchAccess.deleteMany({where:{organizationId:t.organizationId,membershipId:id}});if(m.role!=="OWNER"&&ids.length)await tx.membershipBranchAccess.createMany({data:ids.map(branchId=>({organizationId:t.organizationId,membershipId:id,branchId}))});await tx.organizationMembership.update({where:{id},data:{defaultBranchId:input.defaultBranchId}});await revoke(tx,id)})}
export async function updateStaffAccess(t:TenantContext,id:string,input:{firstName:string;lastName?:string;phone?:string;role:MembershipRole;branchIds:string[];defaultBranchId:string|null},a:StaffActor){return db.$transaction(async tx=>{let m=await membership(tx,t,id);requireStaffPermission(a.role,"MANAGE",m.role);requireStaffPermission(a.role,"MANAGE",input.role);if(m.role==="OWNER"&&input.role!=="OWNER")m=await ownerGuard(tx,t,id);const ids=[...new Set(input.branchIds)];const branches=await tx.branch.findMany({where:{organizationId:t.organizationId,id:{in:ids},status:"ACTIVE"},select:{id:true}});if(branches.length!==ids.length)throw new StaffError("NOT_FOUND","Филиал не найден.");if(input.role!=="OWNER"&&!ids.length)throw new StaffError("INVALID","Сотруднику нужен хотя бы один филиал.");if(input.role!=="OWNER"&&(!input.defaultBranchId||!ids.includes(input.defaultBranchId)))throw new StaffError("INVALID","Основной филиал должен быть среди разрешённых.");const first=input.firstName.trim(),last=input.lastName?.trim()||null;if(!first)throw new StaffError("INVALID","Укажите имя сотрудника.");await tx.user.update({where:{id:m.userId},data:{firstName:first,lastName:last,phone:input.phone?.trim()||null,displayName:[first,last].filter(Boolean).join(" ")}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:t.organizationId,membershipId:id}});if(input.role!=="OWNER")await tx.membershipBranchAccess.createMany({data:ids.map(branchId=>({organizationId:t.organizationId,membershipId:id,branchId}))});await tx.organizationMembership.update({where:{id},data:{role:input.role,defaultBranchId:input.role==="OWNER"?input.defaultBranchId:input.defaultBranchId}});await revoke(tx,id)})}
