import "server-only";
import ExcelJS from "exceljs";
import {db} from "@/lib/db";
import type {TenantContext} from "@/lib/tenant/context";
import {CustomerError} from "@/lib/customers/errors";
import {createCustomer,findCustomerDuplicates} from "@/lib/customers/management";
import {SOURCES} from "@/lib/customers/validation";
const MAX_BYTES=5*1024*1024,MAX_ROWS=2000,MAX_COLUMNS=50,MAX_CELL=500;
type Raw={headers:string[];rows:string[][];formulaRows:number[]};
export type Mapping={firstName:number;lastName?:number;middleName?:number;phone?:number;email?:number;birthDate?:number;source?:number;city?:number;address?:number;comment?:number};
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell="";}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell="";}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
function clean(value:unknown){return String(value??"").trim().slice(0,MAX_CELL);}
async function parse(file:File):Promise<Raw>{if(file.size<=0||file.size>MAX_BYTES)throw new CustomerError("IMPORT_INVALID","Файл должен быть не больше 5 МБ.");const ext=file.name.toLowerCase().split('.').pop(),allowed=ext==="csv"||ext==="xlsx",mimeOk=!file.type||(ext==="csv"&&["text/csv","application/csv","application/vnd.ms-excel","text/plain"].includes(file.type))||(ext==="xlsx"&&file.type==="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");if(!allowed||!mimeOk)throw new CustomerError("IMPORT_INVALID","Поддерживаются только CSV и XLSX с корректным MIME.");const bytes=Buffer.from(await file.arrayBuffer());let rows:string[][]=[],formulaRows:number[]=[];
 if(ext==="csv"){rows=csvRows(bytes.toString("utf8").replace(/^\uFEFF/,""));}else{const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes as unknown as ExcelJS.Buffer);const sheet=workbook.worksheets[0];if(!sheet)throw new CustomerError("IMPORT_INVALID","В книге нет листов.");sheet.eachRow({includeEmpty:false},(r,n)=>{const values:string[]=[];let formula=false;for(let c=1;c<=Math.min(r.cellCount,MAX_COLUMNS);c++){const v=r.getCell(c).value;if(v&&typeof v==="object"&&"formula" in v){formula=true;values.push("");}else if(v&&typeof v==="object"&&"richText" in v)values.push(clean(v.richText.map(x=>x.text).join("")));else values.push(clean(v instanceof Date?v.toISOString().slice(0,10):v));}rows.push(values);if(formula)formulaRows.push(n);});}
 if(rows.length<2)throw new CustomerError("IMPORT_INVALID","Файл не содержит строк для импорта.");if(rows.length-1>MAX_ROWS)throw new CustomerError("IMPORT_INVALID",`Максимум ${MAX_ROWS} строк.`);if(rows[0].length>MAX_COLUMNS)throw new CustomerError("IMPORT_INVALID",`Максимум ${MAX_COLUMNS} колонок.`);return{headers:rows[0].map(clean),rows:rows.slice(1).map(r=>r.slice(0,MAX_COLUMNS).map(clean)),formulaRows};}
export async function createImportPreview(tenant:TenantContext,file:File,userId?:string){const raw=await parse(file);return db.customerImportBatch.create({data:{organizationId:tenant.organizationId,createdByUserId:userId,originalFilename:file.name.slice(0,200),rawRows:raw,status:"UPLOADED",expiresAt:new Date(Date.now()+2*60*60*1000)}});}
export async function getImportBatch(tenant:TenantContext,id:string){return db.customerImportBatch.findFirst({where:{id,organizationId:tenant.organizationId,expiresAt:{gt:new Date()} }});}
export async function analyzeImport(tenant:TenantContext,id:string,mapping:Mapping){const batch=await getImportBatch(tenant,id);if(!batch)throw new CustomerError("NOT_FOUND","Импорт не найден или истёк.");const raw=batch.rawRows as unknown as Raw;if(!Number.isInteger(mapping.firstName)||mapping.firstName<0||mapping.firstName>=raw.headers.length)throw new CustomerError("IMPORT_INVALID","Сопоставьте колонку имени.");const analysis=[];for(let i=0;i<raw.rows.length;i++){const row=raw.rows[i],firstName=clean(row[mapping.firstName]),phone=mapping.phone===undefined?"":clean(row[mapping.phone]),email=mapping.email===undefined?"":clean(row[mapping.email]),sourceRaw=mapping.source===undefined?"":clean(row[mapping.source]).toUpperCase(),source=(SOURCES as readonly string[]).includes(sourceRaw)?sourceRaw:"IMPORT";const contacts=[...(phone?[{type:"PHONE" as const,value:phone,isPrimary:true}]:[]),...(email?[{type:"EMAIL" as const,value:email,isPrimary:true}]:[])];let status:"READY"|"ERROR"|"DUPLICATE"="READY",message="";if(!firstName){status="ERROR";message="Не указано имя";}if(raw.formulaRows.includes(i+2)){status="ERROR";message="Строка содержит формулу";}const duplicates=status==="READY"?await findCustomerDuplicates(tenant,contacts):[];if(duplicates.length){status="DUPLICATE";message="Возможный дубль";}const addressLine=mapping.address===undefined?"":clean(row[mapping.address]);analysis.push({row:i+2,status,message,customer:{firstName,lastName:mapping.lastName===undefined?null:clean(row[mapping.lastName])||null,middleName:mapping.middleName===undefined?null:clean(row[mapping.middleName])||null,birthDate:mapping.birthDate===undefined?null:clean(row[mapping.birthDate])||null,preferredLanguage:null,source,status:"ACTIVE",marketingConsent:false},contacts,address:addressLine?{type:"DELIVERY",country:null,city:mapping.city===undefined?null:clean(row[mapping.city])||null,addressLine,comment:null,isPrimary:true}:null,comment:mapping.comment===undefined?null:clean(row[mapping.comment])||null,duplicates});}await db.customerImportBatch.update({where:{id},data:{mapping,analysis,status:"ANALYZED"}});return analysis;}
export async function confirmImport(tenant:TenantContext,id:string,userId?:string){const batch=await getImportBatch(tenant,id);if(!batch||batch.status!=="ANALYZED")throw new CustomerError("NOT_FOUND","Подтверждённый preview не найден.");const rows=batch.analysis as unknown as Array<{status:string;customer:Record<string,unknown>;contacts:Array<{type:"PHONE"|"EMAIL";value:string;isPrimary:boolean}>;address:{type:string;country:null;city:string|null;addressLine:string;comment:null;isPrimary:boolean}|null;comment:string|null}>;let imported=0,skipped=0,errors=0;for(const row of rows){if(row.status!=="READY"){skipped++;continue;}try{const customer=await createCustomer(tenant,{customer:row.customer,contacts:row.contacts,createdByUserId:userId});if(row.address)await db.customerAddress.create({data:{...row.address,organizationId:tenant.organizationId,customerId:customer.id}});if(row.comment)await db.customerNote.create({data:{organizationId:tenant.organizationId,customerId:customer.id,text:row.comment,createdByUserId:userId}});imported++;}catch{errors++;}}await db.customerImportBatch.update({where:{id},data:{status:"COMPLETED",completedAt:new Date()}});return{imported,skipped,errors};}
