import "server-only";
import {Prisma} from "@/generated/prisma/client";
import {db} from "@/lib/db";
import type {TenantContext} from "@/lib/tenant/context";
import {CustomerError} from "@/lib/customers/errors";
import {normalizeEmail,normalizePhone} from "@/lib/customers/normalization";
import {addressSchema,contactSchema,customerSchema,noteSchema} from "@/lib/customers/validation";

type ContactInput={type:"PHONE"|"EMAIL"|"OTHER";value:string;label?:string|null;isPrimary?:boolean;isVerified?:boolean;allowDuplicate?:boolean};
function normalized(c:ContactInput){const value=c.value.trim();const normalizedValue=c.type==="PHONE"?normalizePhone(value):c.type==="EMAIL"?normalizeEmail(value):value.toLocaleLowerCase();if(!normalizedValue)throw new CustomerError("VALIDATION","Некорректный контакт.");return {...contactSchema.parse({...c,isPrimary:!!c.isPrimary,isVerified:!!c.isVerified}),normalizedValue};}
export async function findCustomerDuplicates(tenant:TenantContext,contacts:ContactInput[],excludeId?:string){const values=contacts.map(normalized).filter(c=>c.type!=="OTHER");if(!values.length)return[];const rows=await db.customer.findMany({where:{organizationId:tenant.organizationId,id:excludeId?{not:excludeId}:undefined,contacts:{some:{OR:values.map(c=>({type:c.type,normalizedValue:c.normalizedValue}))}}},select:{id:true,customerNumber:true,firstName:true,lastName:true},take:10});return rows.map(r=>({id:r.id,customerNumber:r.customerNumber,name:[r.firstName,r.lastName].filter(Boolean).join(" ")}));}
async function allocateNumber(tx:Prisma.TransactionClient,organizationId:string){const rows=await tx.$queryRaw<Array<{value:bigint}>>(Prisma.sql`INSERT INTO "customer_counters" ("organization_id","next_value","updated_at") VALUES (${organizationId}::uuid,2,CURRENT_TIMESTAMP) ON CONFLICT ("organization_id") DO UPDATE SET "next_value"="customer_counters"."next_value"+1,"updated_at"=CURRENT_TIMESTAMP RETURNING "next_value"-1 AS value`);const value=rows[0]?.value;if(!value)throw new CustomerError("VALIDATION","Не удалось создать номер клиента.");return `C-${value.toString().padStart(6,"0")}`;}
export async function createCustomer(tenant:TenantContext,input:{customer:unknown;contacts:ContactInput[];createdByUserId?:string;allowDuplicate?:boolean}){const customer=customerSchema.parse(input.customer),contacts=input.contacts.map(normalized);const duplicates=await findCustomerDuplicates(tenant,input.contacts);if(duplicates.length&&!input.allowDuplicate)throw new CustomerError("POSSIBLE_DUPLICATE","Возможно, такой клиент уже существует.",duplicates);return db.$transaction(async tx=>{const number=await allocateNumber(tx,tenant.organizationId);return tx.customer.create({data:{...customer,organizationId:tenant.organizationId,customerNumber:number,createdByUserId:input.createdByUserId,archivedAt:customer.status==="ARCHIVED"?new Date():null,contacts:{create:contacts.map(c=>({...c,organizationId:tenant.organizationId}))}},include:{contacts:true}});},{maxWait:10000,timeout:30000});}
export async function updateCustomer(tenant:TenantContext,id:string,raw:unknown){const data=customerSchema.parse(raw);const result=await db.customer.updateMany({where:{id,organizationId:tenant.organizationId},data:{...data,archivedAt:data.status==="ARCHIVED"?new Date():null}});if(!result.count)throw new CustomerError("NOT_FOUND","Клиент не найден.");}
export async function archiveCustomer(tenant:TenantContext,id:string){const r=await db.customer.updateMany({where:{id,organizationId:tenant.organizationId},data:{status:"ARCHIVED",archivedAt:new Date()}});if(!r.count)throw new CustomerError("NOT_FOUND","Клиент не найден.");}
export async function addContact(tenant:TenantContext,customerId:string,raw:ContactInput){const c=normalized(raw),duplicates=await findCustomerDuplicates(tenant,[raw],customerId);if(duplicates.length&&!raw.allowDuplicate)throw new CustomerError("POSSIBLE_DUPLICATE","Возможно, такой контакт уже принадлежит другому клиенту.",duplicates);return db.$transaction(async tx=>{const customer=await tx.customer.findFirst({where:{id:customerId,organizationId:tenant.organizationId},select:{id:true}});if(!customer)throw new CustomerError("NOT_FOUND","Клиент не найден.");if(c.isPrimary)await tx.customerContact.updateMany({where:{organizationId:tenant.organizationId,customerId,type:c.type,isPrimary:true},data:{isPrimary:false}});return tx.customerContact.create({data:{...c,organizationId:tenant.organizationId,customerId}});});}
export async function updateContact(tenant:TenantContext,id:string,raw:ContactInput){const c=normalized(raw),old=await db.customerContact.findFirst({where:{id,organizationId:tenant.organizationId},select:{customerId:true}});if(!old)throw new CustomerError("NOT_FOUND","Контакт не найден.");const duplicates=await findCustomerDuplicates(tenant,[raw],old.customerId);if(duplicates.length&&!raw.allowDuplicate)throw new CustomerError("POSSIBLE_DUPLICATE","Возможно, такой контакт уже принадлежит другому клиенту.",duplicates);return db.$transaction(async tx=>{if(c.isPrimary)await tx.customerContact.updateMany({where:{organizationId:tenant.organizationId,customerId:old.customerId,type:c.type,isPrimary:true,id:{not:id}},data:{isPrimary:false}});return tx.customerContact.update({where:{id},data:c});});}
export async function addAddress(tenant:TenantContext,customerId:string,raw:unknown){const data=addressSchema.parse(raw);return db.$transaction(async tx=>{if(!await tx.customer.findFirst({where:{id:customerId,organizationId:tenant.organizationId},select:{id:true}}))throw new CustomerError("NOT_FOUND","Клиент не найден.");if(data.isPrimary)await tx.customerAddress.updateMany({where:{organizationId:tenant.organizationId,customerId,isPrimary:true},data:{isPrimary:false}});return tx.customerAddress.create({data:{...data,organizationId:tenant.organizationId,customerId}});});}
export async function updateAddress(tenant:TenantContext,id:string,raw:unknown){const data=addressSchema.parse(raw);return db.$transaction(async tx=>{const old=await tx.customerAddress.findFirst({where:{id,organizationId:tenant.organizationId},select:{customerId:true}});if(!old)throw new CustomerError("NOT_FOUND","Адрес не найден.");if(data.isPrimary)await tx.customerAddress.updateMany({where:{organizationId:tenant.organizationId,customerId:old.customerId,isPrimary:true,id:{not:id}},data:{isPrimary:false}});return tx.customerAddress.update({where:{id},data});});}
export async function addNote(tenant:TenantContext,customerId:string,raw:unknown,userId?:string){const data=noteSchema.parse(raw);if(!await db.customer.findFirst({where:{id:customerId,organizationId:tenant.organizationId},select:{id:true}}))throw new CustomerError("NOT_FOUND","Клиент не найден.");return db.customerNote.create({data:{...data,organizationId:tenant.organizationId,customerId,createdByUserId:userId}});}
export async function updateNote(tenant:TenantContext,id:string,raw:unknown){const data=noteSchema.parse(raw);const r=await db.customerNote.updateMany({where:{id,organizationId:tenant.organizationId,archivedAt:null},data});if(!r.count)throw new CustomerError("NOT_FOUND","Заметка не найдена.");}
export async function archiveNote(tenant:TenantContext,id:string){const r=await db.customerNote.updateMany({where:{id,organizationId:tenant.organizationId},data:{archivedAt:new Date()}});if(!r.count)throw new CustomerError("NOT_FOUND","Заметка не найдена.");}
