import { compactReference } from "@/lib/ui/reference";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { ContextPanel } from "@/components/ContextPanel";
import { WorkflowTabs } from "@/components/WorkflowTabs";
import { AppShell } from "@/components/AppShell";
import { RetainedActionForm } from "@/components/RetainedActionForm";
import { requireRouteAccess } from "@/lib/auth/session";
import { cashAccountsView, ACCOUNT_LABELS, ACCOUNT_OPERATION_LABELS } from "@/lib/finance/cash-accounts";
import { formatBusinessDateTime } from "@/lib/calendar/timezone";
import { cashOpeningAction, cashExpenseAction, cashTransferAction, cashCorrectionAction, cashCategoryAction } from "./actions";
import "./cash-accounts.css";

const money = (amount: bigint) => `${amount.toLocaleString("ru-KZ")} ₸`;
const amountField = (label: string, initial?: string) => <label>{label}<input name="amountMinor" inputMode="numeric" pattern="[0-9]+" maxLength={12} defaultValue={initial} required/></label>;
const reasonField = <label>Основание<textarea name="reason" minLength={3} maxLength={500} required/></label>;
function CommandContext({ branchId }: { branchId: string }) { return <><input type="hidden" name="idempotencyKey" value={randomUUID()}/><input type="hidden" name="returnBranchId" value={branchId}/></>; }
function Confirmation({ children }: { children: React.ReactNode }) { return <label className="cash-confirm"><input name="confirmed" value="yes" type="checkbox" required/><span>{children}</span></label>; }
export default async function Page({ searchParams }: { searchParams: Promise<{ branchId?: string; accountId?: string; page?: string; saved?: string }> }) {
  const actor = await requireRouteAccess("/cash/accounts"), filters = await searchParams;
  let data: Awaited<ReturnType<typeof cashAccountsView>>;
  try { data = await cashAccountsView(actor, filters); }
  catch (error) { return <AppShell active="/cash" title="Кассы"><p role="alert">{error instanceof Error ? error.message : "Кассы недоступны."}</p><Link href="/cash/accounts">Открыть заново</Link></AppShell>; }
  const current = data.selectedAccounts.filter(row => row.opening), all = data.accounts.filter(row => row.transactions.length), activeCategories = data.categories.filter(row => row.isActive);
  const currentOptions = current.map(row => <option key={row.id} value={row.id}>{ACCOUNT_LABELS[row.kind]} · {data.branch.name}</option>);
  const allOptions = all.map(row => <option key={row.id} value={row.id}>{row.branch.name} · {ACCOUNT_LABELS[row.kind]}</option>);
  const pageLink = (page: number) => `/cash/accounts?${new URLSearchParams({ branchId: data.branch.id, accountId: filters.accountId ?? "", page: String(page) })}`;
  return <AppShell active="/cash" title="Кассы" subtitle="Остатки, расходы и переводы · KZT">
    <WorkflowTabs active="/cash/accounts" items={[{href:"/cash",label:"Оплаты заказов"},{href:"/cash/accounts",label:"Кассы и расходы"}]}/>
    {filters.saved === "1" && <p role="status" className="notice">Операция сохранена.</p>}
    <form className="panel cash-branch-filter"><label>Филиал<select name="branchId" defaultValue={data.branch.id}>{data.branches.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="secondary">Показать</button></form>
    <details className="cash-account-guide"><summary>Как учитываются остатки и операции</summary><p>CRM фиксирует уже совершённые движения денег и не выполняет банковские переводы. После ввода начальных остатков новые оплаты, возвраты, залоги и выданная зарплата попадают в счёт выбранного способа оплаты. Способ оплаты должен быть настроен как наличный или безналичный.</p></details>
    <div className="cash-account-cards">{(Object.keys(ACCOUNT_LABELS) as Array<keyof typeof ACCOUNT_LABELS>).map(kind => {
      const acct = data.selectedAccounts.find(row => row.kind === kind);
      return <section className="panel cash-account" key={kind} data-account-kind={kind}><h2>{ACCOUNT_LABELS[kind]}</h2><p>{data.branch.name} · KZT</p>
        {acct?.opening ? <><strong className={acct.balance < BigInt(0) ? "cash-balance negative" : "cash-balance"}>{money(acct.balance)}</strong>{acct.balance < BigInt(0) && <p role="alert">Отрицательный учётный остаток. Проверьте начальный остаток и записанные движения.</p>}<p>Начальный остаток: {money(acct.opening.amountMinor)}. Записан {formatBusinessDateTime(acct.opening.occurredAt, data.branch.timezone)}.</p><Link href={`/cash/accounts?branchId=${data.branch.id}&accountId=${acct.id}`}>История счёта</Link></> : <p>Начальный остаток не задан. Ноль не предполагается автоматически.</p>}
        {data.canOpen && <details><summary>{acct?.opening ? "Исправить начальный остаток" : "Задать начальный остаток"}</summary><RetainedActionForm action={cashOpeningAction} className="form-grid cash-opening-form"><CommandContext branchId={data.branch.id}/><input type="hidden" name="branchId" value={data.branch.id}/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="replacesOpeningId" value={acct?.opening?.id ?? ""}/>{amountField("Начальный остаток KZT", acct?.opening?.amountMinor.toString())}{reasonField}<Confirmation>{acct?.opening ? "Исправляю начальный остаток; прежняя запись и обратная проводка сохранятся." : "Указываю проверенный фактический остаток на начало учёта этого счёта."}</Confirmation><button className="secondary">Сохранить начальный остаток</button></RetainedActionForm></details>}
      </section>;
    })}</div>
    {!!data.unassigned && <p className="notice">В филиале есть {data.unassigned} денежных записей без привязки к счёту. Они не включены в остатки касс. Старые платежи не переносятся автоматически: начальный остаток вводится по фактически имеющимся деньгам.</p>}
    <div className="cash-command-grid">
      {data.canExpense && <ContextPanel title="Записать расход" primary><p>Расход не является закупочной стоимостью товара и не создаёт оплату поставщику автоматически.</p>{current.length && activeCategories.length ? <RetainedActionForm action={cashExpenseAction} className="form-grid cash-expense-form"><CommandContext branchId={data.branch.id}/><label>Из кассы<select name="accountId" required defaultValue=""><option value="" disabled>Выберите счёт</option>{currentOptions}</select></label><label>Категория<select name="categoryId" required defaultValue=""><option value="" disabled>Выберите категорию</option>{activeCategories.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{amountField("Потрачено KZT")}{reasonField}<Confirmation>Деньги действительно потрачены. При отрицательном учётном остатке проверю расхождение.</Confirmation><button className="primary">Записать расход</button></RetainedActionForm> : <p>Сначала задайте остаток счёта и активную категорию расходов.</p>}</ContextPanel>}
      {data.canTransfer && <ContextPanel title="Перевод между кассами"><p>Обе стороны записываются вместе. Перевод не создаёт выручку или расход бизнеса. Банковский перевод CRM не выполняет.</p>{current.length && all.length > 1 ? <RetainedActionForm action={cashTransferAction} className="form-grid cash-transfer-form"><CommandContext branchId={data.branch.id}/><label>Откуда<select name="fromAccountId" required defaultValue=""><option value="" disabled>Выберите</option>{currentOptions}</select></label><label>Куда<select name="toAccountId" required defaultValue=""><option value="" disabled>Выберите</option>{allOptions}</select></label>{amountField("Переведено KZT")}{reasonField}<Confirmation>Деньги уже перемещены между указанными счетами. CRM только записывает этот факт.</Confirmation><button className="primary">Записать перевод</button></RetainedActionForm> : <p>Нужны два счёта с заданными начальными остатками в доступных филиалах.</p>}</ContextPanel>}
    </div>
    {data.canCategory && <details className="panel"><summary>Категории расходов</summary><p>Удаления нет. Отключение скрывает категорию из новых расходов; названия ранее записанных расходов сохраняются.</p>{[...data.categories, null].map(category => <RetainedActionForm action={cashCategoryAction} className="form-grid cash-category-form" key={category?.id ?? "new"}><input type="hidden" name="returnBranchId" value={data.branch.id}/><input type="hidden" name="id" value={category?.id ?? ""}/><input type="hidden" name="version" value={category?.version ?? ""}/><label>{category ? "Название категории" : "Новая категория"}<input name="name" maxLength={80} defaultValue={category?.name ?? ""} required/></label><label className="cash-confirm"><input type="checkbox" name="isActive" value="yes" defaultChecked={category?.isActive ?? true}/> Активная категория</label><button className="secondary">Сохранить категорию</button></RetainedActionForm>)}</details>}
    <section className="panel cash-account-history"><h2>Движения денег</h2><details className="compact-note"><summary>Учёт и исправления</summary><p>Итоги счетов считаются по всей их истории. Здесь показаны 50 записей на странице; сведения о платежах, залогах и зарплате видны только с соответствующими правами. Исправление сохраняет исходную запись и не означает реальный возврат денег.</p></details>
      <form className="toolbar"><input type="hidden" name="branchId" value={data.branch.id}/><label>Счёт<select name="accountId" defaultValue={filters.accountId ?? ""}><option value="">Оба счёта филиала</option>{currentOptions}</select></label><button className="secondary">Показать историю</button></form>
      {data.rows.map(row => <article className="cash-account-row" key={row.id} data-transaction-id={row.id}><div><strong>{ACCOUNT_OPERATION_LABELS[row.kind] ?? "Движение по счёту"}{row.kind === "REVERSAL" && row.reversalOf ? `: ${ACCOUNT_OPERATION_LABELS[row.reversalOf.kind] ?? "операция"}` : ""}</strong><p>{ACCOUNT_LABELS[data.accounts.find(acct => acct.id === row.cashAccountId)!.kind]} · {formatBusinessDateTime(row.occurredAt, data.branch.timezone)}</p>{row.expenseCategoryName && <p>{row.expenseCategoryName}</p>}<p>{row.reason}</p><p>{row.actorUser?.displayName ?? "Система"}{row.employee ? ` · сотрудник: ${row.employee.user.displayName}` : ""}</p>{row.order && <details className="reference-details"><summary><Link href={`/orders/${row.order.id}`}>{compactReference(row.order.orderNumber)}</Link></summary><p className="reference-id">Номер заказа: <Link href={`/orders/${row.order.id}`}>{row.order.orderNumber}</Link></p><p className="reference-id">ID операции: <code>{row.id}</code></p></details>}</div><div><strong>{money(row.accountEffectMinor)}</strong>{row.sourceType.includes("TRANSFER") && <p>Внутренний перевод</p>}{row.reversal && <p>Исправлено обратной записью</p>}
        {data.canCorrect && !row.reversal && ["CASH_EXPENSE", "CASH_TRANSFER_OUT", "CASH_TRANSFER_IN"].includes(row.kind) && <details><summary>Исправить ошибку</summary><RetainedActionForm action={cashCorrectionAction} className="form-grid cash-correction-form"><CommandContext branchId={data.branch.id}/><input type="hidden" name="transactionId" value={row.id}/>{reasonField}<Confirmation>{row.kind === "CASH_EXPENSE" ? "Исправляю ошибочную запись расхода; это не запись реального возврата денег." : "Исправляю обе стороны ошибочного перевода; фактическое движение проверено отдельно."}</Confirmation><button className="secondary">Создать обратную запись</button></RetainedActionForm></details>}
      </div></article>)}{!data.rows.length && <p>Нет доступных записей по выбранному счёту.</p>}<nav className="toolbar" aria-label="Страницы кассовой истории">{data.page > 1 && <Link href={pageLink(data.page - 1)}>Назад</Link>}<span>Страница {data.page}</span>{data.more && <Link href={pageLink(data.page + 1)}>Далее</Link>}</nav>
    </section>
  </AppShell>;
}
