import {hasPermission} from "@/lib/permissions/effective";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { RetainedActionForm } from "@/components/RetainedActionForm";
import { requireRouteAccess } from "@/lib/auth/session";
import { cashOptions, cashMovements, CASH_KIND_LABELS, type CashFilters } from "@/lib/finance/cash";
import { acceptCashPaymentAction } from "@/app/cash/actions";
import { formatBusinessDateTime } from "@/lib/calendar/timezone";
import { PAYMENT_CHANNEL_LABELS, paymentChannel } from "@/lib/finance/payment-channel";
const money = (amount: bigint, currency: string) => `${amount.toLocaleString("ru-KZ")} ${currency}`;
export default async function Page({ searchParams }: { searchParams: Promise<CashFilters & { saved?: string }> }) {
  const actor = await requireRouteAccess("/cash"), filters = await searchParams;
  const canAccounts=await hasPermission(actor,"CASH_ACCOUNT_VIEW");
  let options: Awaited<ReturnType<typeof cashOptions>>, data: Awaited<ReturnType<typeof cashMovements>>;
  try { [options, data] = await Promise.all([cashOptions(actor, filters), cashMovements(actor, filters)]); }
  catch (error) { return <AppShell active="/cash" title="Касса">{canAccounts&&<Link href="/cash/accounts">Остатки касс, расходы и переводы</Link>}<p className="notice error">{error instanceof Error ? error.message : "Касса недоступна."}</p><Link href="/cash">Открыть кассу заново</Link></AppShell>; }
  const href = (page: number) => { const query = new URLSearchParams(); for (const key of ["branchId", "paymentMethodId", "kind", "orderQuery", "channel"] as const) if (filters[key]) query.set(key, filters[key]!); query.set("from", data.period.fromLabel); query.set("until", data.period.untilLabel); query.set("page", String(page)); return `/cash?${query}`; };
  return <AppShell active="/cash" title="Касса" subtitle="Оплаты заказов и движение денег">
    {canAccounts&&<p><Link className="secondary button-link" href="/cash/accounts">Остатки касс, расходы и переводы</Link></p>}
    {filters.saved === "1" && <p className="notice" role="status">Оплата принята.</p>}
    <form className="card form-grid cash-filters"><label>Филиал<select name="branchId" defaultValue={filters.branchId ?? ""}><option value="">Все доступные</option>{options.branches.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Номер заказа<input name="orderQuery" maxLength={100} defaultValue={filters.orderQuery}/></label>
      {data.canView && <><label>Категория оплаты<select name="channel" defaultValue={filters.channel ?? ""}><option value="">Все</option>{Object.entries(PAYMENT_CHANNEL_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>С даты UTC<input name="from" type="date" defaultValue={data.period.fromLabel} required/></label><label>По дату UTC включительно<input name="until" type="date" defaultValue={data.period.untilLabel} required/></label><label>Способ оплаты<select name="paymentMethodId" defaultValue={filters.paymentMethodId ?? ""}><option value="">Все</option>{options.methods.map(row => <option key={row.id} value={row.id}>{row.displayName}{row.isActive ? "" : " (неактивен)"}</option>)}</select></label><label>Операция<select name="kind" defaultValue={filters.kind ?? ""}><option value="">Все разрешённые</option>{Object.entries(CASH_KIND_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></>}
      <button className="secondary">Показать</button><Link href="/cash">Сбросить</Link>
    </form>
    {options.canCreate && <section><h2>Принять оплату заказа</h2><p>Предоплата, доплата или полная оплата подтверждённого заказа. Сумма не может превышать остаток к оплате.</p>{options.moreOrders && <p>Показаны 50 последних заказов. Уточните номер заказа в поиске выше.</p>}
      {options.orders.length && options.methods.some(row => row.isActive) ? <RetainedActionForm action={acceptCashPaymentAction} className="card form-grid cash-payment-form"><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>Заказ<select name="orderId" defaultValue="" required><option value="" disabled>Выберите заказ</option>{options.orders.map(row => <option key={row.id} value={row.id}>{row.orderNumber} · {row.branch.name} · {row.currency}</option>)}</select></label><label>Сумма в валюте заказа<input name="amountMinor" inputMode="numeric" pattern="[1-9][0-9]*" required placeholder="Например, 5000" maxLength={18}/></label><label>Способ оплаты<select name="paymentMethodId" defaultValue="" required><option value="" disabled>Выберите способ</option>{options.methods.filter(row => row.isActive).map(row => <option key={row.id} value={row.id}>{row.displayName} · {PAYMENT_CHANNEL_LABELS[paymentChannel(row.code)]}</option>)}</select></label><button className="primary">Принять оплату</button></RetainedActionForm> : <p className="notice">{options.orders.length ? "Нет активных способов оплаты. Их настраивает владелец." : "Нет подтверждённых заказов по выбранным условиям."}</p>}
    </section>}
    <section className="card cash-movements"><h2>Движение денег</h2>{!data.canView ? <p>Просмотр финансовых операций недоступен по вашим правам. Право приёма оплаты не открывает финансовую историю.</p> : <><p>Записи существующего финансового журнала. Удаление запрещено; ошибочную запись исправляют обратной проводкой при наличии отдельного права. Возвраты и операции с залогом доступны в заказе согласно вашим правам.</p>
      {data.rows.map(row => <article className="finance-row" key={row.id}><div><strong>{CASH_KIND_LABELS[row.kind as keyof typeof CASH_KIND_LABELS]}</strong><p>{formatBusinessDateTime(row.occurredAt, row.branch.timezone)} · {row.branch.name} · {row.branch.timezone}</p><p>{PAYMENT_CHANNEL_LABELS[paymentChannel(row.paymentMethod?.code)]} · {row.paymentMethod?.displayName ?? "Без способа оплаты"} · {row.actorUser?.displayName ?? "Система"}</p>{row.customer && <Link href={`/customers/${row.customer.id}`}>{row.customer.firstName} {row.customer.lastName}</Link>}{row.order && <p><Link href={`/orders/${row.order.id}`}>{row.order.orderNumber}</Link></p>}</div><div><strong>{money(row.cashEffectMinor, row.currency)}</strong>{row.kind === "REVERSAL" && row.reversalOf && <p>Исправление: {CASH_KIND_LABELS[row.reversalOf.kind as keyof typeof CASH_KIND_LABELS]}</p>}{row.reversal && <p>Исправлена обратной проводкой</p>}{options.canReverse && row.kind !== "REVERSAL" && !row.reversal && <Link href={`/finance/${row.id}/reverse`}>Исправить ошибочную запись</Link>}</div></article>)}{!data.rows.length && <p>Операций по фильтрам нет.</p>}
      <nav className="toolbar" aria-label="Страницы операций">{data.page > 1 && <Link href={href(data.page - 1)}>Назад</Link>}<span>Страница {data.page}</span>{data.more && <Link href={href(data.page + 1)}>Далее</Link>}</nav></>}
    </section>
  </AppShell>;
}
