import ExcelJS from "exceljs";
import {getCurrentSession} from "@/lib/auth/session";
import {getCrmReports} from "@/lib/reports/queries";
export const runtime="nodejs";
function cell(value:unknown):string|number{if(typeof value==="bigint")return value.toString();if(typeof value==="number")return value;const text=String(value??"").replace(/[\r\n\t]+/g," ");return /^\s*[=+\-@]/.test(text)?`'${text}`:text;}
export async function GET(request:Request){const actor=await getCurrentSession();if(!actor)return new Response("Требуется вход.",{status:401});const q=new URL(request.url).searchParams;let data:Awaited<ReturnType<typeof getCrmReports>>;try{data=await getCrmReports(actor,{from:q.get("from")||undefined,until:q.get("until")||undefined,branchId:q.get("branchId")||undefined})}catch(error){return new Response(error instanceof Error?error.message:"Отчёт недоступен.",{status:403})}
 const workbook=new ExcelJS.Workbook();function sheet(name:string,headers:string[],rows:unknown[][]){const s=workbook.addWorksheet(name);s.columns=headers.map((header,index)=>({header,key:String(index),width:25}));for(const row of rows)s.addRow(Object.fromEntries(row.map((value,index)=>[String(index),cell(value)])));s.getRow(1).font={bold:true};s.views=[{state:"frozen",ySplit:1}];s.columns.forEach(column=>{column.width=25});return s;}
 sheet("Условия",["Показатель","Значение"],[["Начало UTC",data.period.from.toISOString()],["Конец UTC не включая",data.period.endExclusive.toISOString()],["Средний чек","Договорная стоимость / число неотменённых заказов, созданных в период; по валютам"],["Баланс","Текущее состояние, не оборот за период"],["Историческая загрузка",data.historicalUtilization.reason],["Аренда единиц-дней",data.rentalQuantityTime.unitDays],["Неполных выдач исключено",data.rentalQuantityTime.incompleteAllocations],["Активных клиентов",data.customerCount],["Новых карточек клиентов",data.newCustomers],["Новые клиенты филиала","Карточки, созданные в период и имеющие заказ в выбранном филиале"]]);
 const hasRevenue=data.orders.some(row=>row.contractTotal!==undefined);sheet("Заказы",["Тип","Валюта","Количество",...(hasRevenue?["Договорная сумма","Средний чек"]:[])],data.orders.map(row=>[row.type,row.currency,row.count,...(hasRevenue?[row.contractTotal,row.averageContract]:[])]));
 sheet("Статусы",["Тип","Статус","Количество"],data.statuses.map(row=>[row.type,row.status,row.count]));sheet("Ответственные",["Текущее назначение","Количество"],data.assignees.map(row=>[row.name,row.count]));
 const debt=data.balances.some(row=>row.debt!==undefined),deposit=data.balances.some(row=>row.deposit!==undefined);sheet("Баланс сейчас",["Валюта",...(debt?["Долг","Переплата"]:[]),...(deposit?["Удерживаемые залоги"]:[])],data.balances.map(row=>[row.currency,...(debt?[row.debt,row.credit]:[]),...(deposit?[row.deposit]:[])]));
 const keys=["revenueEffectMinor","cashEffectMinor","depositEffectMinor","obligationEffectMinor"] as const,visible=keys.filter(key=>data.finance.some(row=>row[key]!==undefined));sheet("Финансовые обороты",["Валюта","Вид","Операций",...visible],data.finance.map(row=>[row.currency,row.kind,row.count,...visible.map(key=>row[key])]));
 sheet("Топ 20 выдач",["Товар","Исполнение","Размер","SKU","Выдано","Движений"],data.topProducts.map(row=>[row.variant?.product.name,row.variant?.execution?.name,row.variant?.size.name,row.variant?.sku,row.quantity,row.movements]));
 sheet("Движения",["Тип","Записей","Сумма количеств со знаком"],data.movements.map(row=>[row.type,row.count,row.quantity]));if(data.inventory)sheet("BULK сейчас",["Показатель","Единиц"],Object.entries(data.inventory));
 return new Response(Buffer.from(await workbook.xlsx.writeBuffer()),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=mariposa-crm-reports.xlsx","Cache-Control":"private, no-store"}});
}
