"use server";
import {redirect,unstable_rethrow} from "next/navigation";import{revalidatePath}from"next/cache";import{requireRouteAccess}from"@/lib/auth/session";import{requirePermission}from"@/lib/permissions/effective";import{createTenantContext}from"@/lib/tenant/context";import{createStaffInvitation,revokeInvitation}from"@/lib/staff/invitations";import{deactivateStaff,reactivateStaff,updateStaffAccess}from"@/lib/staff/management";import{changeOwnPassword}from"@/lib/staff/password";
import {setPermissionOverride} from "@/lib/permissions/management";import{isPermissionKey}from"@/lib/permissions/registry";
const txt=(f:FormData,k:string)=>String(f.get(k)||"").trim(),actor=(s:Awaited<ReturnType<typeof requireRouteAccess>>)=>({userId:s.userId,membershipId:s.membershipId,role:s.role}),fail=(e:unknown)=>{unstable_rethrow(e);return e instanceof Error?e.message:"Операция не выполнена."};
export async function inviteStaffAction(f:FormData){const s=await requireRouteAccess("/settings/staff"),role=String(f.get("role"))as"OWNER"|"DIRECTOR"|"SELLER"|"CASHIER",branches=f.getAll("branchId").map(String);try{await requirePermission(s,"STAFF_INVITE");await createStaffInvitation(createTenantContext(s.organizationId),{email:String(f.get("email")||""),firstName:String(f.get("firstName")||""),lastName:String(f.get("lastName")||""),role,branchIds:branches,defaultBranchId:String(f.get("defaultBranchId")||"")||null},actor(s));revalidatePath("/settings/staff");redirect("/settings/staff?ok=1")}catch(e){if((e as{digest?:string}).digest?.startsWith("NEXT_REDIRECT"))throw e;redirect(`/settings/staff/invite?error=${encodeURIComponent(fail(e))}`)}}
export async function updateStaffAction(f:FormData){const id=txt(f,"membershipId");try{const s=await requireRouteAccess("/settings/staff");await requirePermission(s,"STAFF_EDIT");await updateStaffAccess(createTenantContext(s.organizationId),id,{firstName:txt(f,"firstName"),lastName:txt(f,"lastName"),phone:txt(f,"phone"),role:txt(f,"role")as never,branchIds:f.getAll("branchId").map(String),defaultBranchId:txt(f,"defaultBranchId")||null},actor(s));revalidatePath("/settings/staff");redirect(`/settings/staff/${id}?ok=${encodeURIComponent("Изменения сохранены. Сеансы сотрудника отозваны.")}`)}catch(e){redirect(`/settings/staff/${id}?error=${encodeURIComponent(fail(e))}`)}}
export async function deactivateStaffAction(f:FormData){const id=txt(f,"membershipId");try{const s=await requireRouteAccess("/settings/staff");await requirePermission(s,"STAFF_DEACTIVATE");await deactivateStaff(createTenantContext(s.organizationId),id,actor(s));revalidatePath("/settings/staff");redirect(`/settings/staff/${id}?ok=${encodeURIComponent("Доступ сотрудника отключён.")}`)}catch(e){redirect(`/settings/staff/${id}?error=${encodeURIComponent(fail(e))}`)}}
export async function reactivateStaffAction(f:FormData){const id=txt(f,"membershipId");try{const s=await requireRouteAccess("/settings/staff");await requirePermission(s,"STAFF_EDIT");await reactivateStaff(createTenantContext(s.organizationId),id,actor(s));revalidatePath("/settings/staff");redirect(`/settings/staff/${id}?ok=${encodeURIComponent("Доступ восстановлен. Требуется новый вход.")}`)}catch(e){redirect(`/settings/staff/${id}?error=${encodeURIComponent(fail(e))}`)}}
export async function revokeInvitationAction(f:FormData){try{const s=await requireRouteAccess("/settings/staff");await requirePermission(s,"STAFF_INVITE");await revokeInvitation(createTenantContext(s.organizationId),txt(f,"invitationId"),actor(s));revalidatePath("/settings/staff");redirect("/settings/staff?ok=invite-revoked")}catch(e){redirect(`/settings/staff?error=${encodeURIComponent(fail(e))}`)}}
export async function changePasswordAction(f:FormData){try{const s=await requireRouteAccess("/settings/security"),next=txt(f,"newPassword");if(next!==txt(f,"confirmation"))throw new Error("Пароли не совпадают.");await changeOwnPassword({userId:s.userId,currentSessionId:s.sessionId,currentPassword:txt(f,"currentPassword"),newPassword:next});redirect(`/settings/security?ok=${encodeURIComponent("Пароль изменён. Другие сеансы завершены.")}`)}catch(e){redirect(`/settings/security?error=${encodeURIComponent(fail(e))}`)}}
export async function updatePermissionOverrideAction(f:FormData){const id=txt(f,"membershipId"),key=txt(f,"permissionKey"),value=txt(f,"effect");try{const s=await requireRouteAccess("/settings/staff");await requirePermission(s,"STAFF_PERMISSION_MANAGE");if(!isPermissionKey(key)||!(["ALLOW","DENY","DEFAULT"]as const).includes(value as never))throw new Error("Некорректное право доступа.");await setPermissionOverride(createTenantContext(s.organizationId),id,key,value==="DEFAULT"?null:value as"ALLOW"|"DENY",actor(s));revalidatePath(`/settings/staff/${id}`);redirect(`/settings/staff/${id}?ok=${encodeURIComponent("Индивидуальное право сохранено. Сеансы сотрудника завершены.")}`)}catch(e){redirect(`/settings/staff/${id}?error=${encodeURIComponent(fail(e))}`)}}
