import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { requireRouteAccess } from "@/lib/auth/session";
import { getInquiryFunnel, type FunnelFilters } from "@/lib/reports/inquiry-funnel";
import { SOURCE_LABELS } from "@/lib/inquiries/validation";
const date = (value: Date) => value.toLocaleString("ru-RU", { timeZone: "UTC" });
const ratio = (part: number, total: number) => total ? `${(part / total * 100).toLocaleString("ru-RU", { maximumFractionDigits: 1 })}%` : "недоступно: нет обращений";
export default async function Page({ searchParams }: { searchParams: Promise<FunnelFilters> }) {
  const actor = await requireRouteAccess("/reports"), raw = await searchParams;
  let data: Awaited<ReturnType<typeof getInquiryFunnel>>;
  try { data = await getInquiryFunnel(actor, raw); }
  catch (error) { return <AppShell active="/reports" title="Воронка обращений"><p role="alert">{error instanceof Error ? error.message : "Отчёт недоступен."}</p><Link href="/reports/funnel">Сбросить фильтры</Link></AppShell>; }
  const query = new URLSearchParams({ from: data.period.fromLabel, until: data.period.untilLabel, ...(raw.branchId ? { branchId: raw.branchId } : {}), ...(raw.source ? { source: raw.source } : {}) });
  const pageHref = (page: number) => { const q = new URLSearchParams(query); q.set("page", String(page)); return `/reports/funnel?${q}`; };
  return <AppShell active="/reports" title="Воронка обращений" subtitle="Сохранённые связи одной группы обращений">
    <Link href="/reports">Все отчёты CRM</Link>
    <form method="get" className="card form-grid product-report-filters"><label>Созданы с даты UTC<input type="date" name="from" required defaultValue={data.period.fromLabel}/></label><label>По дату UTC включительно<input type="date" name="until" required defaultValue={data.period.untilLabel}/></label><label>Филиал<select name="branchId" defaultValue={raw.branchId ?? ""}><option value="">Все доступные</option>{data.branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Источник обращения<select name="source" defaultValue={raw.source ?? ""}><option value="">Все источники</option>{Object.entries(SOURCE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="primary">Показать</button></form>
    <section className="card"><h2>Как читать воронку</h2><p>Группа — обращения, созданные в выбранный период UTC. Примерки и заказы учитываются по сохранённым связям этих обращений на момент просмотра: {date(data.asOf)} UTC, включая записи после конца выбранного периода. Для сравнения периодов это разные сроки наблюдения.</p><p>Примерка здесь — созданная запись, а не подтверждение посещения. Заказ — связанный документ, а не оплата или успешная продажа; отменённые записи тоже включены. Текущие статусы не используются как история переходов.</p><p>«Обращение → заказ» включает прямой заказ и заказ через примерку. «Через примерку» требует связи самой примерки с заказом; наличие обоих документов у обращения недостаточно. Несколько записей не увеличивают число обращений; одинаковый заказ считается один раз.</p></section>
    {!data.available ? <p role="alert" className="card">{data.reason}</p> : <>
      <section className="card funnel-summary"><h2>Связи группы</h2><p>Обращений: <strong>{data.total}</strong></p><p>С примеркой: <strong>{data.withFitting}</strong> · {ratio(data.withFitting, data.total)} обращений</p><p>С заказом: <strong>{data.withOrder}</strong> · {ratio(data.withOrder, data.total)} обращений</p><p>С заказом через примерку: <strong>{data.throughFitting}</strong> · {ratio(data.throughFitting, data.withFitting)} обращений с примеркой</p><p>Связанных записей примерок: {data.fittingCount}. Уникальных связанных заказов: {data.orderCount}.</p></section>
      <section className="card funnel-records"><h2>Исходные записи</h2>{!data.rows.length ? <p>Обращений в выбранной группе нет. Конверсия недоступна.</p> : <div className="warehouse-table-wrap"><table className="warehouse-table"><thead><tr>{["Обращение / создание UTC", "Филиал / источник", "Примерки", "Заказы"].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{data.rows.map(row => <tr key={row.id}><td data-label="Обращение / создание UTC"><Link href={`/chats/${row.id}`}>{row.subject}</Link><small>{date(row.createdAt)}</small></td><td data-label="Филиал / источник">{row.branch}<small>{SOURCE_LABELS[row.source] ?? "Источник не указан"}</small></td><td data-label="Примерки">{row.fittings.length ? row.fittings.map(f => <p key={f.id}><Link href={`/fittings/${f.id}`}>Примерка {date(f.startsAt)} UTC</Link></p>) : "Сохранённой доступной связи нет"}</td><td data-label="Заказы">{row.orders.length ? row.orders.map(o => <p key={o.id}><Link href={`/orders/${o.id}`}>{o.orderNumber}</Link></p>) : "Сохранённой доступной связи нет"}</td></tr>)}</tbody></table></div>}<nav className="toolbar" aria-label="Страницы воронки">{data.page > 1 && <Link href={pageHref(data.page - 1)}>Назад</Link>}<span>Страница {data.page} из {data.pages}</span>{data.page < data.pages && <Link href={pageHref(data.page + 1)}>Далее</Link>}</nav></section>
    </>}
    <section className="card"><h2>Границы данных</h2><p>Показаны только сохранённые связи в доступных филиалах. Отсутствие связи не доказывает потерю клиента: старые несвязанные заказы и примерки не приписываются обращениям. Проценты описывают полноту связей этой группы, а не историческую эффективность сотрудников.</p><p>История времени связывания и прошлых значений источника не восстанавливается. Источник берётся из обращения; обязательное значение «В магазине» могло быть установлено по умолчанию. Отличить незаполненный первоначальный источник от подтверждённого нельзя. «Другое» сохраняется отдельной категорией. Время до конверсии и воронка на прошлую дату недоступны.</p></section>
  </AppShell>;
}
