import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { recordBulkLoss, recordBulkReturn } from "../lib/fulfillment/bulk-returns";
import { completeBulkMaintenance, writeOffBulkMaintenance } from "../lib/fulfillment/bulk-maintenance";
import { assessOrderDamage, waiveOrderDamage } from "../lib/finance/order-damage";
import { evaluateReturnSettlement, getUnresolvedDamageAllocationIds } from "../lib/finance/order-settlement";
import { effectsFor } from "../lib/finance/effects";
import { createFinancialTransactionWithClient } from "../lib/finance/transactions";
import { buildCapacitySegments, calculatePeakBlockedCapacity } from "../lib/availability/capacity";

const passed:string[]=[];
const pass=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);passed.push(name)};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
const at=(hour:number)=>new Date(Date.UTC(2045,0,10,hour));

async function main(){
  const rollback=new Error("BULK_3_ROLLBACK");
  await db.$transaction(async tx=>{
    const suffix=randomUUID().slice(0,8);
    const org=await tx.organization.create({data:{name:"BULK-3 targeted",slug:`bulk-3-${suffix}`}});
    const user=await tx.user.create({data:{email:`bulk-3-${suffix}@example.test`,displayName:"BULK-3",passwordHash:"test"}});
    const directorUser=await tx.user.create({data:{email:`bulk-3-director-${suffix}@example.test`,displayName:"BULK-3 Director",passwordHash:"test"}});
    const branch=await tx.branch.create({data:{organizationId:org.id,name:"A",code:"A",city:"Test",timezone:"UTC"}});
    const stock=await tx.location.create({data:{organizationId:org.id,branchId:branch.id,name:"Stock",code:"STOCK",type:"WAREHOUSE"}});
    const repair=await tx.location.create({data:{organizationId:org.id,branchId:branch.id,name:"Repair",code:"REPAIR",type:"REPAIR"}});
    const membership=await tx.organizationMembership.create({data:{organizationId:org.id,userId:user.id,role:"OWNER",status:"ACTIVE",defaultBranchId:branch.id}});
    const directorMembership=await tx.organizationMembership.create({data:{organizationId:org.id,userId:directorUser.id,role:"DIRECTOR",status:"ACTIVE",defaultBranchId:branch.id}});
    await tx.membershipBranchAccess.create({data:{organizationId:org.id,membershipId:directorMembership.id,branchId:branch.id}});
    const paymentMethod=await tx.paymentMethod.create({data:{organizationId:org.id,code:"CASH",displayName:"Cash"}});
    const customer=await tx.customer.create({data:{organizationId:org.id,customerNumber:`C-${suffix}`,firstName:"Fixture"}});
    const size=await tx.size.create({data:{organizationId:org.id,code:"120",name:"120"}});
    const product=await tx.product.create({data:{organizationId:org.id,name:"Белоснежка",internalCode:`B-${suffix}`,trackingMode:"BULK"}});
    const variant=await tx.productVariant.create({data:{organizationId:org.id,productId:product.id,sizeId:size.id,sku:`0060.120-${suffix}`}});
    await tx.stockLevel.create({data:{organizationId:org.id,productVariantId:variant.id,branchId:branch.id,locationId:stock.id,quantity:20}});
    const order=await tx.order.create({data:{organizationId:org.id,orderNumber:`O-${suffix}`,branchId:branch.id,customerId:customer.id,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT",rentalStartAt:at(8),rentalEndAt:at(10)}});
    const item=await tx.orderItem.create({data:{organizationId:org.id,orderId:order.id,productVariantId:variant.id,quantity:6,status:"ISSUED",unitPriceMinor:BigInt(1000),lineTotalMinor:BigInt(6000),currency:"KZT",productNameSnapshot:product.name,variantNameSnapshot:"120",skuSnapshot:variant.sku}});
    const allocation=await tx.capacityAllocation.create({data:{organizationId:org.id,orderId:order.id,orderItemId:item.id,branchId:branch.id,productVariantId:variant.id,sourceType:"ORDER",quantity:6,blockedFrom:at(8),blockedUntil:at(10),issuedAt:at(8),issuedByUserId:user.id,issuedQuantity:6}});
    await tx.stockLevel.updateMany({where:{organizationId:org.id,branchId:branch.id,productVariantId:variant.id,locationId:stock.id},data:{quantity:{decrement:6}}});
    await tx.inventoryMovement.create({data:{organizationId:org.id,productVariantId:variant.id,type:"RENTAL_ISSUE",quantity:-6,fromBranchId:branch.id,fromLocationId:stock.id,sourceType:"CAPACITY_ALLOCATION",sourceId:allocation.id,idempotencyKey:`issue-${suffix}`,createdByUserId:user.id,occurredAt:at(8)}});
    const tenant=createTenantContext(org.id),actor={userId:user.id,membershipId:membership.id,role:"OWNER" as const};
    const firstReturn=await recordBulkReturn(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,idempotencyKey:`return-1-${suffix}`,occurredAt:at(11),dispositions:[{outcome:"DAMAGED",quantity:1,locationId:repair.id},{outcome:"GOOD",quantity:1,locationId:stock.id}]},actor,tx);
    pass("split return regression",firstReturn.returnedQuantity===2&&firstReturn.outstandingAfter===4);
    const damagedLineId=(await tx.bulkPhysicalResolutionLine.findFirstOrThrow({where:{resolutionId:firstReturn.resolutionId,outcome:"DAMAGED"}})).id;
    const repairAllocation=(await tx.capacityAllocation.findFirstOrThrow({where:{bulkSourceResolutionLineId:damagedLineId}})).id;
    const stockAfterReturn=(await tx.stockLevel.aggregate({where:{organizationId:org.id,productVariantId:variant.id,branchId:branch.id},_sum:{quantity:true}}))._sum.quantity??0;
    pass("return increases physical stock",stockAfterReturn===16);
    const loss=await recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:1,reason:"Клиент подтвердил утрату",idempotencyKey:`loss-1-${suffix}`,occurredAt:at(12)},actor,tx);
    pass("partial loss resolution",loss.lostQuantity===1&&loss.outstandingAfter===3);
    pass("loss reduces outstanding",6-2-loss.lostQuantity===3);
    pass("loss does not create return",await tx.inventoryMovement.count({where:{bulkResolutionLine:{resolutionId:loss.resolutionId},type:"RENTAL_RETURN"}})===0);
    pass("loss creates LOSS movement",await tx.inventoryMovement.count({where:{bulkResolutionLine:{resolutionId:loss.resolutionId},type:"LOSS",quantity:-1}})===1);
    pass("loss does not increase stock",((await tx.stockLevel.aggregate({where:{organizationId:org.id,productVariantId:variant.id,branchId:branch.id},_sum:{quantity:true}}))._sum.quantity??0)===stockAfterReturn);
    const lostLineId=(await tx.bulkPhysicalResolutionLine.findFirstOrThrow({where:{resolutionId:loss.resolutionId,outcome:"LOST"}})).id;
    pass("loss requires finance decision",(await getUnresolvedDamageAllocationIds(tx,org.id,order.id)).includes(lostLineId));
    await waiveOrderDamage(tenant,{bulkResolutionLineId:lostLineId,reason:"Компенсация утраты не начисляется",idempotencyKey:`loss-waive-${suffix}`},actor,tx);
    const replay=await recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:1,reason:"Клиент подтвердил утрату",idempotencyKey:`loss-1-${suffix}`},actor,tx);
    pass("loss idempotent replay",replay.resolutionId===loss.resolutionId);
    await tx.organizationMembership.update({where:{id:directorMembership.id},data:{status:"SUSPENDED"}});
    pass("authorization before loss replay",await rejects(()=>recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:1,reason:"Клиент подтвердил утрату",idempotencyKey:`loss-1-${suffix}`},{userId:directorUser.id,membershipId:directorMembership.id,role:"DIRECTOR"},tx)));
    await tx.organizationMembership.update({where:{id:directorMembership.id},data:{status:"ACTIVE"}});
    pass("loss conflicting replay",await rejects(()=>recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:2,reason:"Клиент подтвердил утрату",idempotencyKey:`loss-1-${suffix}`},actor,tx)));
    pass("over loss rejected",await rejects(()=>recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:4,reason:"Чрезмерная утрата",idempotencyKey:`loss-over-${suffix}`},actor,tx)));
    const segments=buildCapacitySegments([{id:allocation.id,sourceType:"ORDER",quantity:6,blockedFrom:at(8),blockedUntil:at(10),issuedQuantity:6,returnedQuantity:2}],"BULK",new Map([[allocation.id,1]]));
    pass("loss stops overdue block exactly",calculatePeakBlockedCapacity(segments,at(12),at(13))===3);
    pass("loss reduces active fleet",stockAfterReturn+3===19);
    const partialSettlement=evaluateReturnSettlement({orderStatus:"CONFIRMED",issuedQuantity:6,returnedQuantity:2,resolvedUnrecoverableQuantity:1,unresolvedDamageCount:1,outstandingMinor:BigInt(0),heldDepositMinor:BigInt(0),damageChargeMinor:BigInt(0),damageWithheldMinor:BigInt(0),activeDamageChargeCount:0});
    pass("unresolved prevents physical completion",!partialSettlement.physicalComplete);
    pass("loss not counted returned",(await tx.capacityAllocation.findUniqueOrThrow({where:{id:allocation.id}})).returnedQuantity===2);
    const charge=await assessOrderDamage(tenant,{bulkResolutionLineId:damagedLineId,amountMinor:BigInt(2500),reason:"Ремонт повреждения",idempotencyKey:`damage-${suffix}`},actor,tx);
    pass("BULK damaged line charge provenance",charge.sourceId===damagedLineId&&charge.sourceType==="RETURN_DAMAGE_ASSESSMENT");
    pass("damage charge effects",charge.revenueEffectMinor===BigInt(2500)&&charge.obligationEffectMinor===BigInt(2500));
    pass("duplicate damage assessment prevented",await rejects(()=>assessOrderDamage(tenant,{bulkResolutionLineId:damagedLineId,amountMinor:BigInt(2500),reason:"Повторная оценка",idempotencyKey:`damage-duplicate-${suffix}`},actor,tx)));
    const secondReturn=await recordBulkReturn(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,idempotencyKey:`return-2-${suffix}`,occurredAt:at(13),dispositions:[{outcome:"DAMAGED",quantity:1,locationId:repair.id}]},actor,tx);
    const waivedLineId=(await tx.bulkPhysicalResolutionLine.findFirstOrThrow({where:{resolutionId:secondReturn.resolutionId,outcome:"DAMAGED"}})).id;
    const waiver=await waiveOrderDamage(tenant,{bulkResolutionLineId:waivedLineId,reason:"Ущерб не подтверждён",idempotencyKey:`waive-${suffix}`},actor,tx);
    pass("waiver path",waiver.entityId===waivedLineId);
    pass("waiver creates no revenue",await tx.financialTransaction.count({where:{sourceId:waivedLineId}})===0);
    pass("damage decision removes unresolved",(await getUnresolvedDamageAllocationIds(tx,org.id,order.id)).length===0);
    const deposit=await createFinancialTransactionWithClient(tx,tenant,"DEPOSIT_RECEIVED",{branchId:branch.id,customerId:customer.id,orderId:order.id,amountMinor:BigInt(3000),currency:"KZT",paymentMethodId:paymentMethod.id,sourceType:"ORDER_DEPOSIT",sourceId:order.id,idempotencyKey:`deposit-${suffix}`,reason:undefined},actor,effectsFor("DEPOSIT_RECEIVED",BigInt(3000)));
    pass("deposit is not revenue",deposit.revenueEffectMinor===BigInt(0));
    const withheld=await createFinancialTransactionWithClient(tx,tenant,"DEPOSIT_WITHHELD",{branchId:branch.id,customerId:customer.id,orderId:order.id,amountMinor:BigInt(2000),currency:"KZT",sourceType:"DAMAGE_DEPOSIT_SETTLEMENT",sourceId:charge.id,idempotencyKey:`withhold-${suffix}`,reason:undefined},actor,effectsFor("DEPOSIT_WITHHELD",BigInt(2000)),deposit.id);
    pass("deposit withholding reduces obligation",withheld.obligationEffectMinor===-BigInt(2000));
    pass("deposit withholding not damage revenue",withheld.revenueEffectMinor===BigInt(0));
    const damageNet=await tx.financialTransaction.aggregate({where:{orderId:order.id,OR:[{kind:"DAMAGE_CHARGE"},{kind:"REVERSAL",reversalOf:{kind:"DAMAGE_CHARGE"}}]},_sum:{revenueEffectMinor:true}});
    pass("no double counted damage revenue",damageNet._sum.revenueEffectMinor===BigInt(2500));
    const beforeComplete=(await tx.stockLevel.aggregate({where:{organizationId:org.id,branchId:branch.id,productVariantId:variant.id},_sum:{quantity:true}}))._sum.quantity??0;
    const completed=await completeBulkMaintenance(tenant,{allocationId:repairAllocation,quantity:1,destinationLocationId:stock.id,idempotencyKey:`repair-complete-${suffix}`},actor,tx);
    pass("repair completion",completed.remainingQuantity===0);
    pass("repair completion preserves stock",((await tx.stockLevel.aggregate({where:{organizationId:org.id,branchId:branch.id,productVariantId:variant.id},_sum:{quantity:true}}))._sum.quantity??0)===beforeComplete);
    pass("repair completion releases allocation",(await tx.capacityAllocation.findUniqueOrThrow({where:{id:repairAllocation}})).status==="RELEASED");

    const waivedRepair=(await tx.capacityAllocation.findFirstOrThrow({where:{bulkSourceResolutionLineId:waivedLineId}})).id;
    const beforeWriteoff=(await tx.stockLevel.aggregate({where:{organizationId:org.id,branchId:branch.id,productVariantId:variant.id},_sum:{quantity:true}}))._sum.quantity??0;
    const writeoff=await writeOffBulkMaintenance(tenant,{allocationId:waivedRepair,quantity:1,idempotencyKey:`writeoff-${suffix}`,note:"Восстановление невозможно"},actor,tx);
    pass("partial/full writeoff command",writeoff.remainingQuantity===0);
    pass("writeoff decreases stock exactly",((await tx.stockLevel.aggregate({where:{organizationId:org.id,branchId:branch.id,productVariantId:variant.id},_sum:{quantity:true}}))._sum.quantity??0)===beforeWriteoff-1);
    pass("writeoff movement provenance",await tx.inventoryMovement.count({where:{bulkMaintenanceEventId:writeoff.eventId,type:"WRITE_OFF",quantity:-1}})===1);
    pass("writeoff closes maintenance",(await tx.capacityAllocation.findUniqueOrThrow({where:{id:waivedRepair}})).status==="RELEASED");
    const writeoffReplay=await writeOffBulkMaintenance(tenant,{allocationId:waivedRepair,quantity:1,idempotencyKey:`writeoff-${suffix}`,note:"Восстановление невозможно"},actor,tx);
    pass("writeoff idempotent replay",writeoffReplay.eventId===writeoff.eventId);
    pass("writeoff conflicting replay",await rejects(()=>writeOffBulkMaintenance(tenant,{allocationId:waivedRepair,quantity:2,idempotencyKey:`writeoff-${suffix}`,note:"Восстановление невозможно"},actor,tx)));
    pass("over writeoff rejected",await rejects(()=>writeOffBulkMaintenance(tenant,{allocationId:waivedRepair,quantity:1,idempotencyKey:`writeoff-over-${suffix}`,note:"Повторное списание"},actor,tx)));
    const finalLoss=await recordBulkLoss(tenant,{orderId:order.id,orderItemId:item.id,allocationId:allocation.id,quantity:2,reason:"Остаток признан утраченным",idempotencyKey:`loss-final-${suffix}`},actor,tx);
    pass("full remaining loss resolution",finalLoss.outstandingAfter===0);
    const finalLostLineId=(await tx.bulkPhysicalResolutionLine.findFirstOrThrow({where:{resolutionId:finalLoss.resolutionId,outcome:"LOST"}})).id;
    await waiveOrderDamage(tenant,{bulkResolutionLineId:finalLostLineId,reason:"Решение по остаточной утрате",idempotencyKey:`loss-final-waive-${suffix}`},actor,tx);
    const finalSettlement=evaluateReturnSettlement({orderStatus:"CONFIRMED",issuedQuantity:6,returnedQuantity:3,resolvedUnrecoverableQuantity:3,unresolvedDamageCount:0,outstandingMinor:BigInt(500),heldDepositMinor:BigInt(1000),damageChargeMinor:BigInt(2500),damageWithheldMinor:BigInt(2000),activeDamageChargeCount:1});
    pass("resolved with loss physically complete",finalSettlement.physicalComplete);
    pass("resolved loss remains distinct",(await tx.capacityAllocation.findUniqueOrThrow({where:{id:allocation.id}})).returnedQuantity===3&&(await tx.bulkPhysicalResolution.aggregate({where:{capacityAllocationId:allocation.id,kind:"LOSS_RESOLUTION"},_sum:{totalQuantity:true}}))._sum.totalQuantity===3);
    pass("finance remains separate",finalSettlement.state==="DEBT_OUTSTANDING");
    await tx.$executeRawUnsafe(`DO $do$ BEGIN BEGIN UPDATE bulk_physical_resolutions SET note='changed' WHERE id='${loss.resolutionId}'; RAISE EXCEPTION 'missing rejection'; EXCEPTION WHEN OTHERS THEN IF SQLERRM='missing rejection' THEN RAISE; END IF; END; END $do$`);
    pass("loss history immutable",true);
    await tx.$executeRawUnsafe(`DO $do$ BEGIN BEGIN UPDATE bulk_maintenance_events SET note='changed' WHERE id='${writeoff.eventId}'; RAISE EXCEPTION 'missing rejection'; EXCEPTION WHEN OTHERS THEN IF SQLERRM='missing rejection' THEN RAISE; END IF; END; END $do$`);
    pass("maintenance history immutable",true);
    await tx.$executeRawUnsafe(`DO $do$ BEGIN BEGIN INSERT INTO bulk_physical_resolutions(organization_id,branch_id,order_id,order_item_id,capacity_allocation_id,product_variant_id,kind,provenance,total_quantity,idempotency_key,occurred_at) VALUES ('${org.id}','${branch.id}','${order.id}','${item.id}','${allocation.id}','${variant.id}','LOSS_RESOLUTION','RECORDED',1,'sql-over-${suffix}',CURRENT_TIMESTAMP); RAISE EXCEPTION 'missing rejection'; EXCEPTION WHEN OTHERS THEN IF SQLERRM='missing rejection' THEN RAISE; END IF; END; END $do$`);
    pass("direct SQL over-loss rejected",true);
    await tx.$executeRawUnsafe(`DO $do$ DECLARE event_id uuid:='${randomUUID()}'; BEGIN BEGIN INSERT INTO bulk_maintenance_events(id,organization_id,branch_id,capacity_allocation_id,product_variant_id,type,quantity,idempotency_key,occurred_at) VALUES (event_id,'${org.id}','${branch.id}','${waivedRepair}','${variant.id}','WRITTEN_OFF',1,'sql-writeoff-${suffix}',CURRENT_TIMESTAMP); SET CONSTRAINTS bulk_writeoff_events_movement_integrity IMMEDIATE; RAISE EXCEPTION 'missing rejection'; EXCEPTION WHEN OTHERS THEN IF SQLERRM='missing rejection' THEN RAISE; END IF; END; END $do$`);
    pass("direct SQL invalid writeoff rejected",true);
    pass("loss movement exact",await tx.inventoryMovement.count({where:{organizationId:org.id,type:"LOSS"}})===2);
    pass("return and loss never overlap",(await tx.bulkPhysicalResolution.aggregate({where:{capacityAllocationId:allocation.id},_sum:{totalQuantity:true}}))._sum.totalQuantity===6);
    pass("serialized model untouched",await tx.productInstance.count({where:{organizationId:org.id}})===0);
    pass("transfer protection remains",await tx.capacityAllocation.count({where:{organizationId:org.id,sourceType:"MAINTENANCE",status:"ACTIVE"}})===0);
    pass("audit loss",await tx.auditLog.count({where:{organizationId:org.id,action:"BULK_LOSS_RESOLVED"}})===2);
    pass("audit writeoff",await tx.auditLog.count({where:{organizationId:org.id,action:"BULK_MAINTENANCE_WRITTEN_OFF"}})===1);
    const [locking]=await tx.$queryRaw<Array<{resolutionLock:boolean;maintenanceLock:boolean}>>`SELECT position('FOR UPDATE' in pg_get_functiondef('public.enforce_bulk_resolution_context()'::regprocedure))>0 AS "resolutionLock",position('FOR UPDATE' in pg_get_functiondef('public.enforce_bulk_maintenance_event()'::regprocedure))>0 AS "maintenanceLock"`;
    pass("concurrent return and loss DB serialization",locking?.resolutionLock);
    pass("concurrent completion and writeoff DB serialization",locking?.maintenanceLock);
    await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE");
    pass("all deferred invariants satisfied",true);
    throw rollback;
  },{maxWait:30_000,timeout:180_000}).catch(error=>{if(error!==rollback)throw error});
  pass("transactional fixture cleanup",await db.organization.count({where:{slug:{startsWith:"bulk-3-"}}})===0);
  if(passed.length<49)throw new Error(`Expected at least 49 assertions, got ${passed.length}`);
  console.log(`BULK-3 targeted: ${passed.length}/${passed.length} passed`);
}
main().finally(()=>db.$disconnect()).catch(error=>{console.error(error);process.exitCode=1});






