import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { addVariant, adjustBulkStock, archiveProduct, createCategory, createProduct, createSerializedInstances, createSize, replaceCurrentPrice, updateProduct } from "../lib/catalog/management";

const organizationId=randomUUID(), otherOrganizationId=randomUUID();
const tenant=createTenantContext(organizationId), otherTenant=createTenantContext(otherOrganizationId);
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
async function rejects(fn:()=>Promise<unknown>,message:string){let rejected=false;try{await fn();}catch{rejected=true;}assert(rejected,message);}
async function cleanup(id:string){await db.inventoryMovement.deleteMany({where:{organizationId:id}});await db.stockAdjustment.deleteMany({where:{organizationId:id}});await db.capacityAllocation.deleteMany({where:{organizationId:id}});await db.productImage.deleteMany({where:{organizationId:id}});await db.productPrice.deleteMany({where:{organizationId:id}});await db.stockLevel.deleteMany({where:{organizationId:id}});await db.productInstance.deleteMany({where:{organizationId:id}});await db.productVariant.deleteMany({where:{organizationId:id}});await db.product.deleteMany({where:{organizationId:id}});await db.category.deleteMany({where:{organizationId:id}});await db.size.deleteMany({where:{organizationId:id}});await db.location.deleteMany({where:{organizationId:id}});await db.branch.deleteMany({where:{organizationId:id}});await db.inventoryCounter.deleteMany({where:{organizationId:id}});await db.organization.deleteMany({where:{id}});}
const productData=(code:string,trackingMode:"SERIALIZED"|"BULK"="SERIALIZED")=>({name:"Stage 4 test",internalCode:code,supplierModel:null,description:null,brand:null,categoryId:null,color:null,isRentable:true,isSellable:true,trackingMode,publicationStatus:"ACTIVE" as const,turnaroundBufferMinutes:null});
async function main(){
 const suffix=organizationId.slice(0,8); await db.organization.createMany({data:[{id:organizationId,name:"Catalog integration",slug:`catalog-${suffix}`},{id:otherOrganizationId,name:"Other tenant",slug:`other-${suffix}`}]});
 const branch=await db.branch.create({data:{organizationId,name:"Test branch",code:"T",city:"Test",timezone:"UTC"}}), location=await db.location.create({data:{organizationId,branchId:branch.id,name:"Stock",code:"S",type:"WAREHOUSE"}});
 const category=await createCategory(tenant,{name:"Test category",parentId:null,sortOrder:1,status:"ACTIVE"}); assert(category.organizationId===organizationId,"E category tenant");
 const size=await createSize(tenant,{code:"M",name:"Medium",sizeSystem:"INT",sortOrder:1,isActive:true}); assert(size.code==="M","F size");
 const product=await createProduct(tenant,{...productData(`SER-${suffix}`),categoryId:category.id}); assert(product.name,"A product");
 await rejects(()=>createProduct(tenant,{...productData(`SER-${suffix}`),categoryId:category.id}),"B duplicate code");
 await updateProduct(tenant,product.id,{...productData(`SER-${suffix}`),categoryId:category.id,name:"Edited"}); assert((await db.product.findUnique({where:{id:product.id}}))?.name==="Edited","C edit");
 const variant=await addVariant(tenant,{productId:product.id,sizeId:size.id,sku:`SKU-${suffix}`}); assert(variant.id,"G variant"); await rejects(()=>addVariant(tenant,{productId:product.id,sizeId:size.id,sku:`OTHER-${suffix}`}),"H duplicate size");
 await replaceCurrentPrice(tenant,{variantId:variant.id,branchId:null,type:"RENTAL",amountMinor:BigInt(1000),currency:"KZT"}); await replaceCurrentPrice(tenant,{variantId:variant.id,branchId:null,type:"RENTAL",amountMinor:BigInt(1200),currency:"KZT"}); const prices=await db.productPrice.findMany({where:{organizationId,productVariantId:variant.id,type:"RENTAL"}}); assert(prices.length===2&&prices.filter(p=>!p.validUntil).length===1,"I price history");
 const batches=await Promise.all([createSerializedInstances(tenant,{variantId:variant.id,branchId:branch.id,locationId:location.id,quantity:3}),createSerializedInstances(tenant,{variantId:variant.id,branchId:branch.id,locationId:location.id,quantity:3})]); assert(batches.flat().length===6,"J/M concurrent instances"); const instances=await db.productInstance.findMany({where:{organizationId}}); assert(new Set(instances.map(x=>x.inventoryNumber)).size===6,"K inventory unique");assert(new Set(instances.map(x=>x.barcode)).size===6,"L barcode unique");
 await rejects(()=>updateProduct(tenant,product.id,{...productData(`SER-${suffix}`,"BULK"),categoryId:category.id}),"N serialized guard");
 const bulk=await createProduct(tenant,productData(`BULK-${suffix}`,"BULK")), bulkSize=await createSize(tenant,{code:"ONE",name:"One",sizeSystem:null,sortOrder:2,isActive:true}), bulkVariant=await addVariant(tenant,{productId:bulk.id,sizeId:bulkSize.id,sku:`BULK-SKU-${suffix}`}); await adjustBulkStock(tenant,{variantId:bulkVariant.id,branchId:branch.id,locationId:location.id,delta:10,reason:"Initial"}); assert((await db.stockLevel.findFirst({where:{organizationId,productVariantId:bulkVariant.id}}))?.quantity===10,"P bulk adjustment"); await rejects(()=>adjustBulkStock(tenant,{variantId:bulkVariant.id,branchId:branch.id,locationId:location.id,delta:-11,reason:"Bad"}),"Q negative stock"); await rejects(()=>updateProduct(tenant,bulk.id,productData(`BULK-${suffix}`,"SERIALIZED")),"O bulk guard");
 await rejects(()=>addVariant(otherTenant,{productId:product.id,sizeId:size.id,sku:"CROSS"}),"R tenant isolation");
 const image1=await db.productImage.create({data:{organizationId,productId:product.id,storageKey:`test/${suffix}/1.webp`,mimeType:"image/webp",width:10,height:10,sortOrder:0,isPrimary:true}}); assert(image1.width===10,"S image metadata"); await rejects(()=>db.productImage.create({data:{organizationId,productId:product.id,storageKey:`test/${suffix}/2.webp`,mimeType:"image/webp",sortOrder:1,isPrimary:true}}),"T primary uniqueness");
 await archiveProduct(tenant,product.id); assert((await db.product.findUnique({where:{id:product.id}}))?.publicationStatus==="ARCHIVED","D archive");
 console.log("PASS A-T (U requires configured Storage; V runs in availability integration). Temporary records will be removed.");
}
main().finally(async()=>{await cleanup(organizationId);await cleanup(otherOrganizationId);await db.$disconnect();}).catch(error=>{console.error(error);process.exitCode=1;});
