import "dotenv/config";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { db } from "../lib/db";
import { APPROVED_WORKBOOK, buildFullCatalogPlan } from "../lib/catalog/full-import-planner";
import { readCatalogImportNamespace } from "../lib/catalog/full-import-target";
import { getCatalogImportDatabaseFingerprint } from "../lib/catalog/full-import-fingerprint";
import { applyFullCatalogPlan, PRODUCTION_CONFIRMATION_PHRASE, verifyAppliedCatalog } from "../lib/catalog/full-import-apply";

const ROLLBACK=new Error("CATALOG_FINAL_3A_REHEARSAL_ROLLBACK");const passed:string[]=[];const pass=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);passed.push(name)};const rejects=async(fn:()=>Promise<unknown>,part:string)=>{try{await fn();return false}catch(e){if(!(e instanceof Error&&e.message.includes(part)))console.error("Unexpected rejection",{expected:part,actual:e instanceof Error?e.message:String(e)});return e instanceof Error&&e.message.includes(part)}};
const stableJson=(value:unknown)=>JSON.stringify(value,(_key,item)=>typeof item==="bigint"?item.toString():item);
async function productionSnapshot(){const org=await db.organization.findFirstOrThrow({where:{name:"MARIPOSA",status:"ACTIVE"},select:{id:true}});return {organizationId:org.id,products:await db.product.count({where:{organizationId:org.id}}),variants:await db.productVariant.count({where:{organizationId:org.id}}),stock:await db.stockLevel.aggregate({where:{organizationId:org.id},_sum:{quantity:true}}),movements:await db.inventoryMovement.count({where:{organizationId:org.id}}),batches:await db.catalogImportBatch.count({where:{organizationId:org.id}}),references:await db.catalogSourceReference.count({where:{organizationId:org.id}}),instances:await db.productInstance.count({where:{organizationId:org.id}})};}

async function main(){const before=await productionSnapshot();let report:Record<string,unknown>={},rehearsalSlug="";try{await db.$transaction(async tx=>{
 const suffix=randomUUID().slice(0,8);rehearsalSlug=`catalog-final-3a-${suffix}`;const organization=await tx.organization.create({data:{name:"CATALOG FINAL-3A REHEARSAL",slug:rehearsalSlug,status:"ACTIVE"}}),branch=await tx.branch.create({data:{organizationId:organization.id,name:"Astana rehearsal",code:`R${suffix.slice(0,5)}`,city:"Astana",timezone:"Asia/Almaty",status:"ACTIVE"}}),location=await tx.location.create({data:{organizationId:organization.id,branchId:branch.id,name:"Rehearsal warehouse",code:"AST-MAIN",type:"WAREHOUSE",isActive:true}});
 const legacySizes=[];for(const code of ["110","120","130","140","150"])legacySizes.push(await tx.size.create({data:{organizationId:organization.id,code,name:code,sizeSystem:"HEIGHT_CM",sortOrder:Number(code)}}));const historicalSizeIds=legacySizes.map(size=>size.id);const snow=await tx.product.create({data:{organizationId:organization.id,name:"Белоснежка",internalCode:"0060",trackingMode:"SERIALIZED",publicationStatus:"ACTIVE"}}),aurora=await tx.product.create({data:{organizationId:organization.id,name:"Аврора",internalCode:"0142",trackingMode:"SERIALIZED",publicationStatus:"ACTIVE"}});
 const snowVariants=[];for(const [i,code] of ["110","120","130","140","150"].entries())snowVariants.push(await tx.productVariant.create({data:{organizationId:organization.id,productId:snow.id,sizeId:legacySizes[i].id,sku:`0060.${code}`}}));const auroraVariants=[];for(const [i,code] of ["110","120","130"].entries())auroraVariants.push(await tx.productVariant.create({data:{organizationId:organization.id,productId:aurora.id,sizeId:legacySizes[i].id,sku:`0142.${code}`}}));
 const instanceRows=[];for(let i=0;i<51;i++)instanceRows.push({organizationId:organization.id,productVariantId:snowVariants[i%5].id,inventoryNumber:`SN-${suffix}-${i}`,barcode:`SN-${suffix}-${i}`,homeBranchId:branch.id,currentBranchId:branch.id,currentLocationId:location.id});for(let i=0;i<17;i++)instanceRows.push({organizationId:organization.id,productVariantId:auroraVariants[i%3].id,inventoryNumber:`AU-${suffix}-${i}`,barcode:`AU-${suffix}-${i}`,homeBranchId:branch.id,currentBranchId:branch.id,currentLocationId:location.id});await tx.productInstance.createMany({data:instanceRows});const historicalInstanceIds=(await tx.productInstance.findMany({where:{organizationId:organization.id},select:{id:true},orderBy:{id:"asc"}})).map(row=>row.id);
 const customer=await tx.customer.create({data:{organizationId:organization.id,customerNumber:`C-${suffix}`,firstName:"Existing"}});await tx.order.createMany({data:[1,2].map(number=>({organizationId:organization.id,orderNumber:`EXISTING-${number}-${suffix}`,branchId:branch.id,customerId:customer.id,type:"RENTAL" as const,channel:"CRM" as const,status:"DRAFT" as const,currency:"KZT"}))});const businessRowsBefore=await tx.order.findMany({where:{organizationId:organization.id},orderBy:{id:"asc"}});
 const namespace=await readCatalogImportNamespace(tx,{organizationId:organization.id,branchId:branch.id,locationId:location.id}),plan=await buildFullCatalogPlan(path.resolve("import",APPROVED_WORKBOOK),namespace),fingerprint=(await getCatalogImportDatabaseFingerprint(tx,organization.id,branch.id,location.id)).sha256;const base={organizationId:organization.id,branchId:branch.id,locationId:location.id,workbookSha256:plan.workbook.sha256,planSha256:plan.planSha256,databaseFingerprint:fingerprint,confirmationPhrase:PRODUCTION_CONFIRMATION_PHRASE,rehearsal:true};
 pass("confirmation guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,confirmationPhrase:"wrong"}),"confirmation phrase"));pass("plan hash guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,planSha256:"0".repeat(64)}),"Plan hash"));pass("workbook hash guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,workbookSha256:"0".repeat(64)}),"Workbook hash"));pass("wrong organization guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,organizationId:randomUUID()}),"target identity"));pass("wrong branch guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,branchId:randomUUID()}),"target identity"));pass("wrong location guard",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,locationId:randomUUID()}),"target identity"));
 const pilotPlan={...plan,target:{...plan.target,organization:{...plan.target.organization,name:"MARIPOSA — PILOT",slug:"mariposa-pilot"}}};pass("PILOT rejected",await rejects(()=>applyFullCatalogPlan(tx,pilotPlan,base),"PILOT"));
 const driftProduct=await tx.product.create({data:{organizationId:organization.id,name:"Drift",internalCode:`DRIFT-${suffix}`,trackingMode:"BULK"}}),driftVariant=await tx.productVariant.create({data:{organizationId:organization.id,productId:driftProduct.id,sizeId:legacySizes[0].id,sku:String(plan.variants[0].sku)}});pass("identifier drift rejected",await rejects(()=>applyFullCatalogPlan(tx,plan,base),"fingerprint drift"));await tx.productVariant.delete({where:{id:driftVariant.id}});await tx.product.delete({where:{id:driftProduct.id}});
 pass("interruption after sizes",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,interruptAfterStage:"SIZES"}),"REHEARSAL_INTERRUPT:SIZES"));const batch=await tx.catalogImportBatch.findFirstOrThrow({where:{organizationId:organization.id}});pass("batch remains resumable",batch.status==="APPLYING");
 const firstProduct=plan.products[0];await tx.product.create({data:{id:firstProduct.id,organizationId:organization.id,name:"CONFLICT",internalCode:firstProduct.internalCode,trackingMode:"BULK",publicationStatus:"DRAFT"}});pass("conflicting deterministic record stops",await rejects(()=>applyFullCatalogPlan(tx,plan,base),"Product deterministic payload conflict"));await tx.product.delete({where:{id:firstProduct.id}});
 pass("second interruption and resume",await rejects(()=>applyFullCatalogPlan(tx,plan,{...base,interruptAfterStage:"EXECUTIONS"}),"REHEARSAL_INTERRUPT:EXECUTIONS"));const applied=await applyFullCatalogPlan(tx,plan,base),verified=await verifyAppliedCatalog(tx,plan,applied.batchId,base),resolvedVariantSizeIds=new Set((await tx.productVariant.findMany({where:{id:{in:plan.variants.map(variant=>String(variant.id))}},select:{sizeId:true}})).map(row=>row.sizeId));pass("interrupted batch reused",applied.batchId===batch.id);pass("full apply verifier",verified.ok);pass("exact rehearsal totals",verified.counts.products===330&&verified.counts.executions===206&&verified.counts.variants===1052&&verified.counts.refs===1063&&verified.counts.stockLevels===1052&&verified.counts.stockQuantity===4915&&verified.counts.movements===1052&&verified.counts.movementQuantity===4915);pass("historical instances preserved",verified.counts.historicalInstances===68);pass("existing natural-key Sizes reused",historicalSizeIds.every(id=>resolvedVariantSizeIds.has(id))&&historicalSizeIds.every(id=>!plan.sizes.some(size=>size.id===id)));pass("pre-existing business baseline preserved",verified.counts.purchases===0&&verified.counts.orders===2&&verified.counts.finance===0&&stableJson(await tx.order.findMany({where:{organizationId:organization.id},orderBy:{id:"asc"}}))===stableJson(businessRowsBefore));
 await tx.$executeRawUnsafe("SAVEPOINT verifier_added_order");await tx.order.create({data:{organizationId:organization.id,orderNumber:`UNEXPECTED-${suffix}`,branchId:branch.id,customerId:customer.id,type:"RENTAL",channel:"CRM",status:"DRAFT",currency:"KZT"}});const addedOrderVerification=await verifyAppliedCatalog(tx,plan,applied.batchId,base);pass("independent verifier rejects added Order",!addedOrderVerification.ok&&addedOrderVerification.errors.includes("business baseline changed"));await tx.$executeRawUnsafe("ROLLBACK TO SAVEPOINT verifier_added_order");
 await tx.$executeRawUnsafe("SAVEPOINT verifier_mutated_order");await tx.order.update({where:{id:businessRowsBefore[0].id},data:{internalComment:"unexpected"}});const mutatedOrderVerification=await verifyAppliedCatalog(tx,plan,applied.batchId,base);pass("independent verifier rejects same-count Order mutation",!mutatedOrderVerification.ok&&mutatedOrderVerification.errors.includes("business baseline changed"));await tx.$executeRawUnsafe("ROLLBACK TO SAVEPOINT verifier_mutated_order");
 const historical=await tx.product.findMany({where:{id:{in:[snow.id,aurora.id]}},select:{publicationStatus:true,trackingMode:true,archivedAt:true}});pass("historical archival rehearsed",historical.length===2&&historical.every(p=>p.publicationStatus==="ARCHIVED"&&p.trackingMode==="SERIALIZED"&&p.archivedAt));const finalInstanceIds=(await tx.productInstance.findMany({where:{organizationId:organization.id},select:{id:true},orderBy:{id:"asc"}})).map(row=>row.id);pass("historical instance identities preserved",JSON.stringify(finalInstanceIds)===JSON.stringify(historicalInstanceIds));const replay=await applyFullCatalogPlan(tx,plan,base),verifiedReplay=await verifyAppliedCatalog(tx,plan,replay.batchId,base);pass("idempotent replay",replay.replayed&&replay.batchId===batch.id&&verifiedReplay.ok&&verifiedReplay.counts.stockQuantity===4915&&verifiedReplay.counts.movements===1052&&await tx.size.count({where:{organizationId:organization.id}})===plan.sizes.length);pass("source provenance unique",await tx.catalogSourceReference.count({where:{importBatchId:applied.batchId}})===1063);
 report={planHash:plan.planSha256,databaseFingerprint:fingerprint,batchId:applied.batchId,counts:verified.counts,passed:[...passed]};throw ROLLBACK;
 },{timeout:900000,maxWait:30000});}catch(e){if(e!==ROLLBACK)throw e}const after=await productionSnapshot();pass("production unchanged",JSON.stringify(before)===JSON.stringify(after));pass("rehearsal fixture rolled back",await db.organization.count({where:{slug:rehearsalSlug}})===0);report={...report,productionBefore:before,productionAfter:after,productionUnchanged:true,assertions:passed.length};await mkdir(path.resolve("import/generated"),{recursive:true});await writeFile(path.resolve("import/generated/mariposa-final-3a-rehearsal.json"),`${JSON.stringify(report,(_k,v)=>typeof v==="bigint"?v.toString():v,2)}\n`);console.log(`CATALOG FINAL-3A rehearsal: ${passed.length}/${passed.length} passed`);console.log(JSON.stringify(report,(_k,v)=>typeof v==="bigint"?v.toString():v,2));}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
