import { readFileSync } from "node:fs";
import { validateRentalHandoverSelections } from "../lib/fulfillment/rental-handover-contract";
import { assertRentalIssuePaid } from "../lib/fulfillment/rental-payment";
import { deriveRentalNextAction } from "../lib/orders/rental-next-action";

let passed=0;const ok=(value:unknown,name:string)=>{if(!value)throw new Error(`FAIL ${name}`);passed++};const rejects=(run:()=>unknown)=>{try{run();return false}catch{return true}};
ok(deriveRentalNextAction({status:"DRAFT",ready:false,issuedQuantity:0,returnedQuantity:0,outstandingMinor:null,fullyAssigned:false})==="RESERVE","DRAFT next action");
ok(deriveRentalNextAction({status:"RESERVED",ready:false,issuedQuantity:0,returnedQuantity:0,outstandingMinor:null,fullyAssigned:false})==="CONFIRM","RESERVED next action");
ok(deriveRentalNextAction({status:"CONFIRMED",ready:false,issuedQuantity:0,returnedQuantity:0,outstandingMinor:BigInt(30000),fullyAssigned:true})==="PAY","CONFIRMED unpaid next action");
ok(deriveRentalNextAction({status:"CONFIRMED",ready:false,issuedQuantity:0,returnedQuantity:0,outstandingMinor:BigInt(0),fullyAssigned:false})==="ASSIGN","serialized assignment next action");
ok(deriveRentalNextAction({status:"CONFIRMED",ready:false,issuedQuantity:0,returnedQuantity:0,outstandingMinor:BigInt(0),fullyAssigned:true})==="PREPARE","ready preparation next action");
ok(deriveRentalNextAction({status:"CONFIRMED",ready:true,issuedQuantity:0,returnedQuantity:0,outstandingMinor:BigInt(0),fullyAssigned:true})==="ISSUE","paid ready issue next action");
ok(deriveRentalNextAction({status:"CONFIRMED",ready:true,issuedQuantity:1,returnedQuantity:0,outstandingMinor:BigInt(0),fullyAssigned:true})==="RETURN","issued next action");
ok(rejects(()=>assertRentalIssuePaid(BigInt(30000),"KZT")),"unpaid issue rejected");
ok(rejects(()=>assertRentalIssuePaid(BigInt(20000),"KZT")),"partial payment issue rejected");
assertRentalIssuePaid(BigInt(0),"KZT");passed++;
ok(rejects(()=>assertRentalIssuePaid(BigInt(-1),"KZT")),"refund overpayment state fails closed");
const bulk=[{productVariantId:"white-120",productInstanceId:null,quantity:3,issuedQuantity:0}];
ok(validateRentalHandoverSelections(bulk,[{kind:"BULK",productVariantId:"white-120",quantity:3}]),"one BULK scan plus explicit quantity");
ok(rejects(()=>validateRentalHandoverSelections(bulk,[{kind:"BULK",productVariantId:"white-120",quantity:4}])),"quantity above outstanding rejected");
ok(rejects(()=>validateRentalHandoverSelections(bulk,[{kind:"BULK",productVariantId:"pink-120",quantity:3}])),"wrong BULK variant rejected");
const serialized=[{productVariantId:"dress-120",productInstanceId:"instance-a",quantity:1,issuedQuantity:0}];
ok(validateRentalHandoverSelections(serialized,[{kind:"SERIALIZED",productInstanceId:"instance-a"}]),"assigned instance accepted");
ok(rejects(()=>validateRentalHandoverSelections(serialized,[{kind:"SERIALIZED",productInstanceId:"instance-b"}])),"wrong instance rejected");
ok(rejects(()=>validateRentalHandoverSelections(serialized,[{kind:"SERIALIZED",productInstanceId:"instance-a"},{kind:"SERIALIZED",productInstanceId:"instance-a"}])),"duplicate instance rejected");
const management=readFileSync("lib/fulfillment/management.ts","utf8"),orders=readFileSync("lib/orders/management.ts","utf8"),actions=readFileSync("app/scan-actions.ts","utf8"),orderActions=readFileSync("app/orders/actions.ts","utf8"),page=readFileSync("app/orders/[id]/page.tsx","utf8"),panel=readFileSync("components/RentalOperationalPanel.tsx","utf8");
const issue=management.slice(management.indexOf("export async function issueOrder"));
ok(issue.indexOf("lockOrderFinance")<issue.indexOf("lockOrderLifecycle")&&issue.indexOf("lockOrderLifecycle")<issue.indexOf("issueInventory"),"issue lock order finance lifecycle capacity");
ok(issue.includes("obligationEffectMinor")&&issue.includes("assertRentalIssuePaid")&&issue.indexOf("assertRentalIssuePaid")<issue.indexOf("issueInventory"),"authoritative ledger guard precedes inventory");
ok(issue.includes("validateRentalHandoverSelections")&&panel.includes("selectionsJson"),"scanner payload revalidated server side");
ok(orderActions.includes('issueOrderAction')&&orderActions.includes('issueVerifiedRental(t,id,JSON.parse(text(f,"selectionsJson"))'),"legacy server action cannot bypass scanner payload");
ok(orders.includes("lockOrderFinance(tx, tenant.organizationId, id)")&&orders.includes("Активное бронирование больше не соответствует"),"confirm lifecycle and allocation topology guarded");
ok(actions.includes('hasPermission(session, "SALE_FULFILL")')&&actions.includes('hasPermission(session, "RENTAL_ISSUE")')&&actions.includes('hasPermission(session, "RENTAL_PREPARE")'),"shared resolver honors effective preparation or issue permission");
ok(page.includes("getEffectivePermissions(session)")&&page.includes('"RENTAL_CONFIRM"')&&page.includes('"RENTAL_PREPARE"')&&page.includes('"RENTAL_ISSUE"'),"rental UI uses one effective-permission snapshot");
ok(!page.includes("await Promise.all([hasPermission"),"rental detail avoids permission-query connection fan-out");
ok(panel.includes("Этот товар не входит в заказ")&&panel.includes("Исполнение не совпадает")&&panel.includes("Размер не совпадает")&&panel.includes("Этот экземпляр не назначен этому заказу"),"wrong item messages are explicit");
ok(panel.includes("Выдача недоступна — осталось оплатить")&&panel.includes('disabled={!allMatched || !paid}'),"mobile issue blocked by payment and match");
ok(panel.includes("assignBarcodeAction")&&panel.includes("markReadyAction")&&panel.includes("issueVerifiedRentalAction"),"canonical preparation and issue actions reused");
ok(page.includes("depositShortageMinor")&&page.includes("Не хватает")&&page.includes("Залог не является оплатой аренды"),"deposit remains separate and advisory");
console.log(`FOUNDATION-1F targeted: ${passed}/${passed} passed`);
