import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const browser=[process.env.CHROME_PATH,"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe","C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"].filter((value):value is string=>Boolean(value)).find(existsSync);if(!browser)throw new Error("Chrome/Edge not found");
const css=["globals.css","design-system.css","scanner.css","orders.css"].map(name=>readFileSync(join("app",name),"utf8")).join("\n"),file=join(tmpdir(),`mariposa-return-intake-${process.pid}.html`);let passed=0;const ok=(value:unknown,name:string)=>{if(!value)throw new Error(`FAIL ${name}`);passed++};
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><main class="main"><h1>Приём возврата</h1><p>R-000003 · Бакытжан</p><div class="return-intake"><section class="return-intake-items" aria-label="Позиции к возврату"><button class="selected"><strong>Платье LAN 008</strong><span>Молочный · Рост 100 см</span><small>К возврату: 1</small></button><button><strong>Туфли N01</strong><span>Белый · 38</span><small>К возврату: 1</small></button></section><section class="card return-intake-card"><header><div><small>R-000003 · Бакытжан</small><h2>Платье LAN 008</h2><p>Молочный · Рост 100 см</p></div><strong>К возврату: 1 шт.</strong></header><form class="return-intake-form"><label>Количество<input type="number" min="1" max="1" value="1"></label><label>Состояние<select><option>Хорошее состояние</option><option>Требуется чистка</option><option>Повреждено</option></select></label><label>Куда принять<select><option>Склад Астана</option></select></label><label>Комментарий<textarea placeholder="При необходимости"></textarea></label><button class="primary">Принять возврат</button></form></section></div></main><pre id="r"></pre><script>const shown=e=>e.getClientRects().length>0&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden',box=e=>{const x=e.getBoundingClientRect();return{left:x.left,right:x.right,top:x.top,bottom:x.bottom,width:x.width,height:x.height}},v=document.documentElement.clientWidth,sw=document.documentElement.scrollWidth,root=box(document.querySelector('.return-intake')),card=box(document.querySelector('.return-intake-card')),controls=[...document.querySelectorAll('input,select,textarea,button')].filter(shown).map(e=>({...box(e),font:parseFloat(getComputedStyle(e).fontSize)})),text=document.body.textContent;document.querySelector('#r').textContent=JSON.stringify({v,sw,root,card,controls,text})</script></body></html>`;
try{writeFileSync(file,html,"utf8");for(const width of [390,430,760,768,1024,1200]){const scale=width<485?500/width:1,outer=width<485?500:width+15,height=width===390?844:1000,out=execFileSync(browser,["--headless=new","--disable-gpu","--no-sandbox",`--force-device-scale-factor=${scale}`,`--window-size=${outer},${height}`,"--dump-dom",`file:///${file.replaceAll("\\","/")}`],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}),encoded=out.match(/<pre id="r">([^<]+)<\/pre>/)?.[1]?.replaceAll("&quot;",'"');if(!encoded)throw new Error("missing render result");const result=JSON.parse(encoded);ok(result.sw<=result.v,`${width} no horizontal overflow`);ok(result.root.left>=0&&result.root.right<=result.v+.5&&result.card.left>=0&&result.card.right<=result.v+.5,`${width} intake stays inside viewport`);ok(result.controls.every((item:{left:number;right:number})=>item.left>=0&&item.right<=result.v+.5),`${width} controls inside viewport`);ok(result.text.includes("R-000003")&&result.text.includes("Бакытжан")&&result.text.includes("Платье LAN 008")&&result.text.includes("Количество к возврату")===false&&result.text.includes("К возврату: 1"),`${width} order customer item and outstanding visible`);ok(result.text.includes("Хорошее состояние")&&result.text.includes("Требуется чистка")&&result.text.includes("Повреждено")&&result.text.includes("Принять возврат"),`${width} canonical conditions and dominant action visible`);if(width<=760){ok(result.controls.every((item:{font:number})=>item.font>=16),`${width} form controls avoid iPhone zoom`);ok(result.controls.every((item:{height:number})=>item.height>=43.5),`${width} touch targets at least 44px`);ok(result.card.top<height&&result.card.bottom<=height*1.6,`${width} primary return workflow remains compact`)}}
}finally{rmSync(file,{force:true})}
console.log(`MOBILE RENTAL RETURN rendered targeted: ${passed}/${passed} passed`);
