import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const browser=[process.env.CHROME_PATH,"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe","C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"].filter((x):x is string=>Boolean(x)).find(existsSync);if(!browser)throw new Error("Chrome/Edge not found");
const css=["globals.css","design-system.css","scanner.css"].map(x=>readFileSync(join("app",x),"utf8")).join("\n"),file=join(tmpdir(),`mariposa-stocktake-${process.pid}.html`);let passed=0;const ok=(v:unknown,n:string)=>{if(!v)throw new Error(`FAIL ${n}`);passed++};
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div class="scanner-backdrop"><section class="scanner-sheet"><header><div><strong>Пересчитать товар</strong><small>Код, сканер или камера</small></div><button>×</button></header><div class="scanner-success stocktake-scan-result"><b class="scanner-success-title">Товар найден</b><strong>Платье 23156 Белоснежка</strong><span>Белый · 110</span><small>Основной шоурум / склад</small><div class="stocktake-figures"><span>Ожидалось <b>16</b></span><span>Фактически <b>15</b></span><span>Разница <b class="negative">-1</b></span></div><label class="stocktake-count-input">Фактически<input type="number" inputmode="numeric" value="15"></label><button class="primary">Сохранить количество</button><button class="secondary stocktake-next">Следующий товар</button></div></section></div><pre id="r"></pre><script>const box=e=>{const x=e.getBoundingClientRect();return{left:x.left,right:x.right,width:x.width,height:x.height}},v=document.documentElement.clientWidth,sw=document.documentElement.scrollWidth,s=box(document.querySelector('.scanner-sheet')),result=box(document.querySelector('.stocktake-scan-result')),input=document.querySelector('input'),ib=box(input),buttons=[...document.querySelectorAll('button')].map(box);document.querySelector('#r').textContent=JSON.stringify({v,sw,s,result,ib,inputFont:parseFloat(getComputedStyle(input).fontSize),buttons})</script></body></html>`;
try{writeFileSync(file,html,"utf8");for(const width of [390,430,760,768,1024,1200]){const scale=width<485?500/width:1,outer=width<485?500:width+15,out=execFileSync(browser,["--headless=new","--disable-gpu","--no-sandbox",`--force-device-scale-factor=${scale}`,`--window-size=${outer},844`,"--dump-dom",`file:///${file.replaceAll("\\","/")}`],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}),encoded=out.match(/<pre id="r">([^<]+)<\/pre>/)?.[1]?.replaceAll("&quot;",'"');if(!encoded)throw new Error("missing render result");const r=JSON.parse(encoded);ok(r.sw<=r.v,`${width} no horizontal overflow`);ok(r.s.left>=0&&r.s.right<=r.v+.5,`${width} sheet in viewport`);ok(r.result.left>=0&&r.result.right<=r.v+.5,`${width} result in viewport`);ok(r.ib.left>=0&&r.ib.right<=r.v+.5,`${width} numeric input in viewport`);if(width<=760)ok(r.inputFont>=16,`${width} avoids iPhone auto zoom`);ok(r.buttons.every((x:{left:number;right:number;height:number})=>x.left>=0&&x.right<=r.v+.5&&x.height>=40),`${width} touch controls`)}}finally{rmSync(file,{force:true})}console.log(`MOBILE STOCKTAKE rendered targeted: ${passed}/${passed} passed`);
