import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const browser=[process.env.CHROME_PATH,"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe","C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"].filter((x):x is string=>Boolean(x)).find(existsSync);if(!browser)throw new Error("Chrome/Edge not found");
const css=["globals.css","design-system.css","scanner.css"].map(x=>readFileSync(join("app",x),"utf8")).join("\n");const file=join(tmpdir(),`mariposa-selector-${process.pid}.html`);let passed=0;const ok=(v:unknown,n:string)=>{if(!v)throw new Error(`FAIL ${n}`);passed++};
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div class="scanner-backdrop"><section class="scanner-sheet"><header><div><strong>Найти товар</strong><small>Код, сканер или камера</small></div><button>×</button></header><div class="scanner-success"><b class="scanner-success-title">✓ Товар найден</b><strong>Платье 23156 Белоснежка</strong><span>Белый · 110</span><small>SKU MP-R0516.BELYY.H-110</small><div class="scanner-success-actions"><a>Открыть товар</a><button>Сканировать ещё</button></div></div><form class="scanner-input"><label>Код / SKU / штрихкод<input placeholder="Введите или отсканируйте код"></label><button class="secondary">Найти код</button></form><button class="scanner-name-search">Искать по названию</button></section></div><pre id="r"></pre><script>const box=e=>{const x=e.getBoundingClientRect();return{left:x.left,right:x.right,top:x.top,bottom:x.bottom,width:x.width,height:x.height}},v=document.documentElement.clientWidth,sw=document.documentElement.scrollWidth,s=box(document.querySelector('.scanner-sheet')),success=box(document.querySelector('.scanner-success')),input=box(document.querySelector('input')),buttons=[...document.querySelectorAll('button')].map(box);document.querySelector('#r').textContent=JSON.stringify({v,sw,s,success,input,inputFont:parseFloat(getComputedStyle(document.querySelector('input')).fontSize),buttons})</script></body></html>`;
try{writeFileSync(file,html,"utf8");for(const width of [390,430,760,768,1024,1200]){const scale=width<485?500/width:1,outer=width<485?500:width+15;const out=execFileSync(browser,["--headless=new","--disable-gpu","--no-sandbox",`--force-device-scale-factor=${scale}`,`--window-size=${outer},844`,"--dump-dom",`file:///${file.replaceAll("\\","/")}`],{encoding:"utf8",stdio:["ignore","pipe","ignore"]});const encoded=out.match(/<pre id="r">([^<]+)<\/pre>/)?.[1]?.replaceAll("&quot;",'"');if(!encoded)throw new Error("missing render result");const r=JSON.parse(encoded);ok(r.sw<=r.v,`${width} no horizontal overflow`);ok(r.s.left>=0&&r.s.right<=r.v+.5,`${width} sheet inside viewport`);ok(r.success.left>=0&&r.success.right<=r.v+.5&&r.success.top<844&&r.success.bottom<844,`${width} success visible without scroll`);ok(r.input.left>=0&&r.input.right<=r.v+.5&&r.input.width>100,`${width} input visible`);if(width<=760)ok(r.inputFont>=16,`${width} input avoids iOS auto zoom`);ok(r.buttons.every((x:{left:number;right:number;height:number})=>x.left>=0&&x.right<=r.v+.5&&x.height>=34),`${width} controls visible`)}}finally{rmSync(file,{force:true})}console.log(`OPERATIONAL SELECTOR rendered targeted: ${passed}/${passed} passed`);
