import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { ensureDefaultPaymentMethods } from "../lib/finance/payment-methods";
import { acceptOrderPayment, refundOrderPayment, synchronizeOrderChargeWithClient } from "../lib/finance/order-payments";
import { deriveOrderPaymentStatus, getOrderFinancialSummary, getOrderPaymentDetails } from "../lib/finance/queries";
import { postPayment, reverseFinancialTransaction } from "../lib/finance/transactions";
import { cancelOrder, confirmOrder, updateOrder } from "../lib/orders/management";

const organizations:string[]=[],users:string[]=[];let passed=0;
const ok=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);passed++};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
const rejectedMessage=async(fn:()=>Promise<unknown>)=>{try{await fn();return ""}catch(error){return error instanceof Error?error.message:String(error)}};

async function cleanup(){if(!organizations.length)return;await db.$transaction(async tx=>{
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');
  await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');
  await tx.financialTransaction.deleteMany({where:{organizationId:{in:organizations}}});await tx.auditLog.deleteMany({where:{organizationId:{in:organizations}}});
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');
  await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');
  await tx.orderEvent.deleteMany({where:{organizationId:{in:organizations}}});await tx.order.deleteMany({where:{organizationId:{in:organizations}}});await tx.customer.deleteMany({where:{organizationId:{in:organizations}}});
  await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:organizations}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:organizations}}});
  await tx.paymentMethod.deleteMany({where:{organizationId:{in:organizations}}});await tx.branch.deleteMany({where:{organizationId:{in:organizations}}});await tx.organization.deleteMany({where:{id:{in:organizations}}});await tx.user.deleteMany({where:{id:{in:users}}});
 },{maxWait:10000,timeout:30000})}

async function main(){await cleanup();
 const orgId=randomUUID(),otherOrgId=randomUUID(),ownerId=randomUUID(),sellerId=randomUUID();organizations.push(orgId,otherOrgId);users.push(ownerId,sellerId);
 await db.organization.createMany({data:[{id:orgId,name:"Stage 9B-1",slug:`stage-9b-1-${orgId.slice(0,8)}`},{id:otherOrgId,name:"Stage 9B-1 Other",slug:`stage-9b-1-other-${orgId.slice(0,8)}`}]});
 const passwordHash=createHash("sha256").update(orgId).digest("hex");await db.user.createMany({data:[{id:ownerId,email:`stage9b1-owner-${orgId}@test.invalid`,displayName:"Owner 9B",passwordHash},{id:sellerId,email:`stage9b1-seller-${orgId}@test.invalid`,displayName:"Seller 9B",passwordHash}]});
 const a=await db.branch.create({data:{organizationId:orgId,name:"A",code:"A",city:"Test",timezone:"Asia/Qyzylorda"}}),b=await db.branch.create({data:{organizationId:orgId,name:"B",code:"B",city:"Test",timezone:"Asia/Qyzylorda"}}),otherBranch=await db.branch.create({data:{organizationId:otherOrgId,name:"Other",code:"O",city:"Test",timezone:"Asia/Qyzylorda"}});
 const owner=await db.organizationMembership.create({data:{organizationId:orgId,userId:ownerId,role:"OWNER",status:"ACTIVE",defaultBranchId:a.id}}),seller=await db.organizationMembership.create({data:{organizationId:orgId,userId:sellerId,role:"SELLER",status:"ACTIVE",defaultBranchId:a.id}});await db.membershipBranchAccess.create({data:{organizationId:orgId,membershipId:seller.id,branchId:a.id}});
 const customer=await db.customer.create({data:{organizationId:orgId,customerNumber:"C-9B",firstName:"Test"}}),secondCustomer=await db.customer.create({data:{organizationId:orgId,customerNumber:"C-9B-2",firstName:"Second"}}),otherCustomer=await db.customer.create({data:{organizationId:otherOrgId,customerNumber:"C-X",firstName:"Other"}});
 const tenant=createTenantContext(orgId),otherTenant=createTenantContext(otherOrgId),actor={userId:ownerId,membershipId:owner.id,role:"OWNER" as const},sellerActor={userId:sellerId,membershipId:seller.id,role:"SELLER" as const};
 const methods=await ensureDefaultPaymentMethods(tenant),otherMethods=await ensureDefaultPaymentMethods(otherTenant),cash=methods.find(x=>x.code==="CASH")!,kaspi=methods.find(x=>x.code==="KASPI")!;
 let seq=0;const make=async(branchId=a.id,total=10000,status:"RESERVED"|"CANCELLED"="RESERVED")=>db.order.create({data:{organizationId:orgId,orderNumber:`R-9B-${++seq}`,branchId,customerId:customer.id,type:"RENTAL",channel:"CRM",status,currency:"KZT",totalMinor:BigInt(total),balanceDueMinor:BigInt(total),cancelledAt:status==="CANCELLED"?new Date():undefined,cancellationReason:status==="CANCELLED"?"test":undefined}});
 const confirm=async(orderId:string)=>confirmOrder(tenant,orderId,actor);
 const obligation=async(orderId:string)=>(await db.financialTransaction.aggregate({where:{organizationId:orgId,orderId},_sum:{obligationEffectMinor:true}}))._sum.obligationEffectMinor??BigInt(0);
 const beforeAllocations=await db.capacityAllocation.count({where:{organizationId:orgId}}),beforeInventory=await db.inventoryMovement.count({where:{organizationId:orgId}});

 const order=await make();await confirm(order.id);ok("A charge once",await db.financialTransaction.count({where:{orderId:order.id,kind:"RENTAL_CHARGE"}})===1);await db.$transaction(tx=>synchronizeOrderChargeWithClient(tx,tenant,order.id,actor));ok("B charge retry",await db.financialTransaction.count({where:{orderId:order.id,sourceType:"ORDER_CHARGE"}})===1);
 let details=await getOrderPaymentDetails(tenant,order.id,actor);ok("F unpaid",details.status==="UNPAID"&&details.outstandingMinor===BigInt(10000));
 const p1=await acceptOrderPayment(tenant,{orderId:order.id,amountMinor:BigInt(3000),paymentMethodId:kaspi.id,idempotencyKey:"scenario-p1"},actor);details=await getOrderPaymentDetails(tenant,order.id,actor);ok("D/G partial",details.status==="PARTIAL"&&details.paidMinor===BigInt(3000)&&details.outstandingMinor===BigInt(7000));
 await acceptOrderPayment(tenant,{orderId:order.id,amountMinor:BigInt(7000),paymentMethodId:cash.id,idempotencyKey:"scenario-p2"},actor);details=await getOrderPaymentDetails(tenant,order.id,actor);ok("E/H two payments full",details.status==="PAID"&&details.paidMinor===BigInt(10000)&&details.outstandingMinor===BigInt(0));
 const fullOrder=await make();await confirm(fullOrder.id);await acceptOrderPayment(tenant,{orderId:fullOrder.id,amountMinor:BigInt(10000),paymentMethodId:kaspi.id,idempotencyKey:"full"},actor);ok("C full payment",(await getOrderFinancialSummary(tenant,fullOrder.id,actor)).outstandingMinor===BigInt(0));
 const cancelledOrder=await make();await confirm(cancelledOrder.id);await cancelOrder(tenant,cancelledOrder.id,"Клиент отказался",actor);const cancelledSummary=await getOrderFinancialSummary(tenant,cancelledOrder.id,actor);ok("B cancelled unpaid charge compensated",await obligation(cancelledOrder.id)===BigInt(0)&&cancelledSummary.outstandingMinor===BigInt(0));
 const refundThenCancelOrder=await make();await confirm(refundThenCancelOrder.id);const cancellationPayment=await acceptOrderPayment(tenant,{orderId:refundThenCancelOrder.id,amountMinor:BigInt(3000),paymentMethodId:kaspi.id,idempotencyKey:"cancel-payment"},actor);ok("A paid cancellation guarded",await rejects(()=>cancelOrder(tenant,refundThenCancelOrder.id,"Нужен возврат",actor))&&(await db.order.findUniqueOrThrow({where:{id:refundThenCancelOrder.id}})).status==="CONFIRMED");await refundOrderPayment(tenant,{orderId:refundThenCancelOrder.id,paymentId:cancellationPayment.id,amountMinor:BigInt(3000),reason:"Возврат перед отменой",idempotencyKey:"cancel-refund"},actor);await cancelOrder(tenant,refundThenCancelOrder.id,"Клиент отказался после возврата",actor);const refundedCancellationSummary=await getOrderFinancialSummary(tenant,refundThenCancelOrder.id,actor);ok("A refund then cancellation clears obligation",await obligation(refundThenCancelOrder.id)===BigInt(0)&&refundedCancellationSummary.outstandingMinor===BigInt(0)&&(await db.order.findUniqueOrThrow({where:{id:refundThenCancelOrder.id}})).status==="CANCELLED");
 const contextOrder=await make();await confirm(contextOrder.id);const editDates={source:"CRM",rentalStart:new Date("2026-10-01T09:00:00.000Z"),rentalEnd:new Date("2026-10-02T09:00:00.000Z"),discountMinor:BigInt(0),internalComment:null};ok("C charged order branch immutable",await rejects(()=>updateOrder(tenant,contextOrder.id,{...editDates,branchId:b.id,customerId:customer.id},actor)));ok("C charged order customer immutable",await rejects(()=>updateOrder(tenant,contextOrder.id,{...editDates,branchId:a.id,customerId:secondCustomer.id},actor)));const contextCharge=await db.financialTransaction.findFirstOrThrow({where:{orderId:contextOrder.id,sourceType:"ORDER_CHARGE"}}),contextOrderAfter=await db.order.findUniqueOrThrow({where:{id:contextOrder.id}});ok("C financial context preserved",contextCharge.branchId===a.id&&contextCharge.customerId===customer.id&&contextOrderAfter.branchId===a.id&&contextOrderAfter.customerId===customer.id);
 ok("I overpayment",await rejects(()=>acceptOrderPayment(tenant,{orderId:fullOrder.id,amountMinor:BigInt(1),paymentMethodId:kaspi.id,idempotencyKey:"over"},actor)));ok("J zero",await rejects(()=>acceptOrderPayment(tenant,{orderId:fullOrder.id,amountMinor:BigInt(0),paymentMethodId:kaspi.id,idempotencyKey:"zero"},actor)));ok("K negative",await rejects(()=>acceptOrderPayment(tenant,{orderId:fullOrder.id,amountMinor:BigInt(-1),paymentMethodId:kaspi.id,idempotencyKey:"negative"},actor)));
 ok("L wrong currency low-level",await rejects(()=>postPayment(tenant,{branchId:a.id,customerId:customer.id,orderId:fullOrder.id,amountMinor:BigInt(1),currency:"USD",paymentMethodId:kaspi.id,sourceType:"STAGE_9B_TEST",idempotencyKey:"currency"},actor)));
 await db.paymentMethod.update({where:{id:cash.id},data:{isActive:false}});const inactiveOrder=await make();await confirm(inactiveOrder.id);ok("M inactive method",await rejects(()=>acceptOrderPayment(tenant,{orderId:inactiveOrder.id,amountMinor:BigInt(1),paymentMethodId:cash.id,idempotencyKey:"inactive"},actor)));await db.paymentMethod.update({where:{id:cash.id},data:{isActive:true}});
 ok("N wrong organization method",await rejects(()=>acceptOrderPayment(tenant,{orderId:inactiveOrder.id,amountMinor:BigInt(1),paymentMethodId:otherMethods[0]!.id,idempotencyKey:"wrong-method"},actor)));
 await db.membershipPermissionOverride.createMany({data:["PAYMENT_CREATE","PAYMENT_REFUND"].map(permissionKey=>({organizationId:orgId,membershipId:seller.id,permissionKey,effect:"ALLOW" as const}))});const branchBOrder=await make(b.id);await confirm(branchBOrder.id);ok("O cross branch",await rejects(()=>acceptOrderPayment(tenant,{orderId:branchBOrder.id,amountMinor:BigInt(1),paymentMethodId:kaspi.id,idempotencyKey:"cross-branch"},sellerActor)));
 const foreignOrder=await db.order.create({data:{organizationId:otherOrgId,orderNumber:"R-X",branchId:otherBranch.id,customerId:otherCustomer.id,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT",totalMinor:BigInt(100)}});ok("P cross tenant",await rejects(()=>acceptOrderPayment(tenant,{orderId:foreignOrder.id,amountMinor:BigInt(1),paymentMethodId:kaspi.id,idempotencyKey:"cross-tenant"},actor)));
 await db.membershipPermissionOverride.deleteMany({where:{membershipId:seller.id,permissionKey:"PAYMENT_CREATE"}});ok("Q missing create",await rejects(()=>acceptOrderPayment(tenant,{orderId:inactiveOrder.id,amountMinor:BigInt(1),paymentMethodId:kaspi.id,idempotencyKey:"no-permission"},sellerActor)));ok("R missing view",await rejects(()=>getOrderPaymentDetails(tenant,order.id,sellerActor)));
 const retryOrder=await make();await confirm(retryOrder.id);const retry={orderId:retryOrder.id,amountMinor:BigInt(1000),paymentMethodId:kaspi.id,idempotencyKey:"retry"};const retryA=await acceptOrderPayment(tenant,retry,actor),retryB=await acceptOrderPayment(tenant,retry,actor);ok("S idempotency",retryA.id===retryB.id&&await db.financialTransaction.count({where:{organizationId:orgId,idempotencyKey:"retry"}})===1);ok("T payload conflict",await rejects(()=>acceptOrderPayment(tenant,{...retry,amountMinor:BigInt(1001)},actor)));
 const concurrentOrder=await make();await confirm(concurrentOrder.id);await acceptOrderPayment(tenant,{orderId:concurrentOrder.id,amountMinor:BigInt(3000),paymentMethodId:kaspi.id,idempotencyKey:"concurrent-first"},actor);const concurrent=await Promise.allSettled([acceptOrderPayment(tenant,{orderId:concurrentOrder.id,amountMinor:BigInt(7000),paymentMethodId:cash.id,idempotencyKey:"concurrent-a"},actor),acceptOrderPayment(tenant,{orderId:concurrentOrder.id,amountMinor:BigInt(7000),paymentMethodId:cash.id,idempotencyKey:"concurrent-b"},actor)]);const concurrentSummary=await getOrderFinancialSummary(tenant,concurrentOrder.id,actor);ok("U concurrent overpayment",concurrent.filter(x=>x.status==="fulfilled").length===1&&concurrentSummary.paidMinor===BigInt(10000)&&concurrentSummary.outstandingMinor===BigInt(0));
 const refund=await refundOrderPayment(tenant,{orderId:fullOrder.id,paymentId:(await db.financialTransaction.findFirstOrThrow({where:{orderId:fullOrder.id,kind:"PAYMENT_RECEIVED"}})).id,amountMinor:BigInt(3000),reason:"Возврат части оплаты",idempotencyKey:"refund-part"},actor);details=await getOrderPaymentDetails(tenant,fullOrder.id,actor);ok("V/Z partial refund balance",refund.kind==="CUSTOMER_REFUND"&&details.status==="PARTIAL"&&details.outstandingMinor===BigInt(3000));ok("X excess refund",await rejects(()=>refundOrderPayment(tenant,{orderId:fullOrder.id,paymentId:p1.id,amountMinor:BigInt(4000),reason:"Лишний возврат",idempotencyKey:"refund-excess"},actor)));ok("Y reason",await rejects(()=>refundOrderPayment(tenant,{orderId:order.id,paymentId:p1.id,amountMinor:BigInt(1),reason:"",idempotencyKey:"refund-reason"},actor)));
 const paymentForFullRefund=await db.financialTransaction.findFirstOrThrow({where:{orderId:retryOrder.id,kind:"PAYMENT_RECEIVED"}});await refundOrderPayment(tenant,{orderId:retryOrder.id,paymentId:paymentForFullRefund.id,amountMinor:BigInt(1000),reason:"Полный возврат",idempotencyKey:"refund-full"},actor);ok("W full refund",(await getOrderFinancialSummary(tenant,retryOrder.id,actor)).paidMinor===BigInt(0));
 await db.membershipPermissionOverride.deleteMany({where:{membershipId:seller.id,permissionKey:"PAYMENT_REFUND"}});ok("AA refund permission",await rejects(()=>refundOrderPayment(tenant,{orderId:order.id,paymentId:p1.id,amountMinor:BigInt(1),reason:"Нет права",idempotencyKey:"refund-denied"},sellerActor)));const oracleMessage=await rejectedMessage(()=>refundOrderPayment(tenant,{orderId:randomUUID(),paymentId:randomUUID(),amountMinor:BigInt(1),reason:"Проверка авторизации",idempotencyKey:"refund-oracle"},sellerActor));ok("D permission checked before payment lookup",oracleMessage.includes("Недостаточно прав")&&!oracleMessage.includes("Платёж недоступен"));
 const reversal=await reverseFinancialTransaction(tenant,refund.id,{branchId:a.id,customerId:customer.id,orderId:fullOrder.id,sourceType:"ORDER_REFUND_CORRECTION",sourceId:fullOrder.id,idempotencyKey:"refund-reversal",reason:"Ошибочный возврат"},actor);ok("AB reversal distinct",reversal.kind==="REVERSAL"&&refund.kind==="CUSTOMER_REFUND");
 ok("AC audit",await db.auditLog.count({where:{organizationId:orgId,action:{in:["ORDER_CHARGE_SYNCHRONIZED","FINANCIAL_TRANSACTION_POSTED"]}}})>=10);ok("AD attribution",(await db.financialTransaction.findUniqueOrThrow({where:{id:p1.id}})).actorMembershipId===owner.id&&(await db.financialTransaction.findUniqueOrThrow({where:{id:p1.id}})).branchId===a.id);
 ok("AE allocations unchanged",await db.capacityAllocation.count({where:{organizationId:orgId}})===beforeAllocations);ok("AF inventory unchanged",await db.inventoryMovement.count({where:{organizationId:orgId}})===beforeInventory);ok("AG deposit untouched",await db.financialTransaction.count({where:{organizationId:orgId,kind:{in:["DEPOSIT_RECEIVED","DEPOSIT_REFUNDED","DEPOSIT_WITHHELD"]}}})===0);ok("AH damage untouched",await db.financialTransaction.count({where:{organizationId:orgId,kind:"DAMAGE_CHARGE"}})===0);
 const security=await db.$queryRaw<Array<{tables:number;rls:number;anon:number;authenticated:number;policies:number}>>`SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p')) tables,(SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relrowsecurity) rls,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='anon') anon,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='authenticated') authenticated,(SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND roles && ARRAY['anon','authenticated','public']::name[]) policies`;
 ok("AI-AL RLS security",security[0]!.tables===security[0]!.rls&&security[0]!.anon===0&&security[0]!.authenticated===0&&security[0]!.policies===0);ok("derived labels",deriveOrderPaymentStatus(BigInt(0),BigInt(100))==="UNPAID"&&deriveOrderPaymentStatus(BigInt(1),BigInt(99))==="PARTIAL"&&deriveOrderPaymentStatus(BigInt(100),BigInt(0))==="PAID");
 await cleanup();ok("AM cleanup",await db.organization.count({where:{slug:{startsWith:"stage-9b-1-"}}})===0);console.log(`PASS Stage 9B-1 A-AM (${passed} checks)`);
}
main().finally(async()=>{await cleanup();await db.$disconnect()}).catch(e=>{console.error(e);process.exitCode=1});
