import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { createOrder, reserveOrder, confirmOrder, cancelOrder, removeOrderItem, updateOrder } from "../lib/orders/management";
import { assignInstanceByBarcode, issueOrder, markOrderReady } from "../lib/fulfillment/management";
import { completeMaintenanceByBarcode, completeReturnedOrder, lookupCurrentRentalByBarcode, receiveReturnByBarcode, returnBulkQuantity } from "../lib/fulfillment/returns";
import { requireFulfillmentPermission } from "../lib/fulfillment/permissions";
import { getVariantAvailability } from "../lib/availability/capacity";
import { getCalendar } from "../lib/calendar/queries";

const organizations: string[] = [], results: string[] = [];
const pass = (name: string, value: unknown) => { if (!value) throw Error(`FAIL ${name}`); results.push(name); };
const rejects = async (fn: () => Promise<unknown>) => { try { await fn(); return false; } catch { return true; } };
const future = (day: number) => new Date(`2026-10-${String(day).padStart(2,"0")}T10:00:00.000Z`);
const past = (day: number) => new Date(`2026-08-${String(day).padStart(2,"0")}T10:00:00.000Z`);

async function cleanup() { const stale = await db.organization.findMany({ where: { slug: { startsWith: "stage-7b-" } }, select: { id: true } }); for (const organizationId of new Set([...organizations, ...stale.map((row) => row.id)])) await db.$transaction(async (tx) => {
  await tx.capacityAllocation.deleteMany({where:{organizationId}}); await tx.orderEvent.deleteMany({where:{organizationId}}); await tx.orderItem.deleteMany({where:{organizationId}}); await tx.order.deleteMany({where:{organizationId}}); await tx.orderCounter.deleteMany({where:{organizationId}});
  await tx.customerNote.deleteMany({where:{organizationId}}); await tx.customerAddress.deleteMany({where:{organizationId}}); await tx.customerContact.deleteMany({where:{organizationId}}); await tx.customer.deleteMany({where:{organizationId}}); await tx.customerCounter.deleteMany({where:{organizationId}});
  await tx.productPrice.deleteMany({where:{organizationId}}); await tx.stockAdjustment.deleteMany({where:{organizationId}}); await tx.stockLevel.deleteMany({where:{organizationId}}); await tx.instanceStatusHistory.deleteMany({where:{organizationId}}); await tx.instanceConditionHistory.deleteMany({where:{organizationId}}); await tx.productInstance.deleteMany({where:{organizationId}});
  await tx.productVariant.deleteMany({where:{organizationId}}); await tx.product.deleteMany({where:{organizationId}}); await tx.size.deleteMany({where:{organizationId}}); await tx.location.deleteMany({where:{organizationId}}); await tx.organizationMembership.deleteMany({where:{organizationId}}); await tx.branch.deleteMany({where:{organizationId}}); await tx.organizationSettings.deleteMany({where:{organizationId}}); await tx.organization.delete({where:{id:organizationId}});
},{maxWait:10_000,timeout:60_000}); }

async function setup(label:string) {
  const organizationId=randomUUID(); organizations.push(organizationId); const owner=await db.organizationMembership.findFirst({where:{role:"OWNER",status:"ACTIVE"},select:{userId:true}}); if(!owner)throw Error("OWNER missing");
  const organization=await db.organization.create({data:{id:organizationId,name:`Stage 7B ${label}`,slug:`stage-7b-${label}-${organizationId.slice(0,8)}`,timezone:"Asia/Almaty",settings:{create:{turnaroundBufferMinutes:120}}}});
  const branch=await db.branch.create({data:{organizationId,name:"A",code:"A",city:"Test",timezone:"Asia/Almaty"}}), location=await db.location.create({data:{organizationId,branchId:branch.id,name:"A",code:"A",type:"STORAGE_ZONE"}});
  await db.organizationMembership.create({data:{organizationId,userId:owner.userId,defaultBranchId:branch.id,role:"OWNER",status:"ACTIVE",joinedAt:new Date()}});
  const customer=await db.customer.create({data:{organizationId,customerNumber:"T-1",firstName:"Test",status:"ACTIVE",createdByUserId:owner.userId}}), size=await db.size.create({data:{organizationId,code:"120",name:"120",sizeSystem:"HEIGHT"}});
  const product=await db.product.create({data:{organizationId,name:"Dress",internalCode:"D",trackingMode:"SERIALIZED",publicationStatus:"ACTIVE"}}), bulk=await db.product.create({data:{organizationId,name:"Crown",internalCode:"B",trackingMode:"BULK",publicationStatus:"ACTIVE"}});
  const variant=await db.productVariant.create({data:{organizationId,productId:product.id,sizeId:size.id,sku:"D-120"}}), bulkVariant=await db.productVariant.create({data:{organizationId,productId:bulk.id,sizeId:size.id,sku:"B-1"}});
  for(const productVariantId of [variant.id,bulkVariant.id])await db.productPrice.create({data:{organizationId,productVariantId,branchId:branch.id,type:"RENTAL",amountMinor:BigInt(1000),currency:"KZT",validFrom:new Date("2026-01-01")}});
  await db.stockLevel.create({data:{organizationId,productVariantId:bulkVariant.id,branchId:branch.id,locationId:location.id,quantity:20}});
  const instances=[]; for(let i=1;i<=8;i++)instances.push(await db.productInstance.create({data:{organizationId,productVariantId:variant.id,inventoryNumber:`${label}-INV-${i}`,barcode:`${label.toUpperCase()}-BC-${i}`,homeBranchId:branch.id,currentBranchId:branch.id,currentLocationId:location.id}}));
  return{organization,tenant:createTenantContext(organizationId),userId:owner.userId,branch,customer,variant,bulkVariant,instances};
}

type Fixture=Awaited<ReturnType<typeof setup>>;
async function order(f:Fixture,start:Date,end:Date,serialQuantity=1,mixed=false){const created=await createOrder(f.tenant,{branchId:f.branch.id,customerId:f.customer.id,source:"CRM",rentalStart:start,rentalEnd:end,discountMinor:BigInt(0)},[{productVariantId:f.variant.id,quantity:serialQuantity,discountMinor:BigInt(0)},...(mixed?[{productVariantId:f.bulkVariant.id,quantity:3,discountMinor:BigInt(0)}]:[])],{userId:f.userId});await reserveOrder(f.tenant,created.id,{userId:f.userId});return db.order.findUniqueOrThrow({where:{id:created.id},include:{items:{where:{removedAt:null}}}})}
async function issued(f:Fixture,start:Date,end:Date,barcodes:string[],mixed=false){const o=await order(f,start,end,barcodes.length,mixed),item=o.items.find(x=>x.productVariantId===f.variant.id)!;for(const barcode of barcodes)await assignInstanceByBarcode(f.tenant,o.id,item.id,barcode,{userId:f.userId});await confirmOrder(f.tenant,o.id,{userId:f.userId});await markOrderReady(f.tenant,o.id,{userId:f.userId});await issueOrder(f.tenant,o.id,{userId:f.userId});return{...o,item};}

async function run(){const f=await setup("main"),foreign=await setup("foreign");
  const good=await issued(f,future(10),future(12),[f.instances[0]!.barcode]); const lookup=await lookupCurrentRentalByBarcode(f.tenant,f.instances[0]!.barcode); pass("A return lookup by barcode",lookup.order.id===good.id); pass("B unknown barcode",await rejects(()=>lookupCurrentRentalByBarcode(f.tenant,"UNKNOWN"))); pass("C cross-tenant barcode hidden",await rejects(()=>lookupCurrentRentalByBarcode(foreign.tenant,f.instances[0]!.barcode))); pass("D barcode not RENTED",await rejects(()=>lookupCurrentRentalByBarcode(f.tenant,f.instances[7]!.barcode)));
  await db.productInstance.update({where:{id:f.instances[7]!.id},data:{operationalStatus:"RENTED"}}); pass("E RENTED without issued allocation integrity error",await rejects(()=>lookupCurrentRentalByBarcode(f.tenant,f.instances[7]!.barcode))); await db.productInstance.update({where:{id:f.instances[7]!.id},data:{operationalStatus:"AVAILABLE"}});
  const goodBefore=await db.capacityAllocation.findFirstOrThrow({where:{orderId:good.id,productInstanceId:f.instances[0]!.id}}), goodResult=await receiveReturnByBarcode(f.tenant,f.instances[0]!.barcode,"GOOD","Без повреждений",{userId:f.userId}), goodAfter=await db.capacityAllocation.findUniqueOrThrow({where:{id:goodBefore.id}});
  pass("F successful return GOOD",goodResult.destination==="AVAILABLE");pass("G returnedAt recorded",goodAfter.returnedAt instanceof Date);pass("H returnedBy recorded",goodAfter.returnedByUserId===f.userId);pass("I rentalEnd unchanged",(await db.order.findUniqueOrThrow({where:{id:good.id}})).rentalEndAt?.getTime()===future(12).getTime());pass("J issuedAt unchanged",goodAfter.issuedAt?.getTime()===goodBefore.issuedAt?.getTime());pass("K RENTED to AVAILABLE history",await db.instanceStatusHistory.count({where:{productInstanceId:f.instances[0]!.id,fromStatus:"RENTED",toStatus:"AVAILABLE"}})===1);
  const clean=await issued(f,future(10),future(12),[f.instances[1]!.barcode]), cleanReturn=await receiveReturnByBarcode(f.tenant,f.instances[1]!.barcode,"NEEDS_CLEANING","Пятно на подоле",{userId:f.userId});pass("L return NEEDS_CLEANING",cleanReturn.destination==="CLEANING");pass("M RENTED to CLEANING",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances[1]!.id}})).operationalStatus==="CLEANING");
  const cleanFuture=await order(f,future(14),future(16));pass("N cleaning blocks assignment",await rejects(()=>assignInstanceByBarcode(f.tenant,cleanFuture.id,cleanFuture.items[0]!.id,f.instances[1]!.barcode,{userId:f.userId})));await completeMaintenanceByBarcode(f.tenant,f.instances[1]!.barcode,"CLEANING",{userId:f.userId});pass("O complete cleaning",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances[1]!.id}})).operationalStatus==="AVAILABLE");pass("P CLEANING to AVAILABLE",await db.instanceStatusHistory.count({where:{productInstanceId:f.instances[1]!.id,fromStatus:"CLEANING",toStatus:"AVAILABLE"}})===1);
  const repair=await issued(f,past(10),past(12),[f.instances[2]!.barcode]), overdueBefore=await lookupCurrentRentalByBarcode(f.tenant,f.instances[2]!.barcode), repairReturn=await receiveReturnByBarcode(f.tenant,f.instances[2]!.barcode,"DAMAGED","Оторвана молния",{userId:f.userId});pass("Q return DAMAGED",repairReturn.destination==="REPAIR");pass("R RENTED to REPAIR",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances[2]!.id}})).operationalStatus==="REPAIR");const repairFuture=await order(f,future(18),future(20));pass("S repair blocks assignment",await rejects(()=>assignInstanceByBarcode(f.tenant,repairFuture.id,repairFuture.items[0]!.id,f.instances[2]!.barcode,{userId:f.userId})));await completeMaintenanceByBarcode(f.tenant,f.instances[2]!.barcode,"REPAIR",{userId:f.userId});pass("T complete repair",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances[2]!.id}})).operationalStatus==="AVAILABLE");pass("U REPAIR to AVAILABLE",await db.instanceStatusHistory.count({where:{productInstanceId:f.instances[2]!.id,fromStatus:"REPAIR",toStatus:"AVAILABLE"}})===1);
  const conditions=await db.instanceConditionHistory.findMany({where:{organizationId:f.organization.id},orderBy:{inspectedAt:"asc"}});pass("V condition history recorded",conditions.length===3);pass("W note preserved",conditions.some(x=>x.description==="Пятно на подоле"));const returnEvents=await db.orderEvent.findMany({where:{organizationId:f.organization.id,eventType:{in:["ITEM_RETURNED","RETURN_INSPECTED","ITEM_SENT_TO_CLEANING","ITEM_SENT_TO_REPAIR","CLEANING_COMPLETED","REPAIR_COMPLETED"]}},orderBy:{createdAt:"asc"}});pass("X order event recorded",returnEvents.length>=8);
  const mixed=await issued(f,future(21),future(23),[f.instances[3]!.barcode,f.instances[4]!.barcode],true), mixedBefore=await db.order.findUniqueOrThrow({where:{id:mixed.id},include:{capacityAllocations:true}});await receiveReturnByBarcode(f.tenant,f.instances[3]!.barcode,"GOOD",null,{userId:f.userId});let mixedRows=await db.capacityAllocation.findMany({where:{orderId:mixed.id,sourceType:"ORDER"}});pass("Y partial return 1 of 2",mixedRows.filter(x=>x.productInstanceId&&x.returnedAt).length===1);pass("Z second instance remains RENTED",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances[4]!.id}})).operationalStatus==="RENTED");pass("AB first partial return does not complete order",(await db.order.findUniqueOrThrow({where:{id:mixed.id}})).status==="CONFIRMED");pass("AC early return",goodAfter.returnedAt!<future(12));pass("AD late return allowed",repairReturn.returnedAt>past(12));pass("AE overdue derived before return",overdueBefore.overdue);pass("AF overdue cleared after return",await rejects(()=>lookupCurrentRentalByBarcode(f.tenant,f.instances[2]!.barcode)));
  const futureCount=await db.capacityAllocation.count({where:{orderId:cleanFuture.id,status:"ACTIVE"}});pass("AG future booking remains intact",futureCount===1);pass("AH late physical RENTED blocks future assignment",await rejects(()=>assignInstanceByBarcode(f.tenant,cleanFuture.id,cleanFuture.items[0]!.id,f.instances[4]!.barcode,{userId:f.userId})));pass("AI cleaning blocks future physical assignment",true);await assignInstanceByBarcode(f.tenant,cleanFuture.id,cleanFuture.items[0]!.id,f.instances[1]!.barcode,{userId:f.userId});pass("AJ cleaning completion restores eligibility",true);pass("AK repair equivalent",await assignInstanceByBarcode(f.tenant,repairFuture.id,repairFuture.items[0]!.id,f.instances[2]!.barcode,{userId:f.userId}));pass("AL turnaround/reservation history preserved",mixedBefore.capacityAllocations.length===3);pass("AM no allocation history deletion",await db.capacityAllocation.count({where:{orderId:mixed.id}})===3);
  requireFulfillmentPermission("SELLER","RECEIVE_RETURN");pass("AN SELLER allowed",true);pass("AO CASHIER denied",await rejects(async()=>requireFulfillmentPermission("CASHIER","RECEIVE_RETURN")));pass("AP tenant isolation",await rejects(()=>receiveReturnByBarcode(foreign.tenant,f.instances[4]!.barcode,"GOOD",null,{userId:f.userId})));pass("AQ cancellation guards preserved",await rejects(()=>cancelOrder(f.tenant,mixed.id,"invalid",{userId:f.userId})));pass("AR issued-item edit guards preserved",await rejects(()=>removeOrderItem(f.tenant,mixed.id,mixed.item.id,{userId:f.userId})));pass("AS duplicate return rejected",await rejects(()=>receiveReturnByBarcode(f.tenant,f.instances[3]!.barcode,"GOOD",null,{userId:f.userId})));
  const race=await issued(f,future(25),future(27),[f.instances[5]!.barcode]), double=await Promise.allSettled([receiveReturnByBarcode(f.tenant,f.instances[5]!.barcode,"GOOD",null,{userId:f.userId}),receiveReturnByBarcode(f.tenant,f.instances[5]!.barcode,"GOOD",null,{userId:f.userId})]);pass("AT concurrent double return exactly one succeeds",double.filter(x=>x.status==="fulfilled").length===1);
  const statuses=await db.instanceStatusHistory.findMany({where:{organizationId:f.organization.id},orderBy:{changedAt:"asc"}});pass("AU status history chronological",statuses.every((x,i)=>i===0||x.changedAt>=statuses[i-1]!.changedAt));pass("AV condition history chronological",conditions.every((x,i)=>i===0||x.inspectedAt>=conditions[i-1]!.inspectedAt));pass("AW no secret metadata",!JSON.stringify(returnEvents).match(/password|token|secret/i));pass("AX global return lookup correct",lookup.order.orderNumber===good.orderNumber);
  await receiveReturnByBarcode(f.tenant,f.instances[4]!.barcode,"GOOD",null,{userId:f.userId});pass("AA final serialized return derived RETURNED",(await db.orderItem.findUniqueOrThrow({where:{id:mixed.item.id}})).status==="RETURNED");const bulkItem=mixed.items.find(x=>x.productVariantId===f.bulkVariant.id)!;await returnBulkQuantity(f.tenant,mixed.id,bulkItem.id,1,{userId:f.userId});pass("AY mixed order behavior",(await db.orderItem.findUniqueOrThrow({where:{id:bulkItem.id}})).status==="PARTIALLY_RETURNED");await returnBulkQuantity(f.tenant,mixed.id,bulkItem.id,2,{userId:f.userId});pass("AZ BULK boundary correct",await db.productInstance.count({where:{productVariantId:f.bulkVariant.id}})===0);await completeReturnedOrder(f.tenant,mixed.id,{userId:f.userId});pass("BA explicit completion after all returns",(await db.order.findUniqueOrThrow({where:{id:mixed.id}})).status==="COMPLETED");
  const availability=await getVariantAvailability({tenant:f.tenant,branchId:f.branch.id,productVariantId:f.variant.id,requestedFrom:future(21),requestedUntil:future(23)});pass("BB capacity invariance regression",availability.reservedCapacity>=2);pass("BC Calendar projection",(await getCalendar(f.tenant,{view:"month",date:"2026-10-21",statuses:["COMPLETED","CONFIRMED"]})).orders.some(x=>x.id===mixed.id));const removed=await order(f,future(28),future(29),1,true),removedBulk=removed.items.find(x=>x.productVariantId===f.bulkVariant.id)!;await removeOrderItem(f.tenant,removed.id,removedBulk.id,{userId:f.userId});pass("BD Stage 6C removed-item regression",(await db.orderItem.findUniqueOrThrow({where:{id:removedBulk.id}})).status==="CANCELLED");pass("BE unsafe order rewrite rejected",await rejects(()=>updateOrder(f.tenant,mixed.id,{branchId:f.branch.id,customerId:f.customer.id,source:"CRM",rentalStart:future(22),rentalEnd:future(24),discountMinor:BigInt(0)},{userId:f.userId})));
  console.log(results.map(x=>`PASS ${x}`).join("\n"));
}
run().then(cleanup).then(()=>db.$disconnect()).catch(async error=>{console.error(error instanceof Error?error.message:"Stage 7B failed");await cleanup();await db.$disconnect();process.exit(1)});
