import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { effectsFor } from "../lib/finance/effects";
import { FinanceError } from "../lib/finance/errors";
import { reverseFinancialTransaction } from "../lib/finance/transactions";
import { createTenantContext } from "../lib/tenant/context";

const prefix="stage-9h-a-",organizations:string[]=[],users:string[]=[];let checks=0;
let operationTimer:NodeJS.Timeout|undefined,currentOperation="startup";
const stage=(name:string)=>{currentOperation=name;console.log(JSON.stringify({at:new Date().toISOString(),stage:name}));if(operationTimer)clearTimeout(operationTimer);operationTimer=setTimeout(()=>{console.error(JSON.stringify({at:new Date().toISOString(),stage:"WATCHDOG_TIMEOUT",operation:currentOperation}));process.exit(124)},30_000);operationTimer.unref()};
const ok=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);checks++};
const rejectsCode=async(fn:()=>Promise<unknown>,code?:string)=>{try{await fn();return false}catch(error){return !code||error instanceof FinanceError&&error.code===code}};
async function cleanup(){stage("cleanup: find organizations");const stale=await db.organization.findMany({where:{slug:{startsWith:prefix}},select:{id:true}}),ids=[...new Set([...organizations,...stale.map(x=>x.id)])];if(!ids.length){stage("cleanup: nothing to delete");return}stage("cleanup: find users");const candidateUsers=await db.organizationMembership.findMany({where:{organizationId:{in:ids}},select:{userId:true}});stage("cleanup: transaction begin");await db.$transaction(async tx=>{
 stage("cleanup: transaction entered");
 await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');
 await tx.auditLog.deleteMany({where:{organizationId:{in:ids}}});await tx.financialTransaction.deleteMany({where:{organizationId:{in:ids}}});
 await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');
 await tx.order.deleteMany({where:{organizationId:{in:ids}}});await tx.customer.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:ids}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:ids}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:ids}}});await tx.branch.deleteMany({where:{organizationId:{in:ids}}});await tx.organization.deleteMany({where:{id:{in:ids}}});await tx.user.deleteMany({where:{id:{in:[...new Set([...users,...candidateUsers.map(x=>x.userId)])]}}});
 stage("cleanup: transaction callback complete");
 },{maxWait:10000,timeout:60000});stage("cleanup: transaction resolved");organizations.length=0;users.length=0;}

async function malformedCount(organizationId?:string){const rows=await db.$queryRaw<Array<{count:number}>>`SELECT count(*)::int count FROM financial_transactions r LEFT JOIN financial_transactions o ON o.id=r.reversal_of_id WHERE r.kind='REVERSAL' AND (${organizationId??null}::uuid IS NULL OR r.organization_id=${organizationId??null}::uuid) AND (o.id IS NULL OR o.kind='REVERSAL' OR r.organization_id IS DISTINCT FROM o.organization_id OR r.branch_id IS DISTINCT FROM o.branch_id OR r.order_id IS DISTINCT FROM o.order_id OR r.customer_id IS DISTINCT FROM o.customer_id OR r.currency IS DISTINCT FROM o.currency OR r.amount_minor IS DISTINCT FROM o.amount_minor OR r.payment_method_id IS DISTINCT FROM o.payment_method_id OR r.related_transaction_id IS DISTINCT FROM o.related_transaction_id OR r.obligation_effect_minor IS DISTINCT FROM -o.obligation_effect_minor OR r.cash_effect_minor IS DISTINCT FROM -o.cash_effect_minor OR r.revenue_effect_minor IS DISTINCT FROM -o.revenue_effect_minor OR r.deposit_effect_minor IS DISTINCT FROM -o.deposit_effect_minor)`;return rows[0]!.count;}

async function main(){stage("main: pre-cleanup");await cleanup();stage("fixture: organization");const organizationId=randomUUID(),userId=randomUUID(),sellerUserId=randomUUID();organizations.push(organizationId);users.push(userId,sellerUserId);await db.organization.create({data:{id:organizationId,name:"Stage 9H-A",slug:`${prefix}${organizationId.slice(0,8)}`}});const hash=createHash("sha256").update(organizationId).digest("hex");stage("fixture: users");await db.user.createMany({data:[{id:userId,email:`9ha-owner-${organizationId}@test.invalid`,displayName:"Owner",passwordHash:hash},{id:sellerUserId,email:`9ha-seller-${organizationId}@test.invalid`,displayName:"Seller",passwordHash:hash}]});
 stage("fixture: domain records");const branch=await db.branch.create({data:{organizationId,name:"A",code:"A",city:"Test",timezone:"Asia/Qyzylorda"}}),branchB=await db.branch.create({data:{organizationId,name:"B",code:"B",city:"Test",timezone:"Asia/Qyzylorda"}});const customer=await db.customer.create({data:{organizationId,customerNumber:"9HA-1",firstName:"Test"}}),customerB=await db.customer.create({data:{organizationId,customerNumber:"9HA-2",firstName:"Other"}});const order=await db.order.create({data:{organizationId,orderNumber:"9HA-1",branchId:branch.id,customerId:customer.id,type:"RENTAL",channel:"CRM",currency:"KZT"}}),orderB=await db.order.create({data:{organizationId,orderNumber:"9HA-2",branchId:branch.id,customerId:customerB.id,type:"RENTAL",channel:"CRM",currency:"KZT"}});const owner=await db.organizationMembership.create({data:{organizationId,userId,role:"OWNER",status:"ACTIVE",defaultBranchId:branch.id}}),seller=await db.organizationMembership.create({data:{organizationId,userId:sellerUserId,role:"SELLER",status:"ACTIVE",defaultBranchId:branch.id}});await db.membershipBranchAccess.create({data:{organizationId,membershipId:seller.id,branchId:branch.id}});await db.membershipPermissionOverride.create({data:{organizationId,membershipId:seller.id,permissionKey:"PAYMENT_REVERSE",effect:"ALLOW"}});const cash=await db.paymentMethod.create({data:{organizationId,code:"CASH",displayName:"Cash"}}),card=await db.paymentMethod.create({data:{organizationId,code:"CARD",displayName:"Card"}});const tenant=createTenantContext(organizationId),ownerActor={userId,membershipId:owner.id,role:"OWNER" as const},sellerActor={userId:sellerUserId,membershipId:seller.id,role:"SELLER" as const};let seq=0;
 const original=async(kind:Exclude<Parameters<typeof effectsFor>[0],"REVERSAL">,options:{orderId?:string|null;customerId?:string|null;paymentMethodId?:string|null;relatedTransactionId?:string|null}={})=>{const amount=BigInt(1000+seq++),effects=effectsFor(kind,amount),needsMethod=effects.cashEffectMinor!==BigInt(0);return db.financialTransaction.create({data:{organizationId,branchId:branch.id,orderId:options.orderId===undefined?order.id:options.orderId,customerId:options.customerId===undefined?customer.id:options.customerId,kind,amountMinor:amount,...effects,currency:"KZT",paymentMethodId:options.paymentMethodId===undefined?(needsMethod?cash.id:null):options.paymentMethodId,relatedTransactionId:options.relatedTransactionId??null,sourceType:"STAGE_9H_A_ORIGINAL",sourceId:randomUUID(),idempotencyKey:`9ha-original-${seq}`}})};
 const input=(key:string,extra:Record<string,unknown>={})=>({branchId:branch.id,customerId:customer.id,orderId:order.id,sourceType:"STAGE_9H_A_CORRECTION",sourceId:randomUUID(),idempotencyKey:key,reason:"Correction",...extra});
 stage("group: normal reversal and replay");const base=await original("PAYMENT_RECEIVED"),reversal=await reverseFinancialTransaction(tenant,base.id,input("normal"),ownerActor);ok("1 normal reversal",reversal.reversalOfId===base.id);ok("12 inverse effects",reversal.obligationEffectMinor===-base.obligationEffectMinor&&reversal.cashEffectMinor===-base.cashEffectMinor&&reversal.revenueEffectMinor===-base.revenueEffectMinor&&reversal.depositEffectMinor===-base.depositEffectMinor);ok("13 correction provenance",reversal.sourceType==="STAGE_9H_A_CORRECTION"&&reversal.sourceId!==base.sourceId);ok("14 correction time",reversal.occurredAt.getTime()>=base.occurredAt.getTime());ok("16 replay",(await reverseFinancialTransaction(tenant,base.id,{...input("normal"),sourceId:reversal.sourceId!},ownerActor)).id===reversal.id);
 stage("group: service provenance guards");const guarded=await original("RENTAL_CHARGE");ok("2 cross order",await rejectsCode(()=>reverseFinancialTransaction(tenant,guarded.id,input("cross-order",{orderId:orderB.id,customerId:customerB.id}),ownerActor),"CONFLICT"));ok("3 cross customer",await rejectsCode(()=>reverseFinancialTransaction(tenant,guarded.id,input("cross-customer",{customerId:customerB.id}),ownerActor),"CONFLICT"));ok("4 cross branch",await rejectsCode(()=>reverseFinancialTransaction(tenant,guarded.id,input("cross-branch",{branchId:branchB.id}),ownerActor),"CONFLICT"));const generic=await original("DISCOUNT",{orderId:null});ok("5 null order to non-null",await rejectsCode(()=>reverseFinancialTransaction(tenant,generic.id,input("null-order"),ownerActor),"CONFLICT"));ok("6 non-null order to null",await rejectsCode(()=>reverseFinancialTransaction(tenant,guarded.id,{...input("nonnull-order"),orderId:undefined},ownerActor),"CONFLICT"));
 stage("group: idempotency conflicts");const other=await original("SALE_CHARGE");ok("17 same key other original",await rejectsCode(()=>reverseFinancialTransaction(tenant,other.id,input("normal"),ownerActor),"CONFLICT"));ok("18 incompatible replay",await rejectsCode(()=>reverseFinancialTransaction(tenant,base.id,{...input("normal"),sourceId:reversal.sourceId!,reason:"Different"},ownerActor),"CONFLICT"));
 stage("group: replay authorization");const permissionOriginal=await original("DAMAGE_CHARGE"),permissionReversal=await reverseFinancialTransaction(tenant,permissionOriginal.id,input("permission-replay"),sellerActor);await db.membershipPermissionOverride.delete({where:{membershipId_permissionKey:{membershipId:seller.id,permissionKey:"PAYMENT_REVERSE"}}});ok("19 revoked permission",await rejectsCode(()=>reverseFinancialTransaction(tenant,permissionOriginal.id,{...input("permission-replay"),sourceId:permissionReversal.sourceId!},sellerActor)));await db.membershipPermissionOverride.create({data:{organizationId,membershipId:seller.id,permissionKey:"PAYMENT_REVERSE",effect:"ALLOW"}});await db.membershipBranchAccess.deleteMany({where:{membershipId:seller.id}});ok("20 revoked branch",await rejectsCode(()=>reverseFinancialTransaction(tenant,permissionOriginal.id,{...input("permission-replay"),sourceId:permissionReversal.sourceId!},sellerActor)));await db.membershipBranchAccess.create({data:{organizationId,membershipId:seller.id,branchId:branch.id}});await db.organizationMembership.update({where:{id:seller.id},data:{status:"SUSPENDED"}});ok("21 inactive membership",await rejectsCode(()=>reverseFinancialTransaction(tenant,permissionOriginal.id,{...input("permission-replay"),sourceId:permissionReversal.sourceId!},sellerActor)));
 const direct=async(source:Awaited<ReturnType<typeof original>>,overrides:Record<string,unknown>)=>rejectsCode(()=>db.financialTransaction.create({data:{organizationId,branchId:source.branchId,customerId:source.customerId,orderId:source.orderId,kind:"REVERSAL",amountMinor:source.amountMinor,obligationEffectMinor:-source.obligationEffectMinor,cashEffectMinor:-source.cashEffectMinor,revenueEffectMinor:-source.revenueEffectMinor,depositEffectMinor:-source.depositEffectMinor,currency:source.currency,paymentMethodId:source.paymentMethodId,relatedTransactionId:source.relatedTransactionId,reversalOfId:source.id,sourceType:"DIRECT_TEST",sourceId:randomUUID(),idempotencyKey:`direct-${randomUUID()}`,reason:"Must fail",...overrides}}));
 stage("group: direct SQL trigger rejections");const sqlOrder=await original("RENTAL_CHARGE");ok("22 SQL cross order",await direct(sqlOrder,{orderId:orderB.id,customerId:customerB.id}));ok("23 SQL cross customer",await direct(sqlOrder,{customerId:customerB.id}));const sqlPayment=await original("PAYMENT_RECEIVED");ok("24 SQL payment method",await direct(sqlPayment,{paymentMethodId:card.id}));const parent=await original("PAYMENT_RECEIVED"),sqlRelated=await original("CUSTOMER_REFUND",{relatedTransactionId:parent.id});ok("25 SQL related",await direct(sqlRelated,{relatedTransactionId:null}));const nullCustomer=await original("DISCOUNT",{orderId:null,customerId:null});ok("7 null customer mismatch",await direct(nullCustomer,{customerId:customer.id}));ok("10 currency mismatch",await direct(sqlOrder,{currency:"USD"}));ok("11 amount mismatch",await direct(sqlOrder,{amountMinor:sqlOrder.amountMinor+BigInt(1)}));
 stage("group: inactive payment method");await db.paymentMethod.update({where:{id:card.id},data:{isActive:false}});const inactive=await original("PAYMENT_RECEIVED",{paymentMethodId:card.id});ok("15 inactive method",(await reverseFinancialTransaction(tenant,inactive.id,input("inactive"),ownerActor)).paymentMethodId===card.id);
 stage("group: existing transaction families");const kinds=["PAYMENT_RECEIVED","CUSTOMER_REFUND","DEPOSIT_RECEIVED","DEPOSIT_REFUNDED","DEPOSIT_WITHHELD","DAMAGE_CHARGE","RENTAL_CHARGE","DISCOUNT"] as const;for(const kind of kinds){stage(`family ${kind}: original`);const row=await original(kind);stage(`family ${kind}: reversal service`);const result=await reverseFinancialTransaction(tenant,row.id,input(`kind-${kind}`),ownerActor);ok(`existing kind ${kind}`,result.reversalOfId===row.id)}
 stage("group: concurrent reversal");const race=await original("SALE_CHARGE"),raceInput=input("race"),raceRows=await Promise.allSettled([reverseFinancialTransaction(tenant,race.id,raceInput,ownerActor),reverseFinancialTransaction(tenant,race.id,raceInput,ownerActor)]);console.log(JSON.stringify({stage:"concurrent reversal result",results:raceRows.map(row=>row.status==="fulfilled"?{status:row.status,id:row.value.id}:{status:row.status,error:row.reason instanceof FinanceError?{name:row.reason.name,code:row.reason.code}:row.reason instanceof Error?{name:row.reason.name,message:row.reason.message}:{type:typeof row.reason}})}));ok("31 concurrent canonical",raceRows.every(x=>x.status==="fulfilled")&&new Set(raceRows.map(x=>x.status==="fulfilled"?x.value.id:"")).size===1&&await db.financialTransaction.count({where:{reversalOfId:race.id}})===1);
 stage("group: audit malformed read-only");const audit=await db.auditLog.findFirst({where:{organizationId,entityId:reversal.id}});ok("32 audit",audit?.actorUserId===userId&&JSON.stringify(audit.metadata).includes(base.id)&&JSON.stringify(audit.metadata).includes("Correction"));ok("33 malformed zero",await malformedCount(organizationId)===0);const before=await db.order.count({where:{organizationId}});await db.financialTransaction.count({where:{organizationId}});ok("34 unrelated read",await db.order.count({where:{organizationId}})===before);console.log(`PASS Stage 9H-A (${checks} checks)`);
}
main().finally(async()=>{stage("finally: cleanup begin");await cleanup();stage("finally: disconnect begin");await db.$disconnect();stage("finally: disconnect resolved");if(operationTimer)clearTimeout(operationTimer)}).catch(error=>{console.error(error);process.exitCode=1});
