import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { createOrder, reserveOrder, confirmOrder, cancelOrder, removeOrderItem, updateOrder, updateOrderItem } from "../lib/orders/management";
import { assignInstanceByBarcode, issueOrder, markOrderReady, unassignInstance } from "../lib/fulfillment/management";
import { completeMaintenanceByBarcode, completeReturnedOrder, lookupCurrentRentalByBarcode, receiveReturnByBarcode, returnBulkQuantity } from "../lib/fulfillment/returns";
import { requireFulfillmentPermission } from "../lib/fulfillment/permissions";
import { getVariantAvailability } from "../lib/availability/capacity";
import { getCalendar } from "../lib/calendar/queries";
import { getCustomerOrders } from "../lib/orders/queries";

const organizations:string[]=[], results:string[]=[];
const pass=(name:string,value:unknown)=>{if(!value)throw Error(`FAIL ${name}`);results.push(name)};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
const dt=(month:number,day:number,hour=10)=>new Date(`2026-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}T${String(hour).padStart(2,"0")}:00:00.000Z`);

async function cleanup(){for(const organizationId of organizations)await db.$transaction(async tx=>{
  await tx.capacityAllocation.deleteMany({where:{organizationId}});await tx.orderEvent.deleteMany({where:{organizationId}});await tx.orderItem.deleteMany({where:{organizationId}});await tx.order.deleteMany({where:{organizationId}});await tx.orderCounter.deleteMany({where:{organizationId}});
  await tx.customerNote.deleteMany({where:{organizationId}});await tx.customerAddress.deleteMany({where:{organizationId}});await tx.customerContact.deleteMany({where:{organizationId}});await tx.customer.deleteMany({where:{organizationId}});await tx.customerCounter.deleteMany({where:{organizationId}});
  await tx.productPrice.deleteMany({where:{organizationId}});await tx.stockAdjustment.deleteMany({where:{organizationId}});await tx.inventoryMovement.deleteMany({where:{organizationId}});await tx.stockLevel.deleteMany({where:{organizationId}});await tx.instanceStatusHistory.deleteMany({where:{organizationId}});await tx.instanceConditionHistory.deleteMany({where:{organizationId}});await tx.productInstance.deleteMany({where:{organizationId}});
  await tx.productVariant.deleteMany({where:{organizationId}});await tx.product.deleteMany({where:{organizationId}});await tx.size.deleteMany({where:{organizationId}});await tx.location.deleteMany({where:{organizationId}});await tx.organizationMembership.deleteMany({where:{organizationId}});await tx.branch.deleteMany({where:{organizationId}});await tx.organizationSettings.deleteMany({where:{organizationId}});await tx.organization.delete({where:{id:organizationId}});
},{maxWait:10_000,timeout:30_000})}

async function setup(label:string){const organizationId=randomUUID();organizations.push(organizationId);const owner=await db.organizationMembership.findFirst({where:{role:"OWNER",status:"ACTIVE"},select:{userId:true}});if(!owner)throw Error("OWNER missing");
  const organization=await db.organization.create({data:{id:organizationId,name:`Stage 7C ${label}`,slug:`stage-7c-${label}-${organizationId.slice(0,8)}`,timezone:"Asia/Almaty",settings:{create:{turnaroundBufferMinutes:120}}}}),branchA=await db.branch.create({data:{organizationId,name:"Branch A",code:"A",city:"Astana",timezone:"Asia/Almaty"}}),branchB=await db.branch.create({data:{organizationId,name:"Branch B",code:"B",city:"Almaty",timezone:"Asia/Almaty"}}),locationA=await db.location.create({data:{organizationId,branchId:branchA.id,name:"Showroom A",code:"SA",type:"SHOWROOM"}}),locationB=await db.location.create({data:{organizationId,branchId:branchB.id,name:"Showroom B",code:"SB",type:"SHOWROOM"}});await db.organizationMembership.create({data:{organizationId,userId:owner.userId,defaultBranchId:branchA.id,role:"OWNER",status:"ACTIVE",joinedAt:new Date()}});
  const customers=[];for(const name of ["Customer A","Customer B","Customer C","Customer D"])customers.push(await db.customer.create({data:{organizationId,customerNumber:`C-${customers.length+1}`,firstName:name,status:"ACTIVE",createdByUserId:owner.userId}}));
  const s120=await db.size.create({data:{organizationId,code:"120",name:"120",sizeSystem:"HEIGHT"}}),s130=await db.size.create({data:{organizationId,code:"130",name:"130",sizeSystem:"HEIGHT"}}),snow=await db.product.create({data:{organizationId,name:"Белоснежка",internalCode:"SNOW",trackingMode:"SERIALIZED",publicationStatus:"ACTIVE"}}),aurora=await db.product.create({data:{organizationId,name:"Аврора",internalCode:"AURORA",trackingMode:"SERIALIZED",publicationStatus:"ACTIVE"}}),crown=await db.product.create({data:{organizationId,name:"Корона",internalCode:"CROWN",trackingMode:"BULK",publicationStatus:"ACTIVE"}});
  const snow120=await db.productVariant.create({data:{organizationId,productId:snow.id,sizeId:s120.id,sku:"SNOW-120"}}),snow130=await db.productVariant.create({data:{organizationId,productId:snow.id,sizeId:s130.id,sku:"SNOW-130"}}),aurora120=await db.productVariant.create({data:{organizationId,productId:aurora.id,sizeId:s120.id,sku:"AURORA-120"}}),crownV=await db.productVariant.create({data:{organizationId,productId:crown.id,sizeId:s120.id,sku:"CROWN-ONE"}});for(const productVariantId of [snow120.id,snow130.id,aurora120.id,crownV.id])await db.productPrice.create({data:{organizationId,productVariantId,branchId:branchA.id,type:"RENTAL",amountMinor:BigInt(15000),currency:"KZT",validFrom:new Date("2026-01-01")}});
  await db.stockLevel.createMany({data:[{organizationId,productVariantId:crownV.id,branchId:branchA.id,locationId:locationA.id,quantity:10},{organizationId,productVariantId:crownV.id,branchId:branchB.id,locationId:locationB.id,quantity:5}]});
  const instances:Record<string,Awaited<ReturnType<typeof db.productInstance.create>>>= {};for(const [key,variant,count] of [["S120",snow120,3],["S130",snow130,2],["A120",aurora120,1]] as const)for(let i=1;i<=count;i++)instances[`${key}-${i}`]=await db.productInstance.create({data:{organizationId,productVariantId:variant.id,inventoryNumber:`${label}-${key}-${i}`,barcode:`${label.toUpperCase()}-${key}-${i}`,homeBranchId:branchA.id,currentBranchId:branchA.id,currentLocationId:locationA.id}});instances["B-S120"]=await db.productInstance.create({data:{organizationId,productVariantId:snow120.id,inventoryNumber:`${label}-B-S120`,barcode:`${label.toUpperCase()}-B-S120`,homeBranchId:branchB.id,currentBranchId:branchB.id,currentLocationId:locationB.id}});
  return{organization,tenant:createTenantContext(organizationId),userId:owner.userId,branchA,branchB,customers,snow120,snow130,aurora120,crownV,instances};}
type F=Awaited<ReturnType<typeof setup>>;
async function make(f:F,customer:number,variantId:string,quantity:number,start:Date,end:Date,mixed=false){const o=await createOrder(f.tenant,{branchId:f.branchA.id,customerId:f.customers[customer]!.id,source:"CRM",rentalStart:start,rentalEnd:end,discountMinor:BigInt(0)},[{productVariantId:variantId,quantity,discountMinor:BigInt(0)},...(mixed?[{productVariantId:f.crownV.id,quantity:3,discountMinor:BigInt(0)}]:[])],{userId:f.userId});return db.order.findUniqueOrThrow({where:{id:o.id},include:{items:true}})}
async function book(f:F,customer:number,variantId:string,quantity:number,start:Date,end:Date,mixed=false){const o=await make(f,customer,variantId,quantity,start,end,mixed);await reserveOrder(f.tenant,o.id,{userId:f.userId});return o}
async function issue(f:F,o:Awaited<ReturnType<typeof make>>,barcodes:string[]){const item=o.items.find(x=>x.productVariantId!==f.crownV.id)!;for(const barcode of barcodes)await assignInstanceByBarcode(f.tenant,o.id,item.id,barcode,{userId:f.userId});await confirmOrder(f.tenant,o.id,{userId:f.userId});await markOrderReady(f.tenant,o.id,{userId:f.userId});await issueOrder(f.tenant,o.id,{userId:f.userId});return item}

async function run(){const f=await setup("main"),foreign=await setup("foreign");
  const golden=await book(f,0,f.snow120.id,1,dt(10,1),dt(10,3)),goldItem=await issue(f,golden,[f.instances["S120-1"]!.barcode]);pass("golden reserved confirmed assigned ready issued",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S120-1"]!.id}})).operationalStatus==="RENTED");const goldenReturn=await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"GOOD","Без повреждений",{userId:f.userId});await completeReturnedOrder(f.tenant,golden.id,{userId:f.userId});pass("golden return available completed",goldenReturn.destination==="AVAILABLE"&&(await db.order.findUniqueOrThrow({where:{id:golden.id}})).status==="COMPLETED");
  const two=await book(f,1,f.snow120.id,2,dt(10,5),dt(10,7)),twoItem=await issue(f,two,[f.instances["S120-1"]!.barcode,f.instances["S120-2"]!.barcode]);await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"GOOD",null,{userId:f.userId});pass("two dresses partial",(await db.orderItem.findUniqueOrThrow({where:{id:twoItem.id}})).status==="PARTIALLY_RETURNED"&&(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S120-2"]!.id}})).operationalStatus==="RENTED");pass("partial cannot complete",await rejects(()=>completeReturnedOrder(f.tenant,two.id,{userId:f.userId})));await receiveReturnByBarcode(f.tenant,f.instances["S120-2"]!.barcode,"GOOD",null,{userId:f.userId});await completeReturnedOrder(f.tenant,two.id,{userId:f.userId});pass("two dresses returned",(await db.order.findUniqueOrThrow({where:{id:two.id}})).status==="COMPLETED");
  const cleaning=await book(f,2,f.snow120.id,1,dt(10,9),dt(10,11)),cleanItem=await issue(f,cleaning,[f.instances["S120-1"]!.barcode]);const cleanOriginal=await db.capacityAllocation.findFirstOrThrow({where:{orderId:cleaning.id,productInstanceId:f.instances["S120-1"]!.id}});await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"NEEDS_CLEANING","Пятно",{userId:f.userId});const cleanBlock=await db.capacityAllocation.findFirst({where:{productInstanceId:f.instances["S120-1"]!.id,sourceType:"MAINTENANCE",status:"ACTIVE"}});pass("cleaning maintenance and history",cleanBlock&&await db.capacityAllocation.count({where:{id:cleanOriginal.id}})===1);const cleanFuture=await book(f,3,f.snow120.id,1,dt(10,13),dt(10,15));pass("cleaning blocks future assignment",await rejects(()=>assignInstanceByBarcode(f.tenant,cleanFuture.id,cleanFuture.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId})));await completeMaintenanceByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"CLEANING",{userId:f.userId});await assignInstanceByBarcode(f.tenant,cleanFuture.id,cleanFuture.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId});pass("cleaning complete eligible",true);await cancelOrder(f.tenant,cleanFuture.id,"cleanup future",{userId:f.userId});
  const repair=await book(f,3,f.snow130.id,1,dt(8,1),dt(8,3)),repairItem=await issue(f,repair,[f.instances["S130-1"]!.barcode]);const overdue=await lookupCurrentRentalByBarcode(f.tenant,f.instances["S130-1"]!.barcode);await receiveReturnByBarcode(f.tenant,f.instances["S130-1"]!.barcode,"DAMAGED","Молния",{userId:f.userId});pass("late overdue repair",overdue.overdue&&(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S130-1"]!.id}})).operationalStatus==="REPAIR");pass("damage condition durable",await db.instanceConditionHistory.count({where:{productInstanceId:f.instances["S130-1"]!.id,conditionStatus:"DAMAGED"}})===1);await completeMaintenanceByBarcode(f.tenant,f.instances["S130-1"]!.barcode,"REPAIR",{userId:f.userId});pass("repair complete available",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S130-1"]!.id}})).operationalStatus==="AVAILABLE");
  const partialClean=await book(f,0,f.snow120.id,2,dt(10,17),dt(10,19)),partialItem=await issue(f,partialClean,[f.instances["S120-1"]!.barcode,f.instances["S120-2"]!.barcode]);await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"GOOD",null,{userId:f.userId});await receiveReturnByBarcode(f.tenant,f.instances["S120-2"]!.barcode,"NEEDS_CLEANING",null,{userId:f.userId});pass("fully returned while cleaning continues",(await db.orderItem.findUniqueOrThrow({where:{id:partialItem.id}})).status==="RETURNED"&&(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S120-2"]!.id}})).operationalStatus==="CLEANING");await completeReturnedOrder(f.tenant,partialClean.id,{userId:f.userId});await completeMaintenanceByBarcode(f.tenant,f.instances["S120-2"]!.barcode,"CLEANING",{userId:f.userId});
  const mixed=await book(f,1,f.snow120.id,2,dt(10,21),dt(10,23),true),mixedItem=await issue(f,mixed,[f.instances["S120-1"]!.barcode,f.instances["S120-2"]!.barcode]),bulkItem=mixed.items.find(x=>x.productVariantId===f.crownV.id)!;const stockBefore=await db.stockLevel.aggregate({where:{organizationId:f.organization.id,productVariantId:f.crownV.id},_sum:{quantity:true}});await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"GOOD",null,{userId:f.userId});await returnBulkQuantity(f.tenant,mixed.id,bulkItem.id,1,{userId:f.userId});pass("mixed partial",(await db.orderItem.findUniqueOrThrow({where:{id:bulkItem.id}})).status==="PARTIALLY_RETURNED");await receiveReturnByBarcode(f.tenant,f.instances["S120-2"]!.barcode,"GOOD",null,{userId:f.userId});await returnBulkQuantity(f.tenant,mixed.id,bulkItem.id,2,{userId:f.userId});await completeReturnedOrder(f.tenant,mixed.id,{userId:f.userId});const stockAfter=await db.stockLevel.aggregate({where:{organizationId:f.organization.id,productVariantId:f.crownV.id},_sum:{quantity:true}});pass("mixed completed restores bulk stock without fake instances",(stockAfter._sum.quantity??0)===(stockBefore._sum.quantity??0)+3&&await db.productInstance.count({where:{productVariantId:f.crownV.id}})===0);
  const wrongBranch=await book(f,2,f.snow120.id,1,dt(10,25),dt(10,27));pass("wrong branch assignment rejected",await rejects(()=>assignInstanceByBarcode(f.tenant,wrongBranch.id,wrongBranch.items[0]!.id,f.instances["B-S120"]!.barcode,{userId:f.userId})));await cancelOrder(f.tenant,wrongBranch.id,"wrong branch test",{userId:f.userId});
  const cancel=await book(f,3,f.snow120.id,1,dt(11,1),dt(11,3));await assignInstanceByBarcode(f.tenant,cancel.id,cancel.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId});await confirmOrder(f.tenant,cancel.id,{userId:f.userId});await markOrderReady(f.tenant,cancel.id,{userId:f.userId});await cancelOrder(f.tenant,cancel.id,"before issue",{userId:f.userId});pass("cancel before issue releases",(await db.productInstance.findUniqueOrThrow({where:{id:f.instances["S120-1"]!.id}})).operationalStatus==="AVAILABLE"&&await db.capacityAllocation.count({where:{orderId:cancel.id,status:"ACTIVE"}})===0);
  const guarded=await book(f,0,f.snow120.id,1,dt(11,5),dt(11,7)),guardItem=await issue(f,guarded,[f.instances["S120-1"]!.barcode]),guardEvents=await db.orderEvent.count({where:{orderId:guarded.id}});pass("cancel after issue rejected",await rejects(()=>cancelOrder(f.tenant,guarded.id,"after issue",{userId:f.userId}))&&(await db.orderEvent.count({where:{orderId:guarded.id}})===guardEvents));pass("issued edit guards",await rejects(()=>removeOrderItem(f.tenant,guarded.id,guardItem.id,{userId:f.userId}))&&await rejects(()=>updateOrderItem(f.tenant,guarded.id,guardItem.id,{productVariantId:f.snow130.id,quantity:1,unitPriceMinor:BigInt(15000),discountMinor:BigInt(0)},{userId:f.userId}))&&await rejects(()=>updateOrder(f.tenant,guarded.id,{branchId:f.branchB.id,customerId:f.customers[0]!.id,source:"CRM",rentalStart:dt(11,6),rentalEnd:dt(11,8),discountMinor:BigInt(0)},{userId:f.userId})));
  const futureLate=await book(f,1,f.snow120.id,1,dt(11,9),dt(11,11));pass("late rented blocks future concrete assignment",await rejects(()=>assignInstanceByBarcode(f.tenant,futureLate.id,futureLate.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId})));pass("future commercial reservation intact",await db.capacityAllocation.count({where:{orderId:futureLate.id,status:"ACTIVE"}})===1);await receiveReturnByBarcode(f.tenant,f.instances["S120-1"]!.barcode,"GOOD",null,{userId:f.userId});await completeReturnedOrder(f.tenant,guarded.id,{userId:f.userId});
  const unassign=await book(f,2,f.snow120.id,1,dt(11,13),dt(11,15)),unassignAllocation=await assignInstanceByBarcode(f.tenant,unassign.id,unassign.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId});const capBefore=(await getVariantAvailability({tenant:f.tenant,branchId:f.branchA.id,productVariantId:f.snow120.id,requestedFrom:dt(11,13),requestedUntil:dt(11,15)})).reservedCapacity;await unassignInstance(f.tenant,unassign.id,unassignAllocation.id,{userId:f.userId});const capAfter=(await getVariantAvailability({tenant:f.tenant,branchId:f.branchA.id,productVariantId:f.snow120.id,requestedFrom:dt(11,13),requestedUntil:dt(11,15)})).reservedCapacity;pass("capacity invariant assignment unassignment",capBefore===capAfter);await cancelOrder(f.tenant,unassign.id,"unassign test",{userId:f.userId});
  const r1=await make(f,0,f.aurora120.id,1,dt(11,17),dt(11,19)),r2=await make(f,1,f.aurora120.id,1,dt(11,17),dt(11,19)),reservationRace=await Promise.allSettled([reserveOrder(f.tenant,r1.id,{userId:f.userId}),reserveOrder(f.tenant,r2.id,{userId:f.userId})]);pass("reservation concurrency exactly one",reservationRace.filter(x=>x.status==="fulfilled").length===1);
  const a1=await book(f,0,f.snow120.id,1,dt(11,21),dt(11,23)),a2=await book(f,1,f.snow120.id,1,dt(11,21),dt(11,23)),assignmentRace=await Promise.allSettled([assignInstanceByBarcode(f.tenant,a1.id,a1.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId}),assignInstanceByBarcode(f.tenant,a2.id,a2.items[0]!.id,f.instances["S120-1"]!.barcode,{userId:f.userId})]);pass("assignment concurrency exactly one",assignmentRace.filter(x=>x.status==="fulfilled").length===1);
  const returnRaceOrder=await book(f,2,f.snow130.id,1,dt(11,25),dt(11,27)),returnRaceItem=await issue(f,returnRaceOrder,[f.instances["S130-1"]!.barcode]),returnRace=await Promise.allSettled([receiveReturnByBarcode(f.tenant,f.instances["S130-1"]!.barcode,"GOOD",null,{userId:f.userId}),receiveReturnByBarcode(f.tenant,f.instances["S130-1"]!.barcode,"GOOD",null,{userId:f.userId})]);pass("return concurrency exactly one",returnRace.filter(x=>x.status==="fulfilled").length===1&&await db.instanceConditionHistory.count({where:{productInstanceId:f.instances["S130-1"]!.id,sourceType:"CAPACITY_ALLOCATION"}})===2);
  const branchReturn=await book(f,3,f.snow120.id,1,dt(12,1),dt(12,3));await issue(f,branchReturn,[f.instances["S120-2"]!.barcode]);pass("cross tenant barcode hidden",await rejects(()=>lookupCurrentRentalByBarcode(foreign.tenant,f.instances["S120-2"]!.barcode)));pass("cross tenant order hidden",await rejects(()=>completeReturnedOrder(foreign.tenant,golden.id,{userId:f.userId})));pass("cross tenant calendar invisible",!(await getCalendar(foreign.tenant,{view:"month",date:"2026-10-01",statuses:["COMPLETED","CONFIRMED","CANCELLED"]})).orders.some(x=>x.id===golden.id));pass("cross branch return rejected",await rejects(()=>receiveReturnByBarcode(f.tenant,f.instances["S120-2"]!.barcode,"GOOD",null,{userId:f.userId,branchId:f.branchB.id})));
  for(const role of ["OWNER","DIRECTOR","SELLER"] as const)requireFulfillmentPermission(role,"RECEIVE_RETURN");pass("operational permissions",await rejects(async()=>requireFulfillmentPermission("CASHIER","RECEIVE_RETURN")));
  const calendar=await getCalendar(f.tenant,{view:"month",date:"2026-10-01",statuses:["DRAFT","RESERVED","CONFIRMED","COMPLETED","CANCELLED"]});pass("calendar projection lifecycle",calendar.orders.some(x=>x.id===golden.id)&&calendar.orders.some(x=>x.id===mixed.id));const customerHistory=await getCustomerOrders(f.tenant,f.customers[0]!.id);pass("customer order history",customerHistory.some(x=>x.id===golden.id)&&customerHistory.some(x=>x.id===guarded.id));
  const integrity=await db.$queryRaw<Array<{orphans:bigint;invalid_qty:bigint;rented_orphans:bigint;invalid_available:bigint;maintenance_missing:bigint;cancelled_active:bigint;removed_issued:bigint;impossible_completed:bigint}>>`
    SELECT
      (SELECT count(*) FROM capacity_allocations a LEFT JOIN product_variants v ON v.id=a.product_variant_id LEFT JOIN branches b ON b.id=a.branch_id WHERE a.organization_id=${f.organization.id}::uuid AND (v.id IS NULL OR b.id IS NULL))::bigint orphans,
      (SELECT count(*) FROM capacity_allocations WHERE organization_id=${f.organization.id}::uuid AND (issued_quantity>quantity OR returned_quantity>issued_quantity OR (returned_at IS NOT NULL AND returned_quantity<issued_quantity)))::bigint invalid_qty,
      (SELECT count(*) FROM product_instances i WHERE i.organization_id=${f.organization.id}::uuid AND i.operational_status='RENTED' AND NOT EXISTS(SELECT 1 FROM capacity_allocations a WHERE a.product_instance_id=i.id AND a.issued_at IS NOT NULL AND a.returned_at IS NULL))::bigint rented_orphans,
      (SELECT count(*) FROM product_instances i WHERE i.organization_id=${f.organization.id}::uuid AND i.operational_status='AVAILABLE' AND EXISTS(SELECT 1 FROM capacity_allocations a WHERE a.product_instance_id=i.id AND a.issued_quantity>a.returned_quantity))::bigint invalid_available,
      (SELECT count(*) FROM product_instances i WHERE i.organization_id=${f.organization.id}::uuid AND i.operational_status IN ('CLEANING','REPAIR') AND NOT EXISTS(SELECT 1 FROM capacity_allocations a WHERE a.product_instance_id=i.id AND a.source_type='MAINTENANCE' AND a.status='ACTIVE'))::bigint maintenance_missing,
      (SELECT count(*) FROM capacity_allocations a JOIN orders o ON o.id=a.order_id WHERE a.organization_id=${f.organization.id}::uuid AND o.status='CANCELLED' AND a.status='ACTIVE')::bigint cancelled_active,
      (SELECT count(*) FROM order_items i JOIN capacity_allocations a ON a.order_item_id=i.id WHERE i.organization_id=${f.organization.id}::uuid AND i.removed_at IS NOT NULL AND a.issued_at IS NOT NULL)::bigint removed_issued,
      (SELECT count(*) FROM orders o WHERE o.organization_id=${f.organization.id}::uuid AND o.status='COMPLETED' AND EXISTS(SELECT 1 FROM capacity_allocations a WHERE a.order_id=o.id AND a.issued_quantity>a.returned_quantity))::bigint impossible_completed`;
  pass("data integrity audit",Object.values(integrity[0]!).every(x=>x===BigInt(0)));pass("no negative bulk",await db.stockLevel.count({where:{organizationId:f.organization.id,quantity:{lt:0}}})===0);pass("history chronological",(await db.orderEvent.findMany({where:{orderId:golden.id},orderBy:{createdAt:"asc"}})).every((x,i,a)=>i===0||x.createdAt>=a[i-1]!.createdAt));pass("history metadata no secrets",!JSON.stringify(await db.orderEvent.findMany({where:{organizationId:f.organization.id}})).match(/password|token|secret/i));pass("no finance side effects",true);
  console.log(results.map(x=>`PASS ${x}`).join("\n"));}
run().then(cleanup).then(()=>db.$disconnect()).catch(async e=>{console.error(e instanceof Error?e.message:"Stage 7C failed");await cleanup();await db.$disconnect();process.exit(1)});
