import "dotenv/config";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { receiveBulk, receiveSerialized, transferBulk, transferSerialized, changeBulk } from "../lib/inventory/management";
import { getInventoryMovements } from "../lib/inventory/movements";
import { requireInventoryPermission } from "../lib/inventory/permissions";
import { startStocktake, scanBarcode, setBulkCount, completeCount, cancelStocktake, resolveMissing, resolveScan, resolveBulk, reconcileStocktake } from "../lib/stocktake/management";
import { createOrder, reserveOrder, confirmOrder } from "../lib/orders/management";
import { assignInstanceByBarcode, markOrderReady, issueOrder } from "../lib/fulfillment/management";
import { receiveReturnByBarcode, returnBulkQuantity, completeReturnedOrder } from "../lib/fulfillment/returns";
import { getVariantAvailability } from "../lib/availability/capacity";

const ids:string[]=[];
const pass=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);console.log(`PASS ${name}`)};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
const date=(day:number)=>new Date(`2026-08-${String(day).padStart(2,"0")}T10:00:00.000Z`);

async function cleanup(){const stale=await db.organization.findMany({where:{slug:{startsWith:"stage-8c-"}},select:{id:true}});for(const organizationId of new Set([...ids,...stale.map(x=>x.id)]))await db.$transaction(async tx=>{
  await tx.stocktakeScan.deleteMany({where:{organizationId}});await tx.stocktakeExpectedItem.deleteMany({where:{organizationId}});await tx.stocktakeBulkCount.deleteMany({where:{organizationId}});await tx.stocktakeSession.deleteMany({where:{organizationId}});
  await tx.inventoryMovement.deleteMany({where:{organizationId}});await tx.capacityAllocation.deleteMany({where:{organizationId}});await tx.orderEvent.deleteMany({where:{organizationId}});await tx.orderItem.deleteMany({where:{organizationId}});await tx.order.deleteMany({where:{organizationId}});await tx.orderCounter.deleteMany({where:{organizationId}});
  await tx.customerNote.deleteMany({where:{organizationId}});await tx.customerAddress.deleteMany({where:{organizationId}});await tx.customerContact.deleteMany({where:{organizationId}});await tx.customer.deleteMany({where:{organizationId}});await tx.customerCounter.deleteMany({where:{organizationId}});
  await tx.productPrice.deleteMany({where:{organizationId}});await tx.stockAdjustment.deleteMany({where:{organizationId}});await tx.stockLevel.deleteMany({where:{organizationId}});await tx.instanceStatusHistory.deleteMany({where:{organizationId}});await tx.instanceConditionHistory.deleteMany({where:{organizationId}});await tx.productInstance.deleteMany({where:{organizationId}});await tx.inventoryCounter.deleteMany({where:{organizationId}});
  await tx.productVariant.deleteMany({where:{organizationId}});await tx.product.deleteMany({where:{organizationId}});await tx.size.deleteMany({where:{organizationId}});await tx.location.deleteMany({where:{organizationId}});await tx.organizationMembership.deleteMany({where:{organizationId}});await tx.branch.deleteMany({where:{organizationId}});await tx.organizationSettings.deleteMany({where:{organizationId}});await tx.organization.delete({where:{id:organizationId}});
},{maxWait:10000,timeout:60000})}

async function setup(label:string){const organizationId=randomUUID();ids.push(organizationId);const owner=await db.organizationMembership.findFirstOrThrow({where:{role:"OWNER",status:"ACTIVE"},select:{userId:true}});await db.organization.create({data:{id:organizationId,name:`Stage 8C ${label}`,slug:`stage-8c-${label}-${organizationId.slice(0,8)}`,timezone:"Asia/Almaty",settings:{create:{turnaroundBufferMinutes:120}}}});await db.organizationMembership.create({data:{organizationId,userId:owner.userId,role:"OWNER",status:"ACTIVE"}});
 const a=await db.branch.create({data:{organizationId,name:"MARIPOSA showroom",code:"A",city:"Astana",timezone:"Asia/Almaty"}}),b=await db.branch.create({data:{organizationId,name:"Secondary",code:"B",city:"Almaty",timezone:"Asia/Almaty"}});
 const aw=await db.location.create({data:{organizationId,branchId:a.id,name:"Warehouse",code:"AW",type:"WAREHOUSE"}}),as=await db.location.create({data:{organizationId,branchId:a.id,name:"Showroom",code:"AS",type:"SHOWROOM"}}),bw=await db.location.create({data:{organizationId,branchId:b.id,name:"Warehouse",code:"BW",type:"WAREHOUSE"}}),bs=await db.location.create({data:{organizationId,branchId:b.id,name:"Showroom",code:"BS",type:"SHOWROOM"}});
 await db.organizationMembership.updateMany({where:{organizationId,userId:owner.userId},data:{defaultBranchId:a.id}});const s120=await db.size.create({data:{organizationId,code:"120",name:"120",sizeSystem:"HEIGHT"}}),s130=await db.size.create({data:{organizationId,code:"130",name:"130",sizeSystem:"HEIGHT"}});
 const snow=await db.product.create({data:{organizationId,name:"Белоснежка",internalCode:"SNOW",trackingMode:"SERIALIZED"}}),aurora=await db.product.create({data:{organizationId,name:"Аврора",internalCode:"AURORA",trackingMode:"SERIALIZED"}}),crown=await db.product.create({data:{organizationId,name:"Корона",internalCode:"CROWN",trackingMode:"BULK"}}),gloves=await db.product.create({data:{organizationId,name:"Перчатки",internalCode:"GLOVES",trackingMode:"BULK"}});
 const snow120=await db.productVariant.create({data:{organizationId,productId:snow.id,sizeId:s120.id,sku:"SNOW-120"}}),snow130=await db.productVariant.create({data:{organizationId,productId:snow.id,sizeId:s130.id,sku:"SNOW-130"}}),aurora120=await db.productVariant.create({data:{organizationId,productId:aurora.id,sizeId:s120.id,sku:"AURORA-120"}}),crownV=await db.productVariant.create({data:{organizationId,productId:crown.id,sizeId:s120.id,sku:"CROWN"}}),glovesV=await db.productVariant.create({data:{organizationId,productId:gloves.id,sizeId:s120.id,sku:"GLOVES"}});
 for(const v of [snow120,snow130,aurora120,crownV,glovesV])await db.productPrice.create({data:{organizationId,productVariantId:v.id,branchId:a.id,type:"RENTAL",amountMinor:BigInt(10000),currency:"KZT",validFrom:new Date("2026-01-01")}});
 const customer=await db.customer.create({data:{organizationId,customerNumber:"C-1",firstName:"Customer",status:"ACTIVE",createdByUserId:owner.userId}});return{o:organizationId,t:createTenantContext(organizationId),u:owner.userId,a,b,aw,as,bw,bs,snow120,snow130,aurora120,crownV,glovesV,customer};}

async function order(f:Awaited<ReturnType<typeof setup>>,serialId:string,bulk=false){const o=await createOrder(f.t,{branchId:f.a.id,customerId:f.customer.id,source:"CRM",rentalStart:date(10),rentalEnd:date(12),discountMinor:BigInt(0)},[{productVariantId:serialId,quantity:1,discountMinor:BigInt(0)},...(bulk?[{productVariantId:f.crownV.id,quantity:3,discountMinor:BigInt(0)}]:[])],{userId:f.u});await reserveOrder(f.t,o.id,{userId:f.u});const full=await db.order.findUniqueOrThrow({where:{id:o.id},include:{items:true}});return full;}

async function run(){await cleanup();const f=await setup("main"),x=await setup("foreign"),actor={userId:f.u};
 const receipts=await receiveSerialized(f.t,{variantId:f.snow120.id,branchId:f.a.id,locationId:f.aw.id,quantity:3,idempotencyKey:"snow-receipt"},actor);await receiveSerialized(f.t,{variantId:f.snow130.id,branchId:f.a.id,locationId:f.aw.id,quantity:2,idempotencyKey:"snow130-receipt"},actor);await receiveSerialized(f.t,{variantId:f.aurora120.id,branchId:f.a.id,locationId:f.aw.id,quantity:1,idempotencyKey:"aurora-receipt"},actor);pass("serialized receipt unique",new Set(receipts.flatMap(r=>[r.productInstanceId])).size===3&&await db.inventoryMovement.count({where:{organizationId:f.o,type:"RECEIPT",productInstanceId:{not:null}}})===6);
 const dress=await db.productInstance.findUniqueOrThrow({where:{id:receipts[0]!.productInstanceId!}});await transferSerialized(f.t,{instanceId:dress.id,fromBranchId:f.a.id,toBranchId:f.a.id,toLocationId:f.as.id,idempotencyKey:"dress-showroom"},actor);pass("serialized transfer",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).currentLocationId===f.as.id);
 await receiveBulk(f.t,{variantId:f.crownV.id,branchId:f.a.id,locationId:f.aw.id,quantity:20,idempotencyKey:"crown-receipt"},actor);await receiveBulk(f.t,{variantId:f.glovesV.id,branchId:f.a.id,locationId:f.aw.id,quantity:10,idempotencyKey:"gloves-receipt"},actor);await transferBulk(f.t,{variantId:f.crownV.id,fromBranchId:f.a.id,fromLocationId:f.aw.id,toBranchId:f.a.id,toLocationId:f.as.id,quantity:12,idempotencyKey:"crown-transfer"},actor);await transferBulk(f.t,{variantId:f.glovesV.id,fromBranchId:f.a.id,fromLocationId:f.aw.id,toBranchId:f.a.id,toLocationId:f.as.id,quantity:6,idempotencyKey:"gloves-transfer"},actor);const crownLevels=await db.stockLevel.findMany({where:{organizationId:f.o,productVariantId:f.crownV.id}});pass("bulk transfer total",crownLevels.reduce((n,v)=>n+v.quantity,0)===20&&crownLevels.some(v=>v.locationId===f.as.id&&v.quantity===12));
 const rental=await order(f,f.snow120.id,true),serializedItem=rental.items.find(i=>i.productVariantId===f.snow120.id)!,bulkItem=rental.items.find(i=>i.productVariantId===f.crownV.id)!;await assignInstanceByBarcode(f.t,rental.id,serializedItem.id,dress.barcode,actor);await confirmOrder(f.t,rental.id,actor);await markOrderReady(f.t,rental.id,actor);const bulkBefore=(await db.stockLevel.aggregate({where:{organizationId:f.o,productVariantId:f.crownV.id,branchId:f.a.id},_sum:{quantity:true}}))._sum.quantity??0;await issueOrder(f.t,rental.id,actor);pass("rental issue ledger",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).operationalStatus==="RENTED"&&await db.inventoryMovement.count({where:{organizationId:f.o,type:"RENTAL_ISSUE",sourceType:"CAPACITY_ALLOCATION"}})===2);pass("bulk issue once",((await db.stockLevel.aggregate({where:{organizationId:f.o,productVariantId:f.crownV.id,branchId:f.a.id},_sum:{quantity:true}}))._sum.quantity??0)===bulkBefore-3);
 const during=await startStocktake(f.t,{branchId:f.a.id,locationId:f.as.id,idempotencyKey:"during-rental"},actor);pass("rented excluded snapshot",await db.stocktakeExpectedItem.count({where:{sessionId:during.id,productInstanceId:dress.id}})===0);const snapBulk=await db.stocktakeBulkCount.findUniqueOrThrow({where:{sessionId_productVariantId:{sessionId:during.id,productVariantId:f.crownV.id}}}),showroomNow=await db.stockLevel.findFirstOrThrow({where:{organizationId:f.o,productVariantId:f.crownV.id,branchId:f.a.id,locationId:f.as.id}});pass("bulk snapshot on hand",snapBulk.expectedQuantity===showroomNow.quantity);await cancelStocktake(f.t,during.id,actor);pass("cancelled immutable",await rejects(()=>scanBarcode(f.t,during.id,dress.barcode,actor)));
 await receiveReturnByBarcode(f.t,dress.barcode,"GOOD","ok",actor);await returnBulkQuantity(f.t,rental.id,bulkItem.id,1,actor);await returnBulkQuantity(f.t,rental.id,bulkItem.id,2,actor);await completeReturnedOrder(f.t,rental.id,actor);pass("return restores inventory",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).operationalStatus==="AVAILABLE"&&((await db.stockLevel.aggregate({where:{organizationId:f.o,productVariantId:f.crownV.id,branchId:f.a.id},_sum:{quantity:true}}))._sum.quantity??0)===bulkBefore);const showroomRestored=(await db.stockLevel.findFirstOrThrow({where:{organizationId:f.o,productVariantId:f.crownV.id,branchId:f.a.id,locationId:f.as.id}})).quantity;
 const missingSession=await startStocktake(f.t,{branchId:f.a.id,locationId:f.as.id,idempotencyKey:"missing"},actor);await setBulkCount(f.t,missingSession.id,f.crownV.id,showroomRestored,actor);await setBulkCount(f.t,missingSession.id,f.glovesV.id,6,actor);await completeCount(f.t,missingSession.id,actor);const expected=await db.stocktakeExpectedItem.findFirstOrThrow({where:{sessionId:missingSession.id,productInstanceId:dress.id}});pass("missing no automatic loss",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).operationalStatus==="AVAILABLE");await resolveMissing(f.t,missingSession.id,expected.id,"MARK_LOST","not found",actor);await reconcileStocktake(f.t,missingSession.id,actor);pass("missing reconciled lost",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).operationalStatus==="LOST"&&await db.inventoryMovement.count({where:{organizationId:f.o,type:"LOSS",productInstanceId:dress.id}})===1);
 const foundSession=await startStocktake(f.t,{branchId:f.a.id,locationId:f.as.id,idempotencyKey:"found"},actor);const foundScan=await scanBarcode(f.t,foundSession.id,dress.barcode,actor);pass("lost unexpected",foundScan.classification==="UNEXPECTED");await setBulkCount(f.t,foundSession.id,f.crownV.id,showroomRestored,actor);await setBulkCount(f.t,foundSession.id,f.glovesV.id,6,actor);await completeCount(f.t,foundSession.id,actor);await resolveScan(f.t,foundSession.id,foundScan.id,"FOUND","physically found",actor);await reconcileStocktake(f.t,foundSession.id,actor);pass("found retains loss history",(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).operationalStatus==="AVAILABLE"&&await db.inventoryMovement.count({where:{organizationId:f.o,productInstanceId:dress.id,type:{in:["LOSS","FOUND"]}}})===2);
 const bulkSession=await startStocktake(f.t,{branchId:f.a.id,locationId:f.as.id,idempotencyKey:"bulk-adjust"},actor);const bcount=await db.stocktakeBulkCount.findUniqueOrThrow({where:{sessionId_productVariantId:{sessionId:bulkSession.id,productVariantId:f.crownV.id}}});await setBulkCount(f.t,bulkSession.id,f.crownV.id,bcount.expectedQuantity-2,actor);for(const e of await db.stocktakeExpectedItem.findMany({where:{sessionId:bulkSession.id}}))await scanBarcode(f.t,bulkSession.id,(await db.productInstance.findUniqueOrThrow({where:{id:e.productInstanceId}})).barcode,actor);await setBulkCount(f.t,bulkSession.id,f.glovesV.id,6,actor);await completeCount(f.t,bulkSession.id,actor);const beforeAdjust=(await db.stockLevel.findFirstOrThrow({where:{organizationId:f.o,productVariantId:f.crownV.id,locationId:f.as.id}})).quantity;await resolveBulk(f.t,bulkSession.id,bcount.id,true,"physical shortage",actor);await resolveBulk(f.t,bulkSession.id,bcount.id,true,"physical shortage",actor);await reconcileStocktake(f.t,bulkSession.id,actor);pass("bulk adjustment idempotent",(await db.stockLevel.findFirstOrThrow({where:{organizationId:f.o,productVariantId:f.crownV.id,locationId:f.as.id}})).quantity===beforeAdjust-2&&await db.inventoryMovement.count({where:{organizationId:f.o,idempotencyKey:`stocktake:${bulkSession.id}:bulk:${bcount.id}`}})===1);
 const stale=await startStocktake(f.t,{branchId:f.a.id,locationId:f.as.id,idempotencyKey:"stale-transfer"},actor);const staleExpected=await db.stocktakeExpectedItem.findFirstOrThrow({where:{sessionId:stale.id,productInstanceId:dress.id}});await transferSerialized(f.t,{instanceId:dress.id,fromBranchId:f.a.id,toBranchId:f.a.id,toLocationId:f.aw.id,idempotencyKey:"after-snapshot"},actor);await completeCount(f.t,stale.id,actor);pass("stale snapshot rejected",await rejects(()=>resolveMissing(f.t,stale.id,staleExpected.id,"MARK_LOST","stale",actor))&&(await db.productInstance.findUniqueOrThrow({where:{id:dress.id}})).currentLocationId===f.aw.id);
 const foreignSession=await startStocktake(x.t,{branchId:x.a.id,locationId:x.as.id,idempotencyKey:"x"},{userId:x.u});pass("cross tenant invisible",await rejects(()=>scanBarcode(x.t,foreignSession.id,dress.barcode,{userId:x.u})));requireInventoryPermission("SELLER","STOCKTAKE");pass("permissions",await rejects(async()=>requireInventoryPermission("SELLER","RECONCILE"))&&await rejects(async()=>requireInventoryPermission("CASHIER","STOCKTAKE")));
 const av=await getVariantAvailability({tenant:f.t,branchId:f.a.id,productVariantId:f.crownV.id,requestedFrom:date(20),requestedUntil:date(22)});pass("bulk capacity sane",av.availableCapacity>=0&&av.availableCapacity<=av.totalCapacity);const history=await getInventoryMovements(f.t,{search:dress.barcode,take:20});pass("movement history filtered bounded",history.length>0&&history.length<=21&&history.every(m=>m.organizationId===f.o));
 const integrity=await db.$queryRaw<Array<{negative:bigint;duplicate_levels:bigint;orphan_movements:bigint;bad_serial_qty:bigint;duplicate_scans:bigint;bulk_instances:bigint}>>`SELECT (SELECT count(*) FROM stock_levels WHERE organization_id=${f.o}::uuid AND quantity<0)::bigint negative,(SELECT count(*) FROM (SELECT product_variant_id,branch_id,location_id,count(*) FROM stock_levels WHERE organization_id=${f.o}::uuid GROUP BY 1,2,3 HAVING count(*)>1)x)::bigint duplicate_levels,(SELECT count(*) FROM inventory_movements m LEFT JOIN product_variants v ON v.id=m.product_variant_id WHERE m.organization_id=${f.o}::uuid AND v.id IS NULL)::bigint orphan_movements,(SELECT count(*) FROM inventory_movements WHERE organization_id=${f.o}::uuid AND product_instance_id IS NOT NULL AND abs(quantity)<>1)::bigint bad_serial_qty,(SELECT count(*) FROM (SELECT session_id,product_instance_id,count(*) FROM stocktake_scans WHERE organization_id=${f.o}::uuid GROUP BY 1,2 HAVING count(*)>1)x)::bigint duplicate_scans,(SELECT count(*) FROM product_instances i JOIN product_variants v ON v.id=i.product_variant_id JOIN products p ON p.id=v.product_id WHERE i.organization_id=${f.o}::uuid AND p.tracking_mode='BULK')::bigint bulk_instances`;pass("integrity audit",Object.values(integrity[0]!).every(v=>v===BigInt(0)));
}
run().then(()=>console.log("PASS Stage 8C warehouse E2E")).finally(async()=>{await cleanup();await db.$disconnect()}).catch(e=>{console.error(e);process.exitCode=1});
