import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { ensureDefaultPaymentMethods } from "../lib/finance/payment-methods";
import { getCustomerOutstandingBalance, getOrderDepositDetails, getOrderFinancialSummary } from "../lib/finance/queries";
import { receiveOrderDeposit, refundOrderDeposit, setOrderRequiredDeposit } from "../lib/finance/order-deposits";
import { acceptOrderPayment } from "../lib/finance/order-payments";
import { cancelOrder, confirmOrder } from "../lib/orders/management";

const organizations:string[]=[],users:string[]=[];let passed=0;
const ok=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);passed++};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
const message=async(fn:()=>Promise<unknown>)=>{try{await fn();return""}catch(error){return error instanceof Error?error.message:String(error)}};

async function cleanup(){if(!organizations.length)return;await db.$transaction(async tx=>{
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');
  await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');
  await tx.financialTransaction.deleteMany({where:{organizationId:{in:organizations}}});await tx.auditLog.deleteMany({where:{organizationId:{in:organizations}}});
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');
  await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');
  await tx.orderEvent.deleteMany({where:{organizationId:{in:organizations}}});await tx.capacityAllocation.deleteMany({where:{organizationId:{in:organizations}}});await tx.orderItem.deleteMany({where:{organizationId:{in:organizations}}});await tx.order.deleteMany({where:{organizationId:{in:organizations}}});await tx.customer.deleteMany({where:{organizationId:{in:organizations}}});
  await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:organizations}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:organizations}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:organizations}}});await tx.branch.deleteMany({where:{organizationId:{in:organizations}}});await tx.organization.deleteMany({where:{id:{in:organizations}}});await tx.user.deleteMany({where:{id:{in:users}}});
 },{maxWait:10000,timeout:30000})}

async function main(){await cleanup();
 const orgId=randomUUID(),otherOrgId=randomUUID(),ownerId=randomUUID(),sellerId=randomUUID();organizations.push(orgId,otherOrgId);users.push(ownerId,sellerId);
 await db.organization.createMany({data:[{id:orgId,name:"Stage 9B-2A",slug:`stage-9b-2a-${orgId.slice(0,8)}`},{id:otherOrgId,name:"Stage 9B-2A Other",slug:`stage-9b-2a-other-${orgId.slice(0,8)}`}]});
 const passwordHash=createHash("sha256").update(orgId).digest("hex");await db.user.createMany({data:[{id:ownerId,email:`stage9b2a-owner-${orgId}@test.invalid`,displayName:"Owner",passwordHash},{id:sellerId,email:`stage9b2a-seller-${orgId}@test.invalid`,displayName:"Seller",passwordHash}]});
 const a=await db.branch.create({data:{organizationId:orgId,name:"A",code:"A",city:"Test",timezone:"Asia/Qyzylorda"}}),b=await db.branch.create({data:{organizationId:orgId,name:"B",code:"B",city:"Test",timezone:"Asia/Qyzylorda"}}),foreignBranch=await db.branch.create({data:{organizationId:otherOrgId,name:"X",code:"X",city:"Test",timezone:"Asia/Qyzylorda"}});
 const owner=await db.organizationMembership.create({data:{organizationId:orgId,userId:ownerId,role:"OWNER",status:"ACTIVE",defaultBranchId:a.id}}),seller=await db.organizationMembership.create({data:{organizationId:orgId,userId:sellerId,role:"SELLER",status:"ACTIVE",defaultBranchId:a.id}});await db.membershipBranchAccess.create({data:{organizationId:orgId,membershipId:seller.id,branchId:a.id}});
 const customer=await db.customer.create({data:{organizationId:orgId,customerNumber:"C-2A",firstName:"Test"}}),foreignCustomer=await db.customer.create({data:{organizationId:otherOrgId,customerNumber:"C-X",firstName:"Other"}});
 const tenant=createTenantContext(orgId),foreignTenant=createTenantContext(otherOrgId),actor={userId:ownerId,membershipId:owner.id,role:"OWNER" as const},sellerActor={userId:sellerId,membershipId:seller.id,role:"SELLER" as const};
 const methods=await ensureDefaultPaymentMethods(tenant),foreignMethods=await ensureDefaultPaymentMethods(foreignTenant),cash=methods.find(x=>x.code==="CASH")!,kaspi=methods.find(x=>x.code==="KASPI")!;
 let seq=0;const make=(status:"DRAFT"|"RESERVED"|"CONFIRMED"|"COMPLETED"|"CANCELLED"="DRAFT",branchId=a.id,total=10000)=>db.order.create({data:{organizationId:orgId,orderNumber:`R-2A-${++seq}`,branchId,customerId:customer.id,type:"RENTAL",channel:"CRM",status,currency:"KZT",totalMinor:BigInt(total),balanceDueMinor:BigInt(total),completedAt:status==="COMPLETED"?new Date():undefined,cancelledAt:status==="CANCELLED"?new Date():undefined,cancellationReason:status==="CANCELLED"?"test":undefined}});
 const deposit=(orderId:string,amountMinor:bigint,methodId:string,key:string)=>receiveOrderDeposit(tenant,{orderId,amountMinor,paymentMethodId:methodId,idempotencyKey:key},actor);
 const refund=(orderId:string,amountMinor:bigint,key:string,confirmed=true)=>refundOrderDeposit(tenant,{orderId,amountMinor,reason:"Возврат залога",confirmed,idempotencyKey:key},actor);

 const defaults=await make();ok("A default zero",defaults.depositRequiredMinor===BigInt(0));ok("B DB negative rejected",await rejects(()=>db.order.update({where:{id:defaults.id},data:{depositRequiredMinor:BigInt(-1)}})));await setOrderRequiredDeposit(tenant,defaults.id,BigInt(20000),actor);ok("C requirement set",(await db.order.findUniqueOrThrow({where:{id:defaults.id}})).depositRequiredMinor===BigInt(20000));ok("E/F requirement no finance",await db.financialTransaction.count({where:{orderId:defaults.id}})===0);
 const draft=defaults;ok("G draft receipt rejected",await rejects(()=>deposit(draft.id,BigInt(1),cash.id,"draft")));const reserved=await make("RESERVED");await setOrderRequiredDeposit(tenant,reserved.id,BigInt(20000),actor);ok("H reserved receipt rejected",await rejects(()=>deposit(reserved.id,BigInt(1),cash.id,"reserved")));const cancelled=await make("CANCELLED");ok("J cancelled receipt rejected",await rejects(()=>deposit(cancelled.id,BigInt(1),cash.id,"cancelled")));const completed=await make("COMPLETED");ok("K completed receipt rejected",await rejects(()=>deposit(completed.id,BigInt(1),cash.id,"completed")));
 const order=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,order.id,BigInt(20000),actor);const beforeEvents=await db.orderEvent.count({where:{orderId:order.id}}),beforeInventory=await db.inventoryMovement.count({where:{organizationId:orgId}}),beforeAllocations=await db.capacityAllocation.count({where:{organizationId:orgId}});const first=await deposit(order.id,BigInt(10000),cash.id,"first");ok("I/L confirmed partial",first.kind==="DEPOSIT_RECEIVED");let state=await getOrderDepositDetails(tenant,order.id,actor);ok("S-U effects",first.cashEffectMinor===BigInt(10000)&&first.revenueEffectMinor===BigInt(0)&&first.obligationEffectMinor===BigInt(0));ok("V/W held shortage",state.heldDepositMinor===BigInt(10000)&&state.depositShortageMinor===BigInt(10000));ok("X shortage not debt",await getCustomerOutstandingBalance(tenant,customer.id,"KZT",actor)===BigInt(0));ok("D snapshot frozen",await rejects(()=>setOrderRequiredDeposit(tenant,order.id,BigInt(10000),actor)));
 const second=await deposit(order.id,BigInt(10000),kaspi.id,"second");state=await getOrderDepositDetails(tenant,order.id,actor);ok("M/N multiple exact",state.totalDepositReceivedMinor===BigInt(20000)&&state.heldDepositMinor===BigInt(20000)&&state.depositShortageMinor===BigInt(0));ok("O excess",await rejects(()=>deposit(order.id,BigInt(1),cash.id,"excess")));ok("P zero negative",await rejects(()=>deposit(order.id,BigInt(0),cash.id,"zero"))&&await rejects(()=>deposit(order.id,BigInt(-1),cash.id,"negative")));
 await db.paymentMethod.update({where:{id:cash.id},data:{isActive:false}});const inactiveOrder=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,inactiveOrder.id,BigInt(100),actor);ok("Q inactive method",await rejects(()=>deposit(inactiveOrder.id,BigInt(100),cash.id,"inactive")));await db.paymentMethod.update({where:{id:cash.id},data:{isActive:true}});ok("R foreign method",await rejects(()=>deposit(inactiveOrder.id,BigInt(100),foreignMethods[0]!.id,"foreign-method")));
 const partialRows=await refund(order.id,BigInt(15000),"refund-15");state=await getOrderDepositDetails(tenant,order.id,actor);ok("Z/AA partial oldest allocation",partialRows.length===2&&partialRows[0]!.amountMinor===BigInt(10000)&&partialRows[1]!.amountMinor===BigInt(5000)&&state.heldDepositMinor===BigInt(5000));ok("AB original methods",partialRows[0]!.paymentMethodId===cash.id&&partialRows[1]!.paymentMethodId===kaspi.id);ok("AC excess refund",await rejects(()=>refund(order.id,BigInt(5001),"refund-excess")));ok("AD confirmation",await rejects(()=>refund(order.id,BigInt(1),"refund-confirm",false)));
 const replayRows=await refund(order.id,BigInt(15000),"refund-15");ok("AG refund replay",replayRows.map(x=>x.id).join()===partialRows.map(x=>x.id).join());ok("refund payload conflict",await rejects(()=>refund(order.id,BigInt(14000),"refund-15")));
 const finalRefund=await refund(order.id,BigInt(5000),"refund-final");ok("Y full refund",finalRefund.length===1&&(await getOrderDepositDetails(tenant,order.id,actor)).heldDepositMinor===BigInt(0));
 const retryOrder=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,retryOrder.id,BigInt(1000),actor);const retryA=await deposit(retryOrder.id,BigInt(1000),cash.id,"receipt-retry"),retryB=await deposit(retryOrder.id,BigInt(1000),cash.id,"receipt-retry");ok("AE receipt replay",retryA.id===retryB.id);ok("AF receipt conflict",await rejects(()=>deposit(retryOrder.id,BigInt(999),cash.id,"receipt-retry")));
 const raceOrder=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,raceOrder.id,BigInt(10000),actor);const receiptRace=await Promise.allSettled([deposit(raceOrder.id,BigInt(10000),cash.id,"race-a"),deposit(raceOrder.id,BigInt(10000),cash.id,"race-b")]);ok("AH concurrent final receipt",receiptRace.filter(x=>x.status==="fulfilled").length===1&&(await getOrderDepositDetails(tenant,raceOrder.id,actor)).heldDepositMinor===BigInt(10000));const refundRace=await Promise.allSettled([refund(raceOrder.id,BigInt(10000),"refund-race-a"),refund(raceOrder.id,BigInt(10000),"refund-race-b")]);ok("AI concurrent refund",refundRace.filter(x=>x.status==="fulfilled").length===1&&(await getOrderDepositDetails(tenant,raceOrder.id,actor)).heldDepositMinor===BigInt(0));
 const cancelOrderId=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,cancelOrderId.id,BigInt(20000),actor);await deposit(cancelOrderId.id,BigInt(20000),cash.id,"cancel-deposit");ok("AJ held cancellation rejected",await rejects(()=>cancelOrder(tenant,cancelOrderId.id,"Отмена с залогом",actor)));await refund(cancelOrderId.id,BigInt(20000),"cancel-deposit-refund");await cancelOrder(tenant,cancelOrderId.id,"Отмена после возврата",actor);ok("AK/AL refunded cancellation",(await db.order.findUniqueOrThrow({where:{id:cancelOrderId.id}})).status==="CANCELLED");
 const receiptCancelOrder=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,receiptCancelOrder.id,BigInt(1000),actor);const receiptCancel=await Promise.allSettled([deposit(receiptCancelOrder.id,BigInt(1000),cash.id,"receipt-cancel"),cancelOrder(tenant,receiptCancelOrder.id,"Конкурентная отмена",actor)]);const receiptCancelState=await db.order.findUniqueOrThrow({where:{id:receiptCancelOrder.id}});ok("receipt versus cancellation consistent",receiptCancel.filter(x=>x.status==="fulfilled").length===1&&(receiptCancelState.status==="CANCELLED"||await getOrderDepositDetails(tenant,receiptCancelOrder.id,actor).then(x=>x.heldDepositMinor===BigInt(1000))));
 const refundCancelOrder=await make("CONFIRMED");await setOrderRequiredDeposit(tenant,refundCancelOrder.id,BigInt(1000),actor);await deposit(refundCancelOrder.id,BigInt(1000),cash.id,"refund-cancel-deposit");const refundCancel=await Promise.allSettled([refund(refundCancelOrder.id,BigInt(1000),"refund-cancel-refund"),cancelOrder(tenant,refundCancelOrder.id,"Отмена одновременно с возвратом",actor)]);const refundCancelState=await db.order.findUniqueOrThrow({where:{id:refundCancelOrder.id}}),refundCancelDeposit=await getOrderDepositDetails(tenant,refundCancelOrder.id,actor);ok("refund versus cancellation consistent",refundCancel.some(x=>x.status==="fulfilled")&&refundCancelDeposit.heldDepositMinor===BigInt(0)&&["CONFIRMED","CANCELLED"].includes(refundCancelState.status));
 await db.membershipPermissionOverride.createMany({data:["DEPOSIT_MANAGE","DEPOSIT_REFUND","DEPOSIT_VIEW"].map(permissionKey=>({organizationId:orgId,membershipId:seller.id,permissionKey,effect:"ALLOW" as const}))});const branchOrder=await make("CONFIRMED",b.id);await setOrderRequiredDeposit(tenant,branchOrder.id,BigInt(100),actor);ok("AM branch isolation",await rejects(()=>receiveOrderDeposit(tenant,{orderId:branchOrder.id,amountMinor:BigInt(100),paymentMethodId:cash.id,idempotencyKey:"branch"},sellerActor)));const foreignOrder=await db.order.create({data:{organizationId:otherOrgId,orderNumber:"R-X",branchId:foreignBranch.id,customerId:foreignCustomer.id,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT",depositRequiredMinor:BigInt(100)}});ok("AN tenant isolation",await rejects(()=>receiveOrderDeposit(tenant,{orderId:foreignOrder.id,amountMinor:BigInt(100),paymentMethodId:cash.id,idempotencyKey:"tenant"},actor)));
 await db.membershipPermissionOverride.deleteMany({where:{membershipId:seller.id,permissionKey:{in:["DEPOSIT_MANAGE","DEPOSIT_VIEW"]}}});const oracle=await message(()=>receiveOrderDeposit(tenant,{orderId:randomUUID(),amountMinor:BigInt(1),paymentMethodId:randomUUID(),idempotencyKey:"oracle"},sellerActor));ok("AO permission first",oracle.includes("Недостаточно прав")&&!oracle.includes("Заказ"));ok("AP view protected",await rejects(()=>getOrderDepositDetails(tenant,order.id,sellerActor)));
 ok("AQ audit attribution",await db.auditLog.count({where:{organizationId:orgId,actorMembershipId:owner.id,action:{in:["ORDER_REQUIRED_DEPOSIT_CHANGED","ORDER_DEPOSIT_REFUNDED","FINANCIAL_TRANSACTION_POSTED"]}}})>5);ok("AR no rental revenue",(await getOrderFinancialSummary(tenant,order.id,actor)).revenueMinor===BigInt(0));ok("AS no OrderEvent",await db.orderEvent.count({where:{orderId:order.id}})===beforeEvents);ok("AT inventory unchanged",await db.inventoryMovement.count({where:{organizationId:orgId}})===beforeInventory);ok("AU allocations unchanged",await db.capacityAllocation.count({where:{organizationId:orgId}})===beforeAllocations);
 const realistic=await make("RESERVED");await setOrderRequiredDeposit(tenant,realistic.id,BigInt(20000),actor);await confirmOrder(tenant,realistic.id,actor);await acceptOrderPayment(tenant,{orderId:realistic.id,amountMinor:BigInt(10000),paymentMethodId:kaspi.id,idempotencyKey:"real-rental"},actor);await deposit(realistic.id,BigInt(10000),cash.id,"real-dep-cash");await deposit(realistic.id,BigInt(10000),kaspi.id,"real-dep-kaspi");let realisticSummary=await getOrderFinancialSummary(tenant,realistic.id,actor);ok("realistic held",realisticSummary.revenueMinor===BigInt(10000)&&realisticSummary.cashMovementMinor===BigInt(30000)&&realisticSummary.heldDepositMinor===BigInt(20000)&&realisticSummary.outstandingMinor===BigInt(0));await refund(realistic.id,BigInt(20000),"real-refund");realisticSummary=await getOrderFinancialSummary(tenant,realistic.id,actor);ok("realistic refunded",realisticSummary.revenueMinor===BigInt(10000)&&realisticSummary.cashMovementMinor===BigInt(10000)&&realisticSummary.heldDepositMinor===BigInt(0)&&realisticSummary.outstandingMinor===BigInt(0));
 const security=await db.$queryRaw<Array<{tables:number;rls:number;anon:number;authenticated:number;policies:number}>>`SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p')) tables,(SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relrowsecurity) rls,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='anon') anon,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='authenticated') authenticated,(SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND roles && ARRAY['anon','authenticated','public']::name[]) policies`;
 ok("AV-AY RLS",security[0]!.tables===security[0]!.rls&&security[0]!.anon===0&&security[0]!.authenticated===0&&security[0]!.policies===0);
 await cleanup();ok("AZ cleanup",await db.organization.count({where:{slug:{startsWith:"stage-9b-2a-"}}})===0);console.log(`PASS Stage 9B-2A A-AZ (${passed} checks)`);
}
main().finally(async()=>{await cleanup();await db.$disconnect()}).catch(error=>{console.error(error);process.exitCode=1});
