import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { ensureDefaultPaymentMethods } from "../lib/finance/payment-methods";
import { acceptOrderPayment } from "../lib/finance/order-payments";
import { receiveOrderDeposit, refundOrderDeposit } from "../lib/finance/order-deposits";
import { assessOrderDamage, waiveOrderDamage, withholdOrderDepositForDamage } from "../lib/finance/order-damage";
import { getOrderReturnSettlement } from "../lib/finance/order-settlement";

const organizations:string[]=[],users:string[]=[];let checks=0;
const ok=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);checks++};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
async function cleanup(){const stale=await db.organization.findMany({where:{slug:{startsWith:"stage-9b-2c-"}},select:{id:true}}),ids=[...new Set([...organizations,...stale.map(row=>row.id)])];if(!ids.length)return;await db.$transaction(async tx=>{
 await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');await tx.financialTransaction.deleteMany({where:{organizationId:{in:ids}}});await tx.auditLog.deleteMany({where:{organizationId:{in:ids}}});await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');
 await tx.capacityAllocation.deleteMany({where:{organizationId:{in:ids}}});await tx.orderItem.deleteMany({where:{organizationId:{in:ids}}});await tx.order.deleteMany({where:{organizationId:{in:ids}}});await tx.customer.deleteMany({where:{organizationId:{in:ids}}});await tx.productInstance.deleteMany({where:{organizationId:{in:ids}}});await tx.productVariant.deleteMany({where:{organizationId:{in:ids}}});await tx.product.deleteMany({where:{organizationId:{in:ids}}});await tx.size.deleteMany({where:{organizationId:{in:ids}}});await tx.location.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:ids}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:ids}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:ids}}});await tx.branch.deleteMany({where:{organizationId:{in:ids}}});await tx.organization.deleteMany({where:{id:{in:ids}}});await tx.user.deleteMany({where:{id:{in:users}}});
 },{maxWait:10000,timeout:60000})}

async function main(){await cleanup();const organizationId=randomUUID(),otherId=randomUUID(),userId=randomUUID(),sellerId=randomUUID();organizations.push(organizationId,otherId);users.push(userId,sellerId);const passwordHash=createHash("sha256").update(organizationId).digest("hex");
 await db.organization.createMany({data:[{id:organizationId,name:"Stage 9B-2C",slug:`stage-9b-2c-${organizationId.slice(0,8)}`},{id:otherId,name:"Stage 9B-2C Other",slug:`stage-9b-2c-other-${organizationId.slice(0,8)}`} ]});await db.user.createMany({data:[{id:userId,email:`owner-${organizationId}@test.invalid`,displayName:"Owner",passwordHash},{id:sellerId,email:`seller-${organizationId}@test.invalid`,displayName:"Seller",passwordHash}]});
 const branch=await db.branch.create({data:{organizationId,name:"A",code:"A",city:"Test",timezone:"Asia/Qyzylorda"}}),branchB=await db.branch.create({data:{organizationId,name:"B",code:"B",city:"Test",timezone:"Asia/Qyzylorda"}}),otherBranch=await db.branch.create({data:{organizationId:otherId,name:"X",code:"X",city:"Test",timezone:"Asia/Qyzylorda"}}),location=await db.location.create({data:{organizationId,branchId:branch.id,name:"A",code:"A",type:"STORAGE_ZONE"}});const owner=await db.organizationMembership.create({data:{organizationId,userId,role:"OWNER",status:"ACTIVE",defaultBranchId:branch.id}}),seller=await db.organizationMembership.create({data:{organizationId,userId:sellerId,role:"SELLER",status:"ACTIVE",defaultBranchId:branch.id}});await db.membershipBranchAccess.create({data:{organizationId,membershipId:seller.id,branchId:branch.id}});
 const customer=await db.customer.create({data:{organizationId,customerNumber:"C-2C",firstName:"Test"}}),otherCustomer=await db.customer.create({data:{organizationId:otherId,customerNumber:"X",firstName:"Other"}}),size=await db.size.create({data:{organizationId,code:"M",name:"M"}}),product=await db.product.create({data:{organizationId,name:"Dress",internalCode:"D",trackingMode:"SERIALIZED"}}),variant=await db.productVariant.create({data:{organizationId,productId:product.id,sizeId:size.id,sku:"D-M"}});const instances:Array<{id:string}>=[];for(let i=0;i<14;i++)instances.push(await db.productInstance.create({data:{organizationId,productVariantId:variant.id,inventoryNumber:`2C-${i}`,barcode:`2C-${i}`,homeBranchId:branch.id,currentBranchId:branch.id,currentLocationId:location.id}}));let instanceIndex=0,sequence=0;
 const tenant=createTenantContext(organizationId),actor={userId,membershipId:owner.id,role:"OWNER" as const},sellerActor={userId:sellerId,membershipId:seller.id,role:"SELLER" as const},methods=await ensureDefaultPaymentMethods(tenant),cash=methods.find(row=>row.code==="CASH")!;
 async function order(count=1,orderBranch=branch.id){return db.order.create({data:{organizationId,orderNumber:`2C-${++sequence}`,branchId:orderBranch,customerId:customer.id,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT",totalMinor:BigInt(10000),balanceDueMinor:BigInt(10000),depositRequiredMinor:BigInt(20000),items:{create:Array.from({length:count},(_,i)=>({organizationId,productVariantId:variant.id,quantity:1,status:"RETURNED" as const,unitPriceMinor:BigInt(10000/count),lineTotalMinor:BigInt(10000/count),currency:"KZT",productNameSnapshot:"Dress",variantNameSnapshot:`M-${i}`,skuSnapshot:`D-${i}`}))}},include:{items:true}})}
 async function allocation(orderId:string,orderItemId:string,result:"GOOD"|"NEEDS_CLEANING"|"DAMAGED",returned=true,allocationBranch=branch.id){return db.capacityAllocation.create({data:{organizationId,orderId,orderItemId,productVariantId:variant.id,productInstanceId:instances[instanceIndex++]!.id,branchId:allocationBranch,quantity:1,sourceType:"ORDER",blockedFrom:new Date(),status:"ACTIVE",issuedAt:new Date(),issuedQuantity:1,returnedAt:returned?new Date():null,returnedQuantity:returned?1:0,returnInspectionResult:returned?result:null,returnNote:returned?"Осмотр":null}})}
 async function funded(o:{id:string}){await acceptOrderPayment(tenant,{orderId:o.id,amountMinor:BigInt(10000),paymentMethodId:cash.id,idempotencyKey:`pay-${o.id}`},actor);await receiveOrderDeposit(tenant,{orderId:o.id,amountMinor:BigInt(20000),paymentMethodId:cash.id,idempotencyKey:`dep-${o.id}`},actor)}
 async function refund(o:{id:string},amount=20000,key=`refund-${o.id}`){return refundOrderDeposit(tenant,{orderId:o.id,amountMinor:BigInt(amount),reason:"Финальный возврат залога",confirmed:true,idempotencyKey:key},actor)}

 const good=await order();await funded(good);await allocation(good.id,good.items[0]!.id,"GOOD");await db.order.update({where:{id:good.id},data:{status:"COMPLETED",completedAt:new Date()}});let state=await getOrderReturnSettlement(tenant,good.id,actor);ok("GOOD held deposit requires refund",state.state==="DEPOSIT_REFUND_REQUIRED"&&state.refundableDepositMinor===BigInt(20000));await refund(good);state=await getOrderReturnSettlement(tenant,good.id,actor);ok("GOOD refund settles",state.state==="SETTLED"&&state.heldDepositMinor===BigInt(0));
 const unresolved=await order();await funded(unresolved);const damaged=await allocation(unresolved.id,unresolved.items[0]!.id,"DAMAGED");await db.order.update({where:{id:unresolved.id},data:{status:"COMPLETED",completedAt:new Date()}});state=await getOrderReturnSettlement(tenant,unresolved.id,actor);ok("unresolved damage state",state.state==="DAMAGE_DECISION_REQUIRED"&&state.unresolvedDamageCount===1);ok("unresolved damage blocks refund",await rejects(()=>refund(unresolved)));await waiveOrderDamage(tenant,{allocationId:damaged.id,reason:"Ущерб клиенту не начисляется",idempotencyKey:"waive-unresolved"},actor);state=await getOrderReturnSettlement(tenant,unresolved.id,actor);ok("waiver permits settlement",state.state==="DEPOSIT_REFUND_REQUIRED"&&state.canRefundDeposit);await refund(unresolved);ok("waived damage settles",(await getOrderReturnSettlement(tenant,unresolved.id,actor)).state==="SETTLED");
 async function damageScenario(amount:number){const o=await order();await funded(o);const a=await allocation(o.id,o.items[0]!.id,"DAMAGED");await db.order.update({where:{id:o.id},data:{status:"COMPLETED",completedAt:new Date()}});const charge=await assessOrderDamage(tenant,{allocationId:a.id,amountMinor:BigInt(amount),reason:"Подтверждённый ущерб",idempotencyKey:`charge-${o.id}`},actor);if(amount===5000)ok("damage debt blocks premature deposit refund",await rejects(()=>refund(o,20000,`premature-${o.id}`)));const withheld=Math.min(amount,20000);if(withheld)await withholdOrderDepositForDamage(tenant,{damageChargeId:charge.id,amountMinor:BigInt(withheld),reason:"Удержание за ущерб",idempotencyKey:`withhold-${o.id}`},actor);return{o,charge,state:await getOrderReturnSettlement(tenant,o.id,actor)}}
 const less=await damageScenario(5000);ok("damage less than deposit",less.state.state==="DEPOSIT_REFUND_REQUIRED"&&less.state.heldDepositMinor===BigInt(15000));await refund(less.o,15000);ok("damage less final settlement",(await getOrderReturnSettlement(tenant,less.o.id,actor)).state==="SETTLED");const equal=await damageScenario(20000);ok("damage equal deposit settled",equal.state.state==="SETTLED"&&equal.state.heldDepositMinor===BigInt(0));const greater=await damageScenario(30000);ok("damage over deposit debt",greater.state.state==="DEBT_OUTSTANDING"&&greater.state.outstandingMinor===BigInt(10000));await acceptOrderPayment(tenant,{orderId:greater.o.id,amountMinor:BigInt(10000),paymentMethodId:cash.id,idempotencyKey:"greater-payment"},actor);ok("payment settles damage debt",(await getOrderReturnSettlement(tenant,greater.o.id,actor)).state==="SETTLED");
 const multiple=await order(2);await funded(multiple);const first=await allocation(multiple.id,multiple.items[0]!.id,"DAMAGED"),second=await allocation(multiple.id,multiple.items[1]!.id,"DAMAGED");await assessOrderDamage(tenant,{allocationId:first.id,amountMinor:BigInt(1000),reason:"Первый ущерб",idempotencyKey:"multi-one"},actor);state=await getOrderReturnSettlement(tenant,multiple.id,actor);ok("multiple damage each requires decision",state.unresolvedDamageCount===1&&state.state==="DAMAGE_DECISION_REQUIRED");await waiveOrderDamage(tenant,{allocationId:second.id,reason:"Второй ущерб прощён",idempotencyKey:"multi-two"},actor);ok("multiple damage all resolved",(await getOrderReturnSettlement(tenant,multiple.id,actor)).unresolvedDamageCount===0);
 const partial=await order(2);await funded(partial);await allocation(partial.id,partial.items[0]!.id,"GOOD");await allocation(partial.id,partial.items[1]!.id,"GOOD",false);state=await getOrderReturnSettlement(tenant,partial.id,actor);ok("partial return state",state.state==="RETURN_INCOMPLETE"&&!state.canRefundDeposit);ok("partial return blocks refund",await rejects(()=>refund(partial)));
 const raceOrder=await order();await funded(raceOrder);const raceDamage=await allocation(raceOrder.id,raceOrder.items[0]!.id,"DAMAGED");await db.order.update({where:{id:raceOrder.id},data:{status:"COMPLETED",completedAt:new Date()}});const race=await Promise.allSettled([refund(raceOrder,20000,"race-refund"),waiveOrderDamage(tenant,{allocationId:raceDamage.id,reason:"Решение в гонке",idempotencyKey:"race-waive"},actor)]);state=await getOrderReturnSettlement(tenant,raceOrder.id,actor);ok("refund versus decision serialized",race[1]!.status==="fulfilled"&&(race[0]!.status==="rejected"&&state.heldDepositMinor===BigInt(20000)||race[0]!.status==="fulfilled"&&state.heldDepositMinor===BigInt(0)));
 ok("finance does not mutate inventory",await db.inventoryMovement.count({where:{organizationId}})===0);ok("audit history retained",await db.auditLog.count({where:{organizationId,action:{in:["ORDER_DAMAGE_CHARGED","ORDER_DAMAGE_WAIVED","ORDER_DAMAGE_DEPOSIT_WITHHELD","ORDER_DEPOSIT_REFUNDED"]}}})>8);ok("finance viewer permission",await rejects(()=>getOrderReturnSettlement(tenant,good.id,sellerActor)));await db.membershipPermissionOverride.createMany({data:["PAYMENT_VIEW","DEPOSIT_VIEW"].map(permissionKey=>({organizationId,membershipId:seller.id,permissionKey,effect:"ALLOW" as const}))});const branchOrder=await order(1,branchB.id);ok("branch isolation",await rejects(()=>getOrderReturnSettlement(tenant,branchOrder.id,sellerActor)));const foreignOrder=await db.order.create({data:{organizationId:otherId,orderNumber:"X",branchId:otherBranch.id,customerId:otherCustomer.id,type:"RENTAL",channel:"CRM",status:"COMPLETED",currency:"KZT"}});ok("tenant isolation",await rejects(()=>getOrderReturnSettlement(tenant,foreignOrder.id,actor)));
 const security=await db.$queryRaw<Array<{tables:number;rls:number;anon:number;authenticated:number;policies:number}>>`SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p')) tables,(SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relrowsecurity) rls,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='anon') anon,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='authenticated') authenticated,(SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND roles && ARRAY['anon','authenticated','public']::name[]) policies`;ok("RLS security",security[0]!.tables===security[0]!.rls&&security[0]!.anon===0&&security[0]!.authenticated===0&&security[0]!.policies===0);
 await cleanup();ok("cleanup",await db.organization.count({where:{slug:{startsWith:"stage-9b-2c-"}}})===0);console.log(`PASS Stage 9B-2C (${checks} checks)`);
}
main().finally(async()=>{await cleanup();await db.$disconnect()}).catch(error=>{console.error(error);process.exitCode=1});
