import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dashboardPeriod } from "../lib/dashboard/queries";
import { evaluateReturnSettlement } from "../lib/finance/order-settlement";
import { allocateMinorUnits } from "../lib/catalog/economics";
import { effectsFor } from "../lib/finance/effects";

let checks = 0;
function ok(value: unknown, message: string) { assert.ok(value, message); checks++; }
function equal(actual: unknown, expected: unknown, message: string) { assert.deepEqual(actual, expected, message); checks++; }
const dashboardSource = readFileSync("lib/dashboard/queries.ts", "utf8"), pageSource = readFileSync("app/page.tsx", "utf8"), economicsSource = readFileSync("lib/catalog/economics.ts", "utf8"), settlementSource = readFileSync("lib/finance/order-settlement.ts", "utf8"), depositSource = readFileSync("lib/finance/order-deposits.ts", "utf8");

ok(!pageSource.includes("124 000"), "Home has no hardcoded revenue");
ok(!pageSource.includes("Алия"), "Home has no hardcoded customer");
ok(pageSource.includes("Быстрые действия"), "Quick Actions retained");
ok(pageSource.includes("Ближайшие"), "Upcoming retained");
ok(dashboardSource.includes('status: "ACTIVE", user: { status: "ACTIVE" }'), "active membership and user checked");
ok(dashboardSource.includes("organization: { status: \"ACTIVE\" }"), "active organization checked");
ok(dashboardSource.includes("userId: actor.userId"), "trusted actor identity checked");
ok(dashboardSource.includes("scopedIds: scoped.map"), "empty branch scope remains explicit");
ok(dashboardSource.includes("allActiveBranchesCovered"), "active coverage reported");
ok(dashboardSource.includes("historicalScopeComplete"), "historical scope separate");
ok(dashboardSource.includes("membership.role === \"OWNER\" ? branches"), "owner includes inactive branches");
ok(dashboardSource.includes("currentBranchId: { in: branchIds }"), "current inventory uses current branch");
ok(dashboardSource.includes("row.revenueEffectMinor"), "net revenue uses effect");
ok(dashboardSource.includes("revenueFamily(row)"), "revenue family classified");
ok(dashboardSource.includes('root.kind === "RENTAL_CHARGE"'), "rental charge family");
ok(dashboardSource.includes('root.kind === "DAMAGE_CHARGE"'), "damage family");
ok(dashboardSource.includes('root.kind === "SALE_CHARGE"'), "sale/other family");
ok(dashboardSource.includes('row.kind === "REVERSAL" ? row.reversalOf'), "reversal uses original family");
ok(dashboardSource.includes("row.occurredAt >= period.rangeStart"), "current transaction period uses row timestamp");
ok(dashboardSource.includes("CROSS_CONTEXT_REVERSAL"), "cross-context reversal diagnosed");
ok(dashboardSource.includes("historicalReversals"), "historical reversal integrity checked");
equal(effectsFor("DISCOUNT", BigInt(20)).revenueEffectMinor, -BigInt(20), "discount once");
equal(effectsFor("PAYMENT_RECEIVED", BigInt(20)).revenueEffectMinor, BigInt(0), "payment not revenue");
equal(effectsFor("CUSTOMER_REFUND", BigInt(20)).revenueEffectMinor, BigInt(0), "refund not revenue");
equal(effectsFor("CUSTOMER_REFUND", BigInt(20)).cashEffectMinor, -BigInt(20), "refund cash separate");
equal(effectsFor("DEPOSIT_RECEIVED", BigInt(20)).revenueEffectMinor, BigInt(0), "deposit not revenue");
equal(effectsFor("DEPOSIT_WITHHELD", BigInt(20)).cashEffectMinor, BigInt(0), "withholding not cash");
equal(effectsFor("DEPOSIT_WITHHELD", BigInt(20)).revenueEffectMinor, BigInt(0), "withholding not damage revenue");
equal(effectsFor("PAYMENT_RECEIVED", BigInt(20)).obligationEffectMinor, -BigInt(20), "payment reduces obligation");
ok(dashboardSource.includes('by: ["orderId", "customerId", "branchId", "currency"]'), "balance buckets preserve contexts");
ok(dashboardSource.includes("obligation > ZERO ? debt : credits"), "debt and credit separated");
ok(dashboardSource.includes("deposit > ZERO"), "held deposits positive buckets only");
ok(dashboardSource.includes("NEGATIVE_DEPOSIT"), "negative deposits diagnosed");
ok(dashboardSource.includes("FUTURE_FINANCIAL_TRANSACTION"), "future finance diagnosed");
ok(dashboardSource.includes("totalAcquisitionCostMinor"), "receipt exact total used");
ok(dashboardSource.includes("purchaseReceipt: { branchId"), "receipt branch used");
ok(dashboardSource.includes("receivedAt: { gte"), "receipt receivedAt used");
ok(!dashboardSource.includes("unitAcquisitionCostMinor"), "acquisition not reconstructed from unit cost");
ok(dashboardSource.includes("remaining = Math.max(commercial - issued"), "planned issue checks remaining quantity");
ok(dashboardSource.includes("order.readyAt ? \"READY_NOT_ISSUED\""), "readiness uses readyAt");
ok(dashboardSource.includes('type: { in: ["RENTAL_ISSUE", "RENTAL_RETURN"] }'), "physical movements canonical");
ok(dashboardSource.includes("Math.abs(movement.quantity)"), "physical movement quantity used");
ok(dashboardSource.includes("issuedOrders.add(order.id)"), "distinct issued orders");
ok(dashboardSource.includes("returnedOrders.add(order.id)"), "distinct returned orders");
ok(dashboardSource.includes("issued - returned"), "active quantity derived");
ok(dashboardSource.includes("returned > 0 && outstanding > 0"), "partial return derived");
ok(dashboardSource.includes("deadline < now"), "overdue requires elapsed deadline");
ok(!dashboardSource.includes("movement row count"), "no row-count physical metric");
ok(dashboardSource.includes("returnInspectionResult === \"DAMAGED\""), "damage decisions based on inspection");
ok(dashboardSource.includes("DEBT_AFTER_RETURN"), "post-return debt alert");
ok(dashboardSource.includes("DEPOSIT_REVIEW_REQUIRED"), "deposit review alert");
ok(settlementSource.includes("evaluateReturnSettlement"), "shared settlement evaluator exists");
ok(depositSource.includes("evaluateReturnSettlement"), "write flow reuses evaluator");
const baseSettlement = { orderStatus: "COMPLETED", issuedQuantity: 1, returnedQuantity: 1, unresolvedDamageCount: 0, outstandingMinor: BigInt(0), heldDepositMinor: BigInt(100), damageChargeMinor: BigInt(0), damageWithheldMinor: BigInt(0), activeDamageChargeCount: 0 };
ok(evaluateReturnSettlement(baseSettlement).canRefundDeposit, "completed returned order can refund");
ok(!evaluateReturnSettlement({ ...baseSettlement, orderStatus: "RETURNED" }).canRefundDeposit, "unsupported status cannot refund");
ok(!evaluateReturnSettlement({ ...baseSettlement, unresolvedDamageCount: 1 }).canRefundDeposit, "unresolved damage blocks refund");
ok(!evaluateReturnSettlement({ ...baseSettlement, outstandingMinor: BigInt(1), activeDamageChargeCount: 1 }).canRefundDeposit, "active damage debt blocks refund");
ok(evaluateReturnSettlement({ ...baseSettlement, orderStatus: "CONFIRMED", issuedQuantity: 0, returnedQuantity: 0 }).refundPhysicalEligible, "pre-issue confirmed refund eligibility preserved");
ok(dashboardSource.includes("MAINTENANCE_CONTEXT_MISSING"), "maintenance mismatch warning");
ok(dashboardSource.includes('operationalStatus: { in: ["CLEANING", "REPAIR", "LOST"] }'), "maintenance and lost states loaded");
ok(economicsSource.includes("getProductEconomicsSummariesWithClient"), "batch economics entry point");
ok(dashboardSource.includes("getProductEconomicsSummariesWithClient"), "Dashboard uses canonical economics module");
ok(!dashboardSource.includes("getProductEconomics("), "no per-product public economics call");
ok(economicsSource.includes("tx.product.findMany"), "batch products loaded once");
ok(economicsSource.includes("order.items.map"), "all order items weighted before ranking");
ok(dashboardSource.includes(".slice(0, 10)"), "Top N applied to completed summaries");
ok(dashboardSource.includes("productBlockLifetime: true"), "Product block marked lifetime");
ok(pageSource.includes("Экономика за всё время"), "lifetime label rendered");
ok(pageSource.includes("Окупаемость недоступна"), "incomplete payback hidden");
ok(dashboardSource.includes("financeDashboard && access.has(\"FINANCE_MARGIN_VIEW\")"), "margin gate combined");
ok(dashboardSource.includes("financeDashboard && access.has(\"PAYMENT_VIEW\")"), "payment gate combined");
ok(dashboardSource.includes("financeDashboard && access.has(\"CUSTOMER_BALANCE_VIEW\")"), "balance gate combined");
ok(dashboardSource.includes("financeDashboard && access.has(\"DEPOSIT_VIEW\")"), "deposit gate combined");
ok(dashboardSource.includes("financeDashboard && access.has(\"FINANCE_PURCHASE_COST_VIEW\")"), "acquisition gate combined");
ok(!dashboardSource.includes("REPORT_FINANCE_VIEW"), "report permission does not bypass fields");
ok(dashboardSource.includes("visibleFinancialWarnings"), "financial warnings filtered");
ok(dashboardSource.includes("quickActions"), "quick actions permission projected");
ok(dashboardSource.includes(".slice(0, 10) : []"), "Upcoming limited after stable ordering");
ok(dashboardSource.includes("branchRows"), "branch comparison filtered from scoped rows");

const astana = "Asia/Almaty", now = new Date("2026-03-31T07:15:30.000Z");
const today = dashboardPeriod({ preset: "TODAY" }, astana, now);
equal(today.rangeStart.toISOString(), "2026-03-30T19:00:00.000Z", "today local midnight");
equal(today.rangeEnd.toISOString(), now.toISOString(), "today ends now");
equal(today.comparisonStart.toISOString(), "2026-03-29T19:00:00.000Z", "yesterday local midnight");
equal(today.comparisonEnd.toISOString(), "2026-03-30T07:15:30.000Z", "today comparison elapsed cutoff");
const seven = dashboardPeriod({ preset: "SEVEN_DAYS" }, astana, now);
equal((seven.rangeEnd.getTime() - seven.rangeStart.getTime()) / 86_400_000, 6.510763888888889, "seven-day current elapsed window");
ok(seven.comparisonEnd > seven.comparisonStart, "seven-day comparison valid");
const month = dashboardPeriod({ preset: "THIS_MONTH" }, astana, now);
ok(!month.comparisonCoverageComparable, "31 vs February marked unequal");
equal(month.comparisonEnd.toISOString(), month.rangeStart.toISOString(), "missing previous day clamps to month end");
const leap = dashboardPeriod({ preset: "THIS_MONTH" }, astana, new Date("2024-02-29T07:00:00Z"));
ok(leap.rangeStart < leap.rangeEnd, "leap February supported");
const custom = dashboardPeriod({ preset: "CUSTOM", start: "2026-04-01", end: "2026-04-03" }, astana, now);
equal((custom.rangeEnd.getTime() - custom.rangeStart.getTime()) / 86_400_000, 3, "custom is end-date inclusive via half-open boundary");
equal(custom.comparisonEnd.toISOString(), custom.rangeStart.toISOString(), "custom comparison adjacent");
const exact = allocateMinorUnits(BigInt(10), [{ id: "b", weight: BigInt(1) }, { id: "a", weight: BigInt(1) }, { id: "c", weight: BigInt(1) }]);
equal([...exact.allocations.values()].reduce((s, x) => s + x, BigInt(0)), BigInt(10), "exact money allocation");
equal(exact.allocations.get("c"), BigInt(4), "deterministic remainder");
ok(dashboardSource.includes('isolationLevel: "RepeatableRead"'), "consistent snapshot");
ok(dashboardSource.includes("const now = input.now ?? new Date()"), "deterministic now");
ok(!dashboardSource.includes(".create("), "Dashboard reader has no creates");
ok(!dashboardSource.includes(".update("), "Dashboard reader has no updates");
ok(!dashboardSource.includes(".delete("), "Dashboard reader has no deletes");
ok(!dashboardSource.includes("Promise.all(products.map"), "no per-product concurrent query fanout");

console.log(`PASS Stage 9D targeted (${checks} checks)`);
