import "dotenv/config";
import {createHash,randomUUID} from "node:crypto";
import {db} from "../lib/db";
import {defaultHasPermission,PERMISSION_REGISTRY,type PermissionKey} from "../lib/permissions/registry";
import {hasPermission} from "../lib/permissions/effective";
import {setPermissionOverride} from "../lib/permissions/management";
import {createTenantContext} from "../lib/tenant/context";
const leads=(Object.keys(PERMISSION_REGISTRY)as PermissionKey[]).filter(k=>k.startsWith("LEAD_"));
const check=(v:unknown,m:string)=>{if(!v)throw new Error(m)};
async function main(){const organizationId=randomUUID(),ownerId=randomUUID(),sellerId=randomUUID();try{await db.organization.create({data:{id:organizationId,name:"Lead permission test",slug:`stage-8e-a-leads-${organizationId.slice(0,8)}`}});const passwordHash=createHash("sha256").update(organizationId).digest("hex");await db.user.createMany({data:[{id:ownerId,email:`owner-${organizationId}@test.invalid`,displayName:"Owner",passwordHash},{id:sellerId,email:`seller-${organizationId}@test.invalid`,displayName:"Seller",passwordHash}]});const owner=await db.organizationMembership.create({data:{organizationId,userId:ownerId,role:"OWNER",status:"ACTIVE"}}),seller=await db.organizationMembership.create({data:{organizationId,userId:sellerId,role:"SELLER",status:"ACTIVE"}}),tenant=createTenantContext(organizationId),ownerCtx={organizationId,membershipId:owner.id,role:"OWNER"as const},sellerCtx={organizationId,membershipId:seller.id,role:"SELLER"as const};check(leads.length===6&&leads.every(k=>defaultHasPermission("OWNER",k)),"OWNER Lead defaults");check(leads.every(k=>defaultHasPermission("DIRECTOR",k)),"DIRECTOR Lead defaults");check(["LEAD_VIEW","LEAD_CREATE","LEAD_EDIT","LEAD_CLOSE","LEAD_CONVERT_TO_ORDER"].every(k=>defaultHasPermission("SELLER",k as PermissionKey))&&!defaultHasPermission("SELLER","LEAD_ASSIGN"),"SELLER Lead defaults");check(leads.every(k=>!defaultHasPermission("CASHIER",k)),"CASHIER Lead defaults");await setPermissionOverride(tenant,seller.id,"LEAD_ASSIGN","ALLOW",{userId:ownerId,membershipId:owner.id,role:"OWNER"});check(await hasPermission(sellerCtx,"LEAD_ASSIGN"),"Seller ALLOW");await setPermissionOverride(tenant,seller.id,"LEAD_VIEW","DENY",{userId:ownerId,membershipId:owner.id,role:"OWNER"});check(!await hasPermission(sellerCtx,"LEAD_VIEW"),"Seller DENY");check(await hasPermission(ownerCtx,"LEAD_VIEW")&&await hasPermission(ownerCtx,"LEAD_ASSIGN"),"OWNER invariant");console.log("PASS Stage 8E-A Lead permissions (7 checks)")}finally{await db.organization.deleteMany({where:{id:organizationId}});await db.user.deleteMany({where:{id:{in:[ownerId,sellerId]}}})}}
main().finally(()=>db.$disconnect()).catch(e=>{console.error(e);process.exitCode=1});
