import "dotenv/config";
import { db } from "../lib/db";

async function main(){
 const organizations=(await db.organization.findMany({where:{slug:{startsWith:"stage-9h-a-"}},select:{id:true}})).map(x=>x.id);if(!organizations.length){console.log("Stage 9H-A cleanup: no fixtures");return;}
 const candidates=await db.organizationMembership.findMany({where:{organizationId:{in:organizations}},select:{userId:true}}),users=(await db.user.findMany({where:{id:{in:[...new Set(candidates.map(x=>x.userId))]},email:{endsWith:"@test.invalid"},memberships:{every:{organizationId:{in:organizations}}}},select:{id:true}})).map(x=>x.id);
 await db.$transaction(async tx=>{await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');await tx.auditLog.deleteMany({where:{organizationId:{in:organizations}}});await tx.financialTransaction.deleteMany({where:{organizationId:{in:organizations}}});await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');await tx.order.deleteMany({where:{organizationId:{in:organizations}}});await tx.customer.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:organizations}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:organizations}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:organizations}}});await tx.branch.deleteMany({where:{organizationId:{in:organizations}}});await tx.organization.deleteMany({where:{id:{in:organizations}}});await tx.user.deleteMany({where:{id:{in:users}}});},{maxWait:10000,timeout:60000});console.log(`Stage 9H-A cleanup: removed ${organizations.length} fixture organizations`);
}
main().finally(()=>db.$disconnect()).catch(error=>{console.error(error);process.exitCode=1});
