import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { ensureDefaultPaymentMethods } from "../lib/finance/payment-methods";
import { receiveOrderDeposit, refundOrderDeposit } from "../lib/finance/order-deposits";
import { assessOrderDamage, waiveOrderDamage, withholdOrderDepositForDamage } from "../lib/finance/order-damage";
import { acceptOrderPayment } from "../lib/finance/order-payments";
import { getOrderDamageDetails, getOrderFinancialSummary } from "../lib/finance/queries";

const organizations:string[]=[],users:string[]=[];let passed=0;
const ok=(name:string,value:unknown)=>{if(!value)throw new Error(`FAIL ${name}`);passed++};
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false}catch{return true}};
async function cleanup(){const stale=await db.organization.findMany({where:{slug:{startsWith:"stage-9b-2b-"}},select:{id:true}});const ids=[...new Set([...organizations,...stale.map(x=>x.id)])];if(!ids.length)return;await db.$transaction(async tx=>{
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"');
  await tx.financialTransaction.deleteMany({where:{organizationId:{in:ids}}});await tx.auditLog.deleteMany({where:{organizationId:{in:ids}}});
  await tx.$executeRawUnsafe('ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"');await tx.$executeRawUnsafe('ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"');
  await tx.capacityAllocation.deleteMany({where:{organizationId:{in:ids}}});await tx.orderEvent.deleteMany({where:{organizationId:{in:ids}}});await tx.orderItem.deleteMany({where:{organizationId:{in:ids}}});await tx.order.deleteMany({where:{organizationId:{in:ids}}});await tx.customer.deleteMany({where:{organizationId:{in:ids}}});await tx.productInstance.deleteMany({where:{organizationId:{in:ids}}});await tx.productVariant.deleteMany({where:{organizationId:{in:ids}}});await tx.product.deleteMany({where:{organizationId:{in:ids}}});await tx.size.deleteMany({where:{organizationId:{in:ids}}});await tx.location.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:ids}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:ids}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:ids}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:ids}}});await tx.branch.deleteMany({where:{organizationId:{in:ids}}});await tx.organization.deleteMany({where:{id:{in:ids}}});await tx.user.deleteMany({where:{id:{in:users}}});
 },{maxWait:10000,timeout:60000})}

async function main(){await cleanup();const organizationId=randomUUID(),otherId=randomUUID(),ownerId=randomUUID(),sellerId=randomUUID();organizations.push(organizationId,otherId);users.push(ownerId,sellerId);
 await db.organization.createMany({data:[{id:organizationId,name:"Stage 9B-2B",slug:`stage-9b-2b-${organizationId.slice(0,8)}`},{id:otherId,name:"Stage 9B-2B Other",slug:`stage-9b-2b-other-${organizationId.slice(0,8)}`} ]});const hash=createHash("sha256").update(organizationId).digest("hex");await db.user.createMany({data:[{id:ownerId,email:`9b2b-owner-${organizationId}@test.invalid`,displayName:"Owner",passwordHash:hash},{id:sellerId,email:`9b2b-seller-${organizationId}@test.invalid`,displayName:"Seller",passwordHash:hash}]});
 const branch=await db.branch.create({data:{organizationId,name:"A",code:"A",city:"Test",timezone:"Asia/Qyzylorda"}}),branchB=await db.branch.create({data:{organizationId,name:"B",code:"B",city:"Test",timezone:"Asia/Qyzylorda"}}),otherBranch=await db.branch.create({data:{organizationId:otherId,name:"X",code:"X",city:"Test",timezone:"Asia/Qyzylorda"}});const location=await db.location.create({data:{organizationId,branchId:branch.id,name:"A",code:"A",type:"STORAGE_ZONE"}});
 const owner=await db.organizationMembership.create({data:{organizationId,userId:ownerId,role:"OWNER",status:"ACTIVE",defaultBranchId:branch.id}}),seller=await db.organizationMembership.create({data:{organizationId,userId:sellerId,role:"SELLER",status:"ACTIVE",defaultBranchId:branch.id}});await db.membershipBranchAccess.create({data:{organizationId,membershipId:seller.id,branchId:branch.id}});const customer=await db.customer.create({data:{organizationId,customerNumber:"D-1",firstName:"Damage"}}),otherCustomer=await db.customer.create({data:{organizationId:otherId,customerNumber:"X-1",firstName:"Other"}});
 const size=await db.size.create({data:{organizationId,code:"M",name:"M"}}),product=await db.product.create({data:{organizationId,name:"Dress",internalCode:"D",trackingMode:"SERIALIZED"}}),variant=await db.productVariant.create({data:{organizationId,productId:product.id,sizeId:size.id,sku:"D-M"}});const instances:Awaited<ReturnType<typeof db.productInstance.create>>[]=[];for(let i=1;i<=5;i++)instances.push(await db.productInstance.create({data:{organizationId,productVariantId:variant.id,inventoryNumber:`D-${i}`,barcode:`DAMAGE-${i}`,homeBranchId:branch.id,currentBranchId:branch.id,currentLocationId:location.id,operationalStatus:"REPAIR"}}));let instanceIndex=0;
 const tenant=createTenantContext(organizationId),actor={userId:ownerId,membershipId:owner.id,role:"OWNER" as const},sellerActor={userId:sellerId,membershipId:seller.id,role:"SELLER" as const};const methods=await ensureDefaultPaymentMethods(tenant),cash=methods.find(x=>x.code==="CASH")!,kaspi=methods.find(x=>x.code==="KASPI")!;
 let seq=0;const makeOrder=async(branchId=branch.id,cust=customer.id)=>db.order.create({data:{organizationId,orderNumber:`D-${++seq}`,branchId,customerId:cust,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT",totalMinor:BigInt(10000),balanceDueMinor:BigInt(10000),depositRequiredMinor:BigInt(20000),items:{create:{organizationId,productVariantId:variant.id,quantity:1,status:"RETURNED",unitPriceMinor:BigInt(10000),lineTotalMinor:BigInt(10000),currency:"KZT",productNameSnapshot:"Dress",variantNameSnapshot:"M",skuSnapshot:"D-M"}}},include:{items:true}});const makeDamage=async(orderId:string,productInstanceId:string|null=instances[instanceIndex++]!.id)=>{const orderItem=await db.orderItem.findFirstOrThrow({where:{organizationId,orderId},include:{order:{select:{branchId:true}}}});return db.capacityAllocation.create({data:{organizationId,orderId,orderItemId:orderItem.id,productVariantId:variant.id,productInstanceId,branchId:orderItem.order.branchId,quantity:1,sourceType:"ORDER",blockedFrom:new Date(),status:"ACTIVE",issuedAt:new Date(),issuedQuantity:1,returnedAt:new Date(),returnedQuantity:1,returnInspectionResult:"DAMAGED",returnNote:"Разрыв ткани"}})};
 const order=await makeOrder(),allocation=await makeDamage(order.id);ok("physical damage has no automatic charge",await db.financialTransaction.count({where:{orderId:order.id,kind:"DAMAGE_CHARGE"}})===0);await acceptOrderPayment(tenant,{orderId:order.id,amountMinor:BigInt(10000),paymentMethodId:kaspi.id,idempotencyKey:"rental-paid"},actor);await receiveOrderDeposit(tenant,{orderId:order.id,amountMinor:BigInt(10000),paymentMethodId:cash.id,idempotencyKey:"dep-cash"},actor);await receiveOrderDeposit(tenant,{orderId:order.id,amountMinor:BigInt(10000),paymentMethodId:kaspi.id,idempotencyKey:"dep-kaspi"},actor);
 ok("amount validation",await rejects(()=>assessOrderDamage(tenant,{allocationId:allocation.id,amountMinor:BigInt(0),reason:"Ущерб",idempotencyKey:"bad-amount"},actor)));ok("reason validation",await rejects(()=>assessOrderDamage(tenant,{allocationId:allocation.id,amountMinor:BigInt(1),reason:"x",idempotencyKey:"bad-reason"},actor)));
 const charge=await assessOrderDamage(tenant,{allocationId:allocation.id,amountMinor:BigInt(30000),reason:"Серьёзный разрыв ткани",idempotencyKey:"damage-30"},actor);const replay=await assessOrderDamage(tenant,{allocationId:allocation.id,amountMinor:BigInt(30000),reason:"Серьёзный разрыв ткани",idempotencyKey:"damage-30"},actor);ok("explicit charge effects",charge.id===replay.id&&charge.obligationEffectMinor===BigInt(30000)&&charge.revenueEffectMinor===BigInt(30000)&&charge.cashEffectMinor===BigInt(0));ok("duplicate decision protected",await rejects(()=>assessOrderDamage(tenant,{allocationId:allocation.id,amountMinor:BigInt(1),reason:"Другая оценка",idempotencyKey:"damage-other"},actor)));
 const withheld=await withholdOrderDepositForDamage(tenant,{damageChargeId:charge.id,amountMinor:BigInt(20000),reason:"Удержание за разрыв",idempotencyKey:"withhold-20"},actor);ok("multiple receipts oldest first",withheld.length===2&&withheld[0]!.relatedTransactionId!==withheld[1]!.relatedTransactionId);ok("withholding effects",withheld.every(x=>x.cashEffectMinor===BigInt(0)&&x.revenueEffectMinor===BigInt(0))&&withheld.reduce((s,x)=>s+x.depositEffectMinor,BigInt(0))===BigInt(-20000));ok("damage read model",(await getOrderDamageDetails(tenant,order.id,actor)).items[0]?.charge?.settledMinor===BigInt(20000));ok("withhold replay",(await withholdOrderDepositForDamage(tenant,{damageChargeId:charge.id,amountMinor:BigInt(20000),reason:"Удержание за разрыв",idempotencyKey:"withhold-20"},actor)).map(x=>x.id).join()===withheld.map(x=>x.id).join());ok("withhold conflict",await rejects(()=>withholdOrderDepositForDamage(tenant,{damageChargeId:charge.id,amountMinor:BigInt(19999),reason:"Удержание за разрыв",idempotencyKey:"withhold-20"},actor)));ok("cannot over-withhold",await rejects(()=>withholdOrderDepositForDamage(tenant,{damageChargeId:charge.id,amountMinor:BigInt(1),reason:"Сверх ущерба",idempotencyKey:"withhold-extra"},actor)));
 await acceptOrderPayment(tenant,{orderId:order.id,amountMinor:BigInt(10000),paymentMethodId:cash.id,idempotencyKey:"damage-payment"},actor);const summary=await getOrderFinancialSummary(tenant,order.id,actor);ok("realistic 10+30 invariant",summary.revenueMinor===BigInt(40000)&&summary.outstandingMinor===BigInt(0)&&summary.heldDepositMinor===BigInt(0)&&summary.cashMovementMinor===BigInt(40000));
 const waiveOrder=await makeOrder(),waiveAllocation=await makeDamage(waiveOrder.id);const waiver=await waiveOrderDamage(tenant,{allocationId:waiveAllocation.id,reason:"Косметический дефект, оплату не берём",idempotencyKey:"waive"},actor);ok("waiver is audit only",waiver.action==="ORDER_DAMAGE_WAIVED"&&await db.financialTransaction.count({where:{orderId:waiveOrder.id,kind:"DAMAGE_CHARGE"}})===0);ok("waiver replay",(await waiveOrderDamage(tenant,{allocationId:waiveAllocation.id,reason:"Косметический дефект, оплату не берём",idempotencyKey:"waive"},actor)).id===waiver.id);ok("charge after waiver blocked",await rejects(()=>assessOrderDamage(tenant,{allocationId:waiveAllocation.id,amountMinor:BigInt(1000),reason:"Передумали начислить",idempotencyKey:"after-waive"},actor)));
 ok("permission first charge",await rejects(()=>assessOrderDamage(tenant,{allocationId:randomUUID(),amountMinor:BigInt(1),reason:"Проверка доступа",idempotencyKey:"seller-charge"},sellerActor)));ok("permission first withhold",await rejects(()=>withholdOrderDepositForDamage(tenant,{damageChargeId:randomUUID(),amountMinor:BigInt(1),reason:"Проверка доступа",idempotencyKey:"seller-withhold"},sellerActor)));
 const branchOrder=await makeOrder(branchB.id),branchAllocation=await makeDamage(branchOrder.id);await db.membershipPermissionOverride.createMany({data:[{organizationId,membershipId:seller.id,permissionKey:"DAMAGE_ASSESS",effect:"ALLOW"},{organizationId,membershipId:seller.id,permissionKey:"DEPOSIT_WITHHOLD",effect:"ALLOW"}]});ok("branch isolation",await rejects(()=>assessOrderDamage(tenant,{allocationId:branchAllocation.id,amountMinor:BigInt(100),reason:"Чужой филиал",idempotencyKey:"branch"},sellerActor)));
 const foreignOrder=await db.order.create({data:{organizationId:otherId,orderNumber:"X",branchId:otherBranch.id,customerId:otherCustomer.id,type:"RENTAL",channel:"CRM",status:"CONFIRMED",currency:"KZT"}});ok("tenant isolation",await rejects(()=>assessOrderDamage(tenant,{allocationId:foreignOrder.id,amountMinor:BigInt(100),reason:"Чужой tenant",idempotencyKey:"tenant"},actor)));
 const raceOrder=await makeOrder(),raceAllocation=await makeDamage(raceOrder.id);await receiveOrderDeposit(tenant,{orderId:raceOrder.id,amountMinor:BigInt(20000),paymentMethodId:cash.id,idempotencyKey:"race-dep"},actor);const raceCharge=await assessOrderDamage(tenant,{allocationId:raceAllocation.id,amountMinor:BigInt(20000),reason:"Гонка операций",idempotencyKey:"race-charge"},actor);const race=await Promise.allSettled([withholdOrderDepositForDamage(tenant,{damageChargeId:raceCharge.id,amountMinor:BigInt(20000),reason:"Удержать",idempotencyKey:"race-withhold"},actor),refundOrderDeposit(tenant,{orderId:raceOrder.id,amountMinor:BigInt(20000),reason:"Вернуть",confirmed:true,idempotencyKey:"race-refund"},actor)]);ok("refund versus withholding serialized",race.filter(x=>x.status==="fulfilled").length===1&&(await getOrderFinancialSummary(tenant,raceOrder.id,actor)).heldDepositMinor===BigInt(0));
 ok("audit attribution",await db.auditLog.count({where:{organizationId,actorMembershipId:owner.id,action:{in:["ORDER_DAMAGE_CHARGED","ORDER_DAMAGE_WAIVED","ORDER_DAMAGE_DEPOSIT_WITHHELD"]}}})>=3);ok("physical ledgers unchanged",await db.inventoryMovement.count({where:{organizationId}})===0&&await db.orderEvent.count({where:{orderId:order.id}})===0);ok("partial return allocation untouched",(await db.capacityAllocation.findUniqueOrThrow({where:{id:allocation.id}})).returnInspectionResult==="DAMAGED");
 const security=await db.$queryRaw<Array<{tables:number;rls:number;anon:number;authenticated:number;policies:number}>>`SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p')) tables,(SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relrowsecurity) rls,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='anon') anon,(SELECT count(*)::int FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee='authenticated') authenticated,(SELECT count(*)::int FROM pg_policies WHERE schemaname='public' AND roles && ARRAY['anon','authenticated','public']::name[]) policies`;ok("RLS security",security[0]!.tables===security[0]!.rls&&security[0]!.anon===0&&security[0]!.authenticated===0&&security[0]!.policies===0);
 await cleanup();ok("cleanup",await db.organization.count({where:{slug:{startsWith:"stage-9b-2b-"}}})===0);console.log(`PASS Stage 9B-2B (${passed} checks)`);
}
main().finally(async()=>{await cleanup();await db.$disconnect()}).catch(error=>{console.error(error);process.exitCode=1});
