import "dotenv/config";
import { db } from "../lib/db";

async function main(){
 const organizations=(await db.organization.findMany({where:{slug:{startsWith:"stage-9c-3-"}},select:{id:true}})).map(row=>row.id);
 if(!organizations.length){console.log("Stage 9C-3 cleanup: no fixtures");return;}
 const candidateUsers=[...new Set((await db.organizationMembership.findMany({where:{organizationId:{in:organizations}},select:{userId:true}})).map(row=>row.userId))];
 const users=(await db.user.findMany({where:{id:{in:candidateUsers},email:{endsWith:"@test.invalid"},memberships:{every:{organizationId:{in:organizations}}}},select:{id:true}})).map(row=>row.id);
 await db.$transaction(async tx=>{
  for(const sql of ['ALTER TABLE "financial_transactions" DISABLE TRIGGER "financial_transactions_immutable_update"','ALTER TABLE "audit_logs" DISABLE TRIGGER "audit_logs_immutable_update"','ALTER TABLE "purchase_receipts" DISABLE TRIGGER "purchase_receipts_immutable"','ALTER TABLE "purchase_receipt_lines" DISABLE TRIGGER "purchase_receipt_lines_immutable"','ALTER TABLE "bulk_acquisition_layers" DISABLE TRIGGER "bulk_acquisition_layers_immutable"','ALTER TABLE "purchase_items" DISABLE TRIGGER "purchase_items_locked_delete"'])await tx.$executeRawUnsafe(sql);
  await tx.auditLog.deleteMany({where:{organizationId:{in:organizations}}});await tx.financialTransaction.deleteMany({where:{organizationId:{in:organizations}}});await tx.inventoryMovement.deleteMany({where:{organizationId:{in:organizations}}});await tx.capacityAllocation.deleteMany({where:{organizationId:{in:organizations}}});await tx.orderEvent.deleteMany({where:{organizationId:{in:organizations}}});await tx.orderItem.deleteMany({where:{organizationId:{in:organizations}}});await tx.order.deleteMany({where:{organizationId:{in:organizations}}});await tx.orderCounter.deleteMany({where:{organizationId:{in:organizations}}});await tx.productInstance.deleteMany({where:{organizationId:{in:organizations}}});await tx.bulkAcquisitionLayer.deleteMany({where:{organizationId:{in:organizations}}});await tx.purchaseReceiptLine.deleteMany({where:{organizationId:{in:organizations}}});await tx.purchaseReceipt.deleteMany({where:{organizationId:{in:organizations}}});await tx.purchaseItem.deleteMany({where:{organizationId:{in:organizations}}});await tx.purchase.deleteMany({where:{organizationId:{in:organizations}}});await tx.supplier.deleteMany({where:{organizationId:{in:organizations}}});await tx.stockLevel.deleteMany({where:{organizationId:{in:organizations}}});await tx.productVariant.deleteMany({where:{organizationId:{in:organizations}}});await tx.product.deleteMany({where:{organizationId:{in:organizations}}});await tx.size.deleteMany({where:{organizationId:{in:organizations}}});await tx.category.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipPermissionOverride.deleteMany({where:{organizationId:{in:organizations}}});await tx.membershipBranchAccess.deleteMany({where:{organizationId:{in:organizations}}});await tx.organizationMembership.deleteMany({where:{organizationId:{in:organizations}}});await tx.customer.deleteMany({where:{organizationId:{in:organizations}}});await tx.location.deleteMany({where:{organizationId:{in:organizations}}});await tx.branch.deleteMany({where:{organizationId:{in:organizations}}});await tx.paymentMethod.deleteMany({where:{organizationId:{in:organizations}}});
  for(const sql of ['ALTER TABLE "financial_transactions" ENABLE TRIGGER "financial_transactions_immutable_update"','ALTER TABLE "audit_logs" ENABLE TRIGGER "audit_logs_immutable_update"','ALTER TABLE "purchase_receipts" ENABLE TRIGGER "purchase_receipts_immutable"','ALTER TABLE "purchase_receipt_lines" ENABLE TRIGGER "purchase_receipt_lines_immutable"','ALTER TABLE "bulk_acquisition_layers" ENABLE TRIGGER "bulk_acquisition_layers_immutable"','ALTER TABLE "purchase_items" ENABLE TRIGGER "purchase_items_locked_delete"'])await tx.$executeRawUnsafe(sql);
  await tx.organization.deleteMany({where:{id:{in:organizations}}});
  await tx.user.deleteMany({where:{id:{in:users}}});
 },{maxWait:10000,timeout:30000});
 console.log(`Stage 9C-3 cleanup: removed ${organizations.length} fixture organizations`);
}
main().finally(()=>db.$disconnect()).catch(error=>{console.error(error);process.exitCode=1;});
