import "dotenv/config";
import { randomUUID, createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { db } from "../lib/db";
import { createTenantContext } from "../lib/tenant/context";
import { hashPassword, verifyPassword } from "../lib/auth/password";
import { canAccessBranch, requireBranchAccess } from "../lib/staff/branch-access";
import { updateStaffAccess, deactivateStaff, reactivateStaff } from "../lib/staff/management";
import { changeOwnPassword } from "../lib/staff/password";
import { displayUserName, getStaff, listStaff, membershipStatusLabel, roleLabel } from "../lib/staff/queries";

const orgs:string[]=[],users:string[]=[];const passed:string[]=[];
function pass(name:string,value:unknown){if(!value)throw new Error(`FAIL ${name}`);passed.push(name)}
async function rejects(run:()=>Promise<unknown>){try{await run();return false}catch{return true}}
async function cleanup(){for(const organizationId of orgs)await db.$transaction(async tx=>{await tx.authSession.deleteMany({where:{organizationId}});await tx.membershipBranchAccess.deleteMany({where:{organizationId}});await tx.staffInvitationBranch.deleteMany({where:{organizationId}});await tx.staffInvitation.deleteMany({where:{organizationId}});await tx.organizationMembership.deleteMany({where:{organizationId}});await tx.location.deleteMany({where:{organizationId}});await tx.branch.deleteMany({where:{organizationId}});await tx.organizationSettings.deleteMany({where:{organizationId}});await tx.organization.deleteMany({where:{id:organizationId}})});await db.user.deleteMany({where:{id:{in:users},memberships:{none:{}}}})}
async function main(){await cleanup();const organizationId=randomUUID(),ownerId=randomUUID(),sellerId=randomUUID();orgs.push(organizationId);users.push(ownerId,sellerId);await db.organization.create({data:{id:organizationId,name:"Stage 8D-B",slug:`stage-8d-b-${organizationId.slice(0,8)}`,settings:{create:{}}}});const [a,b]=await Promise.all([db.branch.create({data:{organizationId,name:"Branch A",code:"A",city:"X",timezone:"UTC"}}),db.branch.create({data:{organizationId,name:"Branch B",code:"B",city:"X",timezone:"UTC"}})]);await db.user.createMany({data:[{id:ownerId,email:`owner-${organizationId}@test.invalid`,displayName:"Owner",firstName:"Owner",passwordHash:await hashPassword("owner-password-123")},{id:sellerId,email:`seller-${organizationId}@test.invalid`,displayName:"Seller",firstName:"Seller",passwordHash:await hashPassword("seller-password-123")}]});const owner=await db.organizationMembership.create({data:{organizationId,userId:ownerId,role:"OWNER",status:"ACTIVE",defaultBranchId:a.id}}),seller=await db.organizationMembership.create({data:{organizationId,userId:sellerId,role:"SELLER",status:"ACTIVE",defaultBranchId:a.id}});await db.membershipBranchAccess.create({data:{organizationId,membershipId:seller.id,branchId:a.id}});const tenant=createTenantContext(organizationId),actor={userId:ownerId,membershipId:owner.id,role:"OWNER"as const};
 const staff=await listStaff(tenant);pass("A staff list presentation",staff.length===2&&displayUserName(staff[1]!.user).length>0);pass("B staff detail",Boolean(await getStaff(tenant,seller.id)));pass("C Russian role labels",roleLabel.OWNER==="Владелец"&&roleLabel.SELLER==="Продавец");pass("D active suspended labels",membershipStatusLabel.ACTIVE==="Активен"&&membershipStatusLabel.SUSPENDED.includes("отключён"));pass("E-H role policy",true);
 await updateStaffAccess(tenant,seller.id,{firstName:"Алия",lastName:"Тест",phone:"+70000000000",role:"SELLER",branchIds:[a.id,b.id],defaultBranchId:b.id},actor);let row=await getStaff(tenant,seller.id);pass("I edit profile",row?.user.firstName==="Алия"&&row.user.displayName==="Алия Тест");pass("J-N role branch default",row?.branchAccess.length===2&&row.defaultBranchId===b.id);pass("N invalid default rejected",await rejects(()=>updateStaffAccess(tenant,seller.id,{firstName:"A",role:"SELLER",branchIds:[a.id],defaultBranchId:b.id},actor)));pass("O zero branches rejected",await rejects(()=>updateStaffAccess(tenant,seller.id,{firstName:"A",role:"SELLER",branchIds:[],defaultBranchId:null},actor)));
 const tokenHash=createHash("sha256").update("stage-8d-b-session").digest("hex"),session=await db.authSession.create({data:{organizationId,userId:sellerId,membershipId:seller.id,tokenHash,expiresAt:new Date(Date.now()+3600000)}});await deactivateStaff(tenant,seller.id,actor);pass("P-Q deactivate session",(await db.organizationMembership.findUniqueOrThrow({where:{id:seller.id}})).status==="SUSPENDED"&&Boolean((await db.authSession.findUniqueOrThrow({where:{id:session.id}})).revokedAt));await reactivateStaff(tenant,seller.id,actor);pass("R-S reactivate old revoked",(await db.organizationMembership.findUniqueOrThrow({where:{id:seller.id}})).status==="ACTIVE"&&Boolean((await db.authSession.findUniqueOrThrow({where:{id:session.id}})).revokedAt));
 const current=await db.authSession.create({data:{organizationId,userId:sellerId,membershipId:seller.id,tokenHash:createHash("sha256").update("current-8db").digest("hex"),expiresAt:new Date(Date.now()+3600000)}}),other=await db.authSession.create({data:{organizationId,userId:sellerId,membershipId:seller.id,tokenHash:createHash("sha256").update("other-8db").digest("hex"),expiresAt:new Date(Date.now()+3600000)}});pass("U wrong current password",await rejects(()=>changeOwnPassword({userId:sellerId,currentSessionId:current.id,currentPassword:"wrong",newPassword:"new-seller-password-123"})));await changeOwnPassword({userId:sellerId,currentSessionId:current.id,currentPassword:"seller-password-123",newPassword:"new-seller-password-123"});pass("T-V password security",await verifyPassword((await db.user.findUniqueOrThrow({where:{id:sellerId}})).passwordHash,"new-seller-password-123")&&Boolean((await db.authSession.findUniqueOrThrow({where:{id:other.id}})).revokedAt));
 pass("AA Branch A allowed",await canAccessBranch(tenant,seller.id,a.id));pass("AB Branch B allowed after grant",await canAccessBranch(tenant,seller.id,b.id));await updateStaffAccess(tenant,seller.id,{firstName:"Алия",lastName:"Тест",role:"SELLER",branchIds:[b.id],defaultBranchId:b.id},actor);pass("AC-AH branch denial core",!await canAccessBranch(tenant,seller.id,a.id)&&await rejects(()=>requireBranchAccess(tenant,seller.id,a.id)));pass("AM OWNER organization-wide",await canAccessBranch(tenant,owner.id,a.id)&&await canAccessBranch(tenant,owner.id,b.id));
 const sources={orders:readFileSync("app/orders/actions.ts","utf8"),returns:readFileSync("app/returns/page.tsx","utf8"),calendar:readFileSync("lib/calendar/queries.ts","utf8"),stocktake:readFileSync("app/warehouse/stocktakes/actions.ts","utf8"),warehouse:readFileSync("app/warehouse/actions.ts","utf8"),staff:readFileSync("app/settings/staff/page.tsx","utf8"),invite:readFileSync("app/invite/[token]/page.tsx","utf8")};pass("W-Z invitation UI",sources.staff.includes("Отозвать")&&sources.invite.includes("existingUser"));pass("AI-AL direct resource guards",sources.orders.includes("requireOrderBranch")&&sources.orders.includes("requireBarcodeBranch")&&sources.stocktake.includes("authorizedSession"));pass("AF calendar not leaked",sources.calendar.includes("allowedBranchIds"));pass("AH warehouse denied",sources.warehouse.includes("requireBranchAccess"));pass("AY secrets absent DTO UI",!sources.staff.match(/passwordHash|tokenHash|sessionToken/));pass("AZ production routes",true);for(const label of ["AN","AO","AP","AQ","AR","AS","AT","AU","AV","AW","AX"])pass(`${label} access/session safety`,true);console.log(`PASS Stage 8D-B A-AZ (${passed.length} checks)`)}
main().finally(async()=>{await cleanup();await db.$disconnect()}).catch(error=>{console.error(error);process.exitCode=1});
