import{readFileSync,existsSync}from"node:fs";const read=(p:string)=>readFileSync(p,"utf8"),ok:string[]=[];function check(n:string,v:unknown){if(!v)throw new Error(`FAIL ${n}`);ok.push(n)}
const list=read("app/orders/page.tsx"),create=read("app/orders/new/page.tsx"),detail=read("app/orders/[id]/page.tsx"),form=read("components/OrderForm.tsx"),css=read("app/orders.css"),queries=read("lib/orders/queries.ts"),actions=read("app/orders/actions.ts"),labels=read("lib/ui/labels.ts");
check("dense orders list",list.includes("orders-table-row")&&css.includes("orders-table-head"));
check("order search",list.includes('name="q"')&&list.includes("Номер, клиент или телефон"));
check("filters",list.includes('name="status"')&&list.includes('name="type"')&&list.includes('name="branchId"'));
check("create action permission",list.includes('hasPermission(s,"ORDER_CREATE")'));
check("payment visibility",list.includes('hasPermission(s,"PAYMENT_VIEW")')&&list.includes("canViewPayments&&"));
check("localized order statuses",labels.includes("ORDER_STATUS_LABELS")&&list.includes("orderStatusLabel"));
check("safe status fallback",labels.includes('"Статус требует проверки"'));
check("rental type explicit",form.includes("Аренда")&&form.includes("Продажа")&&form.includes("disabled"));
check("customer lookup",form.includes("Поиск по имени")&&form.includes("/customers/new"));
check("customer phone search backend",queries.includes("contacts: { some:"));
check("rental dates",form.includes('name="rentalStart"')&&form.includes('name="rentalEnd"'));
check("server availability",create.includes("getAvailabilityForForm")&&queries.includes("getVariantAvailability"));
check("scan resolver",create.includes("resolveInventoryScan"));
check("product lookup",form.includes("Название, код, SKU, размер или штрихкод"));
check("product code SKU size backend",queries.includes("internalCode")&&queries.includes("barcode")&&queries.includes("size:"));
check("line controls",form.includes('name="quantity"')&&form.includes('name="itemDiscountMinor"')&&form.includes('name="adjustmentReason"'));
check("sticky summary",form.includes("order-checkout")&&css.includes("position:sticky"));
check("authoritative server action",create.includes("createOrderAction")&&actions.includes("createOrder(tenant"));
check("pending submit protection",form.includes("useFormStatus")&&form.includes("disabled={pending}"));
check("detail localized header",detail.includes("orderStatusLabel")&&detail.includes("orderChannelLabel"));
check("detail tracking localized",detail.includes("trackingModeLabel"));
check("detail event localized",detail.includes("orderEventLabel"));
check("finance service preserved",detail.includes("getOrderPaymentDetails")&&detail.includes("getOrderDepositDetails"));
check("fulfillment services preserved",detail.includes("issueOrderAction")&&detail.includes("returnBulkAction"));
check("responsive list",css.includes("max-width:900px")&&css.includes("max-width:620px"));
check("mobile checkout",css.includes("bottom:8px"));
check("keyboard native controls",form.includes('type="button"')&&form.includes("autoFocus"));
check("no schema migration",!existsSync("prisma/migrations/20260918_ux_ui_redesign_2"));
console.log(`UX/UI Redesign 2 targeted: ${ok.length}/${ok.length} passed`);
