import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { BarcodeClient } from "@/components/BarcodeClient";
import { getCatalogManagementOptions, getCatalogProductById, type MoneyDto } from "@/lib/catalog/queries";
import { requireRouteAccess } from "@/lib/auth/session";
import { canPerformCatalogAction } from "@/lib/auth/access";
import { CONDITION_LABELS, INSTANCE_STATUS_LABELS } from "@/lib/inventory/labels";
import { createTenantContext } from "@/lib/tenant/context";
import { addVariantAction, adjustStockAction, archiveProductAction, createInstancesAction, deleteImageAction, reorderImagesAction, replacePriceAction, setPrimaryImageAction, setVariantActiveAction } from "../actions";

const money=(m:MoneyDto|null)=>m?`${m.amountMinor.toLocaleString("ru-KZ")} ${m.currency}`:"—";
export default async function ProductDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){
 const session=await requireRouteAccess("/products"), {id}=await params, tenant=createTenantContext(session.organizationId);
 const [product,options]=await Promise.all([getCatalogProductById({tenant,defaultBranchId:session.defaultBranchId,productId:id}),getCatalogManagementOptions(tenant)]); if(!product)notFound();
 const msg=await searchParams, catalog=canPerformCatalogAction(session.role,"MANAGE_CATALOG"), inventory=canPerformCatalogAction(session.role,"MANAGE_INVENTORY"), photos=canPerformCatalogAction(session.role,"MANAGE_PHOTOS");
 return <AppShell active="/products" title={product.name} subtitle={`Код ${product.internalCode}${product.color?` · ${product.color}`:""}`} action={catalog?<Link className="secondary button-link" href={`/products/${id}/edit`}>Редактировать</Link>:undefined}>
  {msg.ok&&<p className="notice ok">{msg.ok}</p>}{msg.error&&<p className="notice error">{msg.error}</p>}
  <section className="product-hero"><div className="hero-photo">{product.images[0]?.url?<img src={product.images[0].url} alt={product.images[0].altText??product.name}/>:<><span>MARIPOSA</span><small>Фото не добавлено</small></>}</div><div className="hero-info"><span className="eyebrow">{product.categoryName??"Без категории"}</span><h2>{product.name}</h2><p>{product.description??"Описание не добавлено."}</p><div className="meta-grid"><div><small>Бренд</small><b>{product.brand??"—"}</b></div><div><small>Модель поставщика</small><b>{product.supplierModel??"—"}</b></div><div><small>Вариантов</small><b>{product.variants.length}</b></div><div><small>Учёт</small><b>{product.trackingMode==="SERIALIZED"?"Поэкземплярный":"Количественный"}</b></div></div>{catalog&&<form action={archiveProductAction}><input type="hidden" name="productId" value={id}/><button className="danger">Архивировать товар</button></form>}</div></section>
  <section className="card"><div className="card-head"><div><h2>Фотографии</h2><p>JPEG, PNG или WebP, до 8 МБ</p></div></div>{photos&&<form action={`/products/${id}/photos`} method="post" encType="multipart/form-data" className="inline-form"><input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/><input name="altText" placeholder="Описание фото"/><button className="primary">Загрузить</button></form>}<div className="photo-manager">{product.images.map((image,index)=><article key={image.id}><div className="managed-photo">{image.url?<img src={image.url} alt={image.altText??product.name}/>:<span>Недоступно</span>}</div><b>{image.isPrimary?"Главное фото":"Фото"}</b>{photos&&<div className="photo-actions">{index>0&&<OrderButton productId={id} images={product.images.map(x=>x.id)} index={index} direction={-1}/>} {index<product.images.length-1&&<OrderButton productId={id} images={product.images.map(x=>x.id)} index={index} direction={1}/>} {!image.isPrimary&&<form action={setPrimaryImageAction}><input type="hidden" name="productId" value={id}/><input type="hidden" name="imageId" value={image.id}/><button className="secondary">Сделать главным</button></form>}<form action={deleteImageAction}><input type="hidden" name="productId" value={id}/><input type="hidden" name="imageId" value={image.id}/><button className="danger">Удалить</button></form></div>}</article>)}</div></section>
  {catalog&&<section className="card"><h2>Добавить размер / вариант</h2><form action={addVariantAction} className="inline-form"><input type="hidden" name="productId" value={id}/><select name="sizeId" required><option value="">Размер</option>{options.sizes.filter(s=>s.isActive).map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select><input name="sku" placeholder="SKU" required/><button className="primary">Добавить</button></form></section>}
  <section className="card variants-card"><div className="card-head"><div><h2>Варианты, цены и остатки</h2><p>Изменение цены создаёт новый период и сохраняет историю</p></div></div>{product.variants.map(v=><details key={v.id} className="variant-details" open><summary><b>{v.size}</b> · {v.sku} · {v.isActive?"активен":"неактивен"} · аренда {money(v.rentalPrice)} · продажа {money(v.salePrice)}</summary><div className="variant-management">{catalog&&<><form action={replacePriceAction} className="inline-form"><input type="hidden" name="productId" value={id}/><input type="hidden" name="variantId" value={v.id}/><select name="type"><option value="RENTAL">Аренда</option><option value="SALE">Продажа</option></select><input name="amount" type="number" min="0" placeholder="Тенге" required/><input name="currency" value="KZT" readOnly/><select name="branchId"><option value="">Все филиалы</option>{options.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="secondary">Изменить цену</button></form><form action={setVariantActiveAction}><input type="hidden" name="productId" value={id}/><input type="hidden" name="variantId" value={v.id}/><input type="hidden" name="isActive" value={String(!v.isActive)}/><button className={v.isActive?"danger":"secondary"}>{v.isActive?"Деактивировать":"Активировать"} вариант</button></form></>}{product.trackingMode==="SERIALIZED"?<><InstanceForm enabled={inventory} productId={id} variantId={v.id} branches={options.branches}/><div className="instances-list">{v.instances.map(i=><div className="instance-row database-instance" key={i.id}><div><strong>{i.inventoryNumber}</strong><small>{i.branchName} · {i.locationName} · {CONDITION_LABELS[i.conditionStatus]??i.conditionStatus}</small></div><BarcodeClient value={i.barcode}/><span className={`badge ${i.operationalStatus.toLowerCase()}`}>{INSTANCE_STATUS_LABELS[i.operationalStatus]??i.operationalStatus}</span></div>)}</div></>:<><StockForm enabled={inventory} productId={id} variantId={v.id} branches={options.branches}/>{v.stockLevels.map(s=><p key={s.id}>{s.branchName}{s.locationName?` · ${s.locationName}`:""}: <b>{s.quantity}</b></p>)}</>}</div></details>)}</section>
 </AppShell>;
}

type Branch={id:string;name:string;locations:Array<{id:string;name:string}>};
function OrderButton({productId,images,index,direction}:{productId:string;images:string[];index:number;direction:-1|1}){const next=[...images], target=index+direction;[next[index],next[target]]=[next[target],next[index]];return <form action={reorderImagesAction}><input type="hidden" name="productId" value={productId}/><input type="hidden" name="imageIds" value={next.join(",")}/><button className="secondary" title={direction<0?"Выше":"Ниже"}>{direction<0?"↑":"↓"}</button></form>}
function InstanceForm({enabled,productId,variantId,branches}:{enabled:boolean;productId:string;variantId:string;branches:Branch[]}){return enabled?<form action={createInstancesAction} className="inline-form"><input type="hidden" name="productId" value={productId}/><input type="hidden" name="variantId" value={variantId}/><input name="quantity" type="number" min="1" max="100" placeholder="Количество" required/><select name="branchId" required><option value="">Филиал</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select name="locationId" required><option value="">Место хранения</option>{branches.flatMap(b=>b.locations.map(l=><option key={l.id} value={l.id}>{b.name} · {l.name}</option>))}</select><input name="purchaseCost" type="number" min="0" placeholder="Закупочная цена"/><input name="notes" placeholder="Примечание"/><button className="primary">Добавить экземпляры</button></form>:null;}
function StockForm({enabled,productId,variantId,branches}:{enabled:boolean;productId:string;variantId:string;branches:Branch[]}){return enabled?<form action={adjustStockAction} className="inline-form"><input type="hidden" name="productId" value={productId}/><input type="hidden" name="variantId" value={variantId}/><select name="branchId" required><option value="">Филиал</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select name="locationId"><option value="">Уровень филиала</option>{branches.flatMap(b=>b.locations.map(l=><option key={l.id} value={l.id}>{b.name} · {l.name}</option>))}</select><input name="delta" type="number" placeholder="+10 или -2" required/><input name="reason" placeholder="Причина" required/><button className="primary">Скорректировать</button></form>:null;}
