"use server";import{redirect}from"next/navigation";import{revalidatePath}from"next/cache";import{requireRouteAccess}from"@/lib/auth/session";import{createTenantContext}from"@/lib/tenant/context";import{requireInventoryPermission}from"@/lib/inventory/permissions";import{startStocktake,scanBarcode,setBulkCount,completeCount,cancelStocktake,reconcileStocktake,resolveMissing,resolveScan,resolveBulk}from"@/lib/stocktake/management";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim(),go=(id:string,ok:boolean,m:string):never=>redirect(`/warehouse/stocktakes/${id}?${ok?"ok":"error"}=${encodeURIComponent(m)}`);async function ctx(a:"STOCKTAKE"|"RECONCILE"){const s=await requireRouteAccess("/warehouse/stocktakes");requireInventoryPermission(s.role,a);return{s,t:createTenantContext(s.organizationId)}}
export async function startAction(f:FormData){try{const{s,t:tenant}=await ctx("STOCKTAKE"),x=await startStocktake(tenant,{branchId:t(f,"branchId"),locationId:t(f,"locationId"),note:t(f,"note"),idempotencyKey:t(f,"idempotencyKey")},{userId:s.userId});redirect(`/warehouse/stocktakes/${x.id}`)}catch(e){redirect(`/warehouse/stocktakes/new?error=${encodeURIComponent(e instanceof Error?e.message:"Ошибка")}`)}}
export async function scanAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("STOCKTAKE"),x=await scanBarcode(tenant,id,t(f,"barcode"),{userId:s.userId});revalidatePath(`/warehouse/stocktakes/${id}`);go(id,true,x.alreadyScanned?"Уже отсканировано.":"Штрихкод принят.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
export async function bulkAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("STOCKTAKE");await setBulkCount(tenant,id,t(f,"variantId"),Number(t(f,"count")),{userId:s.userId});revalidatePath(`/warehouse/stocktakes/${id}`);go(id,true,"Количество сохранено.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
export async function completeAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("STOCKTAKE");await completeCount(tenant,id,{userId:s.userId});go(id,true,"Подсчёт завершён.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
export async function cancelAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("STOCKTAKE");await cancelStocktake(tenant,id,{userId:s.userId});go(id,true,"Инвентаризация отменена.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
export async function resolveAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("RECONCILE"),kind=t(f,"kind"),action=t(f,"resolution"),why=t(f,"reason");if(kind==="missing")await resolveMissing(tenant,id,t(f,"recordId"),action as"MARK_LOST"|"ACKNOWLEDGED",why,{userId:s.userId});else if(kind==="scan")await resolveScan(tenant,id,t(f,"recordId"),action as"ACCEPT_LOCATION"|"ACCEPT_TRANSFER"|"FOUND"|"ACKNOWLEDGED",why,{userId:s.userId});else await resolveBulk(tenant,id,t(f,"recordId"),action==="APPLY_ADJUSTMENT",why,{userId:s.userId});go(id,true,"Решение сохранено.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
export async function reconcileAction(f:FormData){const id=t(f,"sessionId");try{const{s,t:tenant}=await ctx("RECONCILE");await reconcileStocktake(tenant,id,{userId:s.userId});go(id,true,"Инвентаризация сверена.")}catch(e){go(id,false,e instanceof Error?e.message:"Ошибка")}}
