import Link from "next/link";
import {AppShell} from "@/components/AppShell";
import {requireRouteAccess} from "@/lib/auth/session";
import {hasPermission} from "@/lib/permissions/effective";
import {listFittings} from "@/lib/fittings/service";
import {FITTING_STATUS_LABELS} from "@/lib/fittings/validation";
import {workflowOptions} from "@/lib/workspace/conversion";
import {parseBusinessLocalDateTime,parseDateKey,localDateKey,periodFor,daysInRange,dateKey,moveAnchor} from "@/lib/calendar/timezone";
import "../orders/workspace.css";
type Params={branchId?:string;from?:string;until?:string;status?:string;mine?:string;page?:string;view?:string;date?:string;fromInstant?:string;untilInstant?:string};
export default async function Page({searchParams}:{searchParams:Promise<Params>}){
 const session=await requireRouteAccess("/fittings"),p=await searchParams,options=await workflowOptions(session,"FITTING_VIEW",p.branchId||undefined),timezone=options.branch?.timezone??"UTC",view=p.view==="day"||p.view==="week"||p.view==="month"?p.view:"list",anchor=parseDateKey(p.date)??parseDateKey(localDateKey(new Date(),timezone))!,period=periodFor(view==="list"?"week":view,anchor,timezone);
 let from:Date|undefined,until:Date|undefined,error="";
 try{for(const instant of [p.fromInstant,p.untilInstant])if(instant&&!/^[0-9]{4}-[0-9]{2}-[0-9]{2}T/.test(instant))throw Error();from=p.fromInstant?new Date(p.fromInstant):p.from?parseBusinessLocalDateTime(`${p.from}T00:00`,timezone):undefined;until=p.untilInstant?new Date(p.untilInstant):p.until?parseBusinessLocalDateTime(`${p.until}T00:00`,timezone):undefined;if(view!=="list"){from=period.rangeStart;until=period.rangeEnd;}if(from&&Number.isNaN(from.getTime())||until&&Number.isNaN(until.getTime())||from&&until&&until<=from)throw Error();}catch{error="Проверьте период. Конец периода не включается."}
 const list=error?{rows:[],page:1,more:false}:await listFittings(session,{branchId:p.branchId||undefined,from,until,status:p.status,mine:p.mine==="yes",page:view!=="list"?1:/^[0-9]+$/.test(p.page??"")?Number(p.page):1,limit:view!=="list"?1000:50});
 const href=(changes:Record<string,string>)=>{const q=new URLSearchParams(Object.entries(p).filter((v):v is [string,string]=>Boolean(v[1])));for(const [key,value] of Object.entries(changes))q.set(key,value);return`/fittings?${q}`};
 const card=(row:typeof list.rows[number])=><article key={row.id} className="workspace-order-card"><Link href={`/fittings/${row.id}`}><strong>{row.startsAt.toLocaleString("ru",{timeZone:row.branch.timezone})}</strong> · {row.customer?`${row.customer.firstName} ${row.customer.lastName??""}`:row.guestName}</Link><small>{row.branch.name} · {row.assignedTo.user.displayName} · {FITTING_STATUS_LABELS[row.status]}</small></article>;
 return <AppShell active="/fittings" title="Примерки" subtitle="Записи по времени; товар резервируется только в заказе"><div className="toolbar">{await hasPermission(session,"FITTING_MANAGE")&&<Link className="primary-button" href="/fittings/new">Новая примерка</Link>}{Object.entries({list:"Список",day:"День",week:"Неделя",month:"Месяц"}).map(([key,label])=><Link key={key} href={href({view:key,page:"1"})}>{label}</Link>)}</div>
 <form className="panel workspace-filters"><input type="hidden" name="view" value={view}/><label>Филиал<select name="branchId" defaultValue={p.branchId??""}><option value="">Все доступные</option>{options.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{view==="list"?<><label>С даты<input type="date" name="from" defaultValue={from?localDateKey(from,timezone):p.from}/></label><label>До даты (не включая)<input type="date" name="until" defaultValue={until?localDateKey(until,timezone):p.until}/></label></>:<label>Дата календаря<input type="date" name="date" defaultValue={dateKey(anchor)}/></label>}<label>Статус<select name="status" defaultValue={p.status??""}><option value="">Все</option>{Object.entries(FITTING_STATUS_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><input type="checkbox" name="mine" value="yes" defaultChecked={p.mine==="yes"}/> Только мои</label><button>Показать</button><Link href="/fittings">Сбросить</Link></form>
 {error&&<p className="notice error">{error}</p>}{view==="list"?<section className="panel">{list.rows.map(card)}{!list.rows.length&&<p>Примерок по фильтрам нет.</p>}</section>:<><nav className="toolbar"><Link href={href({date:dateKey(moveAnchor(view,anchor,-1))})}>← Предыдущий период</Link><span>{dateKey(period.start)} — {dateKey(period.end)} · {timezone}</span><Link href={href({date:dateKey(moveAnchor(view,anchor,1))})}>Следующий период →</Link></nav>{list.more&&<p className="notice error">Более 1000 примерок: показаны первые 1000. Уточните филиал или выберите меньший период.</p>}<div className="workspace-board">{daysInRange(period.start,period.end).map(day=><section className="workspace-column" key={dateKey(day)}><h2><Link href={href({view:"day",date:dateKey(day)})}>{dateKey(day)}</Link></h2>{list.rows.filter(row=>localDateKey(row.startsAt,timezone)===dateKey(day)).map(card)}</section>)}</div></>}
 {view==="list"&&<nav>{list.page>1&&<Link href={href({page:String(list.page-1)})}>← Назад</Link>} <span>Страница {list.page}</span> {list.more&&<Link href={href({page:String(list.page+1)})}>Далее →</Link>}</nav>}
 </AppShell>;
}
